.TH "scorched3ds" "6" "41.1"
.SH "NAME"
scorched3ds \- Scorched 3D network server
.SH "SYNTAX"
.LP 
.B scorched3ds [\fIoptions\fP] 
.SH "DESCRIPTION"
.LP 
This program is a free (GPL) 3D game based heavily on the classic DOS game 
Scorched Earth "The Mother Of All Games". Scorched3D adds amongst other 
new features a 3D island environment and LAN and internet play.
.br
.SH "OPTIONS"
.LP 
The following options are supported.
.LP 
.TP 15
.B -allowexceptions
Allows any program exceptions to be thrown (core dumps).
.TP 15
.B -settingsdir <string>
The directory in the user's home directory that the scorched3d settings are stored in (Default: .scorched3d).
.TP 15
.B -startserver <string>
Starts a scorched 3d server. Requires the name of the server settings file e.g. data/server.xml.
.PD
.SH "AUTHORS"
.LP 
Scorched3D has been written by Gavin Camp <gcamp@scorched3d.co.uk>.
.BR 
This man page was written by Bruno "Fuddl" Kleinert <fuddl@debian.org> for the 
Debian GNU/Linux distribution (but it may be used by others).
