.TH FLITE 1 "February 25, 2003"
.SH NAME
flite \- A small simple speech synthesizer
.SH SYNOPSIS
.B flite
[\fIOPTION\fR]... \fITEXTFILE\fR [\fIWAVEFILE\fR]
.SH DESCRIPTION
This manual page documents briefly the
.B flite
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page.
Instead, it has documentation in /usr/share/doc/flite/
.PP
Converts text in TEXTFILE to a waveform in WAVEFILE.
If text contains a space, it is treated as a literal
textstring and spoken, and not as a file name.
if WAVEFILE is unspecified or "play" the result is
played on the current systems audio device.  If WAVEFILE
is "none" the waveform is discarded (good for benchmarking)
.SH OPTIONS
.TP
\fB\-\-version\fR
Output \fBflite\fP version number.
.TP
\fB\-?\fR, \fB\-\-help\fR
Output usage information.
.TP
\fB\-o\fR WAVEFILE
Explicitly set output filename.
.TP
\fB\-f\fR TEXTFILE
Explicitly set input filename.
.TP
\fB\-t\fR TEXT
Explicitly set input text string.
.TP
\fB\-p\fR PHONES
Explicitly set input text string and synthesize as phones.
.TP
\fB\-s\fR, \fB\-\-set\fR FEATURE=VALUE
Set feature (guesses type).
.TP
\fB\-\-seti\fR FEATURE=VALUE
Set int feature.
.TP
\fB\-\-setf\fR FEATURE=VALUE
Set float feature.
.TP
\fB\-\-sets\fR FEATURE=VALUE
Set string feature.
.TP
\fB\-b\fR
Benchmark mode.
.TP
\fB\-l\fR
Loop endlessly.
.TP
\fB\-v\fR
Verbose output.
.SH SEE ALSO
.BR flite_time (1), " " t2p (1), " " festival (1)
.SH AUTHOR
This manual page was written by Mario Lang <mlang@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
