.TH upnpc 1

.SH NAME
upnpc \- miniupnpc library test client.

.SH "SYNOPSIS"
Add port redirection:
.br
\fBupnpc\fP [options] \-a ip port external_port protocol

Delete port redirection:
.br
\fBupnpc\fP [options] \-d external_port protocol [port2 protocol2] [...]

Get Connection status:
.br
\fBupnpc\fP [options] \-s

List redirections:
.br
\fBupnpc\fP [options] \-l

Add all redirections to the current host:
.br
\fBupnpc\fP [options] \-r port1 protocol1 [port2 protocol2] [...]

.SH DESCRIPTION
protocol is UDP or TCP

.SH OPTIONS

\fB-u url\fP : bypass discovery process by providing the XML root description url

\fB-m address\fP : provide ip address of the interface to use for sending SSDP-multicast packets.

\fB-p path\fP : use this path for MiniSSDPd socket.

.SH "SEE ALSO"
external-ip(1)
