doc/reference/html/*html usr/share/doc/gnutls-doc/api-reference
doc/reference/html/*png usr/share/doc/gnutls-doc/api-reference
doc/reference/html/*.css usr/share/doc/gnutls-doc/api-reference
doc/reference/html/*.sgml usr/share/doc/gnutls-doc/api-reference
doc/reference/html/*.devhelp* usr/share/doc/gnutls-doc/api-reference
doc/*.html usr/share/doc/gnutls-doc/html
doc/*.png usr/share/doc/gnutls-doc/html
