usr/bin/bdftopcf
usr/bin/bdftruncate
usr/bin/mkfontdir
usr/bin/mkfontscale
usr/bin/ucs2any
usr/share/man/man1/bdftopcf.1
usr/share/man/man1/bdftruncate.1
usr/share/man/man1/mkfontdir.1
usr/share/man/man1/mkfontscale.1
usr/share/man/man1/ucs2any.1
usr/share/aclocal/fontutil.m4
usr/lib/pkgconfig/fontutil.pc usr/share/pkgconfig/
../local/update-fonts-alias usr/sbin
../local/update-fonts-dir usr/sbin
../local/update-fonts-scale usr/sbin
../local/update-fonts-alias.8 usr/share/man/man8
../local/update-fonts-dir.8 usr/share/man/man8
../local/update-fonts-scale.8 usr/share/man/man8
usr/share/fonts/X11/util/map-ISO8859-1
usr/share/fonts/X11/util/map-ISO8859-2
usr/share/fonts/X11/util/map-ISO8859-3
usr/share/fonts/X11/util/map-ISO8859-4
usr/share/fonts/X11/util/map-ISO8859-5
usr/share/fonts/X11/util/map-ISO8859-6
usr/share/fonts/X11/util/map-ISO8859-7
usr/share/fonts/X11/util/map-ISO8859-8
usr/share/fonts/X11/util/map-ISO8859-9
usr/share/fonts/X11/util/map-ISO8859-10
usr/share/fonts/X11/util/map-ISO8859-11
usr/share/fonts/X11/util/map-ISO8859-13
usr/share/fonts/X11/util/map-ISO8859-14
usr/share/fonts/X11/util/map-ISO8859-15
usr/share/fonts/X11/util/map-ISO8859-16
usr/share/fonts/X11/util/map-JISX0201.1976-0
usr/share/fonts/X11/util/map-KOI8-R
usr/bin/fonttosfnt
usr/share/man/man1/fonttosfnt.1
