.TH ONIG-CONFIG 1
.SH NAME
onig-config - provide information about the installed version of libonig
.SH SYNOPSIS

\fBonig-config\fR [ \fB --prefix\fI[=DIR]\fB \fR ] [ \fB --exec-prefix\fI[=DIR]\fB \fR ] [ \fB --libs \fR ] [ \fB --cflags \fR ] [ \fB --version \fR ]

.SH DESCRIPTION
\fBonig-config\fR returns the configuration of the installed Oniguruma
library: the options required to compile a program which uses the
library.


.SH OPTIONS
.TP 10
\fB--prefix=PREFIX\fR
If specified, use \fIPREFIX\fR instead
of the installation prefix that
\fIlibonig\fR was built with when computing
the output for the \fB--cflags\fR and
\fB--libs\fR options. This option is also used for
the exec prefix if \fB--exec-prefix\fR was
not specified. This option must be specified before any
\fB--libs\fR or \fB--cflags\fR options.
.TP
\fB--exec-prefix=PREFIX\fR
If specified, use \fIPREFIX\fR instead
of the installation exec prefix that
\fIlibonig\fR was built with when computing
the output for the \fB--cflags\fR and
\fB--libs\fR options. This option must be specified
before any \fB--libs\fR or \fB--cflags\fR options.
.TP
\fB--libs\fR
Print the linker flags that are necessary to link a
\fIlibonig\fR program.
.TP
\fB--cflags\fR
Print the compiler flags that are necessary to compile a
\fIlibonig\fR program.
.TP
\fB--version\fR
Print the currently installed version of
\fIlibonig\fR on the standard output.


.SH AUTHOR
This manual page was written by Max Kellermann <max@duempel.org> for
the Debian GNU/Linux system (but may be used by others), based on
other Debian manual pages.
