.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH lsb 8 "2002-02-24"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
lsb \- Linux Standard Base support for Debian
.SH DESCRIPTION
The \fBlsb\fP package provides infrastructure for installing Linux
Standard Base applications on Debian.  This manual page is designed to
refer system adminstrators and others to the documentation available.
.PP
The Linux Standard Base is a common runtime environment for
third-party packages.  The goal of the LSB is to make it easy to
create binary packages that will run on any Linux distribution.  For
more information on the standard, please see the LSB web site.
.SH SEE ALSO
.BR /usr/share/doc/lsb-core/README.Debian.gz
.BR http://www.linuxbase.org/
.BR http://refspecs.linuxbase.org/lsb.shtml
.SH AUTHOR
This manual page was written by Chris Lawrence <lawrencc@debian.org>
for the Debian system (but may be used by others).
