#!/bin/sh

set -e

case "${1}" in
	configure)
	# "systemctl enable" fails in a chroot, so the obvious solution breaks in the
	# installer :/
	ln -fs '/lib/systemd/system/dnsmasq.service' '/etc/systemd/system/multi-user.target.wants/dnsmasq.service'
	;;

	abort-upgrade|abort-remove|abort-deconfigure)

		;;

	*)
		echo "postinst called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
