.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH HPIJS 1 "2004-05-15"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
hpijs \- HP IJS server for the GhostScript IJS client driver
.SH DESCRIPTION
hpijs should never be called directly.  GhostScript will run it
if the IjsServer parameter is set to IjsServer=hpijs when invoking the
IJS driver.
.br
.SH OPTIONS
.TP
.B -h
Show version
.SH SEE ALSO
For more information, please refer to /usr/share/doc/hpijs, and
to http://www.openprinting.org/.
.TP
http://hplip.sourceforge.net/
.TP
http://www.openprinting.org/ (search for hpijs driver)
.SH AUTHOR
This manual page was written by Henrique de Moraes Holschuh <hmh@debian.org>,
for the Debian project (but may be used by others).
