etc/xdg/autostart/hplip-systray.desktop
etc/udev/rules.d/* lib/udev/rules.d/
usr/bin/hp-devicesettings
usr/bin/hp-diagnose_plugin
usr/bin/hp-diagnose_queues
usr/bin/hp-fab
usr/bin/hp-faxsetup
usr/bin/hp-linefeedcal
usr/bin/hp-makecopies
usr/bin/hp-pqdiag
usr/bin/hp-print
usr/bin/hp-printsettings
usr/bin/hp-sendfax
usr/bin/hp-systray
usr/bin/hp-toolbox
usr/bin/hp-wificonfig
usr/share/applications
usr/share/pixmaps
