debian/bug/boinc-client/script      usr/share/bug/boinc-client
debian/conffiles/*                  etc/boinc-client
debian/extra/bash/*                 etc/bash_completion.d
debian/extra/udev-cpu_share         usr/share/boinc-client
debian/extra/update-boinc-applinks  usr/bin
usr/bin/switcher                    usr/lib/boinc-client
usr/bin/boinc			    usr/bin
usr/bin/boinccmd		    usr/bin
usr/share/locale/*/BOINC-Client.mo
