.TH GCJH-WRAPPER 1 "June 6, 2002" gcjh-wrapper "Java User's Manual"
.SH NAME
gcjh-wrapper \- a wrapper around gcjh

.SH SYNOPSIS
gcjh-wrapper [\fB\s-1OPTION\s0\fR] ... [\fI\s-1ARGS\s0\fR...]

.SH DESCRIPTION

\fBgcjh-wrapper\fR is a wrapper around gcjh(1) to be called as the java header
compiler. Options different for javah(1) and gcjh(1) are translated,
options unknown to gcjh(1) are silently ignored.

.SH OPTIONS
See gcjh-@BV@(1) for a list of options that gcj understands.

.SH "SEE ALSO"
.BR gcjh-@BV@(1)
,
.BR javah(1)
