.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "AC3DEC" "1" "February 21, 2005" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
ac3dec \- AC\-3 stream decoder
.SH "SYNOPSIS"
.HP 7
\fBac3dec\fR [\fIoption\fR...] [\fIfile\fR...]
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBac3dec\fR
command.
.PP
This manual page was written for the
Debian
distribution because the original program does not have a manual page. Instead, it has documentation in the
GNUInfo
format; see below.
.SH "OPTIONS"
.TP
\fB\-h\fR | \fB\-\-help\fR
Prints a short help message.
.TP
\fB\-v\fR | \fB\-\-version\fR
Print the version of the program.
.TP
\fB\-D \fR\fB\fINAME\fR\fR | \fB\-\-device \fR\fB\fINAME\fR\fR
Select PCM by
\fINAME\fR.
.TP
\fB\-c \fR\fB\fIID\fR\fR | \fB\-\-card \fR\fB\fIID\fR\fR
Select card for bellow modes.
.TP
\fB\-4\fR | \fB\-\-4ch\fR
Four channels mode.
.TP
\fB\-6\fR | \fB\-\-6ch\fR
Six channels mode.
.TP
\fB\-C\fR | \fB\-\-iec958c\fR
Raw IEC958 (S/PDIF) consumer mode.
.TP
\fB\-P\fR | \fB\-\-iec958p\fR
Raw IEC958 (S/PDIF) professional mode.
.TP
\fB\-R\fR | \fB\-\-iec958r\fR
Raw IEC958 (S/PDIF) PCM.
.TP
\fB\-Z \fR\fB\fI#\fR\fR | \fB\-\-zero \fR\fB\fI#\fR\fR
Add
\fI#\fR
zero\-AC3\-frames before stream.
.TP
\fB\-q\fR | \fB\-\-quit\fR
Quit mode.
.SH "SEE ALSO"
.PP
\fBextract_ac3\fR(1).
.SH "AUTHOR"
.PP
This manual page was written by Mikael Magnusson
<mikma@users.sourceforge.net>
for the
Debian
system (but may be used by others). Permission is granted to copy, distribute and/or modify this document under the terms of the
GNU
General Public License, Version 2 or any later version published by the Free Software Foundation.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in
\fI/usr/share/common\-licenses/GPL\fR.
