.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "AS10K1" "1" "February 21, 2005" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
as10k1 \- assembler for the emu10k1(emu10k2) DSP
.SH "SYNOPSIS"
.HP 7
\fBas10k1\fR [\fBoption\fR...] \fIasmfile\fR
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBas10k1\fR
command.
.PP
This manual page was written for the
Debian
distribution because the original program does not have a manual page. Instead, it has documentation in the
GNUInfo
format; see below.
.PP
\fBas10k1\fR
is an assembler for the emu10k1(emu10k2) DSP processor found in Creative Lab's Sound Blaster Live!, Audigy and Audigy 2 series of sound cards. It is used to make audio effects such as a flanger, chorus or reverb.
.SH "OPTIONS"
.TP
\fB\-l \fR\fB\fIlistfile\fR\fR
Specify a listing file, default is none.
.TP
\fB\-o \fR\fB\fIemu10k1 file\fR\fR
Specify an output file, default is based on input, Substituting .asm to .emu10k1
.TP
\fB\-d \fR\fB\fIdbg_options\fR\fR
Turn on debug messages.
.RS
.TP
\fBs\fR
prints all symbols
.TP
\fBg\fR
prints defined gprs
.TP
\fBt\fR
prints tram usage
.TP
\fBt\fR
prints instructions
.RE
.TP
\fB\-h\fR
Prints a short help message.
.TP
\fB\-v\fR
Prints version number.
.SH "SEE ALSO"
.PP
lo10k1(1), ld10k1(8), dl10k1(8).
.SH "AUTHOR"
.PP
This manual page was written by Mikael Magnusson
<mikma@users.sourceforge.net>
for the
Debian
system (but may be used by others). Permission is granted to copy, distribute and/or modify this document under the terms of the
GNU
General Public License, Version 2 any later version published by the Free Software Foundation.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common\-licenses/GPL.
