.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "LO10K1" "1" "February 18, 2005" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
lo10k1 \- emu10k1(emu10k2) patch loader client
.SH "SYNOPSIS"
.HP 7
\fBlo10k1\fR [\fBoption\fR...]
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBlo10k1\fR
.PP
This manual page was written for the
Debian
distribution because the original program does not have a manual page.
.PP
\fBlo10k1\fR
is a program that...
.SH "OPTIONS"
.PP
These programs follow the usual
GNU
command line syntax, with long options starting with two dashes (`\-').
.TP
\fB\-h\fR | \fB\-\-help\fR
Prints a short help message
.TP
\fB\-l \fR\fB\fIpatch_name\fR\fR | \fB\-\-list \fR\fB\fIpatch_name\fR\fR
List some useful information about patch in file
\fIpatch_name\fR.
\fBlo10k1\fR
uses patch produced by
\fBas10k1\fR
from the alsa\-tools package.
.TP
\fB\-p \fR\fB\fIname\fR\fR | \fB\-\-pipe_name \fR\fB\fIname\fR\fR
\fBlo10k1\fR
will use a local named pipe named
\fIname\fR
to communicate with the linker. Default is
\fI/tmp/.ld10k1_port\fR
.TP
\fB\-i\fR \fB\-\-info\fR
Prints some info about card \- not very useful.
.TP
\fB\-s\fR \fB\-\-setup\fR
Clear DSP.
.TP
\fB\-a \fR\fB\fIpatch_name\fR\fR | \fB\-\-add \fR\fB\fIpatch_name\fR\fR
Loads patch from file
\fIpatch_name\fR
to DSP.
.TP
\fB\-d \fR\fB\fInumber\fR\fR | \fB\-\-del \fR\fB\fInumber\fR\fR
Unloads patch
\fInumber\fR
from DSP. Use option
\fB\-\-debug\fR
4 to obtain patch numbers.
.TP
\fB\-q \fR\fB\fIconn_string\fR\fR | \fB\-\-conadd \fR\fB\fIconn_string\fR\fR
Connect patches with each other, to inputs or outputs.
.TP
\fB\-w\fR \fB\-\-condel\fR
Delete connection.
.TP
\fB\-\-debug \fR\fB\fInumber\fR\fR
Print debug information
.RS
.TP
\fB1\fR
register information
.TP
\fB2\fR
List constants
.TP
\fB3\fR
List DSP instructions
.TP
\fB4\fR
Print TRAM information
.TP
\fB5\fR
List loaded patches
.TP
\fB6\fR
List patch order
.TP
\fB7\fR
List FXs
.TP
\fB8\fR
List inputs
.TP
\fB9\fR
List outputs
.TP
\fB100 + number\fR
Print information about patch
\fInumber\fR
.RE
.IP
.TP
\fB\-n\fR \fB\-\-defionames\fR
define default in/out names for loaded patch
.TP
\fB\-\-ctrl\fR
modify control parameters for loaded patch
.TP
\fB\-\-patch_name\fR
load patch with this name
.TP
\fB\-\-where \fR\fB\fInumber\fR\fR
insert patch before
.TP
\fB\-\-renam\fR
rename patch, input, output, fx, patch input, patch output
.TP
\fB\-\-dump\fR
dump DSP setup to file, can by loaded by dl10k1
.TP
\fB\-\-host\fR
lo10k1 uses network socket instead of named socked (host,port)
.TP
\fB\-P \fR\fB\fIpath\fR\fR \fB\-\-path \fR\fB\fIpath\fR\fR
Set include path
.TP
\fB\-\-store \fR\fB\fIfile\fR\fR
Store DSP config to native ld10k1
\fIfile\fR.
.TP
\fB\-\-restore\fR
Restore DSP config from native ld10k1
\fIfile\fR.
.TP
\fB\-\-save_patch\fR
Save patch specified with
\fB\-\-where\fR
to
\fIfile\fR.
.TP
\fB\-\-load_patch\fR
Load patch from
\fIfile\fR
to position specified with
\fB\-\-where\fR.
.TP
\fB\-\-wait \fR\fB\fImsec\fR\fR
Wait for
\fBld10k1\fR
for
\fImsec\fR.
.SH "SEE ALSO"
.PP
ld10k1(8), dl10k1(8), as10k1(1).
.SH "AUTHOR"
.PP
This manual page was written by Mikael Magnusson
<mikma@users.sourceforge.net>
for the
Debian
system (but may be used by others). Permission is granted to copy, distribute and/or modify this document under the terms of the
GNU
General Public License, Version 2 any later version published by the Free Software Foundation.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common\-licenses/GPL.
.SH "AUTHOR"
Mikael Magnusson. 
.br

      <mikma@users.sourceforge.net>
    
