.TH DLLWRAP 1 "26 Oct 2003" "Debian GNU/Linux"
.SH NAME
dllwrap \- Ancient tool for generating PE style dll's.
.SH DESCRIPTION
.B dllwrap 
is deprecated.  You should not use it for any new code.  Use
.B ld \-\-shared
instead.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show summary of options.
.SH AUTHOR
This manual page was written by Ron <ron@debian.org>,
for the Debian project (but may be used by others).
