#!/bin/sh -e

if [ $# -eq 2 ]  && ( [ "$1" = "install" ] || [ "$1" = "upgrade" ] ); then
    if [ "$2" = 0.3.3-4 ]; then
        # Don't care for changes in the X11R7 cm-super-x11.scale
        rm -f /etc/X11/fonts/X11R7/Type1/cm-super-x11.scale
    fi
fi

if dpkg-maintscript-helper supports rm_conffile 2>/dev/null; then
  dpkg-maintscript-helper rm_conffile /etc/defoma/hints/cm-super-x11.hints 0.3.4-3 -- "$@"
fi

#DEBHELPER#

exit 0
