.TH POSTFIX-ADD-POLICY 8
.ad
.fi
.SH NAME
postfix-add-policy
\-
add policy service to Postfix master.cf
.SH "SYNOPSIS"
.na
.nf
\fBpostfix-add-policy\fR [\fIpolicy name\fR...] [\fIusername\fR...] [\fIargv\fR...]
.SH DESCRIPTION
.ad
.fi
The \fBpostfix-add-policy\fR(8) command adds an smtp policy server named
\fIpolicy name\fR running using \fIusername\fR and called as \fIargv\fR to
\/etc/postfix/master.cf to facilitate integration of SMTP policy servers such as
postgrey or postfix-policyd-spf-perl.  The configuration is based on the Postfix
SMTPD_POLICY_README.  Adminstrators should verify it is appropriate for their
requirements.

The original file is copied prior to modification and left in /etc/postfix to
make it possible to revert changes easily.

Available in the Debian package for Postfix version 2.5.3 and later.

.SH DIAGNOSTICS
.ad
.fi
If the given \fIpolicy name\fR  already appears in the master.cf, a message will
be printed to standard out and master.cf will not be modified.

.SH "ENVIRONMENT"
.na
.nf
.ad
.fi
.IP \fBMAIL_CONFIG\fR
Directory with Postfix configuration files.

The \fBpostfix-add-policy\fR(8) command should use this, but it currently
doesn't.  It is hard coded to /etc/postfix.  This should be changed.
.SH "CONFIGURATION PARAMETERS"
.na
.nf
.ad
.fi
None
.SH "FILES"
.na
.nf
/etc/postfix/master.cf
.SH "SEE ALSO"
.na
.nf
postconf(5), Postfix configuration
.SH "LICENSE"
.na
.nf
.ad
.fi
This software is licensed under the MIT open source license.
.SH "AUTHOR(S)"
.na
.nf
Scott Kitterman
<scott@kitterman.com>
