.de EX
.ne 5
.if n .sp 1
.if t .sp .5
.nf
.in +.5i
..
.de EE
.fi
.in -.5i
.if n .sp 1
.if t .sp .5
..
.TH HSCOLOUR "1" "July 2009" "HsColour" "User Commands"
.SH NAME
HsColour \- generate colourised output for Haskell code
.SH SYNOPSIS
.B HsColour
\fIoptions \fR[\fIfile.hs\fR]
.SH DESCRIPTION
HsColour is a program that colourises Haskell code. It currently has six output
formats: ANSI terminal codes, HTML 3.2 with <font> tags, HTML 4.01 with CSS,
XHTML 1.0 with inline CSS styling, LaTeX, and mIRC chat client codes. 

.SS "Flag reference:"

.TP
\fB\-version\fR
Print out version information.
.TP
\fB\-help\fR
A rudimentary help message.

.TP
\fB\-o\fROUTPUT
Write the output to the specified file.

.TP
\fB\-tty\fR
Write output with ANSI terminal code colours (this is the default).

.TP
\fB\-html\fR
Write output in HTML 3.2 format with font tags.

.TP
\fB\-css\fR
Write output in HTML 4.01 format with CSS styling.

.TP
\fB\-icss\fR
Write output in XHTML 1.0 format with inline CSS styling.

.TP
\fB\-latex\fR
Write output as LaTeX source code.

.TP
\fB\-mirc\fR
Output for IRC.

.TP
\fB\-lit\fR
When outputting HTML etc, inform HsColour that the input Haskell code is
Literate Haskell.

.TP
\fB\-lit-tex\fR
When outputting LaTeX, inform HsColour that the input Haskell code is Literate
Haskell.

.TP
\fB\-anchor\fR
In HTML mode add named anchors.

.TP
\fB\-partial\fR
Create output fragments (ie omit the HTML DOCTYPE header, CSS stylesheet link,
or LaTeX prologue) for embedding in a larger document.

.TP
\fB\-print-css\fR
Print out the default CSS definitions, in case you lose the .css file. 

.TP
\fB\-nolit\fR
Turn off \fB\-lit\fR mode.

.TP
\fB\-noanchor\fR
Turn off \fB\-anchor\fR mode.

.TP
\fB\-nopartial\fR
Turn off \fB\-partial\fR mode.

.TP
The HsColour homepage is at http://www.cs.york.ac.uk/fp/darcs/hscolour/ .

.SH COPYRIGHT
Copyright \(co 2003-2009 Malcolm Wallace and Bjorn Bringert
.PP
This program comes with NO WARRANTY, to the extent permitted by law.
You may redistribute copies of this program
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

.SH AUTHOR
The text for this page was constructed from HsColour's main web page by
Erik de Castro Lopo <erikd@mega-nerd.com>, for the Debian GNU/Linux system
(but may be used by others).
