#! /bin/sh
# preinst.skeleton
# Skeleton maintainer script showing all the possible cases.
# Written by Charles Briscoe-Smith, March-June 1998.  Public Domain.

# Abort if any command returns an error value
set -e

# This script is called before this version of this package is installed.
# When this script is called, the package's files have not been unpacked
# yet.

case "$1" in
  install)
    # About to install this package.
    :
    if [ -d /var/www/usr/lib/latex2html ]; then
	rm -rf /var/www/usr/lib/latex2html
    else
	true;
    fi
    # Add a diversion.  This is one of the few things which may be done
    # before installing any files from the package.
    #: dpkg-divert --package foo --add --rename \
    #:             --divert /usr/bin/other.real /usr/bin/other

    # There are two sub-cases:
    if test "${2+set}" = set; then
      # The configuration files from version $2 of this package are
      # still on the system.
      :

    else
      # There is no existing configuration; install from scratch.
      :

    fi

    # Change the default config file name
    if [ -e /etc/latex2html.config ]; then
	cp /etc/latex2html.config /etc/latex2html.conf
    fi

    ;;
  upgrade)
    # About to upgrade this package from version $2 TO THIS VERSION.
    # "prerm upgrade" has already been called for the old version of
    # this package.
    :
    if [ -d /var/www/usr/lib/latex2html ]; then
	rm -rf /var/www/usr/lib/latex2html
    else
	true;
    fi

    # Change the default config file name
    if [ -e /etc/latex2html.config ]; then
	cp /etc/latex2html.config /etc/latex2html.conf
    fi

    ;;
  abort-upgrade)
    # Back out of an attempt to upgrade this package FROM THIS VERSION to
    # version $2.  Undo the effects of "postrm upgrade $2".
    :

    ;;
  *) echo "$0: didn't understand being called with \`$1'" 1>&2
     exit 0;;
esac

#DEBHELPER#

exit 0
