#!/bin/sh

set -e

case "$1" in
	remove)
		# nothing to do
		;;

	purge)
		# Remove old database
		rm -f /var/lib/dhcp3/dhcpd.leases /var/lib/dhcp3/dhcpd.leases~

		# Remove old database directory
		if [ -d /var/lib/dhcp3 ]; then
			rmdir --ignore-fail-on-non-empty /var/lib/dhcp3/
		fi

		# Remove init.d configuration file
		rm -f /etc/default/dhcp3-server
		;;

	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
		# Nothing to do
		;;
esac

#DEBHELPER#

exit 0
