.\"                                      Hey, EMACS: \-*\- nroff \-*\-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1\-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH PPS\-TOOLS 8 "05/22/2012"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage\-specific macros, see man(7)
.SH NAME
pps\-tools \- LinuxPPS support tools and headers
.SH DESCRIPTION
The
.B pps\-tools
package includes the necessary headers for using LinuxPPS PPSAPI
kernel interface in user\-space applications and several support tools.
.PP
.B ppstest: PPSAPI interface tester
.br
.B ppsldisc: setup correct RS232 line discipline
.br
.B ppswatch: continuously print PPS timestamps
.br
.B ppsctl: PPS device manager
.br
.B ppsfind: find pps device by name
.PP
Most tools display a short help message if you run them with \-\-help as option.
Unfortunately they do not come with any further documentation.
.SH "SEE ALSO"
The Wiki on http://linuxpps.org provides some documentation of the LinuxPPS PPSAPI interface.
.SH AUTHORS
This manual page was written by Bernd Zeimetz <bzed@debian.org>,
for the Debian project (and may be used by others).
