#!/bin/sh

set -e

if dpkg-divert --package gnuplot-x11 --list | grep -F /usr/bin/gnuplot-nox
then
    dpkg-divert --remove --package gnuplot-x11 --rename \
        --divert /usr/bin/gnuplot-nox /usr/bin/gnuplot
fi

if dpkg-divert --package gnuplot-x11 --list | grep -F /usr/share/man/man1/gnuplot-nox.1.gz
then
    dpkg-divert --remove --package gnuplot-x11 --rename \
        --divert /usr/share/man/man1/gnuplot-nox.1.gz \
        /usr/share/man/man1/gnuplot.1.gz
fi

#DEBHELPER#

exit 0
