.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH "CJK LaTeX batch commands" 1 29-Jun-2006 "CJK Version 4.6.0"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.\" ====
.\" ==== macro definitions by Werner Lemberg
.\" ====
.
.\" here we define \TeX for troff and nroff
.if t .ds TX \fRT\\h'-0.1667m'\\v'0.20v'E\\v'-0.20v'\\h'-0.125m'X\fP
.if n .ds TX TeX
.
.\" and here the same for \LaTeX
.if t \{\
.ie '\*(.T'dvi' \
.ds LX \fRL\h'-0.36m'\v'-0.15v'\s-3A\s0\h'-0.15m'\v'0.15v'\fP\*(TX
.el .ds LX \fRL\h'-0.36m'\v'-0.22v'\s-2A\s0\h'-0.15m'\v'0.22v'\fP\*(TX
.\}
.if n .ds LX LaTeX
.
.\" \LaTeXe
.\" note that we need \vareps for TeX instead of \eps which can only be
.\" accessed with the \N escape sequence (in the Math Italic font)
.if t \{\
.ie '\*(.T'dvi' .ds LE \*(LX\h'0.15m'2\v'0.20v'\f(MI\N'34'\fP\v'-0.20v'
.el .ds LE \*(LX\h'0.15m'2\v'0.20v'\(*e\v'-0.20v'
.\}
.if n .ds LE LaTeX\ 2e
.
.\" a typewriter font
.if t \{\
.de C
\fC\\$1\fP\\$2
..
.\}
.if n \{\
.de C
\\$1\\$2
..
.\}
.
.\" ====
.\" ==== end of macro definitions
.\" ====
.SH NAME
bg5latex     \- Use \*(LX directly on a Big5 encoded .tex file
.br
bg5pdflatex  \- Use pdf\*(LX directly on a Big5 encoded .tex file
.br
bg5+latex    \- Use \*(LX directly on a Big5+ encoded .tex file
.br
bg5+pdflatex \- Use pdf\*(LX directly on a Big5+ encoded .tex file
.br
cef5latex    \- Use \*(LX directly on a Big5 encoded .tex file
.br
               containing CEF macros
.br
cef5pdflatex \- Use pdf\*(LX directly on a Big5 encoded .tex file
.br
               containing CEF macros
.br
ceflatex     \- Use \*(LX directly on a .tex file containing CEF
.br
               macros
.br
cefpdflatex  \- Use pdf\*(LX directly on a .tex file containing CEF
.br
               macros
.br
cefslatex    \- Use \*(LX directly on an SJIS encoded .tex file
.br
               containing CEF macros
.br
cefspdflatex \- Use pdf\*(LX directly on an SJIS encoded .tex file
.br
               containing CEF macros
.br
gbklatex     \- Use \*(LX directly on a GBK encoded .tex file
.br
gbkpdflatex  \- Use pdf\*(LX directly on a GBK encoded .tex file
.br
sjislatex    \- Use \*(LX directly on an SJIS encoded .tex file
.br
sjispdflatex \- Use pdf\*(LX directly on an SJIS encoded .tex file
.
.
.SH SYNOPSIS
.B bg5latex
.RI "file.tex"
.br
.B bg5pdflatex
.RI "file.tex"
.br
etc.
.
.
.SH DESCRIPTION
This manual page briefly documents the different
.B *latex
batch files that come with the CJK LaTeX macro.
.
.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
The \fB*latex\fP commands are shell scripts that will convert a
(Big5(+), GBK or SJIS encoded) .tex file in a .cjk file using the
respective \fB*conv\fP command resulting in a .cjk file, and will then
run (\fBpdf\fP)\fBlatex\fP on the .cjk file.
.PP
If you use Big5+ encoding, then use \fBbg5+latex\fP or
\fBbg5+pdflatex\fP.
.PP
If you use CEF macro's in your Big5 or SJIS encoded file, use
\fBcef5latex\fP or \fBcefslatex\fP resp. instead.  If it's in plain
ASCII, use \fBceflatex\fP.
.PP
If you use GNU/Emacs (>=20), you don't have to use any of these
commands: just put the Lisp file "cjk-enc.el" in Emacs' load-path,
load the library "cjk-enc" and run "M-x cjk-write-file" to create
a .cjk file.  Then process the .cjk file with \fBlatex\fP or
\fBpdflatex\fP.
.SH SEE ALSO
.BR bg5conv (1),
.BR bg5+conv (1),
.BR cef5conv (1),
.BR cefconv (1),
.BR cefsconv (1),
.BR extconv (1),
.BR sjisconv (1),
the \fBCJK\fP documentation files in
/usr/share/doc/latex-cjk-common/.
.
.
.SH AVAILABILITY
The \fB*latex\fP scripts are part of the CJK macro package for \*(LE
available at the CTAN hosts and its mirrors, and available for Debian
under latex-cjk-chinese and latex-cjk-japanese.
.
.
.SH AUTHOR
The programs mentioned under \fBNAME\fP were written by Werner
Lemberg <wl@gnu.org>.
.PP
This manual page was written by Danai SAE-HAN <danai.sae-han@edpnet.be>
for the Debian project.  It is licensed under the GNU General Public
License version 2 or higher, of which you can find a copy online at
http://www.gnu.org/licenses/gpl.txt or on Debian systems under
/usr/share/common-licenses/GPL-2 (part of the "base-files" package).
