debian/tmp/usr/bin/sjis*
texinput/JIS/EUC-JP* usr/share/texmf/tex/latex/CJK/JIS/
texinput/JIS/JIS* usr/share/texmf/tex/latex/CJK/JIS/
texinput/SJIS/SJIS* usr/share/texmf/tex/latex/CJK/SJIS/
texinput/UTF8/ja.cpx usr/share/texmf/tex/latex/CJK/UTF8/
contrib/wadalab/DNP.sfd usr/share/texmf/fonts/sfd/
contrib/wadalab/wadalab.txt usr/share/doc/latex-cjk-common/
doc/japanese usr/share/doc/latex-cjk-common/
debian/README.Debian-msgothic usr/share/doc/latex-cjk-common/
examples/JIS.tex usr/share/doc/latex-cjk-common/examples/
examples/SJIS.tex usr/share/doc/latex-cjk-common/examples/

texinput/SJIS/c49song.fd usr/share/texmf/tex/latex/CJK/SJIS/
texinput/JIS/c*song.fd usr/share/texmf/tex/latex/CJK/JIS/
