texinput/thai/c90* usr/share/texmf/tex/latex/CJK/thai/
texinput/thai/thaicjk.ldf usr/share/texmf/tex/generic/babel/
doc/thaifont.txt usr/share/doc/latex-cjk-common/
examples/thai*.tex usr/share/doc/latex-cjk-common/examples/
utils/thaifont/tools usr/share/latex-cjk-common/utils/thaifont/
utils/thaifont/texmf/fonts/map/dvips/*/*.map usr/share/texmf/fonts/map/dvips/latex-cjk-thai/
build_thaifonts/c90.enc usr/share/texmf/fonts/enc/dvips/latex-cjk-thai/
build_thaifonts/*.tfm usr/share/texmf/fonts/tfm/latex-cjk-thai/
utils/lisp/emacs/thai-word.el usr/share/emacs/site-lisp/latex-cjk-thai/

# Uncomment these two lines if you don't want CJK to depend
# on ThaiLaTeX for its fonts
#debian/thaifonts/*.afm usr/share/texmf/fonts/afm/latex-cjk-thai/
#debian/thaifonts/*.pfb usr/share/texmf/fonts/type1/latex-cjk-thai/
