debian/tmp/usr/bin/bg5* usr/bin/
debian/tmp/usr/bin/cef* usr/bin/
debian/tmp/usr/bin/extconv usr/bin/
debian/tmp/usr/bin/gbk* usr/bin/

texinput/Bg5/Bg5.* usr/share/texmf/tex/latex/CJK/Bg5/
texinput/Bg5/HK.enc usr/share/texmf/tex/latex/CJK/Bg5/
texinput/CNS/EUC-TW.* usr/share/texmf/tex/latex/CJK/CNS/
texinput/GB/GB.* usr/share/texmf/tex/latex/CJK/GB/
texinput/UTF8/zh-Han?.cpx usr/share/texmf/tex/latex/CJK/UTF8/

doc/CEF.txt usr/share/doc/latex-cjk-common/
doc/chinese/ usr/share/doc/latex-cjk-common/

#debian/Arphic_test.{dvi,ps.gz,tex}
examples/Big5.tex usr/share/doc/latex-cjk-common/examples/
examples/Big5vert.tex usr/share/doc/latex-cjk-common/examples/
examples/CEF_test.tex usr/share/doc/latex-cjk-common/examples/
examples/GB.tex usr/share/doc/latex-cjk-common/examples/
debian/arphic-sampler.tex usr/share/doc/latex-cjk-common/examples/

# Toneless pinyin hyphenation patterns and Babel language file
utils/pyhyphen/pinyin.ldf usr/share/texmf/tex/generic/babel/
utils/pyhyphen/pyhyph.tex usr/share/texmf/tex/generic/hyphen/
utils/pyhyphen/pytest.tex usr/share/doc/latex-cjk-common/examples/
