#!/bin/sh

set -e

if [ -L /etc/apache2/conf.d/javascript-common.conf ]
then
	rm -f /etc/apache2/conf.d/javascript-common.conf
	restart="apache2"
fi

if [ -L /etc/lighttpd/conf-enabled/90-javascript-alias.conf ]
then
	rm -f /etc/lighttpd/conf-enabled/90-javascript-alias.conf
	restart="lighttpd"
fi

if [ -e /usr/share/wwwconfig-common/restart.sh ]
then
	servers="apache2 lighttpd"
	. /usr/share/wwwconfig-common/restart.sh
fi

#DEBHELPER#

exit 0
