# To be changed into an in extenso list if plugins are added
usr/lib/graphviz/libgvplugin_core.so.*
usr/lib/graphviz/libgvplugin_gd.so.*
usr/lib/graphviz/libgvplugin_neato_layout.so.*
usr/lib/graphviz/libgvplugin_pango.so.*
usr/lib/graphviz/libgvplugin_xlib.so.*
usr/lib/graphviz/libgvplugin_dot_layout.so.*
usr/lib/libgvc*.so.*

# Renamed afterwards to libgvcN-config-update in debian/rules
usr/bin/dot usr/sbin
