#!/bin/sh

set -e

if [ "$1" = configure ] && dpkg --compare-versions "$2" lt-nl 0.9.0-2 ; then
    [ -x /usr/share/update-notifier/notify-reboot-required ] && \
        /usr/share/update-notifier/notify-reboot-required || true
fi

#DEBHELPER#

if [ "$1" =  configure ] && dpkg --compare-versions "$2" lt 0.9.0-4; then
    # Ask D-Bus to reload the config file
    if [ -x "/etc/init.d/dbus" ]; then
        invoke-rc.d dbus force-reload || true
    fi
fi

exit 0
