/* Generated by make-libxfce4util-alias.pl. Do not edit this file. */

#ifdef HAVE_GNUC_VISIBILITY

#include <glib.h>

#define IN_HEADER defined
#define IN_SOURCE(x) 1

#if IN_HEADER(__LIBXFCE4UTIL_CONFIG_H__)
#if IN_SOURCE(__LIBXFCE4UTIL_CONFIG_C__)
#endif
#endif
#if IN_HEADER(__XFCE_FILEUTILS_H__)
#if IN_SOURCE(__XFCE_FILEUTILS_C__)
extern __typeof (xfce_mkdirhier) IA__xfce_mkdirhier __attribute((visibility("hidden")));
#define xfce_mkdirhier IA__xfce_mkdirhier

#endif
#endif
#if IN_HEADER(__XFCE_I18N_H__)
#if IN_SOURCE(__XFCE_I18N_C__)
extern __typeof (xfce_textdomain) IA__xfce_textdomain __attribute((visibility("hidden")));
#define xfce_textdomain IA__xfce_textdomain

extern __typeof (xfce_get_file_localized) IA__xfce_get_file_localized __attribute((visibility("hidden"))) G_GNUC_MALLOC;
#define xfce_get_file_localized IA__xfce_get_file_localized

extern __typeof (xfce_get_file_localized_r) IA__xfce_get_file_localized_r __attribute((visibility("hidden")));
#define xfce_get_file_localized_r IA__xfce_get_file_localized_r

extern __typeof (xfce_get_dir_localized) IA__xfce_get_dir_localized __attribute((visibility("hidden"))) G_GNUC_MALLOC;
#define xfce_get_dir_localized IA__xfce_get_dir_localized

extern __typeof (xfce_get_dir_localized_r) IA__xfce_get_dir_localized_r __attribute((visibility("hidden")));
#define xfce_get_dir_localized_r IA__xfce_get_dir_localized_r

extern __typeof (xfce_get_path_localized) IA__xfce_get_path_localized __attribute((visibility("hidden")));
#define xfce_get_path_localized IA__xfce_get_path_localized

extern __typeof (xfce_locale_match) IA__xfce_locale_match __attribute((visibility("hidden")));
#define xfce_locale_match IA__xfce_locale_match

#endif
#endif
#if IN_HEADER(__XFCE_KIOSK_H__)
#if IN_SOURCE(__XFCE_KIOSK_C__)
extern __typeof (xfce_kiosk_new) IA__xfce_kiosk_new __attribute((visibility("hidden"))) G_GNUC_MALLOC;
#define xfce_kiosk_new IA__xfce_kiosk_new

extern __typeof (xfce_kiosk_query) IA__xfce_kiosk_query __attribute((visibility("hidden")));
#define xfce_kiosk_query IA__xfce_kiosk_query

extern __typeof (xfce_kiosk_free) IA__xfce_kiosk_free __attribute((visibility("hidden")));
#define xfce_kiosk_free IA__xfce_kiosk_free

#endif
#endif
#if IN_HEADER(__XFCE_LICENSE_H__)
#if IN_SOURCE(__XFCE_LICENSE_C__)
extern __typeof (xfce_get_license_text) IA__xfce_get_license_text __attribute((visibility("hidden"))) G_GNUC_PURE;
#define xfce_get_license_text IA__xfce_get_license_text

#endif
#endif
#if IN_HEADER(__XFCE_MISCUTILS_H__)
#if IN_SOURCE(__XFCE_MISCUTILS_C__)
extern __typeof (xfce_version_string) IA__xfce_version_string __attribute((visibility("hidden"))) G_GNUC_PURE;
#define xfce_version_string IA__xfce_version_string

extern __typeof (xfce_get_homedir) IA__xfce_get_homedir __attribute((visibility("hidden"))) G_GNUC_PURE;
#define xfce_get_homedir IA__xfce_get_homedir

extern __typeof (xfce_get_homefile_r) IA__xfce_get_homefile_r __attribute((visibility("hidden")));
#define xfce_get_homefile_r IA__xfce_get_homefile_r

extern __typeof (xfce_get_userdir) IA__xfce_get_userdir __attribute((visibility("hidden"))) G_GNUC_PURE;
#define xfce_get_userdir IA__xfce_get_userdir

extern __typeof (xfce_get_userfile_r) IA__xfce_get_userfile_r __attribute((visibility("hidden")));
#define xfce_get_userfile_r IA__xfce_get_userfile_r

extern __typeof (xfce_strjoin) IA__xfce_strjoin __attribute((visibility("hidden"))) G_GNUC_MALLOC;
#define xfce_strjoin IA__xfce_strjoin

extern __typeof (xfce_gethostname) IA__xfce_gethostname __attribute((visibility("hidden"))) G_GNUC_MALLOC;
#define xfce_gethostname IA__xfce_gethostname

extern __typeof (xfce_putenv) IA__xfce_putenv __attribute((visibility("hidden")));
#define xfce_putenv IA__xfce_putenv

extern __typeof (xfce_setenv) IA__xfce_setenv __attribute((visibility("hidden")));
#define xfce_setenv IA__xfce_setenv

extern __typeof (xfce_unsetenv) IA__xfce_unsetenv __attribute((visibility("hidden")));
#define xfce_unsetenv IA__xfce_unsetenv

extern __typeof (xfce_expand_variables) IA__xfce_expand_variables __attribute((visibility("hidden"))) G_GNUC_MALLOC;
#define xfce_expand_variables IA__xfce_expand_variables

#endif
#endif
#if IN_HEADER(__XFCE_POSIX_SIGNAL_HANDLER_H__)
#if IN_SOURCE(__XFCE_POSIX_SIGNAL_HANDLER_C__)
extern __typeof (xfce_posix_signal_handler_init) IA__xfce_posix_signal_handler_init __attribute((visibility("hidden")));
#define xfce_posix_signal_handler_init IA__xfce_posix_signal_handler_init

extern __typeof (xfce_posix_signal_handler_shutdown) IA__xfce_posix_signal_handler_shutdown __attribute((visibility("hidden")));
#define xfce_posix_signal_handler_shutdown IA__xfce_posix_signal_handler_shutdown

extern __typeof (xfce_posix_signal_handler_set_handler) IA__xfce_posix_signal_handler_set_handler __attribute((visibility("hidden")));
#define xfce_posix_signal_handler_set_handler IA__xfce_posix_signal_handler_set_handler

extern __typeof (xfce_posix_signal_handler_restore_handler) IA__xfce_posix_signal_handler_restore_handler __attribute((visibility("hidden")));
#define xfce_posix_signal_handler_restore_handler IA__xfce_posix_signal_handler_restore_handler

#endif
#endif
#if IN_HEADER(__XFCE_RESOURCE_H__)
#if IN_SOURCE(__XFCE_RESOURCE_C__)
extern __typeof (xfce_resource_dirs) IA__xfce_resource_dirs __attribute((visibility("hidden"))) G_GNUC_MALLOC;
#define xfce_resource_dirs IA__xfce_resource_dirs

extern __typeof (xfce_resource_lookup) IA__xfce_resource_lookup __attribute((visibility("hidden"))) G_GNUC_MALLOC;
#define xfce_resource_lookup IA__xfce_resource_lookup

extern __typeof (xfce_resource_lookup_all) IA__xfce_resource_lookup_all __attribute((visibility("hidden"))) G_GNUC_MALLOC;
#define xfce_resource_lookup_all IA__xfce_resource_lookup_all

extern __typeof (xfce_resource_match) IA__xfce_resource_match __attribute((visibility("hidden"))) G_GNUC_MALLOC;
#define xfce_resource_match IA__xfce_resource_match

extern __typeof (xfce_resource_match_custom) IA__xfce_resource_match_custom __attribute((visibility("hidden"))) G_GNUC_MALLOC;
#define xfce_resource_match_custom IA__xfce_resource_match_custom

extern __typeof (xfce_resource_push_path) IA__xfce_resource_push_path __attribute((visibility("hidden")));
#define xfce_resource_push_path IA__xfce_resource_push_path

extern __typeof (xfce_resource_pop_path) IA__xfce_resource_pop_path __attribute((visibility("hidden")));
#define xfce_resource_pop_path IA__xfce_resource_pop_path

extern __typeof (xfce_resource_save_location) IA__xfce_resource_save_location __attribute((visibility("hidden"))) G_GNUC_MALLOC;
#define xfce_resource_save_location IA__xfce_resource_save_location

#endif
#endif
#if IN_HEADER(__XFCE_RC_H__)
#if IN_SOURCE(__XFCE_RC_C__)
extern __typeof (xfce_rc_simple_open) IA__xfce_rc_simple_open __attribute((visibility("hidden"))) G_GNUC_MALLOC;
#define xfce_rc_simple_open IA__xfce_rc_simple_open

extern __typeof (xfce_rc_config_open) IA__xfce_rc_config_open __attribute((visibility("hidden"))) G_GNUC_MALLOC;
#define xfce_rc_config_open IA__xfce_rc_config_open

extern __typeof (xfce_rc_close) IA__xfce_rc_close __attribute((visibility("hidden")));
#define xfce_rc_close IA__xfce_rc_close

extern __typeof (xfce_rc_flush) IA__xfce_rc_flush __attribute((visibility("hidden")));
#define xfce_rc_flush IA__xfce_rc_flush

extern __typeof (xfce_rc_rollback) IA__xfce_rc_rollback __attribute((visibility("hidden")));
#define xfce_rc_rollback IA__xfce_rc_rollback

extern __typeof (xfce_rc_is_dirty) IA__xfce_rc_is_dirty __attribute((visibility("hidden")));
#define xfce_rc_is_dirty IA__xfce_rc_is_dirty

extern __typeof (xfce_rc_is_readonly) IA__xfce_rc_is_readonly __attribute((visibility("hidden")));
#define xfce_rc_is_readonly IA__xfce_rc_is_readonly

extern __typeof (xfce_rc_get_locale) IA__xfce_rc_get_locale __attribute((visibility("hidden")));
#define xfce_rc_get_locale IA__xfce_rc_get_locale

extern __typeof (xfce_rc_get_groups) IA__xfce_rc_get_groups __attribute((visibility("hidden")));
#define xfce_rc_get_groups IA__xfce_rc_get_groups

extern __typeof (xfce_rc_get_entries) IA__xfce_rc_get_entries __attribute((visibility("hidden")));
#define xfce_rc_get_entries IA__xfce_rc_get_entries

extern __typeof (xfce_rc_delete_group) IA__xfce_rc_delete_group __attribute((visibility("hidden")));
#define xfce_rc_delete_group IA__xfce_rc_delete_group

extern __typeof (xfce_rc_get_group) IA__xfce_rc_get_group __attribute((visibility("hidden")));
#define xfce_rc_get_group IA__xfce_rc_get_group

extern __typeof (xfce_rc_has_group) IA__xfce_rc_has_group __attribute((visibility("hidden")));
#define xfce_rc_has_group IA__xfce_rc_has_group

extern __typeof (xfce_rc_set_group) IA__xfce_rc_set_group __attribute((visibility("hidden")));
#define xfce_rc_set_group IA__xfce_rc_set_group

extern __typeof (xfce_rc_delete_entry) IA__xfce_rc_delete_entry __attribute((visibility("hidden")));
#define xfce_rc_delete_entry IA__xfce_rc_delete_entry

extern __typeof (xfce_rc_has_entry) IA__xfce_rc_has_entry __attribute((visibility("hidden")));
#define xfce_rc_has_entry IA__xfce_rc_has_entry

extern __typeof (xfce_rc_read_entry) IA__xfce_rc_read_entry __attribute((visibility("hidden")));
#define xfce_rc_read_entry IA__xfce_rc_read_entry

extern __typeof (xfce_rc_read_entry_untranslated) IA__xfce_rc_read_entry_untranslated __attribute((visibility("hidden")));
#define xfce_rc_read_entry_untranslated IA__xfce_rc_read_entry_untranslated

extern __typeof (xfce_rc_read_bool_entry) IA__xfce_rc_read_bool_entry __attribute((visibility("hidden")));
#define xfce_rc_read_bool_entry IA__xfce_rc_read_bool_entry

extern __typeof (xfce_rc_read_int_entry) IA__xfce_rc_read_int_entry __attribute((visibility("hidden")));
#define xfce_rc_read_int_entry IA__xfce_rc_read_int_entry

extern __typeof (xfce_rc_read_list_entry) IA__xfce_rc_read_list_entry __attribute((visibility("hidden"))) G_GNUC_MALLOC;
#define xfce_rc_read_list_entry IA__xfce_rc_read_list_entry

extern __typeof (xfce_rc_write_entry) IA__xfce_rc_write_entry __attribute((visibility("hidden")));
#define xfce_rc_write_entry IA__xfce_rc_write_entry

extern __typeof (xfce_rc_write_bool_entry) IA__xfce_rc_write_bool_entry __attribute((visibility("hidden")));
#define xfce_rc_write_bool_entry IA__xfce_rc_write_bool_entry

extern __typeof (xfce_rc_write_int_entry) IA__xfce_rc_write_int_entry __attribute((visibility("hidden")));
#define xfce_rc_write_int_entry IA__xfce_rc_write_int_entry

extern __typeof (xfce_rc_write_list_entry) IA__xfce_rc_write_list_entry __attribute((visibility("hidden")));
#define xfce_rc_write_list_entry IA__xfce_rc_write_list_entry

#endif
#endif
#if IN_HEADER(__XFCE_UTF8_H__)
#if IN_SOURCE(__XFCE_UTF8_C__)
extern __typeof (xfce_utf8_remove_controls) IA__xfce_utf8_remove_controls __attribute((visibility("hidden")));
#define xfce_utf8_remove_controls IA__xfce_utf8_remove_controls

extern __typeof (xfce_utf8_strndup) IA__xfce_utf8_strndup __attribute((visibility("hidden"))) G_GNUC_MALLOC;
#define xfce_utf8_strndup IA__xfce_utf8_strndup

#endif
#endif

#endif /* HAVE_GNUC_VISIBILITY */
