#! /bin/sh
set -e

case "$1" in
  configure)
    if dpkg --compare-versions "$2" lt-nl 2.00-6; then
      # Force dpkg to replace this directory with a symlink.
      if [ ! -L /usr/share/doc/grub-linuxbios ] && [ -d /usr/share/doc/grub-linuxbios ]; then
        if rmdir /usr/share/doc/grub-linuxbios 2>/dev/null; then
          ln -sf grub-common /usr/share/doc/grub-linuxbios
        fi
      fi
    fi
  ;;
esac

#DEBHELPER#

exit 0
