#!/bin/sh

set -e

# mpicc seemed to be used as a master alternative by some MPI package. But
# currently, all MPI packages have the mpicc alternative installed as a slave
# link. We remove the link here in order to resolve bugs #531184 and #532910.

update-alternatives --quiet --remove-all mpicc >/dev/null 2>&1 || true
update-alternatives --quiet --remove-all mpiCC >/dev/null 2>&1 || true

#DEBHELPER#

exit 0
