#!/bin/sh

set -e

update-alternatives \
	--install /usr/include/mpi mpi /usr/lib/openmpi/include 40 \
	--slave /usr/lib/libmpi.so libmpi.so /usr/lib/openmpi/lib/libmpi.so \
	--slave /usr/lib/libmpi++.so libmpi++.so /usr/lib/openmpi/lib/libmpi_cxx.so \
	--slave /usr/lib/libmpif77.so libmpif77.so /usr/lib/openmpi/lib/libmpi_f77.so \
	--slave /usr/lib/libmpif90.so libmpif90.so /usr/lib/openmpi/lib/libmpi_f90.so \
	--slave /usr/bin/mpicc mpicc /usr/bin/mpicc.openmpi \
	--slave /usr/bin/mpic++ mpic++ /usr/bin/mpic++.openmpi \
	--slave /usr/bin/mpicxx mpicxx /usr/bin/mpic++.openmpi \
	--slave /usr/bin/mpiCC mpiCC /usr/bin/mpic++.openmpi \
	--slave /usr/bin/mpif77 mpif77 /usr/bin/mpif77.openmpi \
	--slave /usr/bin/mpif90 mpif90 /usr/bin/mpif90.openmpi \
	--slave /usr/share/man/man1/mpicc.1.gz mpicc.1.gz /usr/share/man/man1/mpicc.openmpi.1.gz \
	--slave /usr/share/man/man1/mpic++.1.gz mpic++.1.gz /usr/share/man/man1/mpic++.openmpi.1.gz \
	--slave /usr/share/man/man1/mpicxx.1.gz mpicxx.1.gz /usr/share/man/man1/mpicxx.openmpi.1.gz \
	--slave /usr/share/man/man1/mpiCC.1.gz mpiCC.1.gz /usr/share/man/man1/mpiCC.openmpi.1.gz \
	--slave /usr/share/man/man1/mpif77.1.gz mpif77.1.gz /usr/share/man/man1/mpif77.openmpi.1.gz \
	--slave /usr/share/man/man1/mpif90.1.gz mpif90.1.gz /usr/share/man/man1/mpif90.openmpi.1.gz

#DEBHELPER#

exit 0
