.TH report-hw
.SH NAME
report-hw - dump information on the system's hardware
.SH SYNOPSIS
.B report-hw
.SH DESCRIPTION
.I report-hw
outputs a summary of the system's hardware to standard output. This
hardware summary is aimed at diagnosing problems with hardware autodection,
or other problems during a Debian install, but can also be useful to run
on an installed system.
.SH AUTHOR
The debian-installer team.
