.TH CRAMFSCK 8 "2002 January 1st" "KERNEL SOURCE" "Debian GNU/Linux Manual"
.SH NAME
cramfsck \- check a compressed ROM file system
.SH SYNOPSIS
.B cramfsck
.RB [ -hv ]
.RB [ -x
.IR dir ]
.I file
.SH DESCRIPTION
This manual page documents briefly the
.B cramfsck
command.
This manual page was written for the
.B Debian GNU/Linux
distribution (but may be used by others), because the original
program does not have a manual page.
.PP
.B cramfsck
checks the consistency of a
.B CramFs
file system given by
.IR file .
Unlike other file system checkers, it does not attempt to repair a broken
file system.  This is not a deficiency as
.B CramFs
is not subject to the kind of corruption that a writable file system may
endure.
.PP
.B cramfsck
is also able to extract the contents of the file system.
.SH OPTIONS
.TP
.B -h
Give a brief help message.
.TP
.B -v
Turn on verbose mode.
.TP
.BI "-x " dir
In addition to checking the given file system, extract its contents into
.IR dir .
.SH AUTHOR
.B cramfsck
is written by Linus Torvalds and Daniel Quinlan.  Manual page added by
Herbert Xu.
