.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SEXP\-CONV 1 "July 2011" "nettle 2.2"  "Nettle tools"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
nettle\-hash \- compute message digests
.SH SYNOPSIS
.B nettle-hash -a
.I ALGORITHM
.RI [ OPTIONS ]
.RI [ FILE ]...
.SH DESCRIPTION
This manual page documents briefly the
.B nettle\-hash
command.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
Instead, it has documentation in the GNU Info format; see below.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBnettle\-hash\fP is a program that computes various message digests.
The output is different from the familiar md5sum and sha*sum
family. For each file, the file name and a colon is printed first,
unless input is read from standard input, in which case nothing is
printed. Then the hash is printed in chunks of 64 bits (16 hexadecimal
digits) followed by the name of the algorithm. In raw (binary) mode,
the hash is not split in chunks and is not followed by a newline.

.SH OPTIONS
This program follows the usual GNU command line syntax, with long
options starting with two dashes (`-').  A summary of options is
included below.  For a complete description, see the Info files.
.TP
.B \-a, \-\-algorithm=\fIalgorithm\fP
Compute hash using \fIalgorithm\fP.
.TP
.B \-l, \-\-length=\fIlength\fP
Truncate digests at \fIlength\fP octets. It is an error to specify a
\fIlength\fP greater than the normal length of the selected digest.
.TP
.B \-\-list
List supported hash algorithms.
.TP
.B \-\-help
Show summary of options.
.TP
.B \-V, \-\-version
Show version of program.
.SH SEE ALSO
.BR md5sum (1),
.BR sha1sum (1),
etc.
.SH AUTHOR
This manual page was originally written by Magnus Holmgren <holmgren@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
