.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH PKCS1\-CONV 1 "June 2007" "nettle 1.15" "Nettle tools"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
pkcs1\-conv \- convert keys from PKCS#1 format to s-expression format
.SH SYNOPSIS
.B pkcs1-conv
.RB [{ \-\-private-rsa-key | \-\-public-rsa-key | \-\-public-key-info }
.RB [ \-\-base-64 ]]
.RI <\  FILE
.SH DESCRIPTION
This manual page documents briefly the
.B pkcs1\-conv
command.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBpkcs1\-conv\fP converts private and public RSA keys from PKCS #1 
format to sexp format.
.SH OPTIONS
This program follows the usual GNU command line syntax, with long
options starting with two dashes (`\-').
.PP
By default pkcs1-conv expects a PEM-encapsulated RSA key on standard input,
and will determine its type from the Pre-Encapsulation Boundary.
To convert a DER-encoded (non PEM-encoded) key, one of the first three
options below must be used:
.TP
.B \-\-private-rsa-key
Specify that a DER-encoded RSAPrivateKey, as defined by PKCS #1 (RFC 3447),
and described in section A.1.2 of its appendix A, is to be expected as input.
.TP
.B \-\-public-rsa-key
Specify that a DER-encoded RSAPublicKey, as defined by PKCS #1 (RFC 3447),
and described in section A.1.1 of its appendix A, is to be expected as input.
.TP
.B \-\-public-key-info
Specify that a DER-encoded SubjectPublicKeyInfo, as defined by PKCS #6, 
and described in section A.1 of its appendix A, encapsulating an RSAPublicKey,
is to be expected as input.
.TP
.B \-\-base-64
Together with \-\-private-rsa-key, \-\-public-rsa-key, or \-\-public-key-info,
specify that base64 encoding is applied on top of the DER encoding.
.TP
.B \-?, \-\-help
Show summary of options (not implemented).
.TP
.B \-V, \-\-version
Show version of program.
.SH DIAGNOSTICS
pkcs1\-conv will complain and exit with a status of 1
if the input doesn't match expectations. In PEM mode 
(when no option is used), if no PEM block is found, pkcs1\-conv
will output nothing but exit with a zero status.
.SH EXAMPLES
.nf
$ openssl genrsa \-out privkey.pem
$ pkcs1\-conv < privkey.pem > privkey.sexp
$ openssl rsa \-in privkey.pem \-outform DER \-out privkey.der
$ openssl rsa \-in privkey.pem \-outform DER \-pubout \-out pubkey.der
$ pkcs1-conv \-\-rsa-private-key < privkey.der > privkey.sexp
$ pkcs1-conv \-\-public-key-info < pubkey.der > pubkey.sexp
.fi
.SH SEE ALSO
.BR ssh\-conv (1),
.BR sexp\-conv (1),
.BR rsa (1SSL),
.BR genrsa (1SSL),
RFC 3447.
.SH AUTHOR
This manual page was written by Magnus Holmgren <holmgren@debian.org>
for the Debian GNU/Linux system (but may be used by others).
.SH COPYRIGHT
Copyright © 2007 Magnus Holmgren.
.P
Copying and distribution of this file, with or without modification,
are permitted in any medium without royalty provided the copyright
notice and this notice are preserved.
