usr/bin/bin2c
usr/bin/crt/link.stub		usr/lib/nvidia-cuda-toolkit/bin/crt/
usr/bin/cudafe
usr/bin/cudafe++
usr/bin/cuda-memcheck
usr/bin/cuobjdump
usr/bin/fatbin
usr/bin/fatbinary
usr/bin/filehash
usr/bin/nvlink
usr/bin/nvprof
usr/bin/ptxas

usr/bin/nvcc			usr/lib/nvidia-cuda-toolkit/bin/
debian/nvcc			usr/bin/
debian/nvcc.profile		etc/
debian/gcc			usr/lib/nvidia-cuda-toolkit/bin/
debian/g++			usr/lib/nvidia-cuda-toolkit/bin/

usr/open64/bin/nvopencc		usr/lib/nvidia-cuda-toolkit/bin/
usr/open64/lib/be		usr/lib/nvidia-cuda-toolkit/lib/
usr/open64/lib/gfec		usr/lib/nvidia-cuda-toolkit/lib/
usr/open64/lib/inline		usr/lib/nvidia-cuda-toolkit/lib/
debian/nvopencc			usr/bin/

usr/nvvm/cicc			usr/lib/nvidia-cuda-toolkit/bin/
usr/nvvm/ci_include.h		usr/lib/nvidia-cuda-toolkit/bin/
