.TH CN3D 1 2001-10-05 NCBI "NCBI Tools User's Manual"
.SH NAME
Cn3D \- a 3-dimensional viewer for biological molecules
.SH SYNOPSIS
.B Cn3D
[\|\fIfilename\fP\|]
.SH DESCRIPTION
This manual page documents briefly the \fBCn3D\fP command.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.PP
\fBCn3D\fP is a helper application for your web browser that allows
you to view 3-dimensional structures from NCBI's Entrez retrieval
service.
.SH OPTIONS
.TP
\fIfilename\fP
Initially display the data in \fIfilename\fP.
.SH AUTHOR
This manual page was written by Aaron M. Ucko <ucko@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
.SH SEE ALSO
.ad l
.BR ddv (1),
.BR udv (1),
<http://www.ncbi.nlm.nih.gov/Structure/CN3D/cn3d.shtml>
