usr/share/doc/libtelepathy-glib-doc/telepathy-glib
# Many of the examples are in subdirectories, which dh_installexamples
# can't do (without copying the whole directory, which we don't want either)
# so we do them here.
examples/client/*.c /usr/share/doc/libtelepathy-glib-doc/examples/client
examples/client/*.am /usr/share/doc/libtelepathy-glib-doc/examples/client
examples/extensions/*.xml /usr/share/doc/libtelepathy-glib-doc/examples/extensions
examples/extensions/*.c /usr/share/doc/libtelepathy-glib-doc/examples/extensions
examples/extensions/*.h /usr/share/doc/libtelepathy-glib-doc/examples/extensions
examples/extensions/*.am /usr/share/doc/libtelepathy-glib-doc/examples/extensions
examples/cm/*.am /usr/share/doc/libtelepathy-glib-doc/examples/cm
examples/cm/call/*.am /usr/share/doc/libtelepathy-glib-doc/examples/cm/call
examples/cm/call/*.c /usr/share/doc/libtelepathy-glib-doc/examples/cm/call
examples/cm/call/*.h /usr/share/doc/libtelepathy-glib-doc/examples/cm/call
examples/cm/channelspecific/*.am /usr/share/doc/libtelepathy-glib-doc/examples/cm/channelspecific
examples/cm/channelspecific/*.c /usr/share/doc/libtelepathy-glib-doc/examples/cm/channelspecific
examples/cm/channelspecific/*.h /usr/share/doc/libtelepathy-glib-doc/examples/cm/channelspecific
examples/cm/contactlist/*.am /usr/share/doc/libtelepathy-glib-doc/examples/cm/contactlist
examples/cm/contactlist/*.c /usr/share/doc/libtelepathy-glib-doc/examples/cm/contactlist
examples/cm/contactlist/*.h /usr/share/doc/libtelepathy-glib-doc/examples/cm/contactlist
examples/cm/echo-message-parts/*.am /usr/share/doc/libtelepathy-glib-doc/examples/cm/echo-message-parts
examples/cm/echo-message-parts/*.c /usr/share/doc/libtelepathy-glib-doc/examples/cm/echo-message-parts
examples/cm/echo-message-parts/*.h /usr/share/doc/libtelepathy-glib-doc/examples/cm/echo-message-parts
examples/cm/extended/*.am /usr/share/doc/libtelepathy-glib-doc/examples/cm/extended
examples/cm/extended/*.c /usr/share/doc/libtelepathy-glib-doc/examples/cm/extended
examples/cm/extended/*.h /usr/share/doc/libtelepathy-glib-doc/examples/cm/extended
examples/cm/no-protocols/*.am /usr/share/doc/libtelepathy-glib-doc/examples/cm/no-protocols
examples/cm/no-protocols/*.c /usr/share/doc/libtelepathy-glib-doc/examples/cm/no-protocols
examples/cm/no-protocols/*.h /usr/share/doc/libtelepathy-glib-doc/examples/cm/no-protocols
