.TH GWIBBER 1 "JULY 2012" Linux "User Manuals"
.SH NAME
Gwibber \- Open source social networking client for GNOME
.SH SYNOPSIS
.B gwibber-preferences
has no
.B [
.I OPTIONS
.B ]
.SH DESCRIPTION
.B gwibber-preferences
handles preferences for gwibber. You should not run this binary separately
unless you want to debug any issues with gwibber.
.SH BUGS
Please report all bugs to the Gwibber bug tracker:
<http://launchpad.net/gwibber/>
.SH AUTHOR
Kartik Mistry <kartik@debian.org>

Copyright 2010-2012, Licensed under a Creative Commons Attribution-ShareAlike
License <http://creativecommons.org/licenses/by-sa/3.0/>
