.TH GWIBBER 1 "JULY 2012" Linux "User Manuals"
.SH NAME
Gwibber \- Open source social networking client for GNOME
.SH SYNOPSIS
.B gwibber-client [
.I OPTIONS
.B ]
.SH DESCRIPTION
.B gwibber-client
is wrapper script for gwibber.
.SH OPTIONS
.TP
\-h, \-\-help
Show help message and exit.
.TP
\-r \fIrefresh\fR
Refresh operation in the Gwibber Service.
.TP
\-q, \-quit
Shutdown the Gwibber Service.
.TP
\-m \fIMESSAGE\fR, \-\-message=\fIMESSAGE\fR
Message to post.
.SH BUGS
Please report all bugs to the Gwibber bug tracker:
<http://launchpad.net/gwibber>
.SH AUTHOR
Kartik Mistry <kartik@debian.org>

Copyright 2011-2012. Licensed under a Creative Commons Attribution-ShareAlike
License <http://creativecommons.org/licenses/by-sa/3.0/>
