.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SOAPCPP2 1 "Juni 27, 2003"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
soapcpp2 \- the gSOAP Stub and Skeleton Compiler for C and C++
.SH SYNOPSIS
\fBsoapcpp2\fR [\fIOPTIONS\fR] \fIINPUT\fR
.SH DESCRIPTION
Please see /usr/share/doc/gsoap/soapdoc2.html for details.
.PP
Create stubs and client and server code from input \fIINPUT\fR or
standard input if \fIINPUT\fR is not specified.
.SH OPTIONS
.TP
\fB\-1\fR
Generate SOAP 1.1 bindings.
.TP
\fB\-2\fR
Generate SOAP 1.2 bindings.
.TP
\fB\-C\fR
Generate client-side code only.
.TP
\fB\-S\fR
Generate server-side code only.
.TP
\fB\-T\fR
Generate server-side auto-test code.
.TP
\fB\-L\fR
Do not generate \fBsoapClientLib\fR/\fBsoapServerLib\fR.
.TP
\fB\-a\fR
Use \fBSOAPAction\fR HTTP/WSA header to invoke server-side operations.
.TP
\fB\-b\fR
Serialize byte arrays char[N] as string.
.TP
\fB\-c\fR
Generate C source code.
.TP
\fB\-d\fIpath\fR
Use \fIpath\fR to save files.
.TP
\fB\-e\fR
Generate SOAP RPC encoding style bindings.
.TP
\fB\-f\fIN\fR
File split of \fIN\fR XML serializer implementations per file (N>=10).
.TP
\fB\-h\fR
Display help info.
.TP
\fB\-I\fIpath\fR
use \fIpath\fR(s) for \fB#import\fR.
.TP
\fB\-i\fR
Generate C++ service proxies and objects inherited from \fBsoap\fR struct.
.TP
\fB\-j\fR
Generate C++ service proxies and objects that share a \fBsoap\fR struct.
.TP
\fB\-k\fR
Generate data structure walkers (experimental).
.TP
\fB\-l\fR
Generate linkable modules (experimental).
.TP
\fB\-m\fR
Generate Matlab(tm) code for MEX compiler.
.TP
\fB\-n\fR
Use service name to rename service functions and namespace table.
.TP
\fB\-p\fIname\fR
Save files with new prefix \fIname\fR instead of \fBsoap\fR.
.TP
\fB\-q\fIname\fR
Use \fIname\fR as the C++ namespace of all declarations.
.TP
\fB\-s\fR
Generate deserialization code with strict XML validation checks.
.TP
\fB\-t\fR
Generate code for fully \fBxsi:type\fR typed SOAP/XML messaging.
.TP
\fB\-u\fR
Uncomment comments in WSDL/schema output by suppressing XML comments.
.TP
\fB\-v\fR
Display version info.
.TP
\fB\-w\fR
Do not generate WSDL and schema files.
.TP
\fB\-x\fR
Do not generate sample XML message files.
.TP
\fB\-y\fR
Include C/C++ type access information in sample XML messages.
.SH SEE ALSO
.BR wsdl2h (1).
.SH AUTHOR
This manual page was written by Thomas Wana <greuff@debian.org>,
for the Debian project (but may be used by others).
