debian/tmp/usr/bin/aptitude-*-state-bundle
debian/tmp/usr/share/aptitude/aptitude-defaults*
debian/tmp/usr/share/aptitude/section-descriptions
debian/tmp/usr/share/aptitude/function_groups
debian/tmp/usr/share/aptitude/function_pkgs
debian/tmp/usr/share/aptitude/help*.txt
debian/tmp/usr/share/aptitude/mine-help*.txt
debian/tmp/usr/share/aptitude/FAQ
debian/tmp/usr/share/aptitude/README*
debian/tmp/usr/share/aptitude/NEWS
debian/tmp/usr/share/locale/

debian/README.Debian TODO usr/share/doc/aptitude
src/generic/apt/README.hier usr/share/doc/aptitude
src/generic/apt/pkg_hier* usr/share/doc/aptitude/examples
