#!/bin/sh

set -e

case "${1}" in
	install)
		for FILE in zcat zcmp zdiff zegrep zfgrep zgrep
		do
			dpkg-divert --package zutils --quiet --add --rename --divert /bin/${FILE}.gzip /bin/${FILE}
			dpkg-divert --package zutils --quiet --add --rename --divert /usr/share/man/man1/${FILE}.gzip.1.gz /usr/share/man/man1/${FILE}.1.gz
		done
		;;

	upgrade|abort-upgrade)

		;;

	*)
		echo "preinst called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
