#!/bin/sh

set -e

OLDCFGFILE=/etc/reader.conf
CFGDIR=/var/lib/pcscd
CFGFILE="$CFGDIR/reader.conf"

# /etc/reader.conf is no more used
if [ -f $OLDCFGFILE ]; then
	mv $OLDCFGFILE $OLDCFGFILE.old
fi

# remove /var/lib/pcscd
if [ -d $CFGDIR ]; then
	rm -rf $CFGDIR
fi

# create the pcscd group
addgroup --system pcscd --quiet

# enable pcscd for systemd
[ -x /bin/systemctl ] && [ -d /sys/fs/cgroup/systemd ] && systemctl enable pcscd.socket

#DEBHELPER#
