#!/bin/sh

set -e

if [ "$1" = "purge" ] ; then

  # Remove configuration file
  if [ -f /etc/reader.conf ]; then
    rm -f /etc/reader.conf
  fi

  # Remove configuration file backup
  if [ -f /etc/reader.conf.old ]; then
    rm -f /etc/reader.conf.old
  fi

  # remove cfgdir if it's not in use
  if [ -d /etc/reader.conf.d ]; then
    files=`ls /etc/reader.conf.d`
    if [ -z "$files" ]; then
      rmdir /etc/reader.conf.d
    fi
  fi

fi

#DEBHELPER#
