.TH ERB1.9 1 "April 2003"
.SH NAME
.PP
erb \- an embedded Ruby language interpreter
.SH SYNOPSIS
.PP
erb1.9.1 [switches] [inputfile]
.SH DESCRIPTION
.PP
erb interprets a Ruby code embedded text file. For example, erb
enables you to embed a Ruby code to a HTML file.
A Ruby block starts with `<%' and ends with `%>'. erb replaces
the block with its output.
If `<%' is followed by `=', eRuby replaces the block with a value
of the block.
If `<%' is followed by `#', the block is ignored as a comment.
.SH OPTIONS
.PP

.TP
.fi
.B
\-x
print ruby script
.TP
.fi
.B
\-n
print ruby script with line number
.TP
.fi
.B
\-v
enables verbose mode
.TP
.fi
.B
\-d
set debugging flags (set $DEBUG to true)
.TP
.fi
.B
\-r library
load a library
.TP
.fi
.B
\-K kcode
specifies KANJI code\-set (euc or sjis) or UTF\-8 (utf8)
.TP
.fi
.B
\-S safe_level
set $SAFE (0..4)
.TP
.fi
.B
\-T trim_mode
specify trim_mode (0..2)
.TP
.fi
.B
\-P
disregard the lin which starts in "%" 
.SH SEE ALSO
.PP
eruby(1)
.SH AUTHOR
.PP
This document stands on eruby(1) which is written by Shugo Maeda
<shugo@ruby\-lang.org>.

