.TH GEM1.9.1 "1" "Dec 2007" "gem1.9.1 1.0.0" "User Commands"
.SH NAME
gem1.9.1 \- the front end to RubyGems
.SH SYNOPSIS
.IP
gem1.9.1 command [arguments...] [options...]
.IP
gem1.9.1 \fB\-h\fR | \-\-help
.IP
gem1.9.1 \fB\-v\fR | \-\-version
.fi
.SH DESCRIPTION
.B gem1.9.1
is the front end to RubyGems, a sophisticated package manager for Ruby. This is a
basic help message containing pointers to more information.
.PP
Further help:
.TP
gem1.9.1 help commands
list all 'gem1.9.1' commands
.TP
gem1.9.1 help examples
show some examples of usage
.TP
gem1.9.1 help <COMMAND>
show help on COMMAND
.IP
(e.g. 'gem1.9.1 help install')
.IP
.PP
Further information:
.IP
http://rubygems.org/
.SH EXAMPLES
.IP
.nf
gem1.9.1 install rake
gem1.9.1 list \fB\-\-local\fR
gem1.9.1 build package.gemspec
gem1.9.1 help install
.fi
