.TH RAKE1.9 "1" "July 2006" "ruby 1.9.0" "User Commands"
.SH NAME
rake1.9.1 \- a ruby build program with capabilities similar to make
.SH SYNOPSIS
.IP
rake1.9.1 [-f rakefile] [options] targets...
.IP
rake1.9.1 \-\-help
.IP
rake1.9.1 \-\-version
.fi
.SH DESCRIPTION
.B rake1.9.1
is a simple ruby build program with capabilities similar to make.
This is a basic help message containing pointers to more information.
.PP
Further help:
.TP
rake1.9.1 --help
list all 'rake1.9.1' options
.PP
Further information:
.IP
http://rake.rubyforge.org/
