Document: pcsx2
Title: Debian pcsx2 Manual
Author: <insert document author here>
Abstract: This manual describes what pcsx2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pcsx2/pcsx2.sgml.gz

Format: postscript
Files: /usr/share/doc/pcsx2/pcsx2.ps.gz

Format: text
Files: /usr/share/doc/pcsx2/pcsx2.text.gz

Format: HTML
Index: /usr/share/doc/pcsx2/html/index.html
Files: /usr/share/doc/pcsx2/html/*.html
