#!/bin/sh
# preinst script for fox
#
# see: dh_installdeb(1)

set -e

vers=1.6

# remove still existing alternatives from older packages

if test -e /etc/alternatives/fox-config; then
    update-alternatives --remove fox-config /usr/bin/fox-config-$vers  2>/dev/null
fi
if test -e /etc/alternatives/reswrap; then
    update-alternatives --remove reswrap /usr/bin/reswrap-$vers        2>/dev/null
fi

#DEBHELPER#

exit 0
