#!/bin/sh
# postinst script for fox
#
# see: dh_installdeb(1)

set -e

vers=1.6
prio=16

if [ "$1" = "configure" ]; then

  update-alternatives --install /usr/bin/fox-config fox-config \
    /usr/bin/fox-config-${vers}  ${prio} \
    --slave /usr/share/man/man1/fox-config.1.gz fox-config.1.gz \
    /usr/share/man/man1/fox-config-${vers}.1.gz

  update-alternatives --install /usr/bin/reswrap reswrap \
    /usr/bin/reswrap-${vers}  ${prio} \
    --slave /usr/share/man/man1/reswrap.1.gz reswrap.1.gz \
    /usr/share/man/man1/reswrap-${vers}.1.gz

fi

#DEBHELPER#

exit 0
