.pc
.TH KVM-NBD 1
.SH NAME
kvm-NBD \- obsolete QEMU Disk Network Block Device Server
.SH DESCRIPTION
This is an obsolete utility used by old kvm and qemu-kvm packages
in Debian.  The functionality is now provided by qemu-nbd utility.
Currently kvm-nbd just prints a warning and executes qemu-nbd with
all provided options.
.SH "SEE ALSO"
.BR qemu-nbd (8).
