.pc
.TH KVM-IMG 1
.SH NAME
kvm-img \- obsolete QEMU disk image utility
.SH DESCRIPTION
This is an obsolete utility used by old kvm and qemu-kvm packages
in Debian.  The functionality is now provided by qemu-img utility.
Currently kvm-img just prints a warning and executes qemu-img with
all provided options.
.SH "SEE ALSO"
.BR qemu-img (8).
