.TH PVTK 1
.SH NAME
pvtk \- Visualization Tool Kit
.SH SYNOPSIS
.B mpirun -np 4 -machinefile ~/machines pvtk
.I [script] -MPDENV- DISPLAY=:0

.SH "DESCRIPTION"
This manual page documents briefly the
.B pvtk
command.
Better info can be found at
http://www.vtk.org

.SH AUTHORS
Ken Martin, Will Schroeder, and Bill Lorensen
