.TH VTK 1
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
vtkpython \- Visualization Tool Kit
.SH SYNOPSIS
.B vtkpython
.I vtk_script.py

.SH "DESCRIPTION"
This manual page documents briefly the
.B vtkpython
command.
Better info can be found at
http://public.kitware.com/VTK

.PP
.B vtkpython
This program is like the python interpreter 
.I python
but is linked with The Visualization Toolkit libraries.

.SH OPTIONS
Hopefully, it accepts the same arguments as
.I python

.SH "SEE ALSO"
python(1)

.SH AUTHORS
Ken Martin, Will Schroeder, and Bill Lorensen


This manual page was written by A. Maitland Bottoms
<bottoms@debian.org> for the Debian GNU/Linux system (but may be used by others).
