.TH SCREENLETS-DAEMON 1 "June 5, 2008"

.SH NAME
screenlets-daemon \- An application to track activity of Screenlets

.SH SYNOPSIS
.B screenlets-daemon 

.SH DESCRIPTION
\fBscreenlets-daemon\fP is a program which tracks Screenlets activity.

.SH AUTHOR
screenlets-manager was written by Rico Pfaus <ryx@ryxperience.com>.
.PP
This manual page was written by Julien Lavergne <julien.lavergne@gmail.com>,
for the Debian project (but may be used by others).
