.TH SCREENLETS-DEBIANIZER 1 "October 29, 2010"

.SH NAME
screenlets-debianizer \- An application to debianize Screenlets
.SH SYNOPSIS
.B screenlets-debianizer

.SH DESCRIPTION
\fBscreenlets-debianizer\fP is a program for debianizing Screenlets, Widget-
like mini-applications for GNOME. You can launch it with the directory of your 
screenlets to release it.

.SH AUTHOR
screenlets-packager was written by Guido Tabbernuk <boamaod@gmail.com>.

