.TH SCREENLETS-MANAGER 1 "July 16, 2007"

.SH NAME
screenlets-manager \- An application to manage Screenlets

.SH SYNOPSIS
.B screenlets-manager

.SH DESCRIPTION
\fBscreenlets-manager\fP is a preferences GUI for managing Screenlets, 
Widget-like mini-applications for GNOME. You can launch or stop one, make them 
start on login, install or uninstall others screenlets.

.SH AUTHOR
screenlets-manager was written by Rico Pfaus <ryx@ryxperience.com>.
.PP
This manual page was written by Julien Lavergne <julien.lavergne@gmail.com>,
for the Debian project (but may be used by others).
