.TH SCREENLETS 1 "June 5, 2008"

.SH NAME
screenlets \- Widget-like mini-applications for GNOME

.SH SYNOPSIS
.B screenlets

.SH DESCRIPTION
\fBscreenlets\fP are small owner-drawn applications that can be described as 
"the virtual representation of things lying/standing around on your desk" : 
sticky notes, clocks, rulers, ....
screenlets actually starts screenlets-manager, the GUI to manage all 
screenlets (see man screenlets-manager).

.SH AUTHOR
screenlets was written by Rico Pfaus <ryx@ryxperience.com>.
.PP
This manual page was written by Julien Lavergne <julien.lavergne@gmail.com>,
for the Debian project (but may be used by others).
