.TH SCREENLETS-PACKAGER 1 "July 16, 2007"

.SH NAME
screenlets-packager \- An application to package Screenlets
.SH SYNOPSIS
.B screenlets-packager

.SH DESCRIPTION
\fBscreenlets-packager\fP is a program for packaging Screenlets, Widget-like 
mini-applications for GNOME. You can launch it with the directory of your 
screenlets to release it.

.SH AUTHOR
screenlets-packager was written by Rico Pfaus <ryx@ryxperience.com>.
.PP
This manual page was written by Julien Lavergne <julien.lavergne@gmail.com>,
for the Debian project (but may be used by others).
