#!/bin/sh

set -e

# Script used to generate the orig source tarball for afpfs-ng.

AFPFS_NG_UPSTREAM_VERSION="0.8.1"
AFPFS_NG_DOWNLOAD_URL="http://downloads.sourceforge.net/project/afpfs-ng/afpfs-ng/${AFPFS_NG_UPSTREAM_VERSION}/afpfs-ng-${AFPFS_NG_UPSTREAM_VERSION}.tar.bz2"
AFPFS_NG_TARBALL_CHECKSUM="688560de1cde57ab8d9e0ef7dc6436dbf0267fe8884f9014e50ff92b297b01a8"

# Download and verify afpfs-ng upstream tarball
test -f "afpfs-ng-${AFPFS_NG_UPSTREAM_VERSION}.tar.bz2" || wget -c "${AFPFS_NG_DOWNLOAD_URL}"
COMPUTED_CHECKSUM=`sha256sum "afpfs-ng-${AFPFS_NG_UPSTREAM_VERSION}.tar.bz2" | cut -d ' ' -f 1`
if [ $AFPFS_NG_TARBALL_CHECKSUM != $COMPUTED_CHECKSUM ] ; then
  echo "Checksum verification failed. Checksum was $COMPUTED_CHECKSUM
Expected checksum $AFPFS_NG_TARBALL_CHECKSUM."
  exit 1
else
  echo "Checksum verified. Checksum is $COMPUTED_CHECKSUM."
fi
rm -rf "afpfs-ng-${AFPFS_NG_UPSTREAM_VERSION}"
tar -xjf "afpfs-ng-${AFPFS_NG_UPSTREAM_VERSION}.tar.bz2"
cd "afpfs-ng-${AFPFS_NG_UPSTREAM_VERSION}"
patch -p1 <"../$(dirname $0)/patches/include-headers-fix.patch"
autoreconf -vif
cd ..

# Remove temp files and other cruft from source tarball
# The find command snippet here was taken from debhelper's dh_clean command
# with some modification to delete more unneeded files.
echo "Removing temp files and other cruft from source tarball"
find afpfs-ng-${AFPFS_NG_UPSTREAM_VERSION} \( \( -type f -a \
  \( -name '#*#' -o -name '.*~' -o -name '*~' -o -name DEADJOE \
  -o -name '*.orig' -o -name '*.rej' -o -name '*.bak' \
  -o -name '.*.orig' -o -name .*.rej -o -name '.SUMS' \
  -o -name TAGS -o \( -path '*/.deps/*' -a -name '*.P' \) \
  -o -name config.status -o -name config.cache -o -name config.log \
  \) -exec rm -f "{}" \; \) -o \
  \( -type d -a -name autom4te.cache -prune -exec rm -rf "{}" \; \) \)

# Remove file under APSL-1.1
rm -f afpfs-ng-${AFPFS_NG_UPSTREAM_VERSION}/fuse/mount_afp.1

# Remove empty directories
echo "Removing empty directories"
find afpfs-ng-${AFPFS_NG_UPSTREAM_VERSION} -type d -empty -delete

rm -f "afpfs-ng_${AFPFS_NG_UPSTREAM_VERSION}.orig.tar.gz"
tar --exclude-vcs -czf "afpfs-ng_${AFPFS_NG_UPSTREAM_VERSION}.orig.tar.gz" \
  "afpfs-ng-${AFPFS_NG_UPSTREAM_VERSION}/"
