.\" http://svn.xfce.org/svn/Xfce/xfdesktop/trunk/panel-plugin/Xfce4-popup-menu.c
.\" sets Olivier Fourdan as author

.TH "XFCE4-POPUP-MENU" "1" "2006-11-18" "4.3.99.1" 
.SH "NAME"
xfce4-popup-menu \- shows the Xfce Menu 

.SH "SYNOPSIS"
.B xfce4-popup-menu

.SH "DESCRIPTION" 
.B xfce4-popup-menu
shows the Xfce Menu on a panel if at least one Xfce Menu button is present on
one of your panel(s). The behaviour of  
.B xfce4-popup-menu
is to show only one menu, so if you have several Xfce Menu buttons, only the
first you have defined will pop up the menu.

If you want to show the Xfce Menu under your current mouse position see the
manual page for
.IR xfdesktop (1).


.SH "SEE ALSO"
.IR xfdesktop (1)

.SH "AUTHOR" 
.B xfce4-popup-menu
was written by Olivier Fourdan <fourdan@xfce.org>.
.PP
This manual page was written by Francois Wendling <frwendling@free.fr> for the
Debian project (but may be used by others).
