#!/bin/sh

set -e

# If /etc/freetds has been removed, this is a special case, probably
# caused by purging a previous libct version.  Unconditionally restore
# freetds.conf in this case.
if [ ! -d /etc/freetds ]; then
   mkdir /etc/freetds
    cp -a /usr/share/freetds/freetds.conf /etc/freetds/
fi

# Install a reasonable default on initial config

if [ -z "$2" ] && [ ! -e /etc/freetds/freetds.conf ]; then
    cp -a /usr/share/freetds/freetds.conf /etc/freetds/
fi

#DEBHELPER#
