.\" In .TH, FOO should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.\"
.\" This template provided by Tom Christiansen <tchrist@jhereg.perl.com>.
.\" 
.TH RAKE 1
.SH NAME
rake \- a ruby build program with capabilities similar to make
.SH SYNOPSIS
A short usage summary.
.PP
.B rake
.I options
.\".SH DESCRIPTION
.\" Putting a newline after each sentence can generate better output.
.\"Rake is a simple ruby build program with capabilities similar to make.

.SH OPTIONS
.TP
.BR  \-n,\-\-dry\-run
      Do a dry run without executing actions.
.TP
.BR  \-H,\-\-help
      Display this help message.
.TP
.BR  \-I,\-\-libdir=LIBDIR
      Include LIBDIR in the search path for required modules.
.TP
.BR  \-N\-\-nosearch
      Do not search parent directories for the Rakefile.
.TP
.BR  \-P,\-\-prereqs
      Display the tasks and dependencies, then exit.
.TP
.BR  \-q,\-\-quiet
      Do not log messages to standard output
.TP
.BR  \-f,\-\-rakefile=FILE     
      Use FILE as the rakefile.
.TP
.BR  \-r,\-\-require=MODULE    
      Require MODULE before executing rakefile.
.TP
.BR  \-s,\-\-silent            
      Like \-\-quiet, but also suppresses the 'in directory' announcement.
.TP
.BR  \-T,\-\-tasks             
      Display the tasks and dependencies, then exit.
.TP
.BR  \-t,\-\-trace              
      Turn on invoke/execute tracing, enable full backtrace.
.TP
.BR  \-h,\-\-usage              
      Display usage.
.TP
.BR  \-v,\-\-verbose            
      Log message to standard output (default).
.TP
.BR  \-V,\-\-version           
      Display the program version.

.\".SH "RETURN VALUE"
.\"What the program or function returns if successful.
.\".SH ERRORS
.\"Return codes, either exit status or errno settings.
.\".SH EXAMPLES
.\"Give some example uses of the program.
.SH AUTHOR
Manpage provided by Adam Majer as part of the Debian's rake
package. Upstream author of rake is Jim Weirich.
.SH "SEE ALSO"
.\" Always quote multiple words for .SH
Full documentation is available in /usr/share/doc/rake/html
