.TH libvncserver-config 1 "19 November 2011" "libvncserver 0.9.8.2" "libvncserver-config manual"
.SH NAME
libvncserver-config \- Get information about a libvncserver installation
.SH SYNOPSIS
.B libvncserver-config \fI[--prefix[=DIR]] [--exec-prefix[=DIR]] [--version]
\fI[\-\-link] [\-\-libs] [\-\-cflags]
.SH DESCRIPTION
.B libvncserver-config
displays information about a previous libvncserver installation.
.SH OPTIONS
.IP "--prefix=DIR"
Shows location where architecture-independent files are stored.
.IP "--exec-prefix=DIR"
Shows location where architecture-dependent files are stored.
.IP "--version"
Shows libvncserver version.
.IP "--link"
Shows the complete set of linking options libvncserver has been built with.
.IP "--libs"
Shows the complete set of libs and other linker options you will need in order
to link your application with libvncserver.
.IP "--cflags"
Set of compiler options (CFLAGS) to use when compiling files that use
libvncserver.
.SH "EXAMPLES"
What linker options do I need when I link with libvncserver?

  libvncserver-config \-\-libs

What compiler options do I need when I compile using libvncserver functions?

  libvncserver-config \-\-cflags
.SH AUTHOR
This manual page was written by Ludovic Drolez <ldrolez@debian.org>
for the Debian GNU/Linux system (but may be used by others).
