debian/tmp//usr/lib/llvm-3.2/lib/*		/usr/lib/llvm-3.2/lib/
debian/tmp//usr/lib/llvm-3.2/include/llvm/	usr/include/llvm-3.2/
debian/tmp//usr/lib/llvm-3.2/include/llvm-c/	usr/include/llvm-c-3.2/

build-llvm/Makefile.common		/usr/lib/llvm-3.2/build/
build-llvm/Makefile.config		/usr/lib/llvm-3.2/build/
build-llvm/config.status		/usr/lib/llvm-3.2/build/
Makefile.rules			/usr/lib/llvm-3.2/build/
configure			/usr/lib/llvm-3.2/build/
autoconf/			/usr/lib/llvm-3.2/build/

utils/vim/llvm.vim		usr/share/vim/addons/syntax/llvm-3.2.vim
utils/vim/tablegen.vim		usr/share/vim/addons/syntax/tablegen-3.2.vim

utils/emacs/emacs.el		usr/share/emacs/site-lisp/llvm-3.2/
utils/emacs/llvm-mode.el	usr/share/emacs/site-lisp/llvm-3.2/
utils/emacs/tablegen-mode.el	usr/share/emacs/site-lisp/llvm-3.2/

