libsocialweb/sw-core.h usr/include/libsocialweb/libsocialweb
usr/include/libsocialweb/interfaces/
usr/include/libsocialweb/libsocialweb-keyfob/
usr/include/libsocialweb/libsocialweb-keystore/
usr/include/libsocialweb/libsocialweb/
usr/lib/*/libsocialweb-keyfob.so
usr/lib/*/libsocialweb-keystore.so
usr/lib/*/libsocialweb.so
usr/lib/*/pkgconfig/libsocialweb-keyfob.pc
usr/lib/*/pkgconfig/libsocialweb-keystore.pc
usr/lib/*/pkgconfig/libsocialweb-module.pc
