etc/dbus-1/system.d/ConsoleKit.conf
etc/ConsoleKit/
usr/share/dbus-1/system-services/
usr/share/polkit-1/
usr/lib/ConsoleKit/
var/log/ConsoleKit/
usr/sbin/
usr/bin/
debian/90consolekit etc/X11/Xsession.d/
lib/systemd/system/console-kit-daemon.service
lib/systemd/system/console-kit-log-system-start.service
lib/systemd/system/console-kit-log-system-stop.service
lib/systemd/system/console-kit-log-system-restart.service
lib/systemd/system/basic.target.wants/console-kit-log-system-start.service
lib/systemd/system/halt.target.wants/console-kit-log-system-stop.service
lib/systemd/system/poweroff.target.wants/console-kit-log-system-stop.service
lib/systemd/system/reboot.target.wants/console-kit-log-system-restart.service
