.TH FAKECHANGES 1  "May 10, 2010"

.SH NAME
fakechanges \- reverse engineer a Debian .changes file.

.SH SYNOPSIS
.B fakechanges
.RI "[OPTION]  files..."

.SH DESCRIPTION
fakechanges can reverse engineer the .changes file from the .debs, .dsc,
 .tar.gz, .diff.gz, etc from a package build.

.SH AUTHOR
This manual page was originally written by Erik de Castro Lopo 
<erikd@mega-nerd.com> for the Debian GNU/Linux system (but may be used by 
others).
