.TH CREATE-GNURADIO-OUT-OF-TREE-PROJECT "1" "December 2011" "create-gnuradio-out-of-tree-project 3.5" "User Commands"
.SH NAME
create-gnuradio-out-of-tree-project \- Create a prototype 'out of tree' GNU Radio project
.SH SYNOPSIS
.B create-gnuradio-out-of-tree-project:
[\fIoptions\fR] [\fInew_module_name\fR]
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-T\fR TARBALL, \fB\-\-tarball\fR=TARBALL
path to gr-howto-build-a-block gzipped tarball [default=<get from web>]
.SH "SEE ALSO"
The full documentation for
.B create-gnuradio-out-of-tree-project
is maintained as an HTML file.
See http://gnuradio.org/redmine/projects/gnuradio/wiki/BlocksCodingGuide
