.TH FILE_RX_HRPT "1" "December 2011" "file_rx_hrpt 3.5" "User Commands"
.SH NAME
file_rx_hrpt \- USRP HRPT Receiver
.SH SYNOPSIS
.B file_rx_hrpt:
[\fIoptions\fR]
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.SH "SEE ALSO"
The full documentation for
.B file_rx_hrpt
is maintained as an HTML file.  If the
.B gnuradio-doc
package is properly installed at your site
.IP
.B usr/share/doc/gnuradio-doc/html/noaa__api_8h.html
.PP
should give you access to the complete manual.
