.TH USRP_FLEX "1" "December 2011" "usrp_flex 3.5" "User Commands"
.SH NAME
usrp_flex \- demodulate Flex protocol signals with GNU Radio
.SH SYNOPSIS
.B usrp_flex
[\fIoptions\fR]
.SH DESCRIPTION
demodulate Flex protocol.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-f\fR FREQ, \fB\-\-freq\fR=\fIFREQ\fR
Set receive frequency to FREQ [default=none]
.TP
\fB\-a\fR ADDRESS, \fB\-\-address\fR=\fIADDRESS\fR
Address of UHD device, [default=addr=192.168.10.2]
.TP
\fB\-A\fR ANTENNA, \fB\-\-antenna\fR=\fIANTENNA\fR
select Rx Antenna where appropriate
.TP
\fB\-\-rx\-gain\fR=\fIRX_GAIN\fR
set receive gain in dB (default is midpoint)
.TP
\fB\-c\fR Hz, \fB\-\-calibration\fR=\fIHz\fR
set frequency offset to Hz
.HP
\fB\-v\fR, \fB\-\-verbose\fR
.TP
\fB\-l\fR, \fB\-\-log\fR
log flowgraph to files (LOTS of data)
.TP
\fB\-F\fR FROM_FILE, \fB\-\-from\-file\fR=\fIFROM_FILE\fR
read samples from file instead of USRP
.SH "SEE ALSO"
usrp_flex_all(1) usrp_flex_band(1)
