.TH "LV2_INSPECT" 1 "2 Apr 2009"       
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH LV2_INSPECT 1 "2 Apr 2009"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
.B lv2_inspect \- lv2_inspect, lv2_jack_host, lv2_list 
and
.B lv2_simple_jack_host 
are collection of programs which caring for connecting LV2 plugins (http://lv2plug.in) to jackd.
.SH SYNOPSIS
.B lv2_inspect


.SH SEE ALSO
.BR slv2, 
and
.BR jackd 

.SH AUTHOR
lv2_inspect was written by Dave Robillard.
.PP
This manual page was written by Jaromír Mikeš <mira.mikes@seznam.cz>,
for the Debian project (but may be used by others).
