#!/bin/sh

set -e

# Yes, this uses debconf.
. /usr/share/debconf/confmodule

if [ "$1" = configure ]; then
	# Always update the files; the config script makes sure ths
	# variables always have a sane and current value in them.

	db_get shared/news/server
	echo "$RET" > /etc/news/server

        file=/etc/default/slrnpull
        if test -e $file
        then
            db_get slrnpull/run_from
            sed -i -e "/^[^#]*RUNFROM=/s/=.*/='$RET'/" $file
        fi
fi

#DEBHELPER#
