debian/tmp/usr/share/locale	usr/share
debian/tmp/usr/share/slrn	usr/share

contrib/cleanscore contrib/slrnrc-conv		usr/share/slrn/contrib
contrib/NEWS* contrib/README.*			usr/share/doc/slrn/contrib

debian/default/slrn		etc/default
debian/slrn.rc			etc/news
debian/ppp-ip-up/slrn		etc/ppp/ip-up.d/
debian/ppp-ip-up/slrn		etc/network/if-up.d/
debian/slrn_getdescs		usr/sbin
debian/slrn-icon.xpm		usr/share/pixmaps

src/objs/slrn			usr/bin
