.TH EMMA 1 "october 24, 2006"
.SH NAME
emma \- extendable MySQL managing assistant
.SH SYNOPSIS
.B emma
.RI [-h|--help]\ [-d|--debug\]\ [-l\ output_log\ [-f|--flush]]
.SH DESCRIPTION
This manual page documents briefly the
.B emma
command (
.B Emma
on Debian systems)
.PP
emma is a graphical toolkit for MySQL database developers and administrators,
it is the successor of yamysqlfront.
.PP
Its main features are:
 * Dialogs to create/modify MySQL databases, tables and associated indexes
 * Result sets grouped in tabs
 * SQL editor:
  + Tabs
  + Built-in syntax highlighting
  + Table and field name tab-completion
  + Automatic SQL statement formatting
 * Export to CSV files
 * Multiple simultaneously opened MySQL connections
.PP
.SH OPTIONS
This program follows the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-h, \-\-help
show help message
.TP
.B \-d, \-\-debug
output debug information on stdout
.HP
.B \-l, \-\-log FILE
append all output to a specified log file
.TP
.B \-f, \-\-flush
flush {stdout,log} after each write
.SH AUTHOR
emma was written by Florian Schmidt <flo@fastflo.de>.
.PP
This manual page was written by Piotr Ozarowski <ozarow@gmail.com>,
for the Debian project (but may be used by others).
