.TH TSPSOL "1" "Jan 2005" "TSPSOL, Version 4.8" "User Commands"
.SH NAME
TSPSOL \- Traveling Salesperson Problem solver from GLPK
.SH SYNOPSIS
.B tspsol
[\fIoptions\fR...] \fItsp-file\fR
.SH DESCRIPTION
.SS "Options:"
.TP
\fB\-o\fR filename, \fB\-\-output\fR filename
write solution to filename in plain text format
.TP
\fB\-t\fR, \fB\-\-trace\fR
produce detailed output
.SH "REPORTING BUGS"
Please report bugs to <bug-glpk@gnu.org>.
.SH COPYRIGHT
Copyright \(co 2000, 2001, 2002, 2003, 2004, 2005 Andrew Makhorin <mao@gnu.org>
This program is free software; you may redistribute it under the terms of
the GNU General Public License. This program has absolutely no warranty.
.SH "SEE ALSO"
glpsol(1)
.TP
.BR /usr/share/doc/glpk/
Documentation about GLPK, its C API, the GNU MathProg modeling
language, and MPS and LP file formats in PostScript format.
.PP
See also the official GNU webpage dedicated to GLPK at
<http://www.gnu.org/software/glpk/glpk.html>.
