Document: libeina
Title: Debian libeina Manual
Author: <insert document author here>
Abstract: This manual describes what libeina is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libeina/libeina.sgml.gz

Format: postscript
Files: /usr/share/doc/libeina/libeina.ps.gz

Format: text
Files: /usr/share/doc/libeina/libeina.text.gz

Format: HTML
Index: /usr/share/doc/libeina/html/index.html
Files: /usr/share/doc/libeina/html/*.html
