.TH PAIRALIGN "1" "September 2009" "Version 1.0 (15. July 2009) Revision: 4566" "User Commands"
.SH NAME
pair_align \- Pairwise alignment
.SH SYNOPSIS
.B pair_align
\fI-s <FASTA sequence file> \fR[\fIOptions\fR]
.SH DESCRIPTION
Pairwise alignment \- PairAlign
.TP
\fB\-h\fR,  \fB\-\-help\fR
displays this help message
.TP
\fB\-V\fR,  \fB\-\-version\fR
print version information
.SS "Main Options:"
.TP
\fB\-s\fR,  \fB\-\-seq\fR <FASTA Sequence File>
file with 2 sequences
.TP
\fB\-a\fR,  \fB\-\-alphabet\fR [protein | dna | rna]
sequence alphabet (default protein)
.TP
\fB\-m\fR,  \fB\-\-method\fR [nw, gotoh, sw, lcs]
alignment method (default gotoh)
nw = Needleman\-Wunsch
gotoh = Gotoh
sw = Smith\-Waterman
lcs = Longest common subsequence
.TP
\fB\-o\fR,  \fB\-\-outfile\fR <Filename>
output filename (default out.fasta)
.TP
\fB\-f\fR,  \fB\-\-format\fR [fasta | msf]
output format (default fasta)
.SS "Scoring Options:"
.TP
\fB\-g\fR,  \fB\-\-gop\fR <Int>
gap open penalty (default \fB\-11\fR)
.TP
\fB\-e\fR,  \fB\-\-gex\fR <Int>
gap extension penalty (default \fB\-1\fR)
.TP
\fB\-ma\fR, \fB\-\-matrix\fR <Matrix file>
score matrix (default Blosum62)
.TP
\fB\-ms\fR, \fB\-\-msc\fR <Int>
match score (default 5)
.TP
\fB\-mm\fR, \fB\-\-mmsc\fR <Int>
mismatch penalty (default \fB\-4\fR)
.SS "Banded Alignment Options:"
.TP
\fB\-lo\fR, \fB\-\-low\fR <Int>
lower diagonal
.TP
\fB\-hi\fR, \fB\-\-high\fR <Int>
upper diagonal
.SS "DP Matrix Configuration Options:"
.TP
\fB\-c\fR,  \fB\-\-config\fR [ffff | ... | tttt]
alignment configuration (default ffff)
tfff = First row with 0's
ftff = First column with 0's
fftf = Search last column for max
ffft = Search last row for max
All combinations are allowed.
.SH AUTHOR
.br
pair_align was written by Tobias Rausch.
.PP
This manual page was generated using html2man and polished by
Soeren Sonnenburg <sonne@debian.org>, for the Debian project
(but may be used by others).
