.TH CLIQUER 1 "2011-03-14" "cliquer" CLIQUER
.SH NAME
cliquer \- find cliques in weighted and unweighted graphs.
.SH SYNOPSIS
.B cliquer \-\-help

.B cliquer
[
\fIoptions\fP
]
\fIgraph-filename\fP
.SH DESCRIPTION
.B cliquer
searched for cliques in a graph.
The graph is read from the file given as command line argument,
or \fBstdin\fP if that filename is "\fB\-\fP".

The file must be ASCII as described below or a binary DIMACS-format.

By default it prints the first maximal clique it finds, but this
can be changed with the options described below.

.SH OPTIONS
.TP
.B \-h \-\-help
Displays a short list of options and what they do.
.TP
.B \-a \-\-all
Find all cliques.
.TP
.B \-s \-\-single
Find only one clique (default).
.TP
.B \-w \-\-weight
Tell only maximum weight (no faster than \fB\-s\fP).
.TP
.B \-m \fIN\fP \-\-min \fIN\fP
Search for cliques with weight at least \fIN\fP.

If \fIN\fP=0, searches for maximum weight clique (default).
.TP
.B \-M \fIN\fP \-\-max \fIN\fP
Search for cliques with weight at most \fIN\fP.

If \fIN\fP=0, no limit is imposed (default).

\fIN\fP being positive is incompatible with "\fB\-\-min 0\fP"
("\fB\-\-min 1\fP" is assumed).
.TP
.B \-x \-\-maximal
Require cliques to be maximal.
.TP
.B \-u \-\-unweighted
Assume weight 1 for all vertices.
.TP
.B \-0 \-\-from\-0
Number vertices 0 to n\-1 instead of 1 to n when writing.
.TP
.B \-q \-\-quiet
Suppresses progress output.

Specifying \fB\-q\fP twice suppresses all output except the actual result.
.TP
.B \-r \fIF\fP  \-\-reorder \fIF\fP
Reorder with function \fIF\fP.
Available reordering functions are:
.RS
.TP
.B none
No ordering (same order as in the file).
.TP
.B reverse
Reverse order as in the file.
.TP
.B default
One of the two below, depending on weightedness.
.TP
.B unweighted\-coloring
Coloring method efficient for unweighted graphs.
.TP
.B weighted\-coloring
Coloring method efficient for weighted graphs.
.TP
.B degree
Order by ascending degree.
.TP
.B random
Random order.
.RE

.SH "FILE FORMAT"
The format of the ASCII representation of a graph is the following:
Each line has a single letter (enclosed in spaces) as first part.

A line with '\fBp\fP' starts the graph.
The second token is a name of at most 15 characters and ignored.
Then there is the number of nodes in this graph.
Then the number of edges (currently ignored).

A line with '\fBe\fP' adds an edge.
The two next tokens are the numbers of two nodes to connect.

A line with '\fBn\fP' weights an node.
The first argument is the number of the node to assign a weight to,
the second it's weight.

.SH "EXAMPLE"

 p clausehouse 5 8
 e 4 3
 e 3 1
 e 1 2
 e 2 3
 e 3 5
 e 5 2
 e 2 4
 e 4 5
 n 1 2

.SH COPYRIGHT
Cliquer is Copyright \(co 2002 Sampo Niskanen, Patric Ostergard

Cliquer is licensed under the GNU General Public License as published
by the Free Software Foundation; either version 2 of the License, or
(at your option) any later version. The full license is included in
the file LICENSE.

Basically, you can use Cliquer for any purpose, provided that any
programs or modifications you make and distribute are also licensed
under the GNU GPL.

ABSOLUTELY NO GUARANTEES OR WARRANTIES are made concerning the
suitability, correctness, or any other aspect of these routines.

This manpage is based on text from the cliquer program with the obove
copyright and license with modification Copyright \(co 2011  Bernhard R. Link,
also available under above license.
