.\" $Id: Xsession.options.5 189 2005-06-11 00:04:27Z branden $
.\"
.\" Copyright 1998-2001, 2003-2004 Branden Robinson <branden@debian.org>.
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License with
.\" the Debian operating system, in /usr/share/common-licenses/GPL;  if
.\" not, write to the Free Software Foundation, Inc., 59 Temple Place,
.\" Suite 330, Boston, MA 02111-1307 USA
.TH Xsession.options 5 "2004\-10\-31" "Debian Project"
.SH NAME
Xsession.options \- configuration options for
.BR Xsession (5)
.SH DESCRIPTION
.I /etc/X11/Xsession.options
contains a set of flags that determine some of the behavior of the
.BR Xsession (5)
Bourne shell
.RB ( sh (1))
script.
See the
.BR Xsession (5)
manpage for further information.
.PP
.I Xsession.options
may contain comments, which begin with a hash mark (\(oq#\(cq) and end at
the next newline, just like comments in shell scripts.
The rest of the file consists of options which are expressed as words
separated by hyphens, with only one option per line.
Options are enabled by simply placing them in the file; they are disabled
by prefixing the option name with \(oqno\-\(cq.
.PP
Available options are:
.TP
.B allow\-failsafe
If the \(oqfailsafe\(cq argument is passed to the
.I Xsession
script, an emergency X session is invoked, consisting of only an
.BR x\-terminal\-emulator (1)
in the upper\-left hand corner of the screen.
No window manager is started.
If an
.B x\-terminal\-emulator
program is not available, the session exits immediately.
.TP
.B allow\-user\-resources
If users have a file called
.I .Xresources
in their home directories, these resources will be merged with the default
X resources when they log in.
.TP
.B allow\-user\-xsession
If users have an executable file called
.I .xsession
in their home directories, it can be used as the startup program for the X
session (see
.BR Xsession (5)).
If the file is present but not executable, it may still be used, but is
assumed to be a Bourne shell script, and executed with
.BR sh (1).
.TP
.B use-session-dbus
If the
.BR dbus
package is installed, the session bus will be activated at X session
launch.
.TP
.B use\-ssh\-agent
If the
.BR ssh\-agent (1)
program is available and no agent process appears to be running already,
the X session will be invoked by exec'ing
.B ssh\-agent
with the startup command, instead of the startup command directly.
.PP
All of the above options are enabled by default.
Additional options may be supported by the local administrator.
.BR Xsession (5)
describes how this is accomplished.
.SH AUTHORS
Stephen Early, Mark Eichin, and Branden Robinson developed Debian's X
session handling scripts.
Branden Robinson wrote this manual page.
.SH SEE ALSO
.BR Xsession (5),
.BR ssh\-agent (1),
.BR x\-terminal\-emulator (1)
.\" vim:set et tw=80:
