.\" Copyright 2000, 2003, 2004 Progeny Linux Systems, Inc.
.\" Author: Branden Robinson <branden@progeny.com>
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License with
.\" the Debian operating system, in /usr/share/common-licenses/GPL;  if
.\" not, write to the Free Software Foundation, Inc., 59 Temple Place,
.\" Suite 330, Boston, MA 02111-1307 USA
.TH Xwrapper.config 5 "2004\-10\-31" "Debian Project"
.SH NAME
Xwrapper.config \- configuration options for X server wrapper
.SH DESCRIPTION
.I /etc/X11/Xwrapper.config
contains a set of flags that determine some of the behavior of Debian's X
server wrapper, which is installed on the system as
.IR /usr/bin/X .
The purpose of the wrapper, and of this configuration file, is twofold.
.PP
Firstly, it is intended to implement sound security practices.
Since the X server requires superuser privileges, it may be unwise to
permit just any user on the system to execute it.
Even if the X server is not exploitable in the sense of permitting ordinary
users to gain elevated privileges, a poorly\-written or
insufficiently\-tested hardware driver for the X server may cause bus
lockups and freeze the system, an unpleasant experience for anyone using it
at the time.
.PP
Secondly, a wrapper is a convenient place to set up an execution
environment for the X server distinct from the configurable parameters
of the X server itself.
.PP
.B Xwrapper.config
may be edited by hand, but it is typically configured via
.BR debconf (7),
the Debian configuration tool.
The X server wrapper is part of the
.I x11\-common
Debian package; therefore, the parameters of
.B Xwrapper.config
may be changed with the command
.RS
.BR "dpkg\-reconfigure x11\-common" .
.RE
See
.BR dpkg\-reconfigure (8)
for more information.
.PP
The format of
.B Xwrapper.config
is a text file containing a series of lines of the form
.TP
.IB name = value
.PP
where
.I name
is a variable name containing any combination of numbers, letters, or
underscore (_) characters, and
.I value
is any combination of letters, numbers, underscores (_), or dashes (\-).
.I value
may also contain spaces as long as there is at least one character from the
list above bounding the space(s) on both sides.
Whitespace before and after
.IR name ,
.IR value ,
or the equals sign is legal but ignored.
Any lines not matching the above described legal format are ignored.
Note that this specification may change as the X server wrapper develops.
.PP
Available options are:
.TP
.B allowed_users
may be set to one of the following values:
.BR rootonly ,
.BR console ,
or
.BR anybody .
.B rootonly
indicates that only the root user may start the X server;
.B console
indicates that root, or any user whose controlling TTY is a
virtual console, may start the X server; and
.B anybody
indicates that any user may start the X server.
.SH AUTHORS
The X server wrapper was written by Stephen Early, Mark Eichin, and Branden
Robinson for the Debian Project, with valuable contributions from Erik
Troan, Topi Miettinen, and Colin Phipps.
This manual page was written by Branden Robinson with sponsorship from
Progeny Linux Systems.
.SH SEE ALSO
.BR debconf (7),
.BR dpkg\-reconfigure (8)
.\" vim:set et tw=80:
