.TH ant 1 "Feb 2010" "Debian GNU/Linux"
.SH NAME
ant \- a Java based make tool.

.SH SYNOPSIS

.B ant
[\fIOPTIONS\fR] [\fITARGET\fR [\fITARGET2\fR [\fITARGET3\fR] ...\fR]\fR]

.SH DESCRIPTION

Like 
.B make
.B ant 
is a tool by which projects can be build. But unlike it, 
.B ant 
is based on Java which means it will run on every platform
for which a Java Virtual Machine is available. This makes it a great
tool for building Java software.

By default it takes information from
.B build.xml
which describes the targets.

.TP
\fB\-help, \-h\fR
print help on the command line options
.TP
\fB\-projecthelp, \-p\fR
print project help information
.TP
\fB\-version\fR
print the version information
.TP
\fB\-diagnostics\fR
print information that might be helpful to diagnose or report problems
.TP
\fB\-quiet, \-q\fR
be extra quiet
.TP
\fB\-verbose, \-v\fR
be extra verbose
.TP
\fB\-debug, \-d\fR
print debugging information
.TP
\fB\-emacs, \-e\fR
produce logging information without adornments
.TP
\fB\-lib\fR <\fIpath\fR>
specifies a path to search for jars and classes
.TP
\fB\-logfile\fR <\fIfile\fR>
use the given file to output log to
.TP
\fB\-logger\fR <\fIclassname\fR>
use the given class to perform logging
.TP
\fB\-listener\fR <\fIclassname\fR>
add an instance of the given class as a project listener
.TP
\fB\-noinput\fR
do not allow interactive input
.TP
\fB\-buildfile, \-file, \-f\fR <\fIfile\fR>
use the given buildfile instead of the default
.B build.xml
file. This is the 
.B ant
equivalent of
.B Makefile
.TP
\fB\-D\fR<\fIproperty\fR>=<\fIvalue\fR>
use value for the given property
.TP
\fB\-keep-going, \-k\fR
execute all targets that do not depend on failed target(s)
.TP
\fB\-propertyfile\fR <\fIname\fR>
load all properties from file with \-D properties taking precedence
.TP
\fB\-inputhandler\fR <\fIclass\fR>
the class which will handle input requests
.TP
\fB\-find, \-s\fR <\fIfile\fR>
search for buildfile towards the root of the filesystem and use it
.TP
\fB\-nice\fR <\fInumber\fR>
A niceness value for the main thread: 1 (lowest) to 10 (highest); 5 is the default
.TP
\fB\-nouserlib\fR
Run ant without using the jar files from ${user.home}/.ant/lib
.TP
\fB\-noclasspath\fR
Run ant without using CLASSPATH
.TP
\fB\-autoproxy\fR
Java 1.5+ : use the OS proxies
.TP
\fB\-main\fR <\fIclass\fR>
Override Ant's normal entry point

.SH SEE ALSO
.BR make (1)
.BR mvn (1)

.SH AUTHOR
This manpage is written by Egon Willighagen <egonw@sci.kun.nl>
