.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH APTITUDE 8 "9/8/00"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NOME
aptitude \- interface a pantalla completa para o xestor de paquetes.
.SH SINOPSE
.B aptitude
.SH DESCRICIÓN
.B aptitude
é unha interface en modo texto para o sistema de paquetes de Debian
GNU/Linux.
.br
Permítelle ao usuario ve-la lista de paquetes e realizar tarefas de xestión
de paquetes coma a instalación, actualización e eliminación de paquetes. Por
defecto, aptitude deixa dispoñibles as seguintes teclas e comandos:
.TP
.B q
Saír do contexto actual, gravando os cambios.
.TP
.B x
Saír do contexto actual, abandonando os cambios.
.TP
.B ?
Amosar unha pantalla de axuda en liña.
.TP
.B Arriba, j
Move-la barra de selección un elemento cara a arriba.
.TP
.B Abaixo, k
Move-la barra de selección un elemento cara a abaixo.
.TP
.B ^
Move-la barra de selección cara ao pai do elemento actual.
.TP
.B Intro
Expandir ou contraer un grupo de paquetes.
.TP
.B [
Expandir unha árbore de paquetes completa.
.TP
.B ]
Contraer unha árbore de paquetes completa.
.TP
.B Intro, i
Amosar información acerca dun paquete.
.TP
.B +
Cancela-lo borrado dun paquete, ou solicita-la súa instalación ou
actualización.
.TP
.B -
Cancela-la instalación dun paquete, ou solicita-la súa eliminación.
.TP
.B =
Reter un paquete (ou quitalo da retención se é un paquete retido non
actualizable).
.TP
.B _
Solicita-la eliminación dun paquete e tódolos seus ficheiros de
configuración ("purgar").
.TP
.B u
Actualiza-las listas de paquetes dispoñibles.
.TP
.B g
Realizar tódalas instalacións, eliminacións e actualizacións pendentes.
.TP
.B Control-u
Desface-la última acción ou conxunto de accións.
.TP
.B /
Realizar unha busca.
.TP
.B \\
Repeti-la última busca.
.TP
.B v
Amosar tódalas versións dun paquete dispoñibles.
.SH OPCIÓNS
A versión actual de
.B aptitude
non recoñece opcións de liña de comandos.
.SH VER TAMÉN
.BR apt-get (1),
.BR apt (8),
.BR /usr/share/doc/aptitude/README.
.SH AUTOR
Esta páxina de manual escribiuna Daniel Burrows <Daniel_Burrows@brown.edu>.
.SH TRADUCTOR
Esta páxina de manual traduciuna Jacobo Tarrío Barreiro <jtarrio@trasno.net>.
