.TH mpigdb 1 "21 Mar 2005" "" "mpd cmds"
.SH NAME
mpigdb \- debug a MPI program using mpd
.SH SYNOPSIS
.B mpigdb

.SH DESCRIPTION
.B mpigdb
usage:
.TP
mpigdb -a jobid # to attach to a running job
.TP
mpigdb -n nprocs pgm [pgmars] # to use gdb on a new job

.SH AUTHOR
This manpage has been written by Zach Lowry <zach@zachlowry.net>, modified from
the page written by Junichi Uekawa <dancer@debian.org> for Debian GNU/Linux
