#!/bin/sh

set -e

if [ "$1" = "upgrade" ]; then
	# Remove apm symlinks (legacy, no longer installed since 1.0.25+1)
	rm -f \
		/etc/apm/suspend.d/??alsa \
		/etc/apm/resume.d/??alsa
	[ -d /etc/apm/suspend.d ] && rmdir --ignore-fail-on-non-empty /etc/apm/suspend.d
	[ -d /etc/apm/resume.d ]  && rmdir --ignore-fail-on-non-empty /etc/apm/resume.d
	[ -d /etc/apm ]           && rmdir --ignore-fail-on-non-empty /etc/apm
fi

#DEBHELPER#
