contrib/eventhandlers/* usr/share/nagios3/plugins/eventhandlers
debian-configs/* /etc/nagios3
debian/conf.d/* /etc/nagios3/conf.d
debian/resource.cfg /etc/nagios3
sample-config/*.cfg /usr/share/doc/nagios3-common/examples
sample-config/README /usr/share/doc/nagios3-common/examples
sample-config/template-object/*.cfg /usr/share/doc/nagios3-common/examples/template-object
sample-config/template-object/README /usr/share/doc/nagios3-common/examples/template-object
