.TH "DEE-TOOL" 1 "2012-04-20" "" ""
.SH NAME
dee-tool \- Tool for introspecting dee data.
.SH SYNOPSIS
.B dee-tool
[\fIOPTIONS\fR]
.SH DESCRIPTION
.B dee-tool
is a tool for introspecting dee data. This program is part of libdee.

.SH OPTIONS
Below are the various command-line options.
.TP
\fB\-r\fR, \fB\-\-resource\fR
Dump a resource given by name.
.TP
\fB\-m\fR, \fB\-\-model\fR
Dump a model given by name.
.TP
\fB\-p\fR, \fB\-\-peer\fR
 List peers and leader of a swarm.
.TP
\fB\-\-linger\fR
 Don't exit, but keep the process running the mainloop.
.TP
\fB\-\-private\fR
Use a private (aka peer\-2\-peer) DBus connection.
.TP
\fB\-\-server\fR
Set up a private DBus server. Implies \-\-private and \-\-linger.
.TP
\fB\-\-watch\-changes\fR
Watch for changes to the given resource. Implies \-\-linger.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show help options and exit.

.SH SEE ALSO
.BR Homepage:
<https://launchpad.net/dee>

.SH AUTHOR
dee-tool was written by Mikkel Kamstrup Erlandsen <mikkel.kamstrup@canonical.com>,
and Neil Jagdish Patel <neil.patel@canonical.com>.

.PP
This manual page was written by Kartik Mistry <kartik@debian.org>, for the
Debian project (but may be used by others).
