.TH cpuburn 1 "June 04, 2011" "" ""
.SH NAME
\fBcpuburn, burnBX, burnK6, burnK7, burnMMX, burnP5, burnP6 \fP- a collection of programs to put heavy load on CPU
.SH SYNOPSIS
.nf
.fam C
\fBburnBX\fP
\fBburnK6\fP
\fBburnK7\fP
\fBburnMMX\fP
\fBburnP5\fP
\fBburnP6\fP
.fam T
.fi
.SH DESCRIPTION
These programs are designed to load x86 CPUs as heavily as possible
for the purposes of system testing ("burn in").  They have been
optimized for different processors.  FPU and ALU instructions are
coded in an assembler endless loop.  They do not test every
instruction.  The goal has been to maximize heat production from the
CPU, putting stress on the CPU itself, cooling system, motherboard
(especially voltage regulators) and power supply (likely cause of
\fBburnBX\fP/\fBburnMMX\fP errors).  The programs produce no output,
but signal hardware errors by a return code or (more likely) your
machine locking up.
.TS
lB lR.
burnP5	is optimized for Intel Pentium with or without MMX CPUs
burnP6	is optimized for Intel PentiumPro, Pentium II & III CPUs
burnK6	is optimized for AMD K6 CPUs
burnK7	is optimized for AMD Athlon/Duron CPUs
burnMMX	tests cache/memory interfaces on all CPUs with MMX
burnBX	is an alternate cache/memory test for Intel CPUs
.TE
.P
.SH USAGE
Burn testing is designed to make your computer glitch if it has
hardware problems, so make sure that nothing critical is running and
all critical data is saved back to the hard-drives.  The best is to 
run it with filesystems mounted read-only.  Note that \fIroot\fP 
privileges are not required.

Run the desired program in the background, checking the error result.
You'll may want to repeat this command for every processor you have 
in an SMP or HyperThreading system.  For example,

.fam C
    burnP6 || echo $? &
.fam T

Monitor progress of cpuburn by \fBps\fP.  You can monitor CPU temperature and/or 
system voltages through ACPI or using the lm-sensors package if you system supports
it.  When finished, \fBkill\fP the \fBburn*\fP process(es).  For 
example,

.fam C
    killall burnP6
.fam T

.SH BUGS
Report all bug to submit@bugs.debian.org, for more information
visit http://bugs.debian.org
.SH AUTHORS
cpuburn was written by Robert Redelmeier <redelm@ev1.net>
