.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH MWENEXT 8 "28 July 2007"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
mwenext, mwdisext \- enable or disable an extension for mediawiki
.SH SYNOPSIS
.B mwenext
.RI [ extension ]
.PP
.B mwdisext
.RI [ extension ]
.SH DESCRIPTION
This manual page documents briefly the
.B mwenext
and
.B mwdisext
commands.
.PP
.B mwenext
is a script that enables the specified extensions within the
.B mediawiki
configuration.  It does this by creating symlinks within
.BR /etc/mediawiki-extensions/extensions-enabled .
Likewise,
.B mwdisext
disables an extension by removing those symlinks.
.SH FILES
.TP
.B /etc/mediawiki-extensions/extensions-available
Directory with files giving information on available extensions.
.TP
.B /etc/mediawiki-extensions/extensions-enabled
Directory with links to the files in
.B extensions-available
for enabled extensions.
.SH AUTHOR
This manual page was adapted for a2enmod and a2dismod man page, written by Daniel Stone <daniel@sfarc.net> for the Debian
GNU/Linux distribution, by Romain Beauxis <toots@rastageeks.org>.
