#!/bin/sh

set -e

# versions 0.3.9-1 and 0.3.9-2 shipped /var/lib/scrollkeeper erroneously,
# overwritting the scrollkeeper database which requires a full rebuild
if [ "$1" = "configure" ] && dpkg --compare-versions "$2" ge "0.3.9-1" && dpkg --compare-versions "$2" lt "0.3.9-3" && [ -x "`which scrollkeeper-rebuilddb 2>/dev/null`" ]; then
    echo "Upgrade from broken gparted version detected, running scrollkeeper-rebuilddb..."
    scrollkeeper-rebuilddb -q
fi

#DEBHELPER#
