#! /bin/sh
set -e

case "$1" in
	configure)
		dpkg-trigger rygel-restart
		;;

	triggered)
		# both "/usr/lib/rygel-1.0" and "rygel-restart" triggers
		# should result in rygel being restarted.

		# make running rygel processes restart themselves.
		PIDS=$(pidof /usr/bin/rygel || true)
		if [ "$PIDS" != "" ]; then
			kill -HUP $PIDS
			echo "Running rygel instances was told to restart."
		fi
	;;

	*)
	;;
esac

#DEBHELPER#

