.\" Copyright 2001 Gareth Rees.  All rights reserved.
.\" Copyright 2004-2006 Ned Batchelder.  All rights reserved.
.\" Copyright 2007 Lars Wirzenius.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions are
.\" met:
.\"
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\"
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the
.\"    distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
.\" "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
.\" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
.\" A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
.\" HOLDERS AND CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
.\" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
.\" OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
.\" ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
.\" TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\" USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
.\" DAMAGE.
.\"
.TH PYTHON\-COVERAGE 1
.SH NAME
python\-coverage \- measure code coverage of Python program execution
.SH SYNOPSIS
.BI "python\-coverage \-x " module.py
.IR "" [ ARG ...]
.br
.BI "python\-coverage \-e"
.br
.BI "python\-coverage \-r"
.IR "" [ \-m ]
.br
.BI "python\-coverage \-a "
.IR "" [ file ...]
.SH DESCRIPTION
.B python\\-coverage
executes a Python program and measures which of its statements are
executed and which are not.
It stores the information in the file 
.B .coverage
in the current working directory.
.SH OPTIONS
.TP
.B -e
Erase the 
.B .coverage
file.
.TP
.B -x
Execute a Python module, giving it the remaining command line arguments.
.TP
.B -r
Produce a coverage report.
.TP
.B -m
With
.BR -r ,
show the line numbers that were missed by the execution.
.TP
.B -a
Annotate source files.
For each source file
.IR foo ,
produce
.IR foo,cover ,
with executed lines prefixed by ">" and non-executed by "!".
.TP
.B --help
Produce a help summary.
It might be more helpful than this manual page.
.SH AUTHOR
The
.B python-coverage
command is a one-line Python script which calls the 
.B coverage.py
Python module to do all the work.
The module was riginally developed by Gareth Rees, 
and is now developed by Ned Batchelder.
The module's home page is
.br
.IR http://www.nedbatchelder.com/code/modules/coverage.html .
.PP
This manual page was cobbled together by Lars Wirzenius for Debian,
by copy-pasting from the help texts from the module.
