=head1 NAME

xdg-mount - mount volumes using B<HAL>, with the B<GNOME> or B<Xfce> tools

=head1 SYNOPSIS

B<xdg-mount> [--help] [-d I</dev/file>|-h I</org/freedesktop/Hal/udi>]
[--eject|--unmount] [--no-ui]

=head1 DESCRIPTION

B<xdg-mount> is a wrapper script that will call B<gnome-mount> or 
B<exo-mount> depending on the desktop environment.

=head1 OPTIONS

The following options are understood regardless of the current 
environment.

=over 4

=item B<-?>, B<--help>

Show help options and exit

=item B<-d>, B<--device-file>

Specify the volume to mount by the path to the device file

=item B<-h>, B<--hal-udi>

Specify the volume to mount by its B<HAL> Unique Device Identifier

=item B<-e>, B<--eject>

Eject the volume rather than mounting

=item B<-u>, B<--unmount>

Unmount the volume rather than mounting

=item B<-n>, B<--no-ui>

Do not show the dialogs that may be required for authentication

=back

=head1 SEE ALSO

B<gnome-mount>(1), B<exo-mount>(1).

=head1 AUTHORS

Josselin Mouette <joss@debian.org>
