.\"                                      Hey, EMACS: -*- nroff -*-
.TH AIRPORT-HOSTMON 1 "May 20, 2006"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
airport-hostmon \- Host monitor for the original Apple AirPort Base
Station ("Graphite"), the Lucent RG-1000 base station and the Apple
AirPort Extreme Base Station
.SH SYNOPSIS
.B airport-hostmon

.SH DESCRIPTION

\fBairport-hostmon\fP allows you to monitor the wireless hosts
associated to your base station.

.SH OPTIONS

\fBairport-hostmon\fP accepts no command-line
options. \fBairport-hostmon\fP is a wrapper script around the
\fIHostMonitor.jar\fP jar file located in
\fI/usr/share/java/airport-utils\fP.

You can set the \fBJAVACMD\fP environment variable to use a specific JVM
instead of the one chosen by the wrapper script. Set the \fBDEBUG\fP
environment variable to 1 to get the debug output from the wrapper
script.

.SH ENVIRONMENT VARIABLES

.TP
.B DEBUG
Set this variable to 1 to get the debug output from the wrapper
script.

.TP
.B JAVACMD
The full path to the Java Virtual Machine to use. By default, the
wrapper uses \fBJAVACMD\fP; if it is not set, it looks for
\fBJAVA_BINDIR\fP/java, then for \fBJAVA_HOME\fP/bin/java before
looking for a java executable in the \fBPATH\fP. In the latter case,
the JVM used can be configured using the Debian alternatives system
(see \fBupdate-alternatives\fP(8)).

.TP
.B JAVA_HOME
The full path where your JDK/JRE is installed.

.TP
.B JAVA_BINDIR
The full path to the directory where the java executable is located.

.TP
.B JAVA_ARGS
Extra command-line arguments to be passed to the Java Virtual Machine.

.SH AUTHOR
airport-hostmon was written by Jon Sevy <jsevy@cs.drexel.edu>.
.PP
This manual page was written by Julien BLACHE <jblache@debian.org>,
for the Debian project (but may be used by others).
