#! /bin/sh

set -e

. /usr/share/debconf/confmodule

# This will be replaced with debian/slapd.scripts-common which includes
# various helper functions and $OLD_VERSION and $SLAPD_CONF
#SCRIPTSCOMMON#

# If we are upgrading from an old version then stop slapd and attempt to
# slapcat out the data so we can use it in postinst to do the upgrade

if [ "$MODE" = upgrade ]; then
	dump_databases
fi

#DEBHELPER#

exit 0

# vim: set sw=8 foldmethod=marker: 
