#!/bin/sh

# FIXME very dicey! this isn't well-understood
if ! export | grep LANG ; then
	export LANG=C.UTF-8
fi

# -w: wait for process, then switch back to controlling terminal
# -s: switch to new vt on launch
# -v: verbose. someone might switch back to this vt purposefully; hopefully
#     this will kinda indicate what's going on.
openvt -v -w -s fbvfbterm /usr/share/sprezzatech/sprezzos.png growlight-curses
