.TH LIGHTSPEED 1 "April 2000"
.SH NAME
lightspeed \- Shows how objects moving at speeds near the speed of light look like.
.SH SYNOPSIS
.BI lightspeed " [" \-hsa "] [" object ]
.SH DESCRIPTION
Light Speed! is a simulator which can illustrate the effects of
special relativity on the appearance of objects travelling at
ultra-high speeds. Depending on the particular speed, and one's
point of view, relativistic effects can cause the object to
appear shorter, longer, brighter, darker, deformed and/or
off-color.
.SH CONTROLS
To adjust the velocity, use the slider along the right edge of
the main window. You can also type in a value, using the entry
at the top right (press <Enter> once it is in). To change the
units shown, press the button to the right of the entry, and it
will cycle through a small list.
.PP
The object travels in the positive-x direction, which can be
visually checked by activating Objects -> Coordinate axes.
.PP
Most interactive control is performed with the mouse. By holding
down a particular button, and dragging the pointer around,
various camera motions can be obtained:
.PP
.nf
   Left button:  Revolve camera around view target

   Left button + Shift key:  Revolve view target around camera

   Middle button:  Translate camera left, right, up or down

   Right button:  Dolly in or out
.fi
.PP
The first and last motions are generally the most useful.
Should the camera become difficult to control at any point, it
may be re-initialized by selecting Camera -> Reset View.
.SH OPTIONS
.TP
.BR -h ", " --help
Print this help screen
.TP
.BR -s ", " --simple
Use simplified interface
.TP
.BR -a ", " --advanced
Use advanced interface (default)
.TP
.I object
3D file to load on startup (.3DS or .LWO)
