.TH isql 1 "Dec 2004" UnixODBC "UnixODBC Reference"
.SH NAME
isql \- utility to submit SQL queries to a data source.
.br
iusql \- Unicode version of isql.
.SH SYNOPSIS
.B isql
DSN [UID [PWD]] [options]
.br
.SH DESCRIPTION
.I isql
can be used to submit SQL to a data source and to format/output results.
It can be used in batch or interactive mode.
.br
.SH OPTIONS
.TP
.B DSN
Name of the data source you want to connect to.
.TP
.B UID
Your login to connect the DSN.
.TP
.B PWD
Your password needed to login to the DSN.
.TP 
.B \-b
Batch mode.
It will not do any prompting.
.TP
.B \-dx
Delimit columns with x.
.TP
.B \-x0xXX
Delimit columns with XX, where XX is in hex.
For example -x0x09 will use a tab.
.TP
.B \-w
Wrap results in an HTML table
.TP
.B \-c
Print column names on first row.
This options only has effect in combination with the -d option.
.TP
.B \-mn
Limit column display width to n
.TP
.B \-v
Verbose output.
.TP
.B \-\-version
This prints the version.
.SH EXAMPLES
.TP
.I cat My.sql | isql WebDB MyID MyPWD -w
Each line in My.sql must contain exactly 1 SQL command except for the
last line which must be blank.
.SH AUTHOR
This manual page was written by Kurt Roeckx <kurt@roeckx.be>
for the Debian package of unixODBC.

