#! /bin/sh -e

case "$1" in
    configure)
	update-alternatives --install /usr/bin/x-www-browser \
	    x-www-browser /usr/bin/konqueror 100 \
	    --slave /usr/share/man/man1/x-www-browser.1.gz \
	    x-www-browser.1.gz /usr/share/man/man1/konqueror.1.gz
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
