debian/apport/source_apparmor.py /usr/share/apport/package-hooks/
debian/lib/apparmor/functions /lib/apparmor/
etc/apparmor/subdomain.conf
sbin/apparmor_parser
usr/sbin/aa-status
usr/sbin/apparmor_status
etc/apparmor.d/tunables/alias
etc/apparmor.d/tunables/global
etc/apparmor.d/tunables/home
etc/apparmor.d/tunables/proc
etc/apparmor.d/tunables/multiarch
etc/apparmor.d/abstractions/*
etc/apparmor.d/local/README
