.TH LIT2EPUB 1
.SH NAME
lit2epub \- simple LIT to EPub conversion
.SH SYNOPSIS
\fBlit2epub \fP \fIlit-document\fP [\fIepub-document\fP]
.SH DESCRIPTION
\fBlit2epub\fP is a command line tool for converting a LIT document to an EPub
document. It uses \fIclit\fP and \fIzip\fP for the conversion.

\fBlit2epub\fP needs to be run with at least one arguments, the LIT document to
be converted. The second argument, \fIepub-document\fP, is the resulting EPub
document. If it is not specified, the output EPub is named after the input LIT
document, with the \fI.lit\fP extension changed in \fI.epub\fP, and placed in the
same directory as the LIT document.

.SH AUTHOR
lit2epub was written by Ely Levy <elylevy@cs.huji.ac.il>.
.P
This manual page was written by Pino Toscano <pino@kde.org>,
for the Debian project (but may be used by others).
