debian/tmp/usr/include/rdf_*.h
debian/tmp/usr/include/librdf.h
debian/tmp/usr/include/redland.h
debian/tmp/usr/lib/librdf.a
debian/tmp/usr/lib/librdf.la
debian/tmp/usr/lib/librdf.so
debian/tmp/usr/bin/redland-config
debian/tmp/usr/share/redland/Redland.i
debian/tmp/usr/lib/redland/librdf_storage_*.a
debian/tmp/usr/lib/redland/librdf_storage_*.la
docs/html/* /usr/share/gtk-doc/html/librdf
debian/tmp/usr/lib/pkgconfig/redland.pc /usr/lib/pkgconfig
