.TH PYVERSIONS
.SH NAME
pyversions \- print python version information
.SH SYNOPSIS
.PP
.B pyversions
.I [-h] [-v] [<options>]
.SH DESCRIPTION
.PP
.B pyversions
prints information about installed, supported python runtimes, the
default runtime, and parses the information of the PythonVersion
fields in the package control file.
.SH OPTIONS
.TP
.I -d, --default
Show the default python version.
.TP
.I -s, --supported
Show the supported python versions.
.TP
.I -r, --requested [<version string>|<control file>]
Reads the value of the
.B XS-Python-Version
field in the source section of a control file and shows all matching
python versions. The parameter is interpreted as a version string, if
it is not the name of a file. If the XS-Python-Version field is
missing, get the version information from debian/pyversions.
Without any parameter, it will fall back to list the supported Python
versions after checking debian/control and debian/pyversions.
.TP
.I -i, --installed
Show the installed supported python versions.
.TP
.I -v, --version
Limit the output to the version numbers of the python versions.
.TP
.I -h, --help
Print a help text.
.SH SEE ALSO
Python policy.
.SH AUTHOR
Matthias Klose
