#!/bin/sh
set -e

if [ "$1" = "configure" ] ; then
	update-alternatives --quiet --install /usr/bin/x-www-browser x-www-browser \
		/usr/bin/xlinks2 69 \
	        --slave /usr/share/man/man1/x-www-browser.1.gz x-www-browser.1.gz \
		/usr/share/man/man1/xlinks2.1.gz
	update-alternatives --quiet --install /usr/bin/www-browser www-browser \
		/usr/bin/links2 69 \
	        --slave /usr/share/man/man1/www-browser.1.gz www-browser.1.gz \
		/usr/share/man/man1/links2.1.gz
fi

#DEBHELPER#
