debian/tmp/usr/include/*.h
debian/tmp/usr/include/xmlrpc-c/*.h
debian/tmp/usr/lib/libxmlrpc.a
debian/tmp/usr/lib/libxmlrpc_abyss.a
debian/tmp/usr/lib/libxmlrpc_client.a
debian/tmp/usr/lib/libxmlrpc_server.a
debian/tmp/usr/lib/libxmlrpc_server_abyss.a
debian/tmp/usr/lib/libxmlrpc_server_cgi.a
debian/tmp/usr/lib/libxmlrpc_util.a
debian/tmp/usr/lib/libxmlrpc_xmlparse.a
debian/tmp/usr/lib/libxmlrpc_xmltok.a
debian/tmp/usr/lib/libxmlrpc.so
debian/tmp/usr/lib/libxmlrpc_abyss.so
debian/tmp/usr/lib/libxmlrpc_client.so
debian/tmp/usr/lib/libxmlrpc_server.so
debian/tmp/usr/lib/libxmlrpc_server_abyss.so
debian/tmp/usr/lib/libxmlrpc_server_cgi.so
debian/tmp/usr/lib/libxmlrpc_util.so
debian/tmp/usr/lib/libxmlrpc_xmlparse.so
debian/tmp/usr/lib/libxmlrpc_xmltok.so
debian/tmp/usr/bin/xmlrpc-c-config
tools/xmlrpc/xmlrpc usr/bin
tools/xmlrpc/xmlrpc.html usr/share/doc/libxmlrpc-c3-dev
