.TH UPDATE-GCONF-DEFAULTS 8 "2 Feb 2009"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
update-gconf-defaults \- generate GConf defaults shipped in Debian packages
.SH SYNOPSIS
.B update-gconf-defaults
[options]
.SH DESCRIPTION
This manual page documents briefly the
.B update-gconf-defaults
command.
.PP
.B update-gconf-defaults
is responsible for generating defaults used by GConf from the files
found in
.IR /usr/share/gconf/defaults .
.PP
The syntax of files in this directory consists in lines containing the
key name, some white space, and the key value, which can be an integer,
a boolean, a float, a string or a list of strings. Example:
.PP
/apps/myprogram/frob_number     42
.br
/apps/myprogram/do_foo          true
.br
/apps/myprogram/priority        1.25
.br
/apps/myprogram/name            "Gotcha !"
.br
/apps/myprogram/names           [Ha ha!,Let's keep serious,Ho ho!]
.PP
Files are processed in alphabetical order. Files processed later take
precedence over the previous ones if they include the same defaults.
Thus, it is recommended to name
them
.IR NN _ package
with
.I NN
being a 2-digit number and
.I package
the package name. It is recommended to set
.I NN
as 10 for packages in the Debian archive, 20 for derived distributions,
50 for CDD distributions, and 90 for site-specific packages.
.SH OPTIONS
.TP
.B \-\-source\fR \fIsource_dir
Specify an alternate source directory where to find the defaults.
.TP
.B \-\-destination\fR \fIdestination_dir
Specify an alternate destination directory where to build the resulting GConf tree.
.TP
.B \-\-mandatory
Sets source and destination directories appropriate for the mandatory values.
.SH FILES
.TP
.I /usr/share/gconf/defaults/
The directory from which defaults files are read.
.TP
.I /usr/share/gconf/mandatory/
The directory from which defaults files for mandatory settings are read.
.TP
.I /var/lib/gconf/debian.defaults
The directory where the GConf tree for default settings is generated. It is read by GConf with the default Debian
configuration, and it takes precedence over upstream defaults.
.TP
.I /var/lib/gconf/debian.mandatory
The directory where the GConf tree for mandatory settings is generated. It is read by GConf with the default Debian configuration, and it takes precedence over user settings.
.SH SEE ALSO
.BR dh_gconf (1), gconftool (1).
.SH AUTHOR
Josselin Mouette <joss@debian.org>.
