.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH GLADE 1 "24 January 2005"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
glade \- GUI Builder for GTK+
.SH SYNOPSIS
.B glade
.RI [ options ] " file"
.br
.SH DESCRIPTION
.B Glade
allows a graphical interface to be designed from within a graphical
interface, instead of written as a program using a function or class
library.
.PP
The creation of various GTK graphical "widgets" is supported, allowing
a programmer to concentrate on implementation of an applications
functionality, instead of the presentation.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-without\-devhelp
Disable Devhelp integration
.TP
.B \-\-display=DISPLAY
X display to use
.TP
.B \-v, \-\-version
Show version of program.
.P
.B Glade
also accepts the standard GNOME and GTK options.
.SH FILES
A single input XML file may be given as an argument.  This file should
have been previous created by an interactive session with \fBGlade\fP.
.SH AUTHOR
glade was written by Chema Celorio <chema@ximian.com>.
.PP
This manual page was written by Justin Pryzby
<justinpryzby@users.sf.net>, for the Debian project (but may be used
by others).
.SH SEE ALSO
.BR "gtk-options" (7),
.BR "gnome-options" (7)
.P
The online documentation available through the program's
.I Help
menu.
