.TH TDB_CLOSE 3 "Aug 16, 2000" "Samba" "Linux Programmer's Manual"
.SH NAME
tdb_close \- close a tdb database
.SH SYNOPSIS
.nf
.B #include <tdb.h>
.sp
.BI "int tdb_close(TDB_CONTEXT *" tdb ");"
.sp
.SH DESCRIPTION
Closes a TDB database and frees memory any memory that was used.
.SH "RETURN VALUE"
Returns zero on success and \-1 on failure.
.SH AUTHORS
Software: Andrew Tridgell and Luke Kenneth Casson Leighton
Man page: Ben Woodard <ben@valinux.com>
.SH "SEE ALSO"
.BR gdbm (3),
.BR tdb(3)
