.TH TDB_CHAINLOCK 3 "Oct 13, 2000" "Samba" "Linux Programmer's Manual"
.SH NAME
tdb_chainlock \- lock a group of keys
tdb_chainunlock \- unlock a previously locked group of keys
.SH SYNOPSIS
.nf
.B #include <tdb.h>
.sp
.BI "int tdb_chainlock(TDB_CONTEXT *" tdb ", TDB_DATA " key ");"
.BI "void tdb_chainunlock(TDB_CONTEXT *" tdb ", TDB_DATA " key ");"
.sp
.SH DESCRIPTION
.I tdb_chainlock 
is a low\-level function used to lock a particular key (and a number of
other keys) without any checking: any other process attempting to
perform tdb operations on those keys will block until
.I tdb_chainunlock
is called.
.SH NOTES
It is the user's responsibility to ensure that they do not deadlock
the database using these functions: something which is impossible
using the other access functions.
.SH "RETURN VALUE"
A return value of 0 indicates success and \-1 indicates failure.
.SH AUTHORS
Software: Andrew Tridgell <tridge@linuxcare.com>
Man page: Rusty.
.SH "SEE ALSO"
.BR gdbm (3),
.BR tdb (3),
.BR tdb_lockall (3).
