.TH TDB_DELETE 3 "Aug 16, 2000" "Samba" "Linux Programmer's Manual"
.SH NAME
tdb_delete \- delete a record from a tdb database
.SH SYNOPSIS
.nf
.B #include <tdb.h>
.sp
.BI "int tdb_delete(TDB_CONTEXT *" tdb ", TDB_DATA " key ");"
.sp
.SH DESCRIPTION
Delete the record from the 
.I tdb
database whose key matches
.I key
, a lump of data that is used as the index into the database. The
TDB_DATA structure is defined as:
.PP
.RS
.nf
typedef struct {
	char *dptr;
	size_t dsize;
} TDB_DATA;
.fi
.RE
.PP
.SH "RETURN VALUE"
A return value of 0 indicates success and \-1 indicates failure.
.SH AUTHORS
Software: Andrew Tridgell <tridge@linuxcare.com> and 
Luke Kenneth Casson Leighton
Man page: Ben Woodard <ben@valinux.com>
.SH "SEE ALSO"
.BR gdbm (3),
.BR tdb(3)
