.TH TDB_ERROR 3 "Aug 16, 2000" "Samba" "Linux Programmer's Manual"
.SH NAME
tdb_error - return tdb database error state information.
tdb_errorstr - return a printable string representing the error state of a tdb\
	 database
.SH SYNOPSIS
.nf
.B #include <tdb.h>
.sp
.BI "enum TDB_ERROR tdb_error(TDB_CONTEXT *" tdb ");"
.BI "char *tdb_errorstr(TDB_CONTEXT *" tdb ");"
.sp
.SH DESCRIPTION
.I tdb_error returns the current error state of the
.I tdb
database.
.I tdb_errorstr 
returns a printable string that describes the error state of the
database.
.SH AUTHORS
Software: Andrew Tridgell <tridge@linuxcare.com> and Luke Kenneth
Casson Leighton Man page: Ben Woodard <ben@valinux.com>
.SH "SEE ALSO"
.BR gdbm (3),
.BR tdb(3)
