#!/bin/sh -e

PACKAGE=swi-prolog

if [ "$1" = "configure" ]; then
  update-alternatives --install /usr/bin/prolog prolog /usr/bin/swipl 10 \
    --slave /usr/share/man/man1/prolog.1.gz prolog.1.gz \
    /usr/share/man/man1/swipl.1.gz
fi

# Update library index
rm -f /usr/lib/swi-prolog/library/INDEX.pl
echo "make_library_index('/usr/lib/swi-prolog/library/')." | swipl >/dev/null 2>&1

#DEBHELPER#
