#!/bin/bash
# Wrapper around dh_builddeb to disable parallel invocations of dpkg-deb. This
# would break predictable documentation symlinking in pkgstripfiles.

set -e

DEB_BUILD_OPTIONS=$(echo "$DEB_BUILD_OPTIONS" | sed -r 's/parallel(=[0-9]+)?//')

exec -a "$0" dh_builddeb.pkgbinarymangler "$@"
