.TH pkgmaintainermangler 1 "September 06, 2006" "Adam Conrad"

.SH NAME

pkgmaintainermangler \- change the Debian Maintainer field in a binary package during the build

.SH SYNOPSIS

.B pkgmaintainermangler
.IR directory

.SH DESCRIPTION

.B pkgmaintainermangler
adjusts the maintainer field in binary packages to match a set of rules defined in the
.B pkgmaintainermangler
configuration file, found at
.I /etc/pkgbinarymangler/maintainermangler.conf\fR.

The
.IR directory
option tells pkgmaintainermangler where to find the build directory which contains DEBIAN/control, so it can mangle it appropriately.  As pkgmaintainermangler is generally invoked from a
.B dpkg-deb\fR(1)
wrapper, it will also accept
.B dpkg-deb\fR's
command-line syntax, ignoring superfluous options.

By default, 
.B pkgmaintainermangler
is inactive. To enable it, the
.B enable
option in the configuration file must be set to
.B true\fR.

.SH ENVIRONMENT VARIABLES

.TP
.B NO_PKG_MANGLE
If this variable is set to a nonempty value, then pkgmaintainermangler
is disabled. This is most useful if source packages build nested binary
packages as part of their build.

.SH AUTHOR
.B pkgmaintainermangler
is developed by Adam Conrad <adconrad@ubuntu.com>.
