# input plugins
debian/tmp/usr/lib/xine/plugins/*/xineplug_inp_bluray.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_inp_cdda.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_inp_dvb.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_inp_dvd.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_inp_file.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_inp_http.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_inp_mms.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_inp_net.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_inp_pnm.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_inp_pvr.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_inp_rtp.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_inp_rtsp.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_inp_smb.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_inp_stdin_fifo.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_inp_v4l*.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_inp_vcd.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_inp_vcdo.so

# audio output plugins
debian/tmp/usr/lib/xine/plugins/*/xineplug_ao_out_alsa.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_ao_out_jack.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_ao_out_file.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_ao_out_none.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_ao_out_oss.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_ao_out_pulseaudio.so

# video output plugins which don't fit in elsewhere
debian/tmp/usr/lib/xine/plugins/*/xineplug_vo_out_raw.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_vo_out_none.so

# decoder plugins
debian/tmp/usr/lib/xine/plugins/*/xineplug_decode_bitplane.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_decode_dvaudio.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_decode_dxr3_spu.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_decode_dxr3_video.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_decode_gsm610.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_decode_image.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_decode_lpcm.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_decode_mpc.so
#debian/tmp/usr/lib/xine/plugins/*/xineplug_decode_nsf.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_decode_real.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_decode_rgb.so
#debian/tmp/usr/lib/xine/plugins/*/xineplug_decode_speex.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_decode_spu.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_decode_spucc.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_decode_spucmml.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_decode_spudvb.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_decode_spuhdmv.so
#debian/tmp/usr/lib/xine/plugins/*/xineplug_decode_sputext.so
#debian/tmp/usr/lib/xine/plugins/*/xineplug_decode_theora.so
debian/tmp/usr/lib/xine/plugins/2.2/xineplug_decode_vdpau_h264_alter.so
debian/tmp/usr/lib/xine/plugins/2.2/xineplug_decode_vdpau_h264.so
debian/tmp/usr/lib/xine/plugins/2.2/xineplug_decode_vdpau_mpeg12.so
debian/tmp/usr/lib/xine/plugins/2.2/xineplug_decode_vdpau_mpeg4.so
debian/tmp/usr/lib/xine/plugins/2.2/xineplug_decode_vdpau_vc1.so
#debian/tmp/usr/lib/xine/plugins/*/xineplug_decode_vorbis.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_decode_yuv.so

# demuxer plugins
debian/tmp/usr/lib/xine/plugins/*/xineplug_dmx_asf.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_dmx_audio.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_dmx_avi.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_dmx_fli.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_dmx_flv.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_dmx_games.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_dmx_iff.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_dmx_image.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_dmx_matroska.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_dmx_mng.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_dmx_modplug.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_dmx_nsv.so
#debian/tmp/usr/lib/xine/plugins/*/xineplug_dmx_ogg.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_dmx_playlist.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_dmx_pva.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_dmx_qt.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_dmx_rawdv.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_dmx_real.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_dmx_slave.so
#debian/tmp/usr/lib/xine/plugins/*/xineplug_dmx_sputext.so
debian/tmp/usr/lib/xine/plugins/2.2/xineplug_dmx_vc1_es.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_dmx_yuv4mpeg2.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_dmx_yuv_frames.so

# decoder/demuxer (combined) plugins
debian/tmp/usr/lib/xine/plugins/*/xineplug_flac.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_wavpack.so

# postprocess plugins
debian/tmp/usr/lib/xine/plugins/*/post/xineplug_post_mosaico.so
debian/tmp/usr/lib/xine/plugins/*/post/xineplug_post_audio_filters.so
debian/tmp/usr/lib/xine/plugins/*/post/xineplug_post_visualizations.so
debian/tmp/usr/lib/xine/plugins/*/post/xineplug_post_goom.so
debian/tmp/usr/lib/xine/plugins/*/post/xineplug_post_switch.so
debian/tmp/usr/lib/xine/plugins/*/post/xineplug_post_tvtime.so
