# X-based video output plugins

debian/tmp/usr/lib/xine/plugins/*/xineplug_vo_out_dxr3.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_vo_out_opengl.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_vo_out_sdl.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_vo_out_syncfb.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_vo_out_xcbshm.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_vo_out_xcbxv.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_vo_out_xdirectfb.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_vo_out_xshm.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_vo_out_xv.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_vo_out_xvmc.so
debian/tmp/usr/lib/xine/plugins/*/xineplug_vo_out_xxmc.so
