.TH chm_http 1 "2007-04-05" "" ""
.SH NAME
chm_http \- Simplistic web server to allow browsing of chm files without
extracting them.
.SH SYNOPSIS
.B chm_http
[\fIOPTION\fR]... [\fIFILE\fR]...
.SH DESCRIPTION
.PP
chm_http sets up a simplistic webserver that allows you to view the specified
chm file through a regular web browser, without extracting them. In the words of
the author it's "probably badly broken", so use it with caution.
.PP
.SH USAGE
chm_http [\-\-port=PORT] [\-\-bind=IP] <chmfile>
.SH OPTIONS
.TP
\fB\-\-port=\fIPORT\fR
PORT Specify the port for server
.TP
\fB\-\-bind=\fIIP_ADDRESS\fR
Bind the server with IP ADDRESS
.SH SEE ALSO
Website: <http://www.jedrea.com/chmlib/>
.SH AUTHOR
chm_http was written by Jed Wing <jedwin@ugcs.caltech.edu>
.PP
This manual page was written by Bymin Cutler <cutlerbc@simla.colostate.edu> and
formatted by Kartik Mistry <kartik.mistry@gmail.com>, for the Debian project
(but may be used by others).
