.TH enum_chmLib 1 "2007-04-05" "" ""
.SH NAME
enum_chmLib \- Lists the contents of a chm file.
.SH SYNOPSIS
.B enum_chmLib
[\fIFILE\fR]...
.SH DESCRIPTION
.PP
enum_chmLib lists the contents of the specified chm file to stdout.
.PP
.SH USAGE
enum_chmLib <chmfile>
.SH OPTIONS
enum_chmLib has no options.
.SH SEE ALSO
Website: <http://www.jedrea.com/chmlib/>
.SH AUTHOR
enum_chmLib was written by Jed Wing <jedwin@ugcs.caltech.edu>
.PP
This manual page was written by Bymin Cutler <cutlerbc@simla.colostate.edu> and
formatted by Kartik Mistry <kartik.mistry@gmail.com>, for the Debian project
(but may be used by others).
