.TH extract_chmLib 1 "2007-04-05" "" ""
.SH NAME
extract_chmLib \- Extracts a chm file into a directory.
.SH SYNOPSIS
.B extract_chmLib
[\fIFILE\fR]... [\fIDIR\fR]...
.SH DESCRIPTION
.PP
extract_chmLib extracts the contents of the specified chm file into the
specified directory.
.PP
.SH USAGE
extract_chmLib <chmfile> <dir>
.SH OPTIONS
extract_chmLib has no options.
.SH SEE ALSO
Website: <http://www.jedrea.com/chmlib/>
.SH AUTHOR
extract_chmLib was written by Jed Wing <jedwin@ugcs.caltech.edu>
.PP
This manual page was written by Bymin Cutler <cutlerbc@simla.colostate.edu> and
formatted by Kartik Mistry <kartik.mistry@gmail.com>, for the Debian project
(but may be used by others).
