.TH test_chmLib 1 "2007-04-05" "" ""
.SH NAME
test_chmLib \- Extracts a file out of a chm file.
.SH SYNOPSIS
.B test_chmLib
[\fIFILE\fR] [\fIFILENAME\fR] [\fIDESTFILE\fR]
.SH DESCRIPTION
.PP
test_chmLib pulls <filename> out of <chmfile> and writes it to <destfile>.
.PP
.SH USAGE
test_chmLib <chmfile> <filename> <destfile>
.SH OPTIONS
test_chmLib has no options.
.SH SEE ALSO
Website: <http://www.jedrea.com/chmlib/>
.SH AUTHOR
test_chmLib was written by Jed Wing <jedwin@ugcs.caltech.edu>
.PP
This manual page was written Bymin Cutler <cutlerbc@simla.colostate.edu> and
formatted by Kartik Mistry <kartik.mistry@gmail.com>, for the Debian project
(but may be used by others).
