.\" -*- nroff -*-
.TH SENSIBLE-EDITOR 1 "14 Nov 2010" "Debian"
.SH NAME
sensible-editor, sensible-pager, sensible-browser \- sensible editing, paging, and web browsing
.SH SYNOPSIS
.BR sensible-editor " [OPTIONS...]"
.br
.BR sensible-pager " [OPTIONS...]"
.br
.BR sensible-browser " url"
.br
.SH DESCRIPTION
.BR sensible-editor ", " sensible-pager " and " sensible-browser
make sensible decisions on which editor, pager, and web browser to call,
respectively.  Programs in Debian can use these scripts
as their default editor, pager, or web browser or emulate their behavior.
.SH "SEE ALSO"
Documentation of the EDITOR, VISUAL, PAGER, and BROWSER variables in
.BR environ (7)
