Document: growlight
Title: Debian growlight Manual
Author: <insert document author here>
Abstract: This manual describes what growlight is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/growlight/growlight.sgml.gz

Format: postscript
Files: /usr/share/doc/growlight/growlight.ps.gz

Format: text
Files: /usr/share/doc/growlight/growlight.text.gz

Format: HTML
Index: /usr/share/doc/growlight/html/index.html
Files: /usr/share/doc/growlight/html/*.html
