.TH HEVEA 1
.SH NAME
bibhva \- A BibTeX wrapper for use with HeVeA
.SH SYNOPSIS
.B bibhva
.I 
.RI "[bibtex-options] <basename>"
.SH "DESCRIPTION"
This manual page documents briefly the
.BR bibhva
command.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.PP
This command is a simple wrapper for calling
.B bibtex
for use with
.B hevea.
Calling 
.I bibhva basename
runs 
.B bibtex 
on the input file
.I basename.haux
with output sent to the file
.I basename.hbbl.
.PP
All options are forwarded to
.B bibtex.

.SH SEE ALSO
.BR bibtex (1),
.BR hevea (1)
.P
The HeVeA documentation can be found  on the HeVeA home page
\fI http://hevea.inria.fr/\fR.
On a Debian system it can also be accessed at
\fI/usr/share/doc/hevea-doc/html\fR or through the Debian help
system, provided the package \fIhevea-doc\fR is installed.

.SH AUTHOR
\fBBibhva\fR is written by Luc Maranget <Luc.Maranget@inria.fr>.
.PP
This manual page was written by Ralf Treinen <treinen@debian.org>.
