.TH V86D 8 "June 2008" "v86d" "Manual"
.SH NAME
v86d \- daemon to run x86 code in an emulated environment
.SH SYNOPSIS
.B v86d
.SH DESCRIPTION
v86d provides a backend for kernel drivers that need to execute
x86 BIOS code. The code is executed in a controlled environment
and the results are passed back to the kernel via the netlink
interface.
.PP
v86d should \fBNOT\fR be run by the user, the kernel will call it, when it is needed.
.SH AUTHOR
v86d is written by Michal Januszewski.
.PP
This manual page was written by Evgeni Golov <sargentd@die-welt.net>,
for the Debian project (but may be used by others).
