.TH "Scilab" "1" "November 18, 2008"
.SH NAME
scilab-cli \- Scientific software package - Command Line Interpreter
.SH SYNOPSIS
.B scilab [ \-h  |  \-f file  |  \-e instruction  |  \-l lang  |  \-mem n  |  \-nb  |  \-ns  |  \-nouserstartup  |  \-version ]
.br
This manual page documents briefly the
.B scilab
commands.
scilab-cli provides Scilab as a computing engine. It is similar to call
scilab -nwni. Somes features are disabled in this mode 
(graphic, GUI, Xcos...).
.PP
.SH OPTIONS
A complete list of options is included below.
.TP
.B \-h
Show the list of options.
.TP
.B \-f file
Execute the scilab script given in
.B file
argument.
Note that \-e and \-f options are mutually exclusive.
.TP
.B \-e instruction
Execute the scilab instruction given in
.B instruction
argument.
Note that \-e and \-f options are mutually exclusive.
.TP
.B \-l lang
Launch Scilab in the specified language. The lang must be the locale code 
(ie fr_FR, en_US...)
.TP
.B \-nb
Do not display the Scilab banner at starting time.
.TP
.B \-ns
Do not execute scilab.start startup file
.TP
.B \-mem N
Set the initial stacksize
.TP
.B \-nouserstartup
Do not execute the user startup files SCIHOME/.scilab or SCIHOME/scilab.ini.
.TP
.B \-version
Print product version and exit.
.SH FILES
.IR ~/.Scilab/<Scilab_version>/.scilab 
The user startup script.
.br
.IR ~/.Scilab/<Scilab_version>/scilab.ini
The user startup script.
.br
.IR ~/.Scilab/<Scilab_version>/configuration.xml
The configuration of the GUI
.br
.IR ~/.Scilab/<Scilab_version>/.history.scilab
The history of commands
.br
.IR SCI/modules/jvm/etc/jvm_options.xml
Options given to the JVM
.br
.IR SCI/etc/modules.xml
List of Scilab modules 
.br
.IR SCI/etc/classpath.xml
Where Scilab should load the Java libraries
.br
.IR SCI/etc/librarypath.xml
Where Scilab should look for JNI libraries
.SH AUTHOR
Scilab was written by the Scilab Consortium.
.PP
This manual page was written by Sylvestre Ledru <sylvestre@debian.org>.
