.TH "f-spot" "1"
.SH "NAME"
f-spot \- A program to manage a photo collection
.SH "SYNOPSIS"
\fBf-spot [\fIoption\fB]
.SH "DESCRIPTION"
.B f-spot
is a program that manages a photo collection, with the ability to import directly from a digital camera.
.SH "OPTIONS"
.IP "\-\-view \fIFILE OR DIRECTORY\fR\fP" 10
View a specified image or directory
.IP "\-\-import \fIURI\fR\fP" 10
Import from the given URI
.IP "\-\-slideshow\fP" 10
Display a slideshow
.IP "\-\-shutdown\fP" 10
Shutdown a running f-spot server
.IP "\-\-debug\fP" 10
Run f-spot with mono in debug mode
.IP "\-?, \-\-help\fP" 10
Show help message
.IP "\-\-usage\fP" 10
Display brief usage message
.SH "AUTHOR"
.PP
This manual page was written by Andrew Burton adb@iinet.net.au for the \fBDebian GNU/Linux\fP system (but may be used by others).
