debian/avidemux-qt.desktop usr/share/applications
debian/avidemux-qt.xpm usr/share/pixmaps
usr/bin/avidemux2_qt4
usr/lib/libADM_UIQT4.so
usr/lib/libADM_render_qt4.so
usr/lib/ADM_plugins/videoFilter/libADM_vf_colorYUV_qt4.so
usr/lib/ADM_plugins/videoFilter/libADM_vf_avisynthResize_qt4.so
usr/lib/ADM_plugins/videoFilter/libADM_vf_asharp_qt4.so
usr/lib/ADM_plugins/videoFilter/libADM_vf_sub_qt4.so
usr/lib/ADM_plugins/videoFilter/libADM_vf_mplayerResize_qt4.so
usr/lib/ADM_plugins/videoFilter/libADM_vf_eq2_qt4.so
usr/lib/ADM_plugins/videoFilter/libADM_vf_cnr2_qt4.so
usr/lib/ADM_plugins/videoFilter/libADM_vf_hue_qt4.so
usr/lib/ADM_plugins/videoFilter/libADM_vf_mpdelogo_qt4.so
usr/lib/ADM_plugins/videoFilter/libADM_vf_crop_qt4.so
usr/lib/ADM_plugins/videoFilter/libADM_vf_equalizer_qt4.so
usr/lib/ADM_plugins/videoFilter/libADM_vf_contrast_qt4.so
usr/lib/ADM_plugins/videoFilter/libADM_vf_chromaShift_qt4.so
usr/lib/ADM_plugins/videoEncoder/x264/libADM_vidEnc_x264_Qt.so
usr/lib/ADM_plugins/videoEncoder/xvid/libADM_vidEnc_Xvid_Qt.so
usr/lib/ADM_plugins/videoFilter/libADM_vf_curveEditor_qt4.so
