.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH DPROF2CALLTREE 1 "October 15, 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
dprof2calltree \- convert perl's DProf profiling data to KCachegrind calltree format
.SH SYNOPSIS
.B dprof2calltree
\fB\-f\fP \fIinput\fP
[ \fB\-o\fP \fIoutput\fP ]
.SH DESCRIPTION
\fBdprof2calltree\fP reads the \fItmon.out\fP profiling data output by
Perl's Devel::DProf profiling package, and converts it into calltree format
for use by KCachegrind.
.PP
This utility is part of the KDE Software Development Kit.
.SH OPTIONS
.TP
\fB\-f\fP \fIinput\fP
Specifies the DProf \fItmon.out\fP file to convert.
.TP
\fB\-o\fP \fIoutput\fP
Write the calltree output to the given file for use by KCachegrind.
If omitted, the output will be written to file of the form
\fIcachgrind.out.<input>\fP.
.SH EXAMPLE
If you run a perl script as:
.PP
.RS
perl \-d:DProf yourscript.pl
.RE
.PP
then this will write profiling data to \fItmon.out\fP.  You can then
work with this data in KCachegrind as follows:
.PP
.RS
dprof2calltree \-f tmin.out \-o cachegrind.out.foo
.br
kcachegrind cachegrind.out.foo
.RE
.SH SEE ALSO
.BR kcachegrind (1).
.SH AUTHOR
This converter was written by George Schlossnagle <george@omniti.com>.
.br
This manual page was prepared by Ben Burton <bab@debian.org>
for the Debian GNU/Linux system (but may be used by others).
