.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH FINDMISSINGCRYSTAL 1 "February 6, 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
findmissingcrystal \- determine which KDE Crystal icons are the same as
the KDE Classic hicolor icons
.SH SYNOPSIS
.B findmissingcrystal
.I module
.SH DESCRIPTION
\fBfindmissingcrystal\fP is a small utility that runs through the icons
in the given KDE module and determines which Crystal icons from that
module are identical to the old KDE Classic hicolor icons.
.PP
This script \fBmust\fP be run from the top-level directory of a KDE source
tree (i.e., the directory containing \fIkdelibs\fP, \fIkdebase\fP, etc.).
It is assumed that \fImodule\fP is a top-level module in the source tree,
and it is also assumed that the source tree contains the \fIkdeartwork\fP
module (which contains the old hicolor icons).
.PP
For each Crystal icon in the given module, a message will be output
describing whether the icon is new (no matching hicolor icon was found),
different from the hicolor icon or the same as the hicolor icon.
.PP
This utility is part of the KDE Software Development Kit.
.SH AUTHOR
This manual page was prepared by Ben Burton <bab@debian.org>
for the Debian GNU/Linux system (but may be used by others).
