.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH OP2CALLTREE 1 "October 15, 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
op2calltree \- convert OProfile profiling data to KCachegrind calltree format
.SH SYNOPSIS
.B op2calltree
.SH DESCRIPTION
\fBop2calltree\fP reads the profiling data output by OProfile v0.8 and
converts it into calltree format for use by KCachegrind.
.PP
The OProfile data must be supplied on standard input, and should be
obtained by running:
.PP
.RS
opreport \-gdf
.RE
.PP
This converter will then write a separate calltree data file for each
application, to a file of the form \fIoprof.out.<app>\fP.
.PP
This utility is part of the KDE Software Development Kit.
.SH SEE ALSO
.BR kcachegrind (1).
.SH AUTHOR
This converter was written by Josef Weidendorfer <Josef.Weidendorfer@gmx.de>.
.br
This manual page was prepared by Ben Burton <bab@debian.org>
for the Debian GNU/Linux system (but may be used by others).
