#!/bin/sh

grubmenu=/boot/grub/menu.lst
if [ -f "$grubmenu" ]; then
    # tweak grub to support serial console

    sed -i -e 's,^serial.*,serial --unit=0 --speed=38400,g' $grubmenu
    # force serial console only:
    #sed -i -e 's/ro$/ro console=ttyS0,38400/g' $grubmenu
    if egrep -q ^terminal $grubmenu ; then
        # add terminal entry if not present
        echo terminal console >> $grubmenu
    fi
    # enable both console and serial terminal
    sed -i -e 's,^terminal.*,terminal --timeout=5 console serial,g' $grubmenu

    update-grub
fi

grub2default=/etc/default/grub
if [ -f "$grub2default" ]; then
    grub_pc_version=$(dpkg -l grub-pc | awk '/^ii/{print $3}') || true

    # disable graphical console for grub2:
    if [ -n "$grub_pc_version" ] && dpkg --compare-versions "$grub_pc_version" ge "1.98+20100527-1" ; then
        # enable both serial and regular console if newer version of grub.
        echo GRUB_TERMINAL=\'serial console\' >> $grub2default
    else
        # use regular console only
        echo GRUB_TERMINAL=console >> $grub2default
    fi

    # ensure the updates go live
    update-grub
fi
