debian/themes /usr/share
debian/tmp/usr/share/icons/Crux
debian/tmp/usr/share/icons/Mist
debian/tmp/usr/share/themes/Clearlooks
debian/tmp/usr/share/themes/ClearlooksClassic
debian/tmp/usr/share/themes/Crux/index.theme
debian/tmp/usr/share/themes/Glossy
debian/tmp/usr/share/themes/Glider
debian/tmp/usr/share/themes/Mist/index.theme
debian/tmp/usr/share/themes/Mist/metacity-1
debian/tmp/usr/share/themes/Simple
