#!/bin/sh -e

update-alternatives \
	--install /usr/bin/cli cli /usr/bin/mono 10 \
	--slave /usr/share/man/man1/cli.1.gz cli.1.gz /usr/share/man/man1/mono.1.gz

if [ configure = "$1" ] && [ -x /usr/sbin/update-binfmts ]; then
	update-binfmts --import cli
fi

if [ configure = "$1" ] && [ -d /usr/share/dotnet/mono/ ] && [ -L /usr/share/dotnet/mono ]; then
	# it's a symlink
	rm /usr/share/dotnet/mono
fi

if [ "$1" = "configure" ]; then
	ldconfig
fi
        
#DEBHELPER#
