.TH K3B "1" "December 2002" KDE "KDE Application"
.SH NAME
k3b \- KDE CD burning program
.SH SYNOPSIS
.B k3b
[\fIQt-options\fR] [\fIKDE-options\fR] [\fIFile\fR]
.SH DESCRIPTION
This manual page documents briefly the
.B k3b
KDE Application.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.PP
K3b is a CD burning program that has two aims:
usability and as many features as possible.
.P
This program is part of the official KDE extra gear #1 module.
.SH OPTIONS
.SS "Arguments:"
.TP
File(s)
file(s) to open
.SS "General Options"
.B \-\-help
Show help about options
.TP
.B \-\-help\-qt
Show Qt specific options
.TP
.B \-\-help\-kde
Show KDE specific options
.TP
.B \-\-help\-all
Show all options
.TP
.B \-\-author
Show author information
.TP
.B \-v\fR, \fB\-\-version
Show version information
.TP
.B \-\-license
Show license information
.TP
.B \-\-
End of options
.SS "Options:"
.B \-\-datacd
Create a new data CD project and add all given files
.TP
.B \-\-audiocd
Create a new audio CD project and add all given files
.TP
.B \-\-videocd
Create a new video CD project and add all given files
.TP
.B \-\-mixedcd
Create a new mixed mode CD project and add all given files
.TP
.B \-\-emovixcd
Create a new eMovix CD project and add all given files
.TP
.B \-\-datadvd
Create a new data DVD project and add all given files
.TP
.B \-\-emovixdvd
Create a new eMovix DVD project and add all given files
.TP
.B \-\-copycd
Open the CD copy dialog
.TP
.B \-\-clonecd
Open the CD cloning dialog
.TP
.B \-\-cdimage
Write an ISO image or Bin/Cue image to cd
.TP
.B \-\-erasecd
Erase a CDRW
.TP
.B \-\-formatdvd
Format a DVD-RW or DVD+RW
.TP
.BI \-\-lang \ language
Set the GUI language
.SS "Qt options:"
.TP
.BI \-\-display \ displayname
Use the X-server display \fIdisplayname\fP.
.TP
.BI \-\-session \ sessionId
Restore the application for the given \fIsessionId\fP.
.TP
.B \-\-cmap
Causes the application to install a private color
map on an 8-bit display.
.TP
.BI \-\-ncols \ count
Limits the number of colors allocated in the color
cube on an 8-bit display, if the application is
using the QApplication::ManyColor color
specification.
.TP
.B \-\-nograb
tells Qt to never grab the mouse or the keyboard.
.TP
.B \-\-dograb
running under a debugger can cause an implicit
.B \-nograb, use \fB\-dograb\fR to override.
.TP
.B \-\-sync
switches to synchronous mode for debugging.
.TP
.BI "\-\-fn\fR, \fP\-\-font" \ fontname
defines the application font.
.TP
.BI "-\-bg\fR, \fB\-\-background"  \ color
sets the default background color and an
application palette (light and dark shades are
calculated).
.TP
.BI "\-\-fg\fR, \fB\-\-foreground"  \ color
sets the default foreground color.
.TP
.BI \-\-btn\fR, \fB\-\-button \ color
sets the default button color.
.TP
.BI \-\-name \ name
sets the application name.
.TP
.BI \-\-title \ title
sets the application title (caption).
.TP
.B \-\-visual TrueColor
forces the application to use a TrueColor visual on
an 8-bit display.
.TP
.BI \-\-inputstyle \ inputstyle
sets XIM (X Input Method) input style. Possible
values are 
.BR onthespot ", " overthespot ", " offthespot and root .
.TP
.BI \-\-im " XIM-server"
set XIM server.
.TP
.B \-\-noxim
disable XIM.
.TP
.B \-\-reverse
mirrors the whole layout of widgets.
.SS "KDE options:"
.TP
.BI \-\-caption \ caption
Use \fIcaption\fP as name in the titlebar.
.TP
.BI \-\-icon \ icon
Use \fIicon\fP as the application icon.
.TP
.BI \-\-miniicon \ icon
Use \fIicon\fP as the icon in the titlebar.
.TP
.BI \-\-config \ filename
Use alternative configuration file.
.TP
.BI \-\-dcopserver \ server
Use the DCOP Server specified by \fIserver\fP.
.TP
.B \-\-nocrashhandler
Disable crash handler, to get core dumps.
.TP
.B \-\-waitforwm
Waits for a WM_NET compatible windowmanager.
.TP
.BI \-\-style \ style
sets the application GUI style.
.TP
.BI \-\-geometry \ geometry
sets the client geometry of the main widget.
.SH AUTHOR
K3b was written by
.nh
.ad l
Sebastian Trueg <trueg@informatik.uni-freiburg.de>
and Thomas Froescher <tfroescher@gmx.de>.
.hy
.br
Please use http://bugs.kde.org to report bugs, do not mail the authors directly.
.br
This manual page was prepared by
.nh
.ad l
Karolina Lindqvist <pgd\-karolinali@algonet.se>
.hy
for the Debian GNU/Linux system (but may be used by others).
.SH "SEE ALSO"
If the
.B khelpcenter
program is properly installed at your site, the command
.IP
.B khelpcenter help:/k3b
.PP
should give you access to the complete manual.
.P
Alternatively the manual can be browsed in
.B konqueror
giving it the URL help:/k3b

