usr/lib64/libncurses.so
obj-64/lib/libtic.so usr/lib64
obj-64/lib/libform.so usr/lib64
obj-64/lib/libmenu.so usr/lib64
obj-64/lib/libpanel.so usr/lib64
obj-64/lib/libtinfo.so usr/lib64
obj-64/lib/libncurses.a usr/lib64
obj-64/lib/libncurses++.a usr/lib64
obj-64/lib/libtic.a usr/lib64
obj-64/lib/libform.a usr/lib64
obj-64/lib/libmenu.a usr/lib64
obj-64/lib/libpanel.a usr/lib64
obj-64/lib/libtinfo.a usr/lib64
debian/libtermcap.so  usr/lib64
