=head1 NAME

extract_j2k_from_mj2 - extract j2k bitstreams from a mj2 file

=head1 SYNOPSIS

B<extract_j2k_from_mj2> I<input> I<output-base-name>


=head1 DESCRIPTION

extract_j2k_from_mj2 extracts j2k bitstreams that are wrapped within in mj2 file.

=head1 OPTIONS

=over

=item I<input>
The mj2 file to process

=item  I<output-base-name>

The base name used for each codestream found. Each codestream found will
create a new file with the name specified plus and underscore followed
by 5 digits that specifies the sequence, e.g.

output_00000.j2k

=back

=head1 EXAMPLE

You have a mj2 file that contains 3 j2k codesteams which you want to extract

I<extract_j2k_from_mj2 infile.mj2 example>

The following files will be created :-

example_00000.j2k
example_00001.j2k
example_00002.j2k

=head1 AUTHOR

Written by Robin Cornelius <robin.cornelius@gmail.com> based on the output of extract_j2k_to_mj2 as part of the Debian packaging of OpenJPEG

=head1 COPYRIGHT

Copyright 2009 Robin Cornelius <robin.cornelius@gmail.com>

=head1 SEE ALSO

L<wrap_j2k_to_mj2(1)>, L<frames_to_mj2(1)>, L<mj2_to_frames(1)>, L<http://www.openjpeg.org/index.php?menu=doc#MJ2>
