=head1 NAME

puzzle-diff - Compare pictures with libpuzzle

=head1 SYNOPSIS

[B<-b> I<<contrast barrier for cropping>>] [B<-c>] [B<-C> I<<max cropping ratio>>] [B<-e>] [B<-E> I<<similarity threshold>>] [B<-h>] [B<-H> I<<max height>>] [B<-l> I<<lambdas>>] [B<-n> I<<noise cutoff>>] [B<-p> I<<p ratio>>] [B<-t>] [B<-W> I<<max width>>] <file 1> <file 2>

=head1 DESCRIPTION

puzzle-diff compares two pictures and outputs the normalized distance.

Try I<puzzle-diff -h> for more info.

=head1 EXAMPLES

Output distance between two images:

=over 2

  $ puzzle-diff pic-a-0.jpg pics-a-1.jpg
  0.102286

=back

Compare two images, exit with 10 if they look the same, exit with 20 if they don't (may be useful for scripts):

=over 2

  $ puzzle-diff -e pic-a-0.jpg pics-a-1.jpg
  $ echo $?
  10

=back

Compute distance, without cropping and with computing the average intensity of the whole blocks:

=over 2

  $ puzzle-diff -p 1.0 -c pic-a-0.jpg pic-a-1.jpg
  0.0523151

=back

=head1 AUTHORS

Frank DENIS libpuzzle at pureftpd dot org

=head1 SEE ALSO

L<libpuzzle(3)>, L<puzzle_set(3)>

=cut
