.\"             -*-Nroff-*-
.\"
.TH W 1 "8 Dez 1993 " " " "Linux Benutzerhandbuch"
.SH NAME
w \- Zeigt an, wer am System angemeldet ist und was sie/er gerade tut. 
.SH SYNTAX
.B w
.RB [ \-husfVo ]
.RI [ Benutzer ]
.SH BESCHREIBUNG
.B w
zeigt Informationen über die gerade eingeloggten Benutzer und ihre Prozesse an. Die Kopfzeile enthält die aktuelle Zeit, die Zeit, seit der das System läuft, wie viele Benutzer gerade angemeldet sind und die durchschnittliche Systemlast der letzten 1, 5 und 15 Minuten.

Die folgenden Daten werden für jeden Benutzer angezeigt:
Der Login-Name, der tty-Name, der entfernte Host, die Login-Zeit, die Leerlaufzeit, JCPU , PCPU und die Kommandozeile des laufenden Prozesses.

Die JCPU-Zeit ist die Zeit, die von allen Prozessen genutzt wurde, die an dem jeweiligen Terminal angemeldet sind. Sie enthält keine abgeschlossenen Hintergrund-Aufträge, jedoch die derzeit laufenden Hintergrund-Aufträge.

Die PCPU-Zeit ist die Zeit, die vom derzeit laufenden Prozess bisher genutzt wurde.

.PP
.SH "OPTIONEN"
.TP 0.5i
.B "\-h "
Die Kopfzeile nicht ausgegeben.
.TP 0.5i
.B "\-u "
Ignoriert den Benutzernamen während der aktuelle Prozess und die CPU-Zeiten ermittelt werden. Probieren Sie die Option aus, indem Sie zunächst "su", danach "w" und "w \-u" eingeben.
.TP 0.5i
.B "\-s "
Das kurze Ausgabeformat verwenden.
Den Anmeldenamen, die JCPU und PCPU nicht ausgeben.
.TP 0.5i
.B "\-f "
Umschalten des
.B from
(remote host) Feldes. Die Standardeinstellung ist, das
.B from
Feld nicht auszugeben. Evtl. hat ihr Systemadministrator oder Paketbetreuer jedoch auch eine Version kompiliert, in der das
.B from
Feld standardmäßig angezeigt wird.
.TP 0.5i
.B "\-V "
Versionsinformation anzeigen.
.TP 0.5i
.B "\-o "
Altes Ausgabeformat. Druckt Leerzeichen für Leerlaufzeiten unter einer Minute.
.TP 0.5i
.B "Benutzer "
Zeigt nur Informationen über den angegebenen Benutzer an.

.SH DATEIEN
.TP
.I /var/run/utmp
Informationen darüber, wer gerade angemeldet ist
.TP
.I /proc
Prozessinformationen
.PP

.SH "SIEHE AUCH"
.BR free (1),
.BR ps (1),
.BR top (1),
.BR uptime (1),
.BR utmp (5),
.BR who (1)

.SH AUTOREN
.B w
ist von Charles Blake fast vollständig neu geschrieben worden. Die ursprüngliche Version wurde von Larry Greenfield <greenfie@gauss.rutgers.edu> und Michael K. Johnson <johnsonm@redhat.com> geschrieben.

Berichten Sie Fehler an <albert@users.sf.net>