#!/bin/sh

set -e

case $1 in
	upgrade)
		. /usr/share/debconf/confmodule
		db_version 2.0
		if dpkg --compare-versions "$2" lt 3.0.0~ ; then
			db_fset cman/upgrade-warning seen false
			db_input critical cman/upgrade-warning || true
			db_go
			
			db_get cman/upgrade-warning
			if [ "$RET" = "true" ] ; then
				echo "Aborting cman installation."
				exit 1
			fi
		fi
	;;
esac

#DEBHELPER#

exit 0
