.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH AUTODOCK 1 "Juli 23, 2007"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
autodock \- docking of chemical ligands to protein receptors
.SH SYNOPSIS
.B autodock4
.RI [ options ]
.SH DESCRIPTION
AutoDock perfoms the automated docking of chemical compounds to proteins, i.e. it
predicts how small molecules, such as substrates or drug candidates, bind to a receptor of known 3D structure.

The AutoDockSuite consists of two main programs of which AutoDock performs the
docking of the ligand to a set of grids describing the target protein and
AutoGrid pre-calculates these grids.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
.SH OPTIONS
.TP
.B \-p
.RI parameter_filename
.TP
.B \-l
.RI log_filename
.TP
.B \-o
Use old PDBQ format, charge q in columns 55-61
.TP
.B \-k
Keep original residue numbers
.TP
.B \-i
Ignore header-checking
.TP
.B \-t
Parse the PDBQ file to check torsions, then stop.
.TP
.B \-c < 
.RI command_file
Command mode, by file
.TP
.B \-c |
.RI control_program
Command mode, by control_program
.SH EXAMPLE

On Debian, the directory /usr/share/doc/autodock offers examples to run. Change to that directory and unpack (as root) the gzipped map files, then execute AutoDock as shown below:
.br
gunzip *.map.gz
.br
autodock4 \-p 1pgp.dpf \-l /tmp/1pgp.dlg

The interpretation of results is aided by the AutoDockTools suite. Please also inspect the tutorials offered online. 

.SH SEE ALSO
.BR autogrid (1),
.BR runAdt (1).
.br
http://autodock.scripps.edu
.br
http://autodock.scripps.edu/faqs-help/faq/what-is-the-command-line-to-start-autodock-4
.SH LICENSE
This software is made available under the terms of the GNU Public
License version 2 or later. This implies that this software may be
redistributed if the source is made available. It would however help
the future development of the AutoDockSuite if you register yourself
at http://autodock.scripps.edu/downloads.
.SH AUTHOR
The most prominent author of the version 4 of autodock is G. Morris
<garrett@scripps.edu>. See the AUTHORS file in /usr/share/doc/autodock
for details.
.PP
This manual page was written by Steffen Moeller <moeller@debian.org>,
for the Debian project (but may be used by others and is hopefully
adopted by the upstream developers).
