.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH ANTLR 1 "December 22, 2001" GNU antlr
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH "NAME"
ANTLR \- ANother Tool for Language Recognition
.SH "SYNOPSIS"
.B java antlr.Tool
.B or
.B runantlr
[\fI"args"\fR] \fIfile.g\fR
.br
.SH "DESCRIPTION"
ANTLR, ANother Tool for Language Recognition, (formerly PCCTS) is a
language tool that provides a framework for constructing recognizers,
compilers, and translators from grammatical descriptions containing
C++ or Java actions.
.TP
\fB\-o\fR \fIoutputDir\fR
specify output directory where all output generated.
.TP
\fB\-glib\fR \fIsuperGrammar\fR
specify location of supergrammar file.
.TP
\fB\-debug\fR
launch the ParseView debugger upon parser invocation.
.TP
\fB\-html\fR
generate an html file from your grammar (minus actions).
.TP
\fB\-diagnostic\fR
generate a textfile with diagnostics.
.TP
\fB\-trace\fR
have all rules call traceIn/traceOut.
.TP
\fB\-traceParser\fR
have parser rules call traceIn/traceOut.
.TP
\fB\-traceLexer\fR
have lexer rules call traceIn/traceOut.
.TP
\fB\-traceTreeParser\fR
have tree parser rules call traceIn/traceOut.

.SH "AUTHOR"
This manual page was written by John Leuner <jewel@debian.org>

.SH "SEE ALSO"
.BR java (1),
.BR http://www.antlr.org/
.br

