.TH DOCKMANAGER "1"
.SH NAME
dockmanager \- Helpers for your Dock.
.SH SYNOPSIS
dockmanager-settings [\fIoptions\fR]
.SH OPTIONS
.TP
.SH HOMEPAGE
For more information, please visit http://launchpad.net/dockmanager/
.SH AUTHORS
Michal Hruby <michal.mhr@gmail.com>, Robert Dyer <psybers@gmail.com>, Rico Tzschichholz <ricotz@ubuntu.com>
