#!/bin/sh -e

#DEBHELPER#

case "$1" in
    install | upgrade)
        # The transition from dav_svn.load with authz_svn_module in it,
        # to a separate .load file, happened in 1.6.17dfsg-2.  Here we
        # signal the postinst, with a temp file, to enable authz_svn.
        if grep -q '^LoadModule  *authz_svn_module' \
                   /etc/apache2/mods-enabled/dav_svn.load 2>/dev/null; then
            touch '/etc/apache2/#enable_authz_svn#'
        fi
        ;;
esac
