#!/bin/sh -e

case "$1" in
    configure)
        if [ -z "$2" ]; then
            # Enable on new installs only
            a2enmod dav_svn
        fi
        if [ -f '/etc/apache2/#enable_authz_svn#' ]; then
            # Enable on upgrades where this used to be implied by dav_svn.load
            a2enmod authz_svn
            rm -f '/etc/apache2/#enable_authz_svn#'
        fi
        invoke-rc.d apache2 restart || true
        ;;
esac

#DEBHELPER#
