tools/hook-scripts/*			usr/share/subversion/hook-scripts
BUILD/tools/hook-scripts/*		usr/share/subversion/hook-scripts
debian/contrib/commit-email.pl		usr/share/subversion/hook-scripts
debian/contrib/emacs/psvn.el		usr/share/emacs/site-lisp
debian/contrib/emacs/dsvn.el		usr/share/emacs/site-lisp
debian/contrib/emacs/50psvn.el		etc/emacs/site-start.d

tools/server-side/svn-backup-dumps.py		usr/bin
debian/contrib/svn_load_dirs/svn_load_dirs.pl	usr/bin
debian/contrib/svn-fast-backup			usr/bin
debian/contrib/svn-clean			usr/bin
debian/contrib/svn_apply_autoprops.py		usr/bin
debian/bin/svn-bisect				usr/bin
debian/bin/svnwrap				usr/bin
