sbin/extlinux			/usr/bin
usr/man/man1/extlinux.1		/usr/share/man/man1
usr/share/syslinux/chain.c32	/usr/lib/extlinux
usr/share/syslinux/mbr.bin	/usr/lib/extlinux
usr/share/syslinux/memdisk	/usr/lib/extlinux

debian/local/zz-extlinux	/etc/kernel/postrm.d
debian/local/zz-extlinux	/etc/kernel/postinst.d
debian/local/extlinux-install	/usr/sbin
debian/local/extlinux-install.8	/usr/share/man/man8
debian/local/extlinux-update	/usr/sbin
debian/local/extlinux-update.8	/usr/share/man/man8
