usr/bin/lss16toppm
usr/bin/md5pass
usr/bin/mkdiskimage
usr/bin/isohybrid.pl
usr/bin/ppmtolss16
usr/bin/pxelinux-options
usr/bin/sha1pass
usr/bin/syslinux2ansi
usr/man/man1/lss16toppm.1	/usr/share/man/man1
usr/man/man1/ppmtolss16.1	/usr/share/man/man1
usr/man/man1/syslinux2ansi.1	/usr/share/man/man1
usr/share/syslinux/*		/usr/lib/syslinux

README				/usr/share/doc/syslinux
doc/*				/usr/share/doc/syslinux
debian/manpages/isohybrid.pl.1	/usr/share/man/man1
