.TH "RDFPIPE" "1" "April 06, 2007" "rdflib 2.4.0" ""

.SH "NAME"
rdfpipe \- Serialization format converter

.SH "SYNOPSIS"
.nf 
.fam C
\fBrdfpipe\fP [OPTION]... [FILE]...
.fam T
.fi 

.SH "DESCRIPTION"
\fBrdfpipe\fR is a command\-line application for converting between any of the different serialization formats rdflib supports.


.SH "OPTIONS"

.TP 
.B 
\fB\-\-help\fP
Print help and exit.

.TP
.B
\fB\-\-input\-format \fP\fIFORMAT\fP
Format of the input document(s). It must be one of: 'xml', 'trix', 'n3', 'nt', 'rdfa'.

.TP
.B
\fB\-\-ns=\fP\fIprefix\fP\fB=\fP\fINAMESPACEURI\fP
Register a namespace binding (QName prefix to a base URI).  This can be used more than once.

.TP
.B
\fB\-\-output \fP\fIFORMAT\fP
Format of the final serialized RDF graph. One of: 'n3', 'xml', 'pretty-xml', 'turtle', 'nt'.

.TP
.B
\fB\-\-stdin\fP
Parse RDF from STDIN (useful for piping).

.SH "AUTHOR"
Written by Chimezie Ogbuji <chimezie@gmail.com>. This manpage has been written by Nacho Barrientos Arias <chipi@criptonita.com> for the Debian GNU/Linux system (but may be used by others).

.SH "BUGS"
Report bugs to Chimezie Ogbuji <chimezie@gmail.com>.

.SH "COPYRIGHT"
See /usr/share/doc/python-rdflib/copyright for further information.

.SH "SEE ALSO"
http://rdflib.net/

.PP 
.nf 
.fam C
