.TH DH_NUMPY 1 "2012-01-29" "Numpy"
.SH NAME
dh_numpy \- adds Numpy depends to python:Depends substvar
.SH SYNOPSYS
\fBdh_numpy\fR [\fIdebhelper\ options\fR]
.SH DESCRIPTION
dh_numpy adds information about the correct versioned depends on python-numpy to python:Depends substvar.
.PP
This is needed because some Python extensions require strict versioned depends on python-numpy, and using this helper script is the easiest and most consistent way to get them.
.PP
The helper script uses the information stored in /usr/share/numpy/versions, and the architecture type of the package, to generate the Depends information; for a detailed description of how the dependencies are generate, please refer to /usr/share/doc/python-numpy/README.DebianMaints .
.SH "SEE ALSO"
\fIdebhelper\fR(7)
.PP
This program is not a part of debhelper (and it's provided by python-numpy).
