.TH "CCLIB-CDA" "1" "2011-07-17" "" "User commands"

.SH NAME
cclib-cda \- command-line interface for charge decomposition analysis with cclib

.SH SYNOPSIS
.B cclib-cda
.RI [ files ]

.SH DESCRIPTION
The command cclib-cda a simple command-line interface to cclib that invokes the
charge decomposition analysis (CDA) for a given log file.

.SH AUTHOR
This manpage was written by \fBKarol M. Langner\fR <\&karol.langner@gmail.com\&>
for the Debian distribution (but may be used by others).
