.TH GConf-cleaner "1" "August 2007" "GConf-cleaner 0.0.3" "User commands"
.SH NAME
GConf-cleaner - tool to clean gconf settings

.SH DESCRIPTION
GConf Cleaner is a tool to clean your GConf database up that
is possibly cluttered with unnecessary or invalid keys.  You
may want to keep a clean your GConf database. this tool
might help you in this case.

.SH SEE ALSO
Project homepage is located at: http://code.google.com/p/gconf-cleaner/

.SH AUTHORS
Akira TAGOH <akira@tagoh.org>

This manual page was written for the Debian system by
Julien Valroff <julien@kirya.net> but may be used by others.

.SH COPYRIGHT
Copyright 2007 Akira TAGOH <akira@tagoh.org>

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

