usr/share/icons/hicolor/128x128/apps/kdcraw.png
usr/share/icons/hicolor/32x32/apps/kdcraw.png
usr/share/icons/hicolor/48x48/apps/kdcraw.png
usr/share/icons/hicolor/64x64/apps/kdcraw.png
usr/share/kde4/apps/libkdcraw/profiles/adobergb.icm
usr/share/kde4/apps/libkdcraw/profiles/applergb.icm
usr/share/kde4/apps/libkdcraw/profiles/prophoto.icm
usr/share/kde4/apps/libkdcraw/profiles/srgb-d65.icm
usr/share/kde4/apps/libkdcraw/profiles/srgb.icm
usr/share/kde4/apps/libkdcraw/profiles/widegamut.icm

