lib/matplotlib/backends/Matplotlib.nib /usr/share/matplotlib/
lib/matplotlib/mpl-data/fonts/ /usr/share/matplotlib/mpl-data/
lib/matplotlib/mpl-data/images/ /usr/share/matplotlib/mpl-data/
lib/matplotlib/mpl-data/lineprops.glade /usr/share/matplotlib/mpl-data/
matplotlibrc.template /usr/share/matplotlib/matplotlib.conf
lib/matplotlib/mpl-data/matplotlibrc /etc/
lib/matplotlib/mpl-data/sample_data/ /usr/share/matplotlib/
