.TH PYCENTRAL
.SH NAME
py_compilefiles \- byte-compile python .py files
.SH SYNOPSIS
\fBpy_compilefiles\fP [\fIoptions\fP] [\fIfile\fP ...] [\fB\-\fP]
.SH DESCRIPTION
.B py_compilefiles
compiles Python .py source files into .pyc or .pyo bytecode format.
.SH OPTIONS
.TP
\fB\-f\fP
force rebuild even if timestamps are up-to-date.
.TP
\fB\-i\fP
ignore errors on byte compilation.
.TP
\fB\-q\fP
quiet operation.
.TP
\fB\-x\fP \fIregexp\fP
skip files matching the regular expression regexp
the regexp is search for in the full path of the file.
.PP
If a filename is given as a minus sign (\fB\-\fP), a list of files separated
by newline is read from standard input.
.SH AUTHOR
Matthias Klose, Bastian Kleineidam
