.TH PYCENTRAL
.SH NAME
pycentral \- register and build utility for Python packages
.SH SYNOPSIS
.PP
.B pycentral
.I [\-h] [\-v] <cmd> [<cmd options>] [<args>]
.SH DESCRIPTION
.PP
.B pycentral
 provides support for installing python modules independent
 of the current installed Python version and handling
 byte-compilation and -removal tasks in installation scripts.
.SH OPTIONS
.TP
.I \-v, \-\-version
Limit the output to the version numbers of the python versions.
.TP
.I \-h, \-\-help
Print a help text.
.PP
pycentral has the following sub commands. For fine grained help,
call: pycentral <cmd>.
.TP
.I bccompile
Byte compile .py files in a package.
.TP
.I bcremove
Remove the byte compiled .py files.
.TP
.I list
List all managed files.
.TP
.I pkginstall
Make a package available for all supported runtimes.
.TP
.I pkgprepare
Prepare a package for all supported runtimes.
.TP
.I pkgremove
Remove a package installed for all supported runtimes.
.TP
.I pkglist
List pycentral-managed files of a package for all supported runtimes.
.TP
.I rtinstall
Make installed packages available for this runtime.
.TP
.I rtremove
Remove packages installed for this runtime.
.TP
.I updatedefault
Update the default python version.
.TP
.I 
debhelper
move files to pycentral locaation, variable substitutions (called by
dh_pycentral).
.TP
.I pycentraldir <package>
Show the installation directory used by pycentral for <package>.
.TP
.I showdefault
Show default python version number. Deprecated, use pyversions(1)
.TP
.I showsupported
Show the supported python versions. Deprecated, use pyversions(1)
.TP
.I showversions
Show version numbers of supported python versions.
Deprecated, use pyversions(1)
dh_pycentral, should not be called directly).
.TP
.I version
Show the pycentral version.

.SH FILES
.B /etc/python/debian_config
is searched for the attribute
.I overwrite-local.
If set to 1, or True, existing files in
/usr/lib/pythonX.Y/*-packages are overwritten with symbolic links
to the pycentral install area. The default is to abort the
installation of a package, when files already exist. This behaviour
may be useful, when python libraries were manually installed into this
directory.
The attribute
.I byte-compile
can be set to a comma separated list of the values
.I standard
and
.I optimze
to indicate how files should be byte-compiled.

.SH SEE ALSO
pyversions(1), Python policy.
.SH AUTHOR
Matthias Klose
