Document: xbmc
Title: Debian xbmc Manual
Author: <insert document author here>
Abstract: This manual describes what xbmc is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/xbmc/xbmc.sgml.gz

Format: postscript
Files: /usr/share/doc/xbmc/xbmc.ps.gz

Format: text
Files: /usr/share/doc/xbmc/xbmc.text.gz

Format: HTML
Index: /usr/share/doc/xbmc/html/index.html
Files: /usr/share/doc/xbmc/html/*.html
