#!/bin/bash

echo "spacefm-prerm $1"

for spacefm_file in \
    /usr/share/spacefm/spacefm-manual-en.html \
    /usr/share/spacefm/ui/prefdlg.ui \
    /usr/share/spacefm/ui/find-files.ui \
    /usr/share/spacefm/ui/godlg.ui \
    /usr/share/spacefm/ui/appchooserdlg.ui \
    /usr/share/spacefm/ui/file_properties.ui \
    /usr/share/spacefm/ui/about-dlg.ui \
    /usr/share/spacefm/ui \
    /usr/share/mime/packages/spacefm-mime.xml \
    /usr/share/mime/packages \
    /usr/share/applications/spacefm-find.desktop \
    /usr/share/applications/spacefm-folder-handler.desktop \
    /usr/share/applications/spacefm.desktop \
    /usr/share/locale/*/LC_MESSAGES/spacefm.mo \
    /usr/share/doc/spacefm/spacefm-manual-en.html \
    /usr/share/doc/spacefm \
    /usr/share/pixmaps/spacefm-48-pyramid-red.png \
    /usr/share/pixmaps/spacefm-128-pyramid-red.png \
    /usr/share/pixmaps/spacefm-128-pyramid-blue.png \
    /usr/share/pixmaps/spacefm-48-folder-blue.png \
    /usr/share/pixmaps/spacefm-48-cube-red.png \
    /usr/share/pixmaps/spacefm-root.png \
    /usr/share/pixmaps/spacefm-48-pyramid-green.png \
    /usr/share/pixmaps/spacefm-128-cube-red.png \
    /usr/share/pixmaps/spacefm-find.png \
    /usr/share/pixmaps/spacefm-48-folder-red.png \
    /usr/share/pixmaps/spacefm-128-pyramid-green.png \
    /usr/share/pixmaps/spacefm-48-cube-green.png \
    /usr/share/pixmaps/spacefm.png \
    /usr/share/pixmaps/spacefm-128-cube-blue.png \
    /usr/share/pixmaps/spacefm-48-pyramid-blue.png \
    /usr/share/pixmaps/spacefm-48-cube-blue.png \
    /usr/share/pixmaps/spacefm-128-cube-green.png \
    /usr/share/pixmaps \
    /usr/bin/spacefm \
    /usr/bin/spacefm-auth
do
    if [ -d "$spacefm_file" ]; then
        rmdir --ignore-fail-on-non-empty "$spacefm_file"
    else
        rm -f "$spacefm_file"
    fi
done


