.TH UPDATE-FLASHPLUGIN-NONFREE 8 "August 15, 2007"

.SH NAME
update-flashplugin-nonfree \- program to get the newest Adobe Flash Player

.SH SYNOPSIS
.B update-flashplugin-nonfree
.RI --install
.br
.B update-flashplugin-nonfree
.RI --uninstall

.SH DESCRIPTION
The program
.B update-flashplugin-nonfree
takes care of
downloading last minute information from Debian about suitable versions,
removing the installed Adobe Flash Plugin if it has been reported as insecure,
or, if a newer suitable version is available,
downloading a newer Adobe Flash Player and its installer from the Adobe download site,
run the downloaded installer to install the Adobe Flash Player on the local system,
and then move the installed files to where they fit on a Debian system.
.PP
A copy of the downloaded .tar.gz is saved in /var/cache/flashplugin-nonfree for later reuse.
.PP
The program
.B update-flashplugin-nonfree
is used in the
.B postinst
and
.B prerm
scripts of the Debian package,
but this program can also be run manually by root.

.SH OPTIONS
.TP
.B \-\-install
To install, update or remove the Adobe Flash Player
depending on downloaded last minute information from Debian about suitable versions.
.TP
.B \-\-uninstall
To remove the Adobe Flash Player.
.TP
.B \-\-verbose
Produce detailed information about what's happening.
.TP
.B \-\-quiet
Produce no informational output.

.SH SEE ALSO
.TP
.B http://wiki.debian.org/FlashPlayer
If you subscribe to this wiki page, then you will receive updates via e-mail.
.TP
.B http://www.adobe.com/
The Adobe homepage.
