.\" $Id: update-fonts-alias.8 189 2005-06-11 00:04:27Z branden $
.\"
.\" Copyright 1999, 2002, 2004 Branden Robinson <branden@debian.org>.
.\"
.\" This is free software; you can redistribute it and/or modify it under
.\" the terms of the GNU General Public License as published by the Free
.\" Software Foundation, version 2.
.\"
.\" This is distributed in the hope that it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
.\" for more details.
.\"
.\" You should have received a copy of the GNU General Public License with
.\" the Debian operating system, in /usr/share/common-licenses/GPL;  if
.\" not, write to the Free Software Foundation, Inc., 59 Temple Place,
.\" Suite 330, Boston, MA 02111-1307 USA
.\"
.\" We need the URL macro from groff's www macro package, but also want
.\" things to work all right for people who don't have it.  So we define
.\" our own URL macro and let the www macro package override it if it's
.\" available.
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.TH update\-fonts\-alias 8 "2004\-11\-11" "Debian Project"
.SH NAME
update\-fonts\-alias \- compile fonts.alias files
.SH SYNOPSIS
.B update\-fonts\-alias
[\fIOPTION\fR]
.I directory ...
.SH DESCRIPTION
.B update\-fonts\-alias
assembles a
.I fonts.alias
file in an X font directory using one or more alias files found in a
subdirectory of
.IR /etc/X11/fonts/ .
It is typically invoked only from the post\-installation and post\-removal
scripts of a
.I  package
containing X Window System fonts that provide aliases for their XLFD names,
but may be invoked at any time to reconstruct
.I fonts.alias
files.
For each
.IR directory ,
which is simply the last component of its path (such as \(oq75dpi\(cq or
\(oqmisc\(cq),
.B update\-fonts\-alias
will assemble either
.IR /usr/lib/X11/fonts/ directory /fonts.alias
or
.IR /usr/share/fonts/X11/ directory /fonts.alias
from the files found in
.IR /etc/X11/fonts/ directory / package .alias .
.PP
This enables multiple packages to provide aliases for fonts in the same
directory.
No font package actually provides the
.I fonts.alias
file in the X font directory itself, so there is no danger of overwriting
one package's aliases with those of another.
.PP
For instance, the two packages \(oqxfonts\-base\(cq and
\(oqxfonts\-base\-transcoded\(cq may both install fonts into the directory
.IR /usr/lib/X11/fonts/misc .
They each place their
.I fonts.alias
files in
.I /etc/X11/fonts/misc/xfonts\-base.alias
and
.I /etc/X11/fonts/misc/xfonts\-base\-transcoded.alias
(respectively).
.B update\-fonts\-alias
concatenates these two files (as well as any others that match
.IR /etc/X11/fonts/misc/*.alias )
into
.IR /usr/lib/X11/fonts/misc/fonts.alias .
.PP
The format of
.I fonts.alias
files is described in the
.BR mkfontdir (1x)
manual page.
.PP
An example of how to use
.B update\-fonts\-alias
in package maintainer scripts is provided in the Debian Policy Manual.
.SH OPTIONS
.B \-h\fR, \fB\-\-help
displays a brief usage message and exits.
.SH OPERANDS
.B update\-fonts\-alias
takes one or more X font directory names to operate on as operands.
Only the final path component of the directory name should be specified;
e.g.,
.RS
.B update\-fonts\-alias 75dpi
.RE
is correct, while
.RB \(oq "update\-fonts\-alias /usr/X11R6/lib/X11/fonts/75dpi" \(cq
and
.RB \(oq "update\-fonts\-alias /usr/lib/X11/fonts/75dpi" \(cq
are not.
.SH ENVIRONMENT
.TP
.B COLUMNS
indicates the width of the terminal device in character cells.
This value is used for formatting diagnostic messages.
If not set, the terminal is queried using
.BR stty (1)
to determine its width.
If that fails, a value of \(oq80\(cq is assumed.
.SH DIAGNOSTICS
.SS Errors
.TP
.B usage error: one or more font directories must be provided
.B update\-fonts\-alias
was invoked without operands.
Supply one or more X font directory names to operate on.
.TP
.B usage error: unrecognized option
.B update\-fonts\-alias
was invoked with an unrecognized option argument.
Use only the options documented in \(lqOPTIONS\(rq, above.
.TP
.B fatal error: path to X font directory must be used
A directory name was supplied that was not an X font directory name.
Supply X font directory names only.
.SS Warnings
.TP
.BI "warning: absolute path " directory " was provided"
Usage of absolute paths is deprecated.
Use only the final component of the X font directory name for
.IR directory .
.TP
.BI "warning: " directory " does not exist or is not a directory"
The supplied
.I directory
was invalid.
.B update\-fonts\-alias
skipped it.
.SH "EXIT STATUS"
.TP
0
.B update\-fonts\-alias
ran successfully.
.TP
1
.B update\-fonts\-alias
experienced a fatal error; see the section on diagnostic messages above.
.TP
2
.B update\-fonts\-alias
was invoked with invalid arguments.
.SH BUGS
See
.URL "http://bugs.debian.org/xfonts\-utils" "the Debian Bug Tracking System" .
If you wish to report a bug in
.BR update\-fonts\-alias ,
please see
.I /usr/share/doc/debian/bug\-reporting.txt
or the
.BR reportbug (1)
command.
.SH AUTHOR
.B update\-fonts\-alias
was written by Branden Robinson.
.SH "SEE ALSO"
.BR mkfontdir (1x)
.\" vim:set et tw=80:
