.TH "gnome-open" 1 "2008-07-04" "GNOME"
.SH NAME
gnome-open \- Open files and URLs using the GNOME file handlers
.SH SYNOPSIS
.B gnome-open
[OPTION]... [URL]...
.SH DESCRIPTION
This program opens files using file handlers configured in GNOME.
.SH OPTIONS
Usage: gnome-open [OPTION...]

.B Dynamic Modules

\fB\--load-modules=MODULE1,MODULE2,...\fR
.RS
Dynamic modules to load
.RE

.B Help Options

\fB\-?, --help\fR
.RS
Show a brief help message
.RE

\fB\--usage\fR
.RS
Display a brief usage message
.RE

.B Bonobo activation Support

\fB--oaf-ior-fd=FD\fR
.RS
File descriptor to print IOR on
.RE

\fB--oaf-activate-iid=IID\fR
.RS
IID to activate
.RE

\fB--oaf-private\fR
.RS
Prevent registering of server with OAF
.RE

.B GNOME Library

\fB--disable-sound\fR
.RS
Disable sound server usage
.RE

\fB--enable-sound\fR
.RS
Enable sound server usage
.RE

\fB--espeaker=HOSTNAME:PORT\fR
.RS
Host:port on which the sound server to use is running
.RE

\fB--version\fR
.RS
Prints the version number
.RE

.SH EXAMPLES

\fBOpen a web page\fR
.RS
gnome-open www.gnome.org
.RE

\fBOpen an OpenOffice.org document\fR
.RS
gnome-open Spinach.odf
.RE

\fBOpen a directory in Nautilus\fR
.RS
gnome-open ~
.RE

\fBSend an e-mail\fR
.RS
gnome-open mailto:gnome-list@mail.gnome.org
.RE

\fBPossible useless use of gnome-open\fR
.RS
gnome-open /usr/share/applications/gedit.desktop
.RE

.SH REPORTING BUGS
Please report bugs at http://bugzilla.gnome.org/

.SH AUTHOR
This manual page was written by Jonathan Carter <jonathan@ubuntu.com>
