.\"     Title: sasldb
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 12/14/2008
.\"    Manual: 
.\"    Source: 
.\"
.TH "SASLDB" "5" "12/14/2008" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
sasldb \- auxiliary property plugin
.SH "SYNOPSIS"
.PP
Cyrus SASL auxprop plugin to access the sasldb authentication backend
.SH "DESCRIPTION"
.PP
This document describes configuration options for the Cyrus SASL auxiliary property plugin
\fBsasldb\fR\&.
.PP
\fBsasldb\fR
is the default and fallback plugin\&. It will be used if explicitly configured, but also if other mechanisms have failed to load e\&.g\&. because they haven\'t been configured properly\&.
.PP
This plugin reads all user data from a Berkeley database\&. On Debian systems the default location for this database is
\fI/etc/sasldb2\fR\&.
.PP
Passwords are stored in plaintext format to enable usage of shared\-secret mechanisms\&. To protect the passwords, access has been restricted to user
root
and group
sasl\&. An application must be member of the
sasl
group to conduct
\fBsasldb\fR
SASL authentication\&.
.PP
Use the
\fBsaslpasswd2\fR(8)
utility to create and modify
\fBsasldb\fR
users\&. The
\fBsasldblistusers2\fR(8)
command prints a list of existing
\fBsasldb\fR
users to
STDOUT\&.
.SH "OPTIONS"
.PP
The following configuration parameters are applicable in the context of the
\fBsasldb\fR
plugin:
.PP
\fIsasldb_path\fR: (default: \fI/etc/sasldb2\fR)
.RS 4
Specifies the path to the database when
\fIauxprop_plugin\fR:
\fBsasldb\fR
is used\&. The default path is system dependant, but usually
\fI/etc/sasldb2\fR\&.
.RE
.SH "EXAMPLE"
.PP
The following example shows a typical
\fBsasldb\fR
configuration\&. The database is located at the default location
\fI/etc/sasldb2\fR\&.
.sp
.RS 4
.nf
pwcheck_method: auxprop
auxprop_plugin: sasldb
mech_list: plain login cram\-md5 digest\-md5
.fi
.RE
.SH "SEE ALSO"
.PP
\fBauthdaemond\fR(5),
\fBldapdb\fR(5),
\fBlibsasl\fR(5),
\fBsaslauthd\fR(8),
\fBsaslauthd.conf\fR(5),
\fBsaslpasswd2\fR(5),
\fBsasldblistusers2\fR(5),
\fBsasldb\fR(5),
\fBsql\fR(5)
.SH "README FILES"
.PP
\fIREADME\&.Debian\fR
.SH "AUTHOR"
.PP
This manual was written for the Debian distribution because the original program does not have a manual page\&. Parts of the documentation have been taken from the Cyrus SASL\'s
\fIoptions\&.html\fR\&.
.PP
.RS 4
.nf
Patrick Ben Koetter
<p@state\-of\-mind\&.de>
.fi
.RE
