.\"     Title: sql
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 12/14/2008
.\"    Manual: Cyrus SASL sql auxprop plugin
.\"    Source: 
.\"
.TH "SQL" "5" "12/14/2008" "" "Cyrus SASL sql auxprop plugin"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
sql \- auxiliary property plugin
.SH "SYNOPSIS"
.PP
Cyrus SASL auxprop plugin to access sql authentication backends\&.
.SH "DESCRIPTION"
.PP
This document describes configuration options for the Cyrus SASL auxiliary property plugin
\fBsql\fR\&.
.PP
\fBsql\fR
is a generic plugin for various SQL backends\&. Currently it provides access to either MySQL, PostgreSQL or SQLite databases\&.
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
Note
.PP
The plugin requires that passwords in the database are stored in plaintext format in order to use shared\-secret mechanisms\&.
.SH "CONFIGURATION SYNTAX"
.PP
The following syntax is mandatory for
\fBsql\fR
plugin configuration:
.sp
.RS 4
\h'-04'\(bu\h'+03'SQL statements specified with
\fIsql_select\fR,
\fIsql_select\fR
and
\fIsql_select\fR
must not be enclosed in quotes\&.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Macros, e\&.g\&.
\fB%u\fR,
\fB%r\fR
and
\fB%v\fR, specified within SQL statements must be quoted individually\&.
.RE
.PP
See
the section called \(lqEXAMPLE\(rq
for a valid configuration example\&.
.SH "OPTIONS"
.PP
The following configuration parameters are applicable in the context of the
\fBsql\fR
plugin:
.PP
\fIsql_engine\fR (default: \fBmysql\fR)
.RS 4
Specifies the type of SQL engine to use for connections to the SQL backend\&. The following types are available:
.PP
\fBmysql\fR
.RS 4
Enables the mysql driver for connections to a MySQL server\&.
.RE
.PP
\fBpgsql\fR
.RS 4
Enables the pgsql driver for connections to a PostgreSQL server\&.
.RE
.PP
\fBsqlite\fR
.RS 4
Enables the sqlite driver for connections to a SQLite server\&.
.RE
.RE
.PP
\fIsql_hostnames\fR (default: empty)
.RS 4
A comma\-separated list of one or more SQL servers the plugin should try to connect to and query from\&. Specify servers separated in
hostname[:port]
format\&.
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
Note
Specify
localhost
when using the MySQL engine to communicate over a UNIX domain socket and
127\&.0\&.0\&.1
to attempt a connection that uses a TCP socket\&.
.RE
.PP
\fIsql_user\fR (default empty)
.RS 4
Configures the username the plugin will send when it authenticates to the SQL server\&.
.RE
.PP
\fIsql_passwd\fR (defaults: empty)
.RS 4
Configures the password the plugin will send when it authenticates to the SQL server\&.
.RE
.PP
\fIsql_database\fR (default: empty)
.RS 4
Specifies the name of the database which contains auxiliary properties (e\&.g\&. username, realm, password etc\&.)
.RE
.PP
\fIsql_select\fR (default: empty)
.RS 4
Mandatory
SELECT
statement used to fetch properties from the SQL database\&.
.RE
.PP
\fIsql_insert\fR (default: empty)
.RS 4
Optional
INSERT
statement used to create properties for new users in the SQL database\&.
.RE
.PP
\fIsql_update\fR (default: empty)
.RS 4
Optional
UPDATE
statement used to modify properties in the SQL database\&.
.RE
.PP
\fIsql_usessl\fR (default: \fBno\fR)
.RS 4
Specify either
\fByes\fR,
\fBon\fR,
\fB1\fR
or
\fBtrue\fR, and the plugin will try to establish a secure connection to the SQL server\&.
.sp
Does this really work? I remember it doesn\'t \&.\&.\&.
.RE
.SS "Macros"
.PP
The sql plugin provides macros to build
\fIsql_select\fR,
\fIsql_select\fR
and
\fIsql_select\fR
statements\&. They will be replaced with arguments sent from the client\&. The following macros exist:
.PP
%u
.RS 4
The name of the user whose properties are being selected, inserted or updated\&.
.RE
.PP
%p
.RS 4
The name of the property being selected, inserted or updated\&. While this could technically be anything, Cyrus SASL will try
\fIuserPassword\fR
and
\fIcmusaslsecret\fR\fI\fIMECHNAME\fR\fR
(where
\fIMECHNAME\fR
is the name of a SASL mechanism)\&.
.RE
.PP
%r
.RS 4
Name of the realm to which the user belongs\&. This could be the KERBEROS realm, the FQDN of the computer the SASL application is running on or whatever is after the @ on a username\&.
.RE
.PP
%v
.RS 4
Value of the property being stored during insert or update operations\&. While this could technically be anything depending on the property itself, it generally is a
\fIuserPassword\fR\&.
.RE
.SH "EXAMPLE"
.PP
The following example shows a typical
\fBsql\fR
configuration:
.sp
.RS 4
.nf
pwcheck_method: auxprop
auxprop_plugin: sql
mech_list: plain login cram\-md5 digest\-md5
sql_engine: pgsql
sql_hostnames: 127\&.0\&.0\&.1, 192\&.0\&.2\&.1
sql_user: username
sql_passwd: secret
sql_database: company
sql_select: SELECT password FROM users WHERE user = \'%u\'@\'%r\'
.fi
.RE
.SH "SEE ALSO"
.PP
\fBauthdaemond\fR(5),
\fBldapdb\fR(5),
\fBlibsasl\fR(5),
\fBsaslauthd\fR(8),
\fBsaslauthd.conf\fR(5),
\fBsaslpasswd2\fR(5),
\fBsasldblistusers2\fR(5),
\fBsasldb\fR(5),
\fBsql\fR(5)
.SH "README FILES"
.PP
\fIREADME\&.Debian\fR
.SH "AUTHOR"
.PP
This manual was written for the Debian distribution because the original program does not have a manual page\&. Parts of the documentation have been taken from the Cyrus SASL\'s
\fIoptions\&.html\fR\&.
.PP
.RS 4
.nf
Patrick Ben Koetter
<p@state\-of\-mind\&.de>
.fi
.RE
