#!/bin/sh

set -e

case "${1}" in
	install|upgrade)
		if [ -e /etc/init.d/fuse ]
		then
			case $(md5sum /etc/init.d/fuse | awk '{ print $1 }') in
				d0b8cce6d932e1cd90812ce32c3f81a4|453b0e3f3f8facb9efc6cc73df8a7f05)
					update-rc.d -f fuse remove

					rm -f /etc/init.d/fuse
					;;
			esac
		fi
		;;

	abort-upgrade)

		;;

	*)
		echo "preinst called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
