Document: mash
Title: Debian mash Manual
Author: <insert document author here>
Abstract: This manual describes what mash is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mash/mash.sgml.gz

Format: postscript
Files: /usr/share/doc/mash/mash.ps.gz

Format: text
Files: /usr/share/doc/mash/mash.text.gz

Format: HTML
Index: /usr/share/doc/mash/html/index.html
Files: /usr/share/doc/mash/html/*.html
