.TH RAWSTUDIO 1 "2008-09-20" "1.1" "raw-image converter"

.SH NAME
rawstudio \- GTK+ raw-image converter

.SH SYNOPSIS
\fBrawstudio\fR

.SH DESCRIPTION
\fBrawstudio\fR can read and convert RAW-images from many different cameras, including Nikon and Canon. Rawstudio uses dcraw.

.SH OPTIONS
\fBrawstudio\fR has no options.

.SH SEE ALSO
\fBHomepage:\fR <\fIhttp://www.rawstudio.org/\fR>

.SH AUTHOR
rawstudio was written by Anders Brander <\fIanders@brander.dk\fR> and Anders Kvist <\fIanders@kvistmail.dk\fR>.
.PP
This manual page was written by Daniel Baumann <\fIdaniel@debian.org\fR>, for the Debian project (but may be used by others).
