#!/bin/sh
set -e

if ! getent passwd ganglia >/dev/null; then
	echo Adding system user: ganglia.
	useradd -r -c "Ganglia Monitor" -d "/var/lib/ganglia" -s "/bin/false" -U ganglia
fi

#if we have an old 2.5.x gmond
if [ -f /etc/gmond.conf ]; then
  if [ ! -e /etc/ganglia/gmond.conf ]; then
    gmond -r /etc/gmond.conf >/etc/ganglia/gmond.conf
  else
    gmond -r /etc/gmond.conf >/etc/ganglia/gmond.conf.old
  fi
  rm /etc/gmond.conf
fi
#DEBHELPER#

exit 0
