#!/bin/sh
set -e

if ! getent passwd ganglia >/dev/null; then
	echo Adding system user: ganglia.
	useradd -r -c "Ganglia Monitor" -d "/var/lib/ganglia" -s "/bin/false" -U ganglia
fi

if [ ! -d /var/lib/ganglia/rrds ]; then
  mkdir -p /var/lib/ganglia/rrds
fi
if [ -d /var/lib/ganglia/rrds ]; then
  chown ganglia:ganglia /var/lib/ganglia
  chown -R nobody /var/lib/ganglia/rrds
  chmod 0755 /var/lib/ganglia
  chmod -R o-w /var/lib/ganglia/rrds
fi
 
#DEBHELPER#

exit 0
