.TH imlib2-config 1 "29 Oct 2000" imlib2-config
.SH NAME
.HP
imlib2-config - imlib2 build information script
.SH SYNOPSIS
.HP 
imlib2-config [options]
.P
.SH DESCRIPTION
.HP
.I imlib2-config 
is a script that's used by make and other build enviroments to
gather imlib2 information.
.HP
Run
.I imlib2-config
for additional information.
