usr/bin/curl-config
usr/lib/*/libcurl-gnutls.a
usr/lib/*/libcurl-gnutls.la
usr/lib/*/libcurl-gnutls.so
usr/lib/*/pkgconfig/libcurl.pc
usr/include
../../docs/libcurl/libcurl.m4	usr/share/aclocal
../../docs/*.html		usr/share/doc/libcurl4-gnutls-dev/html
../../docs/*.pdf		usr/share/doc/libcurl4-gnutls-dev/pdf
../../docs/libcurl/*.html	usr/share/doc/libcurl4-gnutls-dev/libcurl/html
../../docs/libcurl/*.pdf	usr/share/doc/libcurl4-gnutls-dev/libcurl/pdf
