.TH 3DS2MGF "1" "November 2007" "3ds2mgf 2.0" "RADIANCE"
.SH NAME
3ds2mgf \- Autodesk 3D Studio to Raytracer file Translator
.SH SYNOPSIS
.B 3ds2mgf
\fIinputfile\fR[\fI.3ds\fR] [\fIoutputfile\fR] [\fIoptions\fR]
.SH DESCRIPTION
.PP
\fB\-snnn\fR        \- Smooth triangles with angles < nnn
.HP
\fB\-l\fR<filename> \- Specifies native material library
.HP
\fB\-a\fR<filename> \- Use animation information in specified file
.HP
\fB\-fnnn\fR        \- Generate frame nnn of animation
.HP
\fB\-x\fR<object>   \- Exclude this object from conversion
.HP
\fB\-b\fR<object>   \- Convert this object as a box
.HP
+i, \fB\-i\fR       \- Turn internal bounding on or off
.HP
+v, \fB\-v\fR       \- Turn verbose status messages on or off
.HP
\fB\-op\fR          \- Output to POV\-Ray 2.0 format
.HP
\fB\-op1\fR         \- Output to POV\-Ray 1.0 format
.HP
\fB\-ov\fR          \- Output to Vivid format
.HP
\fB\-ol\fR          \- Output to poLyray format
.HP
\fB\-om\fR          \- Output to MGF
.HP
\fB\-or\fR          \- Output to RAW triangle format
.PP
ex. /usr/bin/3ds2mgf birdshow +v \fB\-lmaterials\fR.inc
.SH "SEE ALSO"
mgf2inv(1), mgf2meta(1), mgf2rad(1), mgfilt(1)
