.TH @NAME@ 1 "May 24, 2003" @name@ "Debian Free Documentation"
.SH NAME
@name@ \- A program with a man page covered by the GFDL with invariant sections
.SH SYNOPSIS
@name@ [\fB\s-1OPTION\s0\fR] ... [\fI\s-1ARGS\s0\fR...]

.SH DESCRIPTION

\fB@name@\fR is documented by a man page, which is covered by the "GNU
Free Documentation License" (GFDL) containing invariant sections.
.P
In November 2002, version 1.2 of the GNU Free Documentation License (GNU
FDL) was released by the Free Software Foundation after a long period
of consultation. Unfortunately, some concerns raised by members of the
Debian Project were not addressed, and as such the GNU FDL can apply
to works that do not pass the Debian Free Software Guidelines (DFSG),
and may thus only be included in the non-free component of the Debian
archive, not the Debian distribution itself.

.SH "SEE ALSO"
.BR http://gcc.gnu.org/onlinedocs/
for the complete documentation,
.BR http://lists.debian.org/debian-legal/2003/debian-legal-200304/msg00307.html
for a proposed statement of Debian with respect to the GFDL,
.BR gfdl(7)

.SH AUTHOR
This manual page was written by the Debian GCC maintainers,
for the Debian GNU/Linux system.
