.TH GCC-@TOOL@-@BV@ 1 "May 8, 2012" gcc-@TOOL@-@BV@ ""
.SH NAME
gcc-@TOOL@ \- a wrapper around @TOOL@ adding the --plugin option

.SH SYNOPSIS
gcc-@TOOL@ [\fB\s-1OPTION\s0\fR] ... [\fI\s-1ARGS\s0\fR...]

.SH DESCRIPTION

\fBgcc-@TOOL@\fR is a wrapper around @TOOL@(1) adding the appropriate
\fB\-\-plugin\fR option for the GCC @BV@ compiler.

.SH OPTIONS
See @TOOL@(1) for a list of options that @TOOL@ understands.

.SH "SEE ALSO"
.BR @TOOL@(1)
