#! /bin/sh -e

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
    update-alternatives --quiet --remove java /usr/bin/gij-@BV@
    update-alternatives --quiet --remove rmiregistry /usr/bin/grmiregistry-@BV@
    update-alternatives --quiet --remove keytool /usr/bin/gkeytool-@BV@
    update-alternatives --quiet --remove orbd /usr/bin/gorbd-@BV@
    update-alternatives --quiet --remove rmid /usr/bin/grmid-@BV@
fi

#DEBHELPER#

exit 0
