.TH GIJ-WRAPPER 1 "August 11, 2001" gij-wrapper "Java User's Manual"
.SH NAME
gij-wrapper \- a wrapper around gij

.SH SYNOPSIS
gij-wrapper [\fB\s-1OPTION\s0\fR] ... \fI\s-1JARFILE\s0\fR [\fI\s-1ARGS\s0\fR...]
.PP
gij-wrapper [\fB\-jar\fR] [\fB\s-1OPTION\s0\fR] ... \fI\s-1CLASS\s0\fR [\fI\s-1ARGS\s0\fR...]

.SH DESCRIPTION

\fBgij-wrapper\fR is a wrapper around gij(1) to be called as the java
interpreter. Options different for java(1) and gij(1) are translated,
options unknown to gij(1) are silently ignored.

.SH OPTIONS
See gij-@BV@(1) for a list of options that gij understands.

.SH "SEE ALSO"
.BR gij-@BV@(1)
,
.BR java(1)
