.TH "usbmuxd" 1
.SH NAME
usbmuxd \- iPhone/iPod Touch USB multiplex server daemon
.SH SYNOPSIS
.B usbmuxd
[options]
.SH DESCRIPTION

usbmuxd stands for "USB multiplexing daemon".  To the user/developer what it
actually does is to proxy requests over a USB cable on directly to a listening
TCP port on the iPhone.

.SH OPTIONS
.TP
.B \-h|\-\-help
Print this message.
.TP 
.B \-v|\-\-verbose
Be verbose (use twice or more to increase).
.TP 
.B \-f|\-\-foreground
Do not daemonize (implies one -v).
.TP 
.B \-U|\-\-user[=USER]
Change to this user after startup (needs usb privileges).
If USER is not specified, defaults to usbmux.
.TP 
.B \-u|\-\-udev
Run in udev operation mode.
.TP
.B \-x|\-\-exit
Tell a running instance to exit if there are no devices
connected (must be in udev mode).
.TP
.B \-X|\-\-force-exit
Tell a running instance to exit, even if there are still
devices connected (always works).

.SH AUTHORS
Hector Martin "marcan" <hector@marcansoft.com>

Nikias Bassen <nikias@gmx.li>

Paul Sladen <libiphone@paul.sladen.org>

Man page written to conform with Debian by Julien Lavergne.
