.TH KDEVELOP 1
.SH NAME
kdevelop \- Integrated Development Environment for KDE
.SH SYNOPSIS
.B kdevelop
.I [Qt-options] [KDE-options] [options] file(s)
.SH DESCRIPTION
.B KDevelop
is an integrated development environment for KDE.
.SH PROGRAM OPTIONS
.TP
.B --profile \fI<profile>\fB
Profile to load.
.TP
.B --project \fI<project>\fB
Project to load.
.TP
.B file(s)
Files to load.
.so kdeopt.part
.SH SEE ALSO
More detailed user documentation is available from
.BR help:/kdevelop
(either enter this URL into \fBkonqueror\fP, or run `khelpcenter
help:/kdevelop').
