#!/bin/sh

set -e

if [ "$1" = upgrade ]; then
  if dpkg --compare-versions "$2" lt-nl 4.0.3-7 && \
     dpkg --compare-versions "$2" gt 4.0.3-3; then
    if ! test -L /tmp/.screen && test -d /tmp/.screen && test -n "`find /tmp/.screen -type p 2>/dev/null`"; then
      ln -s /tmp/.screen /var/run/screen
    fi
  fi
fi

#DEBHELPER#
