=head1 NAME

dh_haskell_provides - calculates Haskell virtual package names on Cabalized libraries

=head1 SYNOPSIS

B<dh_haskell_provides> [S<I<debhelper options>>]
[B<-X>I<package>]
[B<--exclude=>I<package>]
[S<I<file>> ...]

=head1 DESCRIPTION

dh_haskell_provides is a debhelper program that calculates the correct virtual
package to provide, so that dependencies can guarantee ABI stability.

For a package with an idea of package-version-longhashstring, it generates a
virtual package of the form libghc-package-dev-version-longh for the -dev
package and libghc-package-prof-version-longh for the prof package
respectively.

This script writes the debian/$package.substvars file, including in it the
haskell:Provides.  So, to use this package, include in the Provides: field in
debian/control ${haskell:Provides}.

=head1 SEE ALSO

L<dh_haskell_depends(1)>
L<dh_haskell_shlibdeps(1)>
L<debhelper(7)>

=head1 AUTHOR

Joachim Breitner <nomeata@debian.org>

Based on ideas in dh_ocaml.
