=pod

=head1 NAME

gphotofs - filesystem to mount digital cameras

=head1 DESCRIPTION

GPhotoFS is a filesystem client based on libgphoto2 that exposes
supported cameras as filesystems; while some cameras implement the
USB Mass Storage class and already appear as filesystems (making
this program redundant), many use the Picture Transfer Protocol (PTP)
or some other custom protocol. But as long as the camera is supported
by libgphoto2, it can be mounted as a filesystem using this program.

As libgphoto2 is a userspace library for interacting with cameras,
it is natural that if one to build a filesystem ontop of it, one
should use FUSE, and that is what I have done.

=head1 SYNOPSIS

=over 2

=item mounting

  gphotofs <mountpoint>

=item unmounting

  fusermount -u <mountpoint>

=back

=head1 NOTES

You must have permission to read and write the device.  By default,
devices recognized by libgphoto2 are created with read/write access for
group "plugdev", so users must be added to this group to use GPhotoFS.

=head1 LIMITATIONS

GPhotoFS currently can't add or remove directories, rename files or
directories, add or modify files and get space information.

=head1 SEE ALSO

L<fusermount(1)>

=head1 AUTHOR

This manpage was written by Florian Ragwitz E<lt>rafl@debian.orgE<gt> for the
Debian GNU/Linux distribution, but may be used by others under the terms of the
GNU General Public License version 2.

=cut
