usr/share/xplanet/rgb.txt etc/xplanet

usr/share/xplanet/config/default etc/xplanet/config
usr/share/xplanet/config/earth_markers etc/xplanet/config
usr/share/xplanet/config/moon_orbit etc/xplanet/config
usr/share/xplanet/config/overlay_clouds etc/xplanet/config
usr/share/xplanet/config/README

usr/share/xplanet/markers/earth etc/xplanet/markers
usr/share/xplanet/markers/brightStars
usr/share/xplanet/markers/mars
usr/share/xplanet/markers/moon
usr/share/xplanet/markers/README

usr/share/xplanet/origin/cassini etc/xplanet/origin
usr/share/xplanet/origin/galileo etc/xplanet/origin
usr/share/xplanet/origin/README

usr/share/xplanet/satellites/iss etc/xplanet/satellites
usr/share/xplanet/satellites/iss.tle etc/xplanet/satellites
usr/share/xplanet/satellites/README

usr/share/xplanet/arcs/*
usr/share/xplanet/ephemeris/*
usr/share/xplanet/fonts/*
usr/share/xplanet/spice/*
usr/share/xplanet/stars/*

usr/share/man/*
usr/bin/*
