.TH "playsound_simple" "1" "8-28-2008"

.SH "NAME" 
playsound_simple \- Plays an audio file using SDL_sound

.SH "SYNOPSIS"
.PP
.B playsound_simple
.IR audiofile  
[audiofile...]

.SH "DESCRIPTION" 
.PP
This manual page documents briefly the \fBplaysound_simple\fR command.
.PP
.B playsound_simple
plays an
.I audio file
using SDL_sound. If several 
.IR audiofiles
are specified, they will be played the one after the other.
.PP
.B playsound_simple
supports various audio file formats : MPEG audio, Ogg Vorbis, WAV, VOC, AIFF,
MIDI, AU and a few others.

.SH "SEE ALSO"
.BR playsound (1)

.SH "AUTHORS"
.PP
.\" from Source
Copyright \(co 2001 Ryan C. Gordon. <icculus@icculus.org>


This manual page was written by Francois Wendling <frwendling@free.fr> for the Debian GNU/Linux system (but may be used by others).
