.TH PLAYSOUND "1" "May 2008" "playsound 0.1.5" "User Commands"
.SH NAME
playsound \- quick and dirty test for SDL_sound
.SH SYNOPSIS
.B playsound
[\fI...options...\fR] \fI[soundFile1]\fR ... \fI[soundFileN]\fR
.SH DESCRIPTION
`playsound' plays a sound.
.TP
\fB\-\-rate\fR \fBn\fR
Playback at sample rate of n HZ.
.TP
\fB\-\-format\fR \fBfmt\fR
Playback in fmt format (see below).
.TP
\fB\-\-channels\fR \fBn\fR
Playback on n channels (1 or 2).
.TP
\fB\-\-decodebuf\fR \fBn\fR
Buffer n decoded bytes at a time (default 16384).
.TP
\fB\-\-audiobuf\fR \fBn\fR
Buffer n samples to audio device (default 4096).
.TP
\fB\-\-volume\fR \fBn\fR
Playback volume multiplier (default 1.0).
.TP
\fB\-\-stdin\fR \fB[ext]\fR
Read from stdin (treat data as format [ext])
.TP
\fB\-\-version\fR
Display version information and exit.
.TP
\fB\-\-decoders\fR
List supported data formats and exit.
.TP
\fB\-\-predecode\fR
Decode entire sample before playback.
.TP
\fB\-\-loop\fR \fBn\fR
Loop playback n times.
.TP
\fB\-\-seek\fR \fBlist\fR
List of seek points and playback durations.
.TP
\fB\-\-credits\fR
Shameless promotion.
.TP
\fB\-\-help\fR
Display this information and exit.
.SH AUTHOR
Written by Ryan C. Gordon
.PP
This manual page was written by Barry deFreese <bddebian@comcast.net> for 
the Debian distribution but may be used elsewhere.
.SH "REPORTING BUGS"
Report bugs to <icculus@clutteredmind.org>.
.SH COPYRIGHT
Copyright \(co 2001 Ryan C. Gordon <icculus@clutteredmind.org>
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
