Document: wifite
Title: Debian wifite Manual
Author: <insert document author here>
Abstract: This manual describes what wifite is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/wifite/wifite.sgml.gz

Format: postscript
Files: /usr/share/doc/wifite/wifite.ps.gz

Format: text
Files: /usr/share/doc/wifite/wifite.text.gz

Format: HTML
Index: /usr/share/doc/wifite/html/index.html
Files: /usr/share/doc/wifite/html/*.html
