#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
	if [ -d /var/lib/apt-xapian ]; then
		echo "Removing old index /var/lib/apt-xapian..."
		rm -r /var/lib/apt-xapian
	fi
fi

# FIXME: remove test when we are not interested in lenny anymore
if test -x /usr/bin/dpkg-maintscript-helper && dpkg-maintscript-helper supports rm_conffile; then
	dpkg-maintscript-helper rm_conffile /etc/cron.weekly/ept-cache 1.0.1 -- "$@"
fi

#DEBHELPER#
