.TH "canberra\-gtk\-play" "1" "2010\-08\-01"
.SH "NAME"
canberra\-gtk\-play \- play a sound event
.SH "SYNOPSIS"
.PP
.B canberra\-gtk\-play
.RI "[ " OPTIONS... " ]"
.SH "DESCRIPTION"
.PP
This manual page documents briefly the \fBcanberra\-gtk\-play\fR command.
.PP
.B canberra\-gtk\-play
plays sound events that are specified by the XDG Sound Theme and Name
Specification.
.SH "OPTIONS"
.SS "Application Options"
.TP
.BR \-v , " \-\-version"
Display version number and quit
.TP
.BR \-i , " \-\-id=" \fISTRING\fR
Event sound identifier
.TP
.BR \-f , " \-\-file=" \fIPATH\fR
Play file
.TP
.BR \-d , " \-\-description=" \fISTRING\fR
Event sound description
.TP
.BR \-c , " \-\-cache\-control=" "{ \fIpermanent\fR|\fIvolatile\fR|\fInever\fR }"
Specify how \fBcanberra\-gtk\-play\fR manages its cache. \fIpermanent\fR will
cause the sample to be cached permanently, \fIvolatile\fR to be cached until
the cache needs to be freed.
.TP
.BR \-l , " \-\-loop=" \fIINTEGER\fR
Loop how many times (default: 1)
.TP
.BR \-V , " \-\-volume=" \fISTRING\fR
A floating point dB value for the sample volume (ex: 0.0)
.TP
.BI \-\-property= STRING
An arbitrary property
.TP
.BI \-\-display= DISPLAY
X display to use
.SS "Help Options"
.TP
.BR \-h , " \-\-help"
Show help options
.TP
.BR \-\-help\-all
Show all help options
.TP
.BR \-\-help\-gtk
Show GTK+ Options
.SS "GTK+ Options"
.TP
.BI \-\-class= CLASS
Program class as used by the window manager
.TP
.BI \-\-name= NAME
Program name as used by the window manager
.TP
.BI \-\-screen= SCREEN
X screen to use
.TP
.BR \-\-sync
Make X calls synchronous
.TP
.BI \-\-gtk\-module= MODULES
Load additional GTK+ modules
.TP
.BR \-\-g\-fatal\-warnings
Make all warnings fatal
.SH "AUTHORS"
.PP
\fBcanberra\-gtk\-play\fR is Copyright 2008 Lennart Poettering.
.PP
This manual page was written by Francois Wendling <frwendling@free.fr> for the
Debian GNU/Linux system (but may be used by others).
