.TH SNOWDROP 1
.SH NAME
sd-eng, sd-engf, sd-c \- text watermarking and watermark recovery
.SH SYNOPSIS
.B sd-eng [\fI-6\fP] \fI-i\fP \fBorigfile\fP \fBnewfile\fP \fB"Recipient"\fP [\fB"Comment"\fB]
.P
.B sd-eng [\fI-6\fP] \fI-e\fP \fBorigfile\fP \fBnewfile\fP
.P
.B sd-eng [\fI-6\fP] \fI-l\fP
.SH DESCRIPTION
snowdrop is a stenographic text watermarking and watermark recovery system.
It is composed of three programs:
.TP
.B sd-eng
Watermark normal English text.
.TP
.B sd-engf
Watermark fine quality English text, yeilding higher quality output but
encoding less information.
.TP
.B sd-c
Watermark C code.
.P
The three programs operate similarly, with the same parameters and usage.  The
watermark is encoded in using a number of techniques, such as whitespace
reformatting, typo insertation, word substitutions, punctuation changes,
and for C code, logic reordering, variable name mangling, etc.
.P
The watermark is a md5sum, which is retreivable from as little as
5 or 10 lines of the watermarked document. Even large changes to a medium
sized document should not obscure the watermark, as it is stored redundently
in multiple independent channels.
.P
The three usage modes are adding a watermark, checking for the presense of a
watermark, and listing the contents of your database of watermarks. Note
that to later check a watermark, you must retain a copy of the original,
un-watermarked file.
.SH OPTIONS
.TP
.B -i
Inject a watermark into a file. You must pass it the original file, the
filename to output the watwrmarked version to, information about who
you intend the watermarked file for, and an optional comment.
.TP
.B -e
Extract a watermark from a file. Needs the original file
and the new file that you suspect bears the watermark.
.TP
.B -l
Lists the contents of the watermark database. Each of the three programs
will have a different list.
.TP
.B -6
Enable 64 bit watermarking. The default is a weak 32 bit watermark.
.SH ENVIRONMENT
.TP
.B SD_SYNONYMS
This variable can be used to point snowdrop at a customized synonyms file.
.SH FILES
.TP
.B ~/.snowdrop/database
Database of watermarked files.
.SH "SEE ALSO"
.TP
.B /usr/share/snowdrop/README
Explain snowdrop in more depth, its limitations, and how to write additional
watermarking modules for other tpyes of files.
.SH AUTHOR
Michal Zalewski <lcamtuf@coredump.cx>
