.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH GMOCK_GEN 1 "2010-04-15"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
gmock_gen \- program to generate gmock header files
.SH SYNOPSIS
.B gmock_gen
.RI " files" ...
.br
.SH DESCRIPTION
This manual page documents briefly the
.B gmock_gen
commands.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
This program will read in a C++ source file and output the Google Mock
classes for the specified classes.  If no class is specified, all
classes in the source file are emitted.
.br
The program is documented fully by
.IR "http://code.google.com/p/googlemock/"
.SH AUTHOR
gmock_gen was written by nnorwitz@gmail.com.
.PP
This manual page was written by Fredrik Hallenberg <hallon@debian.org>,
for the Debian project (and may be used by others).
