#!/bin/sh

set -e

update-alternatives --install \
    /usr/bin/assistant assistant "/usr/bin/assistant" "40" \
    --slave /usr/share/man/man1/assistant.1.gz assistant.1.gz \
    "/usr/share/man/man1/assistant.1.gz"

update-alternatives --install \
    /usr/bin/linguist linguist "/usr/bin/linguist" "40" \
    --slave /usr/share/man/man1/linguist.1.gz linguist.1.gz \
    "/usr/share/man/man1/linguist.1.gz"

#DEBHELPER#
