#!/bin/sh

set -e

update-alternatives --install \
    /usr/bin/lupdate lupdate "/usr/bin/lupdate-qt4" "40" \
    --slave /usr/share/man/man1/lupdate.1.gz lupdate.1.gz \
    "/usr/share/man/man1/lupdate-qt4.1.gz"

update-alternatives --install \
    /usr/bin/lrelease lrelease "/usr/bin/lrelease-qt4" "40" \
    --slave /usr/share/man/man1/lrelease.1.gz lrelease.1.gz \
    "/usr/share/man/man1/lrelease-qt4.1.gz"

#DEBHELPER#
