.TH UPDATE-INFO-DIR 8
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
update-info-dir \- update or create index file
from all installed info files in directory
.SH SYNOPSIS
.B update-info-dir
.I "[options]"
.B [directory]
.br
.SH DESCRIPTION
Update, or create, the index file
.I dir
of available documentation in
/usr/share/info/ (the default) or in given DIRECTORY. The
index file
.I info
is the directory is usually presented by info browsers on startup.
.SH OPTIONS
.TP
.B \-h,--help
Display help and exit.
.PP
.SH SEE ALSO
emacs(1)
info(1)
install-info(1)
.SH AUTHOR
This manual page was written by Norbert Preining <preining@logic.at>,
for the Debian GNU/Linux system (but may be used by others).

This manual page was written for the Debian GNU/Linux distribution
because the original script was designed for Debian packaging system.
