.TH GPICK 1 "November 11, 2010"
.SH NAME
gpick \- advanced color picker written in C++ using GTK+ toolkit
.SH SYNOPSIS
.B gpick
[OPTION...] [FILE...]
.SH DESCRIPTION
\fBgpick\fP starts an application and opens FILE if it is specified
.SH HELP OPTIONS
.TP
.B \-h, \-\-help
Show help options.
.TP
.B \-\-help-all
Show all help options.
.TP
.B \-\-help-gtk
Show GTK+ Options
.SH APPLICATION OPTIONS
.TP
.B \-g\, \-\-geometry=GEOMETRY
Window geometry
.TP
.B \-p\, \-\-pick
Pick a color
.TP
.B \-v\, \-\-version
Print version information
.TP
.B \-\-display=DISPLAY
X display to use
.br
.SH AUTHOR
gpick was written by Albertas Vyšniauskas
.PP
This manual page was written by Elías Alejandro Año Mendoza <ealmdz@gmail.com>,
for the Debian project (and may be used by others).
