.TH "ICEDOVE" "1" "February 27, 2010" "Christoph Göhre" "Linux User's Manual"
.SH "NAME"
icedove \- Mail User Agent (MUA) and newsgroup/RSS client for X11 derived from the Mozilla Thunderbird.
.SH "SYNOPSIS"
.B icedove
[\fIOPTIONS\fR] [\fIURL\fR]

.B /usr/lib/icedove/icedove\-bin
[\fIOPTIONS\fR] [\fIURL\fR]

.SH "DESCRIPTION"
\fBIcedove\fR provides IMAP/POP support, a built-in RSS reader, support for
HTML mail, powerful quick search, saved search folders, advanced message
filtering, junk mail controls, message grouping, labels, return receipts, smart
address book, LDAP address completion, import tools and the ability to manage
multiple identities in email and newsgroup accounts.
.PP
\fBIcedove\fR provides enterprise and government grade security such as S/MIME,
digital signing, message encryption, and support for certificates and security
devices.

.SH "USAGE"
\fBicedove\fR is a simple shell script that will set up the
environment for the actual executable, \fBicedove\-bin\fR.
If there is an Icedove mail client already running, \fBicedove\fR will
arrange for it to create a new mail client window; otherwise it will start
the Icedove application.

.SH "OPTIONS"
A summary of the options supported by \fBicedove\fR is included below.

.SS "X11 options"
.TP
.BI \-\-display= DISPLAY
X display to use
.TP
.B \-\-sync
Make X calls synchronous
.TP
.B \-\-no\-xshm
Don't use X shared memory extension
.TP
.BI \-\-xim\-preedit= STYLE
.TP
.BI \-\-xim\-status= STYLE
.TP
.B \-\-g\-fatal\-warnings
Make all warnings fatal

.SS "Mozilla options"
.TP
.B \-h, \-help
Show summary of options.
.TP
.B \-v, \-version
Print Icedove version.
.TP
\fB\-P\fR [\fIprofile\fR]
Start with \fIprofile\fR. When no profile is given, displays the Profile Manager. May require \fB\-no\-remote\fR, see below.
.TP
.B \-migration
Start with migration wizard. May require \fB\-no\-remote\fR, see below.
.TP
.B \-ProfileManager
Start with profile manager. May require \fB\-no\-remote\fR, see below.
.TP
.B \-no\-remote
Don't connect to a running Icedove instance. This option can be necessary
in conjunction to several of the options above, that won't have any effect
when an Icedove instance is running unless \fB\-no\-remote\fR is used at
the same time.
.TP
\fB\-UILocale\fR \fIlocale\fR
Start with \fIlocale\fR resources as User Interface locale. By default, it is
guessed from environment and available locales for Icedove.
.TP
.B \-safe\-mode
Starts Icedove in safe mode, i.e. disabling all extensions and
showing a bit more debugging messages.
.TP
.B \-jsconsole
Start with Javascript Console
.TP
.B \-addressbook
Open the address book at startup.
.TP
.B \-compose
Compose a mail or news message.
.TP
.B \-mail
Open the mail folder view.
.TP
\fB\-mail\fR \fIURL\fR
Open the message specified by this \fIURL\fR.
.TP
.B \-news
Open the news client.
.TP
.B \-setDefaultMail
Set Icedove as the default mail client.
.TP
.B \-options
Open the options dialog.
.TP
.B \-file
Open the specified email file
.SS "Debugger options"
.TP
.B \-g, \-debug
Starts Icedove through a debugger (gdb by default).
.TP
\fB\-\-debugger\fR \fIprogram\fR
Use \fIprogram\fR as a debugger for Icedove. Implies \fB\-debug\fR.

.SH "ENVIRONMENT"
\fIMOZILLA_DISABLE_PLUGINS\fR \- when set, totally disables loading plugins.

.SH "FILES"
\fI/usr/bin/icedove\fR \- shell script wrapping
\fBicedove\-bin\fR
.br

\fI/usr/lib/icedove/icedove\-bin\fR \- \fBicedove\fR
executable
.br
.SH "BUGS"
To report a bug, please visit \fIhttp://bugzilla.mozilla.org/\fR and/or report bugs
to the Debian Bug Tracking System, as usual.

.SH "AUTHORS"
.TP
.B The Mozilla Organization
.I http://www.mozilla.org/about.html
