usr/lib/pkgconfig/signond.pc
usr/lib/libsignon-plugins-common.so
usr/include/signond/*
usr/share/dbus-1/interfaces/com.google.code.AccountsSSO.SingleSignOn.AuthService.xml
usr/share/dbus-1/interfaces/com.google.code.AccountsSSO.SingleSignOn.Identity.xml
usr/share/dbus-1/interfaces/com.google.code.AccountsSSO.SingleSignOn.AuthSession.xml

# extensions
usr/include/signon-extension/SignOn/*
usr/lib/libsignon-extension.so
usr/lib/pkgconfig/SignOnExtension.pc
