#! /bin/sh
set -e

case $1 in
	purge)
		rm -f /etc/default/pcmciautils
		rm -f /etc/udev/rules.d/60-pcmcia.rules
		rm -f /etc/pcmcia/config.opts /etc/pcmcia/config.opts~
		rmdir /etc/pcmcia || true
		;;
esac

#DEBHELPER#
