.TH "NaCl" "1" 
.SH "NAME" 
nacl-sha256 \(em program to calculate the sha256 hash 
.SH "SYNOPSIS" 
.PP 
\fBnacl-sha256\fR 
.SH "DESCRIPTION" 
.PP 
This manual page documents briefly the 
\fBnacl-sha256\fR command. 
.PP 
This manual page was written for the \fBDebian\fP distribution 
because the original program does not have a manual page. 
Instead, it has documentation in the GNU. 
.PP 
\fBnacl-sha256\fR is a program that uses NaCl to calculate the sha256 hash of the first 4096 bytes of input. 
.SH "OPTIONS" 
.PP 
These program expects input on standard input and prints the sha256 hash of the first 4096 bytes on standard output. 
.SH "SEE ALSO" 
.PP 
nacl-sha512 (1). 
.SH "AUTHOR" 
.PP 
This manual page was written by Sergiusz Pawlowicz debian@pawlowicz.name for 
the \fBDebian\fP system (and may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License, Version 2 any 
later version published by the Free Software Foundation. 
 
.PP 
On Debian systems, the complete text of the GNU General Public 
License can be found in /usr/share/common-licenses/GPL. 
 
.\" created by instant / docbook-to-man, Sat 14 Jan 2012, 02:59 
