usr/bin/vala-0.16
usr/bin/valac-0.16
usr/bin/vala-gen-introspect-0.16
usr/bin/vapigen-0.16
usr/bin/vapicheck-0.16
usr/share/man/man1/valac-0.16.1
usr/share/man/man1/vapigen-0.16.1
usr/share/man/man1/vala-gen-introspect-0.16.1
usr/share/pkgconfig/vapigen-0.16.pc
usr/lib/*/vala-0.16/gen-introspect-0.16
vala.m4 /usr/share/vala-0.16/
vapigen/vapigen.m4 /usr/share/vala-0.16/
vapigen/Makefile.vapigen /usr/share/vala-0.16/
