usr/bin/vala-0.20
usr/bin/valac-0.20
usr/bin/vala-gen-introspect-0.20
usr/bin/vapigen-0.20
usr/bin/vapicheck-0.20
usr/share/man/man1/valac-0.20.1
usr/share/man/man1/vapigen-0.20.1
usr/share/man/man1/vala-gen-introspect-0.20.1
usr/share/pkgconfig/vapigen-0.20.pc
usr/lib/*/vala-0.20/gen-introspect-0.20
vala.m4 /usr/share/vala-0.20/
vapigen/vapigen.m4 /usr/share/vala-0.20/
vapigen/Makefile.vapigen /usr/share/vala-0.20/
