usr/bin/vala-0.18
usr/bin/valac-0.18
usr/bin/vala-gen-introspect-0.18
usr/bin/vapigen-0.18
usr/bin/vapicheck-0.18
usr/share/man/man1/valac-0.18.1
usr/share/man/man1/vapigen-0.18.1
usr/share/man/man1/vala-gen-introspect-0.18.1
usr/share/pkgconfig/vapigen-0.18.pc
usr/lib/*/vala-0.18/gen-introspect-0.18
vala.m4 /usr/share/vala-0.18/
vapigen/vapigen.m4 /usr/share/vala-0.18/
vapigen/Makefile.vapigen /usr/share/vala-0.18/
