.TH bsnes 6 "August 5, 2011"
.SH NAME
bsnes \- Accurate SNES/Super Famicom emulator
.SH SYNOPSIS
.B bsnes
<ROM location>
.SH OPTIONS
<ROM location> \-\- from the command line, you can supply the name of a ROM file as
an argument to start playing that ROM

.SH KEYBOARD SHORTCUTS
F11 \-\- toggle fullscreen mode

.SH DESCRIPTION

bsnes is a Super Nintendo / Super Famicom emulator that strives to provide the
most faithful hardware emulation possible. It focuses on accuracy and clean
code, rather than speed and special features. It is meant as a reference
emulator to document how the underlying hardware works. It is thus very useful
for development and research. And while it can be used for general purpose
gaming, it will require significantly more powerful hardware than a typical
emulator. Although not as polished as the SNES emulation (yet), there is also
support for NES, Gameboy, Gameboy Color and Gameboy Advance games.

.SH Supported Filetypes

.B SFC:
SNES cartridge \-\- ROM image.

.B BS:
Satellaview BS\-X flash cartridge \-\- EEPROM image.

.B ST:
Sufami Turbo cartridge \-\- ROM image.

.B SRM, PSR:
non\-volatile memory, often used to save game data \-\- (P)SRAM image.

.B GB/GBC/GBA:
Gameboy (Color/Advance) cartridge \-\- ROM image.

.B NES/FC:
NES cartridge \-\- ROM image.

Note that bsnes can not open ROMs with different filename extensions or with copier headers.

.SH Known Limitations

.B Satellaview BS\-X emulation:
this hardware is only partially supported. This is mostly because the satellite
network it used (St. GIGA) has been shut down. Access to this network would be
required to properly reverse engineer much of the hardware. Working around this
would require game\-specific hacks, which are contrary to the design goals of
this emulator. As a result, most BS\-X software will not function correctly.

.B Netplay:
internet multiplay is not currently supported nor planned.

.SH PROFILES

bsnes comes with three profiles, where "accuracy" and "compatibility" are focused on accuracy in emulating the SNES (compatibility makes minor tradeoffs in favor of speed) and "performance" is focused on using less resources. Which profile to use can be set with:

# update\-alternatives \-\-config bsnes\-bin

.SH SYSTEM FOLDERS

bsnes does not only need ROMs containing games, but also data that was originally stored in chips belonging to the consoles. The files containing this data are organized in system folders. The system folders contain system info and firmware/BIOS images and are located in "$HOME/.config/bsnes". For example, to play GBA games, a GBA bios image is required. The file has to be named "bios.rom" and placed inside the "Game Boy Advance.sys" folder in "$HOME/.config/bsnes". The checksum of the file has to match the one given in "/usr/share/bsnes/Game Boy Advance.sys/manifest.xml".

.SH SEE ALSO

\fBbsnes\-purify\fR(6), \fBlaevateinn\fR(6)

.SH MORE INFO
Website: http://byuu.org/bsnes/

.SH BSNES AUTHOR
byuu

.SH MAN PAGE AUTHORS
Brandon Barnes, Tobias Hansen
