.TH bsnes\-compatibility 6 "August 5, 2011"
.SH NAME
bsnes\-compatibility \- Accurate SNES/Super Famicom emulator (compatibility profile)
.SH SYNOPSIS
.B bsnes\-compatibility
<ROM location>
.SH OPTIONS
<ROM location> \-\- from the command line, you can supply the name of a ROM file as
an argument to start playing that ROM

.SH SEE ALSO

\fBbsnes\fR(6)

.SH MAN PAGE AUTHOR
Tobias Hansen
