#!/bin/sh

set -e

case "$1" in
    configure)
        update-alternatives --quiet \
            --install /usr/bin/www-browser www-browser /usr/bin/elinks 35 \
            --slave /usr/share/man/man1/www-browser.1.gz www-browser.1.gz /usr/share/man/man1/elinks.1.gz
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

#DEBHELPER#

exit 0
