#!/bin/bash

set -e

install -d -m 755 licenses

install -d -m 755 debian/manpages/usr/share/man/man{1,2,3,4,5,6,7,8}
install -p -m 644 man2/intro.2 debian/manpages/usr/share/man/man2
install -p -m 644 man3/intro.3 debian/manpages/usr/share/man/man3
gzip -9 debian/manpages/usr/share/man/man{2,3}/*

# Installing manpages files
for i in man[145678]; do
	echo "-- Installing section ${i#man}:"
	for j in $i/*.*; do
		echo -n ${j#*/}
		case ${j#*/} in
		time.1|\
		console.4|fd.4|fstab.5|ftpusers.5|lilo.conf.5|nfs.5|exports.5|ttytype.5|\
		passwd.5|lilo.8|zic.8|zdump.8|\
		mdoc.samples.7|environ.5)
			echo -n "(skipped)"
			;; 
		ldd.1|ldconfig.8|ld.so.8|nscd.conf.5|nscd.8)
			echo -n "(skipped, provided by eglibc)"
			;; 
		*)
			read Y < $j 
			case "$Y" in
			.so*)
				echo -n "(symlinked)"
				Y=${Y#.so }
				if [ ! -f $Y ]
				then
				    echo -n " (ignored) "
				    continue
				fi
				if [ "${Y%/*}" = "$i" ]; then
					Y=${Y#*/}.gz
				else
					Y=../$Y.gz
				fi
				ln -s $Y debian/manpages/usr/share/man/$j.gz
				;;
			*)
				install -p -m 644 $j debian/manpages/usr/share/man/$i
				perl -pe 'exit if /^\.(Dd|TH)/; s/\.\\"\s*//o' \
				    < $j > licenses/`basename $j`
				;;
			esac
			;;
		esac
		echo -n " "
	done
	gzip -9 debian/manpages/usr/share/man/$i/*.?
	echo
done

# Installing manpages-dev files
for i in man[23]; do
	echo "-- Installing section ${i#man}:"
	install -d -m 755 debian/manpages-dev/usr/share/man/$i
	for j in $i/*.*; do
		echo -n ${j#*/}
		case ${j#*/} in
		intro.*)
			;;
		infnan.3|query_module.2|set_mempolicy.2)
			echo -n "(skipped)"
			;; 
		fgetxattr.2|flistxattr.2|fremovexattr.2|fsetxattr.2|\
		getxattr.2|lgetxattr.2|listxattr.2|llistxattr.2|lremovexattr.2|\
		lsetxattr.2|removexattr.2|setxattr.2)
			echo -n "(skipped, provided by libattr1-dev)"
			;; 
		*)
			read Y < $j 
			case "$Y" in
			.so*)
				echo -n "(symlinked)"
				Y=${Y#.so }
				if [ ! -f $Y ]
				then
				    echo -n " (ignored) "
				    continue
				fi
				if [ "${Y%/*}" = "$i" ]; then
					Y=${Y#*/}.gz
				else
					Y=../$Y.gz
				fi
				ln -s $Y debian/manpages-dev/usr/share/man/$j.gz
				;;
			*)
				install -p -m 644 $j debian/manpages-dev/usr/share/man/$i
				perl -pe 'exit if /^\.(Dd|TH)/; s/\.\\"\s*//o' \
				    < $j > licenses/`basename $j`
				;;
			esac
			;;
		esac
		echo -n " "
	done
	gzip -9 debian/manpages-dev/usr/share/man/$i/*.?
	echo
done

