#!/bin/sh
set -e


case "$1" in
    configure)

	# dpkg-reconfigure does not set DPKG_MAINTSCRIPT_PACKAGE (#560317)
	if [ -z "$DPKG_MAINTSCRIPT_PACKAGE" ]
	then
		echo "ERROR: DPKG_MAINTSCRIPT_PACKAGE is not set, usually a bug in dpkg-reconfigure"
		exit 1
	fi

        # <target: squeeze>
        if dpkg --compare-versions "$2" lt-nl 195.36.24-1 ; then
            # remove obsolete diversions
            dpkg-divert --remove --rename --package $DPKG_MAINTSCRIPT_PACKAGE --divert /usr/lib/nvidia/libGL.a.xlibmesa /usr/lib/libGL.a > /dev/null
        fi
        # </target: squeeze>

    ;;
esac


#DEBHELPER#

exit 0
