.TH MEMDISKFIND 1 2010\-06\-22 4.00 "Syslinux Project"

.SH NAME
\fBmemdiskfind\fR \- utility to search for a MEMDISK instance

.SH SYNOPSIS
\fBmemdiskfind

.SH DESCRIPTION
\fBmemdiskfind\fR is a simple utility to search for a MEMDISK instance and output the parameters needed to use the "phram" driver in Linux to map it.

.SH SEE ALSO
\fIsyslinux\fR(1)

.SH HOMEPAGE
More information about the Syslinux project can be found on the homepage at <\fIhttp://www.syslinux.org/\fR>.

.SH AUTHOR
memdiskfind was written by H. Peter Anvin <\fIhpa@zytor.com\fR>.
.PP
This manual page was written by Daniel Baumann <\fIdaniel.baumann@progress-technologies.net\fR>.
