.TH SHA1PASS 1 2010\-06\-22 4.00 "Syslinux Project"

.SH NAME
\fBsha1pass\fR \- Create a SHA1 password hash

.SH SYNOPSIS
\fBsha1pass\fR [\fIPASSWORD\fR] [\fISALT\fR]

.SH DESCRIPTION
\fBsha1pass\fR creates a SHA1 password hash. In the absence of a salt value on the command line, a random salt vector will be generated.

.SH SEE ALSO
\fIsyslinux\fR(1)

.SH HOMEPAGE
More information about the Syslinux project can be found on the homepage at <\fIhttp://www.syslinux.org/\fR>.

.SH AUTHOR
sha1pass was written by H. Peter Anvin <\fIhpa@zytor.com\fR>.
.PP
This manual page was written by Daniel Baumann <\fIdaniel.baumann@progress-technologies.net\fR>.
