.TH COMPIZ-DECORATOR 1 "May 18, 2010"
.SH NAME
compiz-decorator \- Automatic decorator loader
.SH SYNOPSIS
.B compiz-decorator
.SH DESCRIPTION
.B compiz-decorator
is a program that automatically launches the best decorator based on your
environment and what decorators are available.
.SH AUTHOR
compiz-decorator was written by CyberOrg <cyberorg@cyberorg.info> and
others.
.PP
This manual page was written by Travis Watkins <amaranth@ubuntu.com>,
for the Ubuntu project (but may be used by others).
