Document: libjpeg-turbo
Title: Debian libjpeg-turbo Manual
Author: <insert document author here>
Abstract: This manual describes what libjpeg-turbo is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libjpeg-turbo/libjpeg-turbo.sgml.gz

Format: postscript
Files: /usr/share/doc/libjpeg-turbo/libjpeg-turbo.ps.gz

Format: text
Files: /usr/share/doc/libjpeg-turbo/libjpeg-turbo.text.gz

Format: HTML
Index: /usr/share/doc/libjpeg-turbo/html/index.html
Files: /usr/share/doc/libjpeg-turbo/html/*.html
