Document: fbv
Title: Debian fbv Manual
Author: <insert document author here>
Abstract: This manual describes what fbv is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fbv/fbv.sgml.gz

Format: postscript
Files: /usr/share/doc/fbv/fbv.ps.gz

Format: text
Files: /usr/share/doc/fbv/fbv.text.gz

Format: HTML
Index: /usr/share/doc/fbv/html/index.html
Files: /usr/share/doc/fbv/html/*.html
