builds/mono/2.0/debug/lib/nunit.core.dll*              /usr/lib/cli/nunit.core-2.6/
builds/mono/2.0/debug/lib/nunit.core.interfaces.dll*   /usr/lib/cli/nunit.core.interfaces-2.6/
builds/mono/2.0/debug/framework/nunit.framework.dll*   /usr/lib/cli/nunit.framework-2.6/
builds/mono/2.0/debug/framework/nunit.mocks.dll*       /usr/lib/cli/nunit.mocks-2.6/
builds/mono/2.0/debug/lib/nunit.util.dll*              /usr/lib/cli/nunit.util-2.6/
