.TH --VERSION: "1" "August 2009" "SyncEvolution 0.9" "User Commands"
.SH NAME
synccompare \- normalize or compare addressbook files
.SH DESCRIPTION

.nf
Usage: synccompare <file>
       synccompare <left file> <right file>

Either normalizes a file or compares two of them in a side-by-side
diff.

Checks environment variables:

CLIENT_TEST_SERVER=funambol|scheduleworld|egroupware|synthesis
      Enables code which simplifies the text files just like
      certain well-known servers do. This is useful for testing
      to ignore the data loss introduced by these servers or (for
      users) to simulate the effect of these servers on their data.

CLIENT_TEST_CLIENT=evolution|addressbook (Mac OS X/iPhone)
      Same as for servers this replicates the effect of storing
      data in the clients.

CLIENT_TEST_LEFT_NAME="before sync"
CLIENT_TEST_RIGHT_NAME="after sync"
CLIENT_TEST_REMOVED="removed during sync"
CLIENT_TEST_ADDED="added during sync"
      Setting these variables changes the default legend
      print above the left and right file during a
      comparison.

CLIENT_TEST_COMPARISON_FAILED=1
      Overrides the default error code when changes are found.
.fi

