.TH --VERSION: "1" "August 2009" "SyncEvolution 0.9" "User Commands"
.SH NAME
sync-ui \- Graphical interface to syncevolution SyncML client
.SH DESCRIPTION

.nf
Usage: sync-ui

sync-ui provides a graphical interface to configure synchronization
sources and sync the local Evolution addressbook, calendar, and so on.

.fi

