.TH COMPIZ 1 "September 29, 2006"

.SH NAME
compiz \- OpenGL window and compositing manager

.SH SYNOPSIS
.B compiz
.RI [ options ]
.RI [ plugins ]
.SH DESCRIPTION
.B compiz
is a compositing window-manager using OpenGL for rendering.

.SH OPTIONS
.TP
.B \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
.TP
.BI "\-\-display " DISPLAY
Manage the display called
.I DISPLAY
instead of the name obtained from the
.I $DISPLAY
environment variable.
.TP
.BI "\-\-refresh\-rate " RATE
Set the default refresh rate.
.TP
.BI \-\-fast\-filter
Use a fast texture filter.
.TP
.BI \-\-indirect\-rendering
Force an indirect rendering context. Use this when running compiz on AIGLX.
.TP
.BI \-\-strict\-binding
Enable strict binding of textures. Use this when running compiz on AIGLX.
.TP
.BI \-\-use\-cow
Make use of the composite overlay window.
.TP
.BI \-\-replace
Replace any existing window managers on the given X display.
.TP
.BI \-\-sm\-disable
Disable the session management.
.TP
.BI "\-\-sm\-client\-id " ID
Use the given
.I ID
as the client ID for session management.
.TP
.BI "\-\-bg\-image " IMAGE
Use
.I IMAGE
as background image.

.SH AUTHOR
compiz was written by David Reveman <davidr@novell.com> and others.
.PP
This manual page was written by Thierry Reding <thierry@gilfi.de>,
for the Debian project (but may be used by others).
