Document: apitrace
Title: Debian apitrace Manual
Author: <insert document author here>
Abstract: This manual describes what apitrace is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/apitrace/apitrace.sgml.gz

Format: postscript
Files: /usr/share/doc/apitrace/apitrace.ps.gz

Format: text
Files: /usr/share/doc/apitrace/apitrace.text.gz

Format: HTML
Index: /usr/share/doc/apitrace/html/index.html
Files: /usr/share/doc/apitrace/html/*.html
