#! /bin/sh -e
# postinst script for lighttpd

set -e

if [ "$1" = "configure" ]; then
   	if [ ! -r /var/www/index.lighttpd.html ];
   	then
   		cp /usr/share/lighttpd/index.html /var/www/index.lighttpd.html
	fi
fi

# dh_installinit will call this function upon failure of rc.d invocation
# Fixes: #383425
start_failed()
{
	echo "Failed to start Lighttpd. Maybe another webserver is already listening on port 80?"
	exit 0
}

#DEBHELPER#

exit 0
