out/bin/src/vboxdrv/*.* /usr/src/modules/virtualbox/vboxdrv
out/bin/src/vboxdrv/linux /usr/src/modules/virtualbox/vboxdrv
out/bin/src/vboxdrv/Makefile /usr/src/modules/virtualbox/vboxdrv

out/bin/src/vboxnetflt/*.* /usr/src/modules/virtualbox/vboxnetflt
out/bin/src/vboxnetflt/linux /usr/src/modules/virtualbox/vboxnetflt
out/bin/src/vboxnetflt/Makefile /usr/src/modules/virtualbox/vboxnetflt

out/bin/src/vboxnetadp/*.* /usr/src/modules/virtualbox/vboxnetadp
out/bin/src/vboxnetadp/linux /usr/src/modules/virtualbox/vboxnetadp
out/bin/src/vboxnetadp/Makefile /usr/src/modules/virtualbox/vboxnetadp

out/bin/src/vboxpci/*.* /usr/src/modules/virtualbox/vboxpci
out/bin/src/vboxpci/linux /usr/src/modules/virtualbox/vboxpci
out/bin/src/vboxpci/Makefile /usr/src/modules/virtualbox/vboxpci

out/bin/src/vboxdrv/*-generated.h /usr/src/modules/virtualbox/include
out/bin/src/vboxdrv/include/iprt/* /usr/src/modules/virtualbox/include/iprt
out/bin/src/vboxdrv/include/VBox/* /usr/src/modules/virtualbox/include/VBox
out/bin/src/vboxdrv/include/internal/* /usr/src/modules/virtualbox/include/internal

out/bin/src/vboxnetflt/include/iprt/* /usr/src/modules/virtualbox/include/iprt
out/bin/src/vboxnetflt/include/VBox/* /usr/src/modules/virtualbox/include/VBox

out/bin/src/vboxnetadp/include/iprt/* /usr/src/modules/virtualbox/include/iprt
out/bin/src/vboxnetadp/include/VBox/* /usr/src/modules/virtualbox/include/VBox
out/bin/src/vboxnetadp/include/internal/* /usr/src/modules/virtualbox/include/internal

out/bin/src/vboxpci/include/iprt/* /usr/src/modules/virtualbox/include/iprt
out/bin/src/vboxpci/include/VBox/* /usr/src/modules/virtualbox/include/VBox

out/bin/src/vboxdrv/r0drv /usr/src/modules/virtualbox
out/bin/src/vboxdrv/common /usr/src/modules/virtualbox
out/bin/src/vboxdrv/generic /usr/src/modules/virtualbox
out/bin/src/vboxdrv/math /usr/src/modules/virtualbox
out/bin/src/vboxdrv/VBox /usr/src/modules/virtualbox
out/bin/src/vboxdrv/include/iprt/nocrt /usr/src/modules/virtualbox/include/iprt

debian/control debian/changelog debian/copyright debian/compat /usr/src/modules/virtualbox/debian
debian/virtualbox-source.files/control.modules.in /usr/src/modules/virtualbox/debian
debian/virtualbox-source.files/postinst.modules.in /usr/src/modules/virtualbox/debian
debian/virtualbox-source.files/udev /usr/src/modules/virtualbox/debian
debian/virtualbox-source.files/rules /usr/src/modules/virtualbox/debian

debian/virtualbox-source.files/Makefile /usr/src/modules/virtualbox
