.TH P11-KIT 1 2011-07-28 p11-kit
.SH NAME
p11-kit \- List the PKCS#11 modules provided on the system

.SH SYNOPSIS
.B p11-kit
[\fIOPTIONS\fR]

.SH DESCRIPTION
List the PKCS#11 modules installed on the system

.SH OPTIONS
.TP
\fB\-l\fR
Lists all of the PKCS#11 modules provided.
.TP
\fB\-v\fR
Turn on verbose mode.
.TP
\fB-h\fR
Print usage information.
