fonts/type1/public/lm/*.pfb usr/share/texmf/fonts/type1/public/lm
fonts/afm/public/lm/*.afm usr/share/texmf/fonts/afm/public/lm
fonts/tfm/public/lm/*.tfm usr/share/texmf/fonts/tfm/public/lm
fonts/enc/dvips/lm/*.enc usr/share/texmf/fonts/enc/dvips/lm
fonts/map/dvips/lm/*.map usr/share/texmf/fonts/map/dvips/lm
# install cork-lm.map which helps xdvi/dvips/etc for old dvi files
# with old file names. This file is not disabled by default
# in lmodern.cfg.
debian/cork-lm.map usr/share/texmf/fonts/map/dvips/lm
tex/latex/lm/*.fd tex/latex/lm/*.sty usr/share/texmf/tex/latex/lm
debian/lmodern.scale etc/X11/fonts/Type1

