.Dd April 5, 2001
.Dt CH_LAB 1
.Os "Edinburgh Speech Tools"
.Sh NAME
.Nm ch_lab
.Nd change/copy label files
.Sh SYNOPSIS
.Nm ch_lab
.Op Fl S Ar frame spacing
.Op Fl start Ar time
.Op Fl end Ar time
.Op Fl ext Ar file extension
.Op Fl extract Ar file
.Op Fl extend Ar time
.Op Fl f Ar sample frequency
.Op Fl lf Ar sample frequency
.Op Fl itype Ar file type
.Op Fl key Ar key file
.Op Fl lablist Ar list of labels
.Op Fl length Ar time
.Op Fl map Ar map file
.Op Fl name Ar feature name
.Op Fl class Ar class
.Op Fl o Ar output file
.Op Fl otype Ar file type
.Op Fl pad Ar high | low
.Op Fl pos Ar list of labels
.Op Fl q Ar timestep
.Op Fl range Ar range
.Op Fl sed Ar sed file
.Op fl shift Ar time delta
.Op Fl style Ar output stype
.Op Fl vocab Ar vocab file
.Op Fl verify
.Op Fl nopath
.Op Fl base
.Op Fl combine
.Op Fl divide
.Op Fl h
.Ar input files ...
.Sh DESCRIPTION
.Nm ch_lab
copies from one or more input label files to an output label file, optionally
performing various operations along the way.
.Pp
The following option flags are recognized:
.Pp
.Bl -tag -width 4n -offset indent -compact
.It Fl h
Print a summary of usage to standard output.
.It Fl S Ar frame spacing
frame spacing of output
.It Fl start Ar time
start time, in seconds, for label extraction
.It Fl end Ar time
end time, in seconds, for label extraction
.It Fl ext Ar file extension
filename extension to use for multiple output files
.It Fl extract Ar file
extract a single file from a list of files
.It Fl extend Ar time
extend track file by
.Ar time
seconds beyond label file
.It Fl f Ar sample frequency
sample frequency of label file
.It Fl lf Ar sample frequency
sample frequency for labels
.It Fl itype Ar file type
type of input label file: esps htk ogi
.It Fl key Ar key file
key label file
.It Fl lablist Ar list
list of labels to be considered as blank
.It Fl length Ar time
length of track produced, in seconds
.It Fl map Ar map file
label mapping file
.It Fl name Ar feature name
eg. Fo Phoneme
.It Fl class Ar class
name of class defined in op file
.It Fl o Ar output file
output file name
.It Fl otype Ar file type
output file type: xmg, ascii, esps, htk
.It Fl pad Ar high | low
pad with high or low values
.It Fl pos Ar list
list of labels to be regarded as 'pos'
.It Fl q Ar timestep
quantize label timings to nearst value
.It Fl range Ar range
difference between high and low values
.It Fl sed Ar sed file
perform regex editing using sed file
.It fl shift Ar time delta
shift the times of the labels
.It Fl style Ar output style
output style e.g. track
.It Fl vocab Ar file
file containing list of words in vocabulary
.It Fl verify
check that only labels in vocab file are in label file
.It Fl nopath
ignore pathnames when searching label lists
.It Fl base
use base filenames for lists of label files
.It Fl combine
.It Fl divide
.El
.Sh SEE ALSO
.Xr ch_wave 1
.Xr ch_track 1
