.Dd April 5, 2001
.Dt CH_UTT 1
.Os "Edinburgh Speech Tools"
.Sh NAME
.Nm ch_utt
.Nd change/copy utterance file
.Sh SYNOPSIS
.Nm ch_utt
.Op Fl h
.Op Fl f Ar feature
.Op Fl o Ar output file
.Op Fl otype Fl file type
.Op Fl sysdir Fl directory
.Ar input file
.Sh DESCRIPTION
.Nm ch_utt
copies an input utterance file to an output file, optionally changing its format
or performing other operations along the way.
.Pp
The following option flags are recognized:
.Pp
.Bl -tag -width 4n -offset indent -compact
.It Fl h
Print a short summary of options to standard output
.It Fl f Ar feature
Feature to use as item ID when merging utterances.
.It Fl o Ar output file
Output file name
.It Fl otype Fl file type
Output file type.  For the full list of supported file formats, see the output
of the
.Fl h
option.
.It Fl sysdir Fl directory
Look for unqualified system entities in this directory
.El
.Sh SEE ALSO
.Xr ch_track 1
.Xr ch_lab 1
