.TH "SPEECH-TOOLS" "1" "August 2007" "speech-tools" "User Commands"
.SH NAME
speech-tools \- Programs for audio and speech manipulation
.SH DESCRIPTION
This program does not have a dedicated manual page.
.BR
Please refer to the documentation, in
.BR
/usr/share/doc/speech-tools-doc/doc/index.html
.BR
It is distributed in the Debian package
.I speech-tools-doc.
