.TH YaKuake 1 "Oct 2005" "" ""
.SH NAME
YaKuake \- a Quake-style terminal emulator based on KDE Konsole technology.
.SH SYNOPSIS
.B YaKuake 
[Qt\-options] [KDE\-options]
.SH DESCRIPTION
YaKuake is inspired from the terminal in the Quake game: when you press a key
(by default F12, but that can be changed) a terminal window slides down from
the top of the screen. Press the key again, and the terminal slides back.

It is faster than a keyboard shortcut because it is already loaded into memory
and as such is very useful to anyone who frequently finds themselves switching
in and out of terminal sessions.
.SH OPTIONS
YaKuake has no application-specific options.

Generic options:
.TP
.B  \-\-help
Show help about options
.TP
.B  \-\-help\-qt  
Show Qt specific options
.TP
.B  \-\-help\-kde  
Show KDE specific options
.TP
.B  \-\-help\-all  
Show all options
.TP
.B  \-\-author  
Show author information
.TP
.B \-v,  \-\-version  
Show version information
.TP
.B  \-\-license  
Show license information
.TP
.B  \-\-  
End of options
.SH SEE ALSO
YaKuake Homepage: http://extragear.kde.org/apps/yakuake/
.SH AUTHOR
YaKuake was written by Francois Chazal <neptune3k@free.fr>.
YaKuake is currently maintained by Eike Hein <sho@eikehein.com>.
.SH OTHER
This manual page was written by Ana Beatriz Guerrero Lopez <ana@ekaia.org>,
for the Debian project (but may be used by others).
