.\" -*- nroff -*-
.\"
.\" Copyright (c) 2008 Luca Capello http://luca.pca.it <luca@pca.it>

.TH STUMPISH 1 "Jul 22, 2007"

.SH NAME
stumpish \- the StumpWM Interactive SHell

.SH SYNOPSIS
.B stumpish
.RI [[-e]
.I command
.RI [args...]]

.SH DESCRIPTION
StumpISH is the StumpWM shell.  Use it to interact a running StumpWM
instance.
.PP
When run from a terminal with no arguments, \fBstumpish\fP accepts
commands interactively and prints each result.
.PP
If standard input is a pipe, \fBstumpish\fP executes any number of
commands and prints the concatenated results.
.PP
If the '\-e' option and one argument are given on the command line,
stumpish reads any number of lines from standard input and uses them
as the argument to the named command.  Otherwise, if one or more
arguments are provided on the command line, the first is considered
the name of the command to execute and the remainder is concatenated
to form the argument.

.SH OPTIONS
.TP
.BI \-r
Do not use readline, only available when run interactively.
.TP
.BI \-\-help
Show the help and exit.

.SH SEE ALSO
.BR stumpwm (1)

.SH AUTHORS
StumpISH was written by Jonathan Moore Liles
<wantingwaiting@users.sf.net> and is licensed under the terms of the
GNU General Public License (GPL), version 2 or later.

This manual page was written by Luca Capello <luca@pca.it> for the
Debian StumpWM package and is licensed under the terms of the GNU
General Public License (GPL), version 2 or later.  Check
/usr/share/doc/stumpwm/copyright for more information.
