.\" -*- nroff -*-
.\"
.\" Copyright (c) 2007-2008 Luca Capello <luca@pca.it>

.TH STUMPWM 1 "Jul 23, 2008"

.SH NAME
stumpwm \- a Common Lisp window manager

.SH SYNOPSIS
.B stumpwm

.SH DESCRIPTION
Stumpwm is a tiling, keyboard driven X11 Window Manager written
entirely in Common Lisp.

StumpWM attempts to be customizable yet visually minimal.  There are
no window decorations, no icons, and no buttons.  It does have various
hooks to attach your personal customizations, and variables to tweak.

.SH FILES
.I ~/.stumpwmrc

.SH ENVIRONMENT
.B LISP
.IP
Specify which Common Lisp implementation should be used.  Default to
CLISP, other values are SBCL and CMUCL (all lowercase).  This can also
be configured in \fI~/.stumpwmrc\fP as "\fB;debian=lisp\fP".

.SH SEE ALSO
.BR clisp (1),
.BR sbcl (1),
.BR cmucl (1)
.P
The complete StumpWM documentation is available under the info
subsystem, as well as the SLIME documentation.

.SH AUTHORS
StumpWM was principally written by Shawn Betts <sabetts@vcn.bc.ca> and
is licensed under the terms of the GNU General Public License (GPL),
version 2 or later.

This manual page was written by Luca Capello <luca@pca.it> for the
Debian StumpWM package and is licensed under the terms of the GNU
General Public License (GPL), version 2 or later.  Check
/usr/share/doc/stumpwm/copyright for more information.
