debian/tmp/usr/lib/iceweasel/components usr/lib/iceweasel
debian/iceweasel-xremote-client usr/lib/iceweasel

debian/tmp/usr/lib/iceweasel/defaults/preferences usr/share/iceweasel/defaults
debian/tmp/usr/lib/iceweasel/searchplugins/* etc/iceweasel/searchplugins/locale/en-US/
debian/tmp/usr/lib/iceweasel/icons usr/share/iceweasel
debian/tmp/usr/lib/iceweasel/chrome usr/share/iceweasel
debian/tmp/usr/lib/iceweasel/modules usr/share/iceweasel

debian/tmp/usr/lib/iceweasel/application.ini usr/lib/iceweasel
debian/tmp/usr/lib/iceweasel/blocklist.xml usr/lib/iceweasel

debian/tmp/usr/lib/iceweasel/defaults/profile etc/iceweasel/

debian/iceweasel.desktop usr/share/applications

build-browser/debian/branding/mozicon16.xpm usr/share/iceweasel/icons/
build-browser/debian/branding/mozicon50.xpm usr/share/iceweasel/icons/
build-browser/debian/branding/mozicon128.png usr/share/iceweasel/icons/

debian/iceweasel.js etc/iceweasel/pref
debian/vendor.js usr/share/iceweasel/defaults/preferences

debian/debsearch.xml etc/iceweasel/searchplugins/common
debian/duckduckgo.xml etc/iceweasel/searchplugins/common

debian/tmp/usr/lib/iceweasel/extensions/\{972ce4c6-7e08-4474-a285-3208198ce6fd\} usr/lib/iceweasel/extensions

build-browser/debian/branding/iceweasel.xpm usr/share/pixmaps

debian/firefox usr/bin

usr/lib/iceweasel/chrome.manifest

usr/lib/iceweasel/webapprt-stub
usr/lib/iceweasel/webapprt usr/share/iceweasel
