.TH SMJS 1 "September 2, 2010"
.SH NAME
smjs - javascript shell
.SH SYNOPSIS
\fBsmjs\fP
.SH DESCRIPTION
The "JS shell", a simple interpreter program that uses the JS API and more
than a few internal interfaces (some of these internal interfaces could
be replaced by jsapi.h calls). The js program built from this
source provides a test vehicle for evaluating scripts and calling functions,
trying out new debugger primitives, etc.

\fBIt is not recommended for production use\fP, as it contains dangerous
(security-wise) debugging features.

.SH AUTHOR
This manpage was originally written by Bastian Kleineidam
<calvin@debian.org> for the Debian distribution of Spidermonkey, further
modified by Mike Hommey <glandium@debian.org>.

The main author of Spidermonkey is the Mozilla Project.
