.TH AGAVE 1 "August 25, 2006"
.SH NAME
Agave \- colorscheme designer for the gnome desktop
.SH SYNOPSIS
.B agave
.RI [ options ]
.SH DESCRIPTION
Agave is a program for generating colorschemes from a starting color.  It
currently supports five different colorscheme types:

 * Complements: The starting color and the color directly across the color wheel
 * Split Complements: the starting color and the two colors that are slightly
   offset from the color directly across the color wheel
 * Triads: the starting color and the two colors 1/3 of the way around the wheel
   in each direction.
 * Tetrads: The starting color and its complement plus another color slightly
   offset from the starting color and _its_ complement
 * Analogous: The starting color and two colors slightly offset in hue
 * Monochromatic: The starting color and two other colors of the same hue, one
   lighter, and one darker
.PP
\fBUsing Agave\fP

 * Choose a starting color by clicking on the color button or selecting a color
   from the palette, and then select a scheme type from the combo box.  The
   generated scheme will be displayed in the main window. 
 * The left-most Color in the main window is the currently-selected color.  This
   color can be added to your favorites list with the '+' button in the bottom
   right, or with the keyboard shortcut 'Ctrl+D'.
 * To make one of the other colors in the scheme the currently-selected color, you
   can double-click the colorswatch.
 * To copy a hexstring representation of the color (e.g. #FFFFFF) to the
   clipboard, right-click the colorswatch and select the 'copy' menu
   item.
.SH OPTIONS
.SS 
.SS Help Options:
.TP
.B  -?, --help             
Show help options
.TP
.B  --help-all               
Show all help options
.TP
.B  --help-gtk               
Show GTK+ Options
.SS
.SS GTK+ Options
.TP
.B  --class=CLASS            
Program class as used by the window manager
.TP
.B  --name=NAME              
Program name as used by the window manager
.TP
.B  --screen=SCREEN          
X screen to use
.TP
.B  --sync
Make X calls synchronous
.TP
.B  --gtk-module=MODULES     
Load additional GTK+ modules
.TP
.B  --g-fatal-warnings
Make all warnings fatal
.SS
.SS Application Options:
.TP
.B  -d, --debug              
Enable Debugging output
.TP
.B  --display=DISPLAY        
X display to use
.PP
.SH AUTHOR
Agave was written by Jonathon Jongsma <jonathon.jongsma@gmail.com>.
.PP
This manual page was written by Varun Hiremath <varunhiremath@gmail.com>,
for the Debian project (but may be used by others).
