.TH libassuan-config 1 "02 Jan 2004" libassuan-config
.SH NAME
.HP
libassuan-config - libassuan build information script
.SH SYNOPSIS
.HP 
libassuan-config [options]
.P
.SH DESCRIPTION
.HP
.I libassuan-config 
is a script that's used by make and other build enviroments to
gather libassuan information.
.HP
Run
.I libassuan-config
for additional information.
