.TH PYPPD "1" "November 2010" "Debian" "User Commands"
.SH NAME
pyppd \- A CUPS PostScript Printer Driver's compressor and generator
.SH SYNOPSIS
.B pyppd
[\fIoptions\fR] \fIppds_directory\fR
.SH OPTIONS
.TP
\fB\-\-version\fR
show program's version number and exit
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-v\fR, \fB\-\-verbose\fR
run verbosely (can be supplied multiple times to
increase verbosity)
.TP
\fB\-d\fR, \fB\-\-debug\fR
print debug messages
.TP
\fB\-o\fR FILE, \fB\-\-output\fR=\fIFILE\fR
write archive to FILE [default pyppd\-ppdfile]
.SH AUTHOR
This manpage has been written by Didier Raboud <didier@raboud.com> for the Debian project with help2man as a start.
.SH COPYRIGHT
Copyright \(co 2010 Vitor Baptista.
.br
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.
