#!/bin/sh

set -e

# In case the user want to purge all files of the fwknop-server package
# we must remove manually pid, socket and log files before the main 
# directories are removed.
if [ "$1" = "purge" ]; then

	# Handle the /var/run/fwknop directory that contains pid and digest
	# files
	if [ -d /var/run/fwknop ]; then
	    find /var/run/fwknop/ -type f -exec rm {} \;
	    rmdir /var/run/fwknop
	fi

fi

#DEBHELPER#

exit 0;
