.\"                                      Hey, EMACS: -*- nroff -*-
.TH NIKON-CURVE 1 "16 Aug 2006"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
nikon-curve \- generate interpolation data from Nikon tone curves
.SH SYNOPSIS
\fB nikon-curve\fR [ \fIoptions and input file\fP ]
.SH DESCRIPTION
\fBnikon-curve\fP reads in a Nikon NTC/NCV or NEF file, interprets its tone
curve, and writes out a simple ASCII file containing a table of interpolation
values.
.SH OPTIONS
A summary of options is included below.
.TP
.B \-h
Show summary of options.
.TP
.B \-o
Specify output file.
.TP
.B \-sr
Specify sampling resolution. Default is 65536.
.TP
.B \-or
Specify output resolution. Default is 256.
.TP
.B \-nef
Specify an NEF file to get tone curve data from.
.PP
The \-or and \-sr options are ignored for NEF files.
.PP
NOTE: If a resolution is not specified, a default one will be used.
If the -o option is not specified, default files will be used.
.SH EXAMPLE
.RS
nikon-curve -sr 65536 -or 256 curveFile -o exportFile
.RE
.SH AUTHOR
nikon-curve was written by Shawn Freeman and Udi Fuchs.
.PP
This manual page was written by Hubert Chan <hubert@uhoreg.ca>,
for the Debian project (but may be used by others).
