#!/bin/sh

set -e

# remove schema files
# make sure this is synced with /usr/share/debhelper/autoscripts/postrm-gconf
if [ "$1" = purge ]; then
        OLD_DIR=/etc/gconf/schemas
        SCHEMA_FILES="ufraw.schemas"
        if [ -d $OLD_DIR ]; then
                for SCHEMA in $SCHEMA_FILES; do
                        rm -f $OLD_DIR/$SCHEMA
                done
                rmdir -p --ignore-fail-on-non-empty $OLD_DIR
        fi
fi

#DEBHELPER#
