This patch is part of a series of patches for speech-tools for
Debian GNU/Linux, to provide Debian specific building of speech-tools

--- speech-tools-1.2.3.orig/Makefile
+++ speech-tools-1.2.3/Makefile
@@ -59,7 +59,7 @@
 ALL = .config_error .sub_directories
 
 # Try and say if config hasn't been created
-config_dummy := $(shell test -f config/config || ( echo '*** '; echo '*** Making default config file ***'; echo '*** '; ./configure; )  >&2)
+#config_dummy := $(shell test -f config/config || ( echo '*** '; echo '*** Making default config file ***'; echo '*** '; ./configure; )  >&2)
 
 # force a check on the system file
 system_dummy := $(shell $(MAKE) -C $(TOP)/config -f make_system.mak TOP=.. system.mak)
@@ -105,8 +105,9 @@
 		exit 2 ;\
 	fi
 
-config/config: config/config.in config.status
-	./config.status
+# This clashes badly with Debian package setup
+#config/config: config/config.in config.status
+#	./config.status
 
 configure: configure.in
 	autoconf
