.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "RACKUP" "1" "December 2010" "" ""
.
.SH "NAME"
\fBrackup\fR
.
.P
rackup(1) \-\- An utility for run Rack\-based applications
.
.SH "SYNOPSIS"
\fBrackup\fR [ruby options] [rack options] [rackup config]
.
.SH "DESCRIPTION"
Rackup is a useful tool for running Rack applications, which uses the Rack::Builder DSL to configure middleware and build up applications easily\.
.
.P
rackup automatically figures out the environment it is run in, and runs your application as FastCGI, CGI, or standalone with Mongrel or WEBrick \-all from the same configuration\.
.
.SH "OPTIONS"
Ruby options:
.
.TP
\fB\-e\fR, \fB\-\-eval\fR [LINE]
evaluate a LINE of code
.
.TP
\fB\-d\fR, \fB\-\-debug\fR
set debugging flags (set $DEBUG to true)
.
.TP
\fB\-w\fR, \fB\-\-warn\fR
turn warnings on for your script
.
.TP
\fB\-I\fR, \fB\-\-include\fR [PATH]
specify $LOAD_PATH (may be used more than once)
.
.TP
\fB\-r\fR, \fB\-\-require\fR [LIBRARY]
require the library, before executing your script
.
.P
Rack options:
.
.TP
\fB\-s\fR, \fB\-\-server\fR [SERVER]
serve using SERVER (webrick/mongrel)
.
.TP
\fB\-o\fR, \fB\-\-host\fR [HOST]
listen on HOST (default: 0\.0\.0\.0)
.
.TP
\fB\-p\fR, \fB\-\-port\fR [PORT]
use PORT (default: 9292)
.
.TP
\fB\-E\fR, \fB\-\-env\fR [ENVIRONMENT]
use ENVIRONMENT for defaults (default: development)
.
.TP
\fB\-D\fR, \fB\-\-daemonize\fR
run daemonized in the background
.
.TP
\fB\-P\fR, \fB\-\-pid\fR [FILE]
file to store PID (default: rack\.pid)
.
.P
Common options:
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show the help message
.
.TP
\fB\-\-version\fR
Show version
.
.SH "EXAMPLES"
This is a simple example on how to start an application based on Rack with rackup:
.
.P
$ rackup \-Ilib blog/config\.ru
.
.P
[2010\-12\-10 15:01:11] INFO WEBrick 1\.3\.1
.
.P
[2010\-12\-10 15:01:11] INFO ruby 1\.9\.2 (2010\-08\-18) [x86_64\-linux]
.
.P
[2010\-12\-10 15:01:11] INFO WEBrick::HTTPServer#start: pid=4496 port=9292
.
.SH "AUTHORS"
Copyright (C) 2007, 2008, 2009, 2010 \fBChristian Neukirchen\fR \fB<http://purl\.org/net/chneukirchen>\fR
.
.P
For a complete list of authors and contributors to the project, please take a look here \fIhttps://github\.com/rack/rack/contributors\fR
.
.P
This manual page was written by Ermenegildo Fiorito \fIfiorito\.g@gmail\.com\fR for the Debian Project
.
.SH "SEE ALSO"
ruby(1) \fIhttp://rack\.rubyforge\.org\fR
