#!/bin/sh
#
# Author: Dario Minnucci <midget@debian.org>
# Date:   Fri, 29 Jun 2007 00:28:43 +0200
#         Delete 'mon' user on purge step.
#

set -e

#echo "----------------------------------------------"
#echo " debian/postrm: $1"
#echo "----------------------------------------------"

case "$1" in
    purge)
        # Remove 'mon' user
        echo -n "Removing user 'mon' ... "
		userdel mon
		echo "done."
    ;;
esac

#DEBHELPER#

