.TH CAML2HTML 1 "November 9, 2010" "Caml2html User Manual"
.SH NAME
.PP
caml2html - colorizes a set of OCaml source files.
.SH SYNOPSIS
.PP
caml2html [options] file*
.SH DESCRIPTION
.PP
Caml2html colorizes a set of OCaml source files (.ml, \&.mli,
\&.mll, \&.mly, \&...).
Type annotations will be shown when the mouse pointer passes over
an expression if the corresponding \&.annot file is available.
.PP
To obtain a \&.annot file, compile your OCaml source files with
\f[B]ocamlc\ -dtypes\f[] or \f[B]ocamlopt\ -dtypes\f[].
.SH OPTIONS
.TP
.B -annotfilter {innermost|outermost}
choose whether innermost or outermost type annotations should be
used (default: innermost)
.RS
.RE
.TP
.B -charset 
specify charset to use (default: iso\[en]8859\[en]1)
.RS
.RE
.TP
.B -css
use CSS named style.css for styling
.RS
.RE
.TP
.B -cssurl 
use the given URL as CSS for styling
.RS
.RE
.TP
.B -inhead
use default styling and place it in the head section of the
document (default when applicable)
.RS
.RE
.TP
.B -inline
use inline styling (HTML only, default fallback if -inhead is not
applicable)
.RS
.RE
.TP
.B -body
output only document's body, for inclusion into an existing
document (see also -make-css and -make-latex-defs)
.RS
.RE
.TP
.B -ln
add line number at the beginning of each line
.RS
.RE
.TP
.B -hc
comments are treated as raw HTML or LaTeX code (no newlines inside
of tags)
.RS
.RE
.TP
.B -t
add a title to the HTML page
.RS
.RE
.TP
.B -nf
do not add footnotes to the HTML page
.RS
.RE
.TP
.B -ie7
drop support for type annotations on Internet Explorer 6 and older
.RS
.RE
.TP
.B -noannot
do not insert type annotations as read from \&.annot files (HTML
output only)
.RS
.RE
.TP
.B -notab
do not replace tabs by spaces
.RS
.RE
.TP
.B -tab 
replace tab by n spaces (default = 8)
.RS
.RE
.TP
.B -d 
generate files in directory dir, rather than in current directory
.RS
.RE
.TP
.B -o 
output file
.RS
.RE
.TP
.B -v
print version number to stdout and exit
.RS
.RE
.TP
.B -make-css 
create CSS file with default color definitions and exit
.RS
.RE
.TP
.B -ext <NAME:CMD>
use the given external command CMD to handle comments that start
with (*NAME.
NAME must be a lowercase identifier.
.RS
.RE
.TP
.B -latex
output LaTeX code instead of HTML.
.RS
.RE
.TP
.B -make-latex-defs 
create a file containing the default LaTeX color definitions and
matching highlighting commands, and exit.
is not included.
.RS
.RE
.TP
.B -help|--help
Display this list of options
.RS
.RE
.SH AUTHORS
Sylvain Le Gall.

