.TH SOFTWARE\-PROPERTIES\-GTK 1 "Mar 2010" "Software Sources List editor"
.SH NAME
software\-properties\-gtk
\- Software Sources List editor
.SH SYNOPSIS
software\-properties\-gtk [options] 
.SH DESCRIPTION
Software Sources List editor
.SH OPTIONS
.SS Options:
.TP
.B  \-\-debug  
Print some debug information to the command line
.TP
.B  \-\-massive\-debug  
Print a lot of debug information to the command line
.TP
.B  \-\-no\-update  
No update on repository change (useful if called from an external program)
.TP
.B  \-\-enable\-component  <name>
Enable the specified component of the distro's repositories [component_arg]
.TP
.B \-\-open\-tab
Open specific tab number on startup
.TP
.B  \-\-enable\-ppa  <name>
Enable PPA with the given name [ppa_arg]
.SS Generic options:
.TP
.B  \-\-help  
Show help about options
