
usr/bin/konsolekalendar
usr/share/applications/kde4/konsolekalendar.desktop
usr/share/doc/kde/HTML/*/konsolekalendar/
usr/share/kde4/apps/konsolekalendar/pics/hi128-apps-konsolekalendar.png
usr/share/kde4/apps/konsolekalendar/pics/hi16-apps-konsolekalendar.png
usr/share/kde4/apps/konsolekalendar/pics/hi22-apps-konsolekalendar.png
usr/share/kde4/apps/konsolekalendar/pics/hi32-apps-konsolekalendar.png
usr/share/kde4/apps/konsolekalendar/pics/hi48-apps-konsolekalendar.png
usr/share/locale/*/LC_MESSAGES/konsolekalendar.mo
