.TH DIRAC_ENCODER "1" "July 2005" "dirac_encoder" "User Commands"
.SH NAME
dirac_encoder \- encodes video files to dirac
.br
dirac_decoder \- decodes dirac video files
.br
dirac_instrumentation \- displays instrumentation for dirac video files
.SH DESCRIPTION
Encode, decode or display instrumentation of dirac files with these programs.
For more information about how to use them just call them without parameters.
