.\" sfconvert - convert between various audio formats
.\" Copyright (c) 2001 Daniel Kobras <kobras@debian.org>
.\"
.\" This manual page is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc.,59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
.\"
.\" This manual page is written especially for Debian Linux.
.\"
.TH SFCONVERT 1 "March 2001" "Debian Project" "Debian GNU/Linux"
.SH NAME
sfconvert \- convert between various audio formats
.SH SYNOPSIS
\fBsfconvert\fR \fIinfile\fR \fIoutfile\fR [ \fIoptions ...\fR ]
[ \fIoutput keywords ...\fR ]
.SH DESCRIPTION
The
.B sfconvert
tool can be used to convert audio files from one audio format to another.
The files' audio formats have to be supported by
.BR libaudiofile .
.SH OPTIONS
The following keywords specify the format of the output sound file:
.TP
\fBbyteorder\fR \fIe\fR
Desired endianness of output sample data. \fIe\fR may be one of \fBbig\fR 
or \fBlittle\fR.
.TP
\fBchannels\fR \fIn\fR
Number of output channels. \fIn\fR is \fB1\fR for mono, and \fB2\fR for
stereo files.
.TP
\fBformat\fR \fIf\fR
Audio format of output file. \fIf\fR has to be one of the currently
supported formats: \fBaiff\fR (Audio Interchange File Format),
\fBaifc\fR (AIFF-C File Format), \fBnext\fR (NeXT/Sun Format),
\fBwave\fR (MS RIFF WAVE Format), \fBbicsf\fR (Berkeley/IRCAM/CARL
Sound File Format), \fBavr\fR (Audio Visual Research File Format),
\fBiff\fR (Amiga IFF/8SVX Sound File Format), or \fBnist\fR (NIST SPHERE
File Format).
.TP
\fBinteger\fR \fIn\fR \fIs\fR
Produce integer samples. \fIn\fR specifies the width of individual samples
in bits, \fIs\fR yields the encoding and may be one of
\fB2scomp\fR (2's complement signed data), or
\fBunsigned\fR (unsigned data). The \fBinteger\fR and \fBfloat\fR options
(see below) are mutually exclusive.
.TP
\fBfloat\fR \fIm\fR
Produce floating point samples with a maximum amplitude of \fIm\fR
(usually \fB1.0\fR). This options may not be used together with option
\fBinteger\fR.
.SH SEE ALSO
.BR sfinfo (1).
.SH AUTHOR
.B sfconvert
was written by Michael Pruett <michael@68k.org>.
.PP
This manual page was written by Daniel Kobras <kobras@debian.org>
for the Debian GNU/Linux system (but may be used by others).
It is based on the sfconvert plain text documentation as distributed
with audiofile.

