
usr/bin/kuiviewer
usr/lib/kde4/kuiviewerpart.so
usr/lib/kde4/quithumbnail.so
usr/share/applications/kde4/kuiviewer.desktop
usr/share/icons/hicolor/16x16/apps/kuiviewer.png
usr/share/icons/hicolor/32x32/apps/kuiviewer.png
usr/share/icons/hicolor/48x48/apps/kuiviewer.png
usr/share/kde4/apps/kuiviewer/kuiviewerui.rc
usr/share/kde4/apps/kuiviewerpart/kuiviewer_part.rc
usr/share/kde4/services/designerthumbnail.desktop
usr/share/kde4/services/kuiviewer_part.desktop
