#!/bin/sh

#
# postinst script for libpuzzle-php
#

set -e

if which dpkg-maintscript-helper >/dev/null && dpkg-maintscript-helper supports mv_conffile ; then
    dpkg-maintscript-helper mv_conffile \
        /etc/php5/conf.d/libpuzzle.ini /etc/php5/mods-available/libpuzzle.ini \
        0.9-4.1+b1 -- "$@"
fi

if [ "$1" = "configure" ]; then
    if which php5dismod >/dev/null ; then
        php5enmod libpuzzle
    fi
fi

#DEBHELPER#

exit 0
