.\"     Title: ytasm
.\"    Author: Sam Hocevar <sho@debian.org>
.\"      Date: July 2009
.\"    Manual: TASM Frontend For The Yasm Modular Assembler
.\"
.TH "YTASM" "1" "July 2009" "Tasm" "TASM Frontend For The Yasm Modular Assembler"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
ytasm \- TASM Frontend For The Yasm Modular Assembler
.SH "SYNOPSIS"
.HP 5
\fBytasm\fR [\fB\fIoptions\fR\fR] {\fIsource\fR} [,\fIobject\fR] [\fI,listing\fR] [\fI,xref\fR]
.HP 5
\fBytasm\fR \fB/h\fR
.SH "DESCRIPTION"
.PP
The Yasm Modular Assembler is a portable, retargetable assembler written under the
\(lqnew\(rq
(2 or 3 clause) BSD license. \fBytasm\fR is the TASM-compatible frontend.
.SH "SEE ALSO"
.PP
\fByasm\fR(1),
.PP
Related tools:
\fBas\fR(1),
\fBld\fR(1),
\fBnasm\fR(1)
