#!/bin/sh

set -e

case "$1" in
   configure)
      # Continue below
      ;;
   abort-upgrade|abort-remove|abort-deconfigure)
      exit 0;
      ;;
   *)
      echo "postinst called with unknown argument \`$1'" >&2
      exit 0;
      ;;
esac

update-alternatives \
	--install /usr/include/mpi mpi /usr/include/mpich2 40 \
	--slave /usr/lib/libmpi.so libmpi.so /usr/lib/libmpich.so \
	--slave /usr/lib/libmpi++.so libmpi++.so /usr/lib/libmpichcxx.so \
	--slave /usr/lib/libmpif77.so libmpif77.so /usr/lib/libfmpich.so \
	--slave /usr/lib/libmpif90.so libmpif90.so /usr/lib/libmpichf90.so \
	--slave /usr/bin/mpicc mpicc /usr/bin/mpicc.mpich2 \
	--slave /usr/bin/mpic++ mpic++ /usr/bin/mpic++.mpich2 \
	--slave /usr/bin/mpicxx mpicxx /usr/bin/mpicxx.mpich2 \
	--slave /usr/bin/mpif77 mpif77 /usr/bin/mpif77.mpich2 \
	--slave /usr/bin/mpif90 mpif90 /usr/bin/mpif90.mpich2 \
	--slave /usr/share/man/man1/mpicc.1.gz mpicc.1.gz /usr/share/man/man1/mpicc.mpich2.1.gz \
	--slave /usr/share/man/man1/mpic++.1.gz mpic++.1.gz /usr/share/man/man1/mpic++.mpich2.1.gz \
	--slave /usr/share/man/man1/mpicxx.1.gz mpicxx.1.gz /usr/share/man/man1/mpicxx.mpich2.1.gz \
	--slave /usr/share/man/man1/mpif77.1.gz mpif77.1.gz /usr/share/man/man1/mpif77.mpich2.1.gz \
	--slave /usr/share/man/man1/mpif90.1.gz mpif90.1.gz /usr/share/man/man1/mpif90.mpich2.1.gz

#DEBHELPER#

exit 0
