debian/tmp/usr/include
debian/tmp/usr/lib/lib*.a
debian/tmp/usr/lib/lib*.la
debian/tmp/usr/lib/lib*.so
debian/tmp/usr/lib/gtkglext-1.0
debian/tmp/usr/lib/pkgconfig
examples/*.c /usr/share/doc/libgtkglext1-dev/examples
examples/*.h /usr/share/doc/libgtkglext1-dev/examples
examples/*.rgb /usr/share/doc/libgtkglext1-dev/examples
examples/*.lwo /usr/share/doc/libgtkglext1-dev/examples
examples/Makefile.am /usr/share/doc/libgtkglext1-dev/examples
m4macros/gtkglext.m4 /usr/share/aclocal
