.TH "GBEMOL" "1" 
.SH "NAME" 
gbemol \(em graphical frontend for the Music Player Daemon (MPD) 
.SH "SYNOPSIS" 
.PP 
\fBgbemol\fR [\fB-mclphf\fP]  
.SH "DESCRIPTION" 
.PP 
\fBgbemol\fR is a graphical frontend for the Music 
Player Daemon (MPD), written in C and using GTK+ toolkit. It allows one to 
use MPD with a user-friendly interface.  
.PP 
Features include an easy-to-use, tag-oriented library browser, a two 
mode playlist, cover art support (APIC tag only, for now), system tray icon 
docking, song, album and artist information 
.PP 
More info at project homepage: http://gbemol.sourceforge.net/ 
.SH "OPTIONS" 
.IP "\fB-m\fP         " 10 
Start minimized to tray 
.IP "\fB-f\fP         " 10 
Start on full mode. 
.IP "\fB-c\fP         " 10 
Start on compact mode 
.IP "\fB-l\fP         " 10 
Start with library selected 
.IP "\fB-p\fP         " 10 
Start with playlist selected 
.IP "\fB-h\fP         " 10 
Help message 
.SH "SEE ALSO" 
.PP 
mpd (1) 
.PP 
Project homepage: http://gbemol.sourceforge.net/ 
.SH "AUTHOR" 
.PP 
This manual page was written by Andrea Colangelo <warp10@ubuntu.com> for 
the \fBDebian\fP system (but may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License, Version 2 any 
later version published by the Free Software Foundation. 
 
.PP 
On Debian systems, the complete text of the GNU General Public 
License can be found in /usr/share/common-licenses/GPL-2. 
 
.\" created by instant / docbook-to-man, Tue 26 Jun 2012, 11:21 
