Document: enlightenment
Title: Debian enlightenment Manual
Author: <insert document author here>
Abstract: This manual describes what enlightenment is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/enlightenment/enlightenment.sgml.gz

Format: postscript
Files: /usr/share/doc/enlightenment/enlightenment.ps.gz

Format: text
Files: /usr/share/doc/enlightenment/enlightenment.text.gz

Format: HTML
Index: /usr/share/doc/enlightenment/html/index.html
Files: /usr/share/doc/enlightenment/html/*.html
