Document: zfs
Title: Debian zfs Manual
Author: <insert document author here>
Abstract: This manual describes what zfs is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/zfs/zfs.sgml.gz

Format: postscript
Files: /usr/share/doc/zfs/zfs.ps.gz

Format: text
Files: /usr/share/doc/zfs/zfs.text.gz

Format: HTML
Index: /usr/share/doc/zfs/html/index.html
Files: /usr/share/doc/zfs/html/*.html
