#!/bin/sh

set -e

case $1 in
	(configure)
	# We want /usr/include/bits and /usr/include/gnu to become
	# symlinks, but only after succesfully unpacking libc6-dev-alt
	if ! test -h /usr/include/bits ; then
		rm -rf /usr/include/bits
		ln -sf MULTIARCHDIR/bits /usr/include/
	fi
	if ! test -h /usr/include/gnu ; then
		rm -rf /usr/include/gnu
		ln -sf MULTIARCHDIR/gnu /usr/include/
	fi
	;;
	(*)
	;;
esac
