.TH EVOLUTION 1 2004\-11\-06 "GNOME" "GNOME"
.SH NAME
evolution \- groupware suite for GNOME containing e\-mail, calendar,
addressbook, to-do list and memo tools
.SH SYNOPSIS
.B evolution
.RI [ OPTIONS ] " " [ MAILTO ]
.SH DESCRIPTION
This manual page briefly introduces the 
.B evolution
command.  Evolution is a graphical groupware suite, a single
application for reading and sending e\-mail and for managing
calendars, address books, notes, to-do lists and memos.  It is written
for the GNOME graphical desktop.
.PP
.RI "An optional " MAILTO " expression can be specified, typically"
.RI "invoked from another application. An example " MAILTO " expression"
is `mailto:username@example.com`. This will open a new composer window
with an empty e-mail to `username@example.com`. More advanced expressions
are also suppported, but should conform to RFC 2368.
.PP
For a more detailed explanation of Evolution, please see the Help menu.
.SH OPTIONS
.TP
.B \-?,  \-\-help
Show a help message listing all the options and their meanings.
.TP
.BI "\-c, \-\-component=" COMPONENT
Start Evolution by activating the desired component.
.I COMPONENT
is one of `mail', `calendar', `contacts', `tasks' or `memos'.
.TP
.B \-\-offline
Start in offline mode.
.TP
.B \-\-online
Start in online mode.
.TP
.B \-\-force-online
Ignore network availability.
.TP
.B \-\-express
Start in "express" mode.
.TP
.B \-\-force\-shutdown
Forcibly shut down all Evolution components.
.TP
.BI \-\-debug= FILE
.RI "Send the debugging output of all components to " FILE "."
.TP
.B \-\-disable-eplugin
Disable loading of any plugins.
.TP
.B \-\-disable-preview
Disable preview pane of Mail, Contacts and Tasks.
.TP
.B \-i, \-\-import
Import URIs or file names given as rest of arguments.
.TP
.B \-q, \-\-quit
Request a running Evolution process to quit.
.TP
.BI \-\-display= DISPLAY
X display to use.
.TP
.BI \-\-clutter-display= DISPLAY
X display to use.
.TP
.BI \-\-screen= SCREEN
X screen to use.
.PP
In addition, the usual GTK+ and GNOME command line options apply.
See the output of \-\-help for details.
.SH "SEE ALSO"
http://projects.gnome.org/evolution/
.SH AUTHOR
Evolution was originally developed by the company Ximian, now a part
of Novell.
Evolution is now part of GNOME, and many people have touched the code.
See the "About" item in the "Help" menu for a list.
.PP
This manual page was originally written by Lars Wirzenius for the
Debian system.
.\" Copyright 2004 Lars Wirzenius
.\" You may copy this manual page under the terms of the version 2 of
.\" the GNU General Public License.
.\" Updated by Oystein Gisnas
.\" Updated by Noël Köthe
