invesalius-3.0 /usr/bin/
icons 	/usr/share/invesalius
locale 	/usr/share/invesalius/
presets /usr/share/invesalius/
docs/user_guide_pt_BR.pdf /usr/share/invesalius/docs/

invesalius/session.py /usr/share/invesalius/invesalius
invesalius/version.py /usr/share/invesalius/invesalius
invesalius/presets.py /usr/share/invesalius/invesalius
invesalius/style.py /usr/share/invesalius/invesalius
invesalius/utils.py /usr/share/invesalius/invesalius
invesalius/constants.py /usr/share/invesalius/invesalius
invesalius/math_utils.py /usr/share/invesalius/invesalius
invesalius/invesalius.py /usr/share/invesalius/invesalius
invesalius/i18n.py /usr/share/invesalius/invesalius
invesalius/project.py /usr/share/invesalius/invesalius
invesalius/control.py /usr/share/invesalius/invesalius

invesalius/reader/*.py /usr/share/invesalius/invesalius/reader/
invesalius/net/*.py /usr/share/invesalius/invesalius/net/
invesalius/gui/*.py /usr/share/invesalius/invesalius/gui/
invesalius/gui/widgets/*.py /usr/share/invesalius/invesalius/gui/widgets/
invesalius/data/*.py /usr/share/invesalius/invesalius/data/

debian/invesalius-3.0.desktop /usr/share/applications
debian/invesalius.xpm /usr/share/pixmaps
