.TH FSCK.NFS 8 "May 2004" "Initscripts"
.SH NAME
fsck.nfs \- Dummy fsck.nfs script that always returns success.
.SH SYNOPSIS
.B fsck.nfs
.SH DESCRIPTION
Debian GNU/Linux need this for when the root file system is on NFS: there is
no way to find out if root is NFS mounted and we really want to do a
"fsck -a /".
.SH EXIT CODE
The exit code returned by
.B mount.nfs
is always zero, meaning successful completion.
.SH SEE ALSO
.BR fsck (8),
.BR fstab (5).
