#!/bin/sh

set -e 

# Remove possible leftovers of imagectn -> dcmqrscp transition

if [ "$1" = "purge" ] ; then

   if [ -d /var/lib/dcmtk/db ]; then
      rmdir -p --ignore-fail-on-non-empty /var/lib/dcmtk/db/STORESCP || :
   fi

   if [ -e /etc/default/imagectn.dpkg-old ]; then
      rm -f /etc/default/imagectn.dpkg-old
   fi

   if [ -e /etc/init.d/imagectn.dpkg-old ]; then
      rm -f /etc/init.d/imagectn.dpkg-old
   fi
fi

#DEBHELPER#	

