.TH DH_ZATHURA 1 "2012-03-21" "zathura"
.SH NAME
/usr/share/zathura/dh_zathura \- adds zathura depends to misc:Depends substvar
.SH SYNOPSYS
\fBdh_zathura\fR [\fIdebhelper\ options\fR] [\fB\-\-substvar=\fR\fIname]
.SH DESCRIPTION
dh_zathura adds information about the correct dependency on zathura to
misc:Depends substvar. This is needed because an ABI breakage might make the
a plugin unusable.
.PP
The helper script uses the information stored in zathura's pkg-config file to
determine the ABI version.
.SH "OPTIONS"
.IP "\fB\-\-substvar=\fR\fIname" 4
Change the substvar name to something other than misc:Depends.
.SH "SEE ALSO"
\fIdebhelper\fR(7)
.PP
This program is provided by zathura-dev and is not part of debhelper.
.SH "AUTHOR"
Sebastian Ramacher <s.ramacher@gmx.at>
