etc/apt/apt.conf.d/20dbus
etc/dbus-1/system.d/org.debian.apt.conf
usr/bin/aptd /usr/sbin
usr/bin/aptdcon
usr/share/dbus-1/system-services/org.debian.apt.service
usr/share/polkit-1/actions/org.debian.apt.policy
usr/share/locale
usr/share/man
usr/share/apport/package-hooks/aptdaemon.py
#usr/share/aptdaemon/lintian-*fatal.tags*
# install our own (more relaxed) Ubuntu tags file
../../debian/lintian-*fatal*.Ubuntu usr/share/aptdaemon/
