usr/lib/python2.*/*-packages/aptdaemon/test.py
tests/repo/glatzor.gpg /usr/share/aptdaemon/tests/repo/
tests/repo/gstreamer0.10-silly_0.1-0_all.deb /usr/share/aptdaemon/tests/repo/
tests/repo/Packages /usr/share/aptdaemon/tests/repo/
tests/repo/Release /usr/share/aptdaemon/tests/repo/
tests/repo/Release.gpg /usr/share/aptdaemon/tests/repo/
tests/repo/silly-base_0.1-0_all.deb /usr/share/aptdaemon/tests/repo/
tests/repo/silly-base_0.1-0update1_all.deb /usr/share/aptdaemon/tests/repo/
tests/repo/silly-broken_0.1-0_all.deb /usr/share/aptdaemon/tests/repo/
tests/repo/silly-config_0.1-0_all.deb /usr/share/aptdaemon/tests/repo/
tests/repo/silly-depend-base_0.1-0_all.deb /usr/share/aptdaemon/tests/repo/
tests/repo/silly-essential_0.1-0_all.deb /usr/share/aptdaemon/tests/repo/
tests/repo/silly-fail_0.1-0_all.deb /usr/share/aptdaemon/tests/repo/
tests/repo/silly-important_0.1-0_all.deb /usr/share/aptdaemon/tests/repo/
tests/repo/silly-postinst-input_0.1-0_all.deb /usr/share/aptdaemon/tests/repo/
tests/dpkg-wrapper.sh /usr/share/aptdaemon/tests/repo/
tests/fake-polkitd.py /usr/share/aptdaemon/tests/
