#!/bin/sh

set -e

if [ "$1" = "configure" ]
then
    . /usr/share/debconf/confmodule
    mkdir -p /var/lib/sheepdog/
    if [ -r /etc/default/sheepdog ];then
        db_get sheepdog/start
        if [ "$RET" ];then 
		   SERVICE_START="yes"
		else
		   SERVICE_START="no"
	    sed -i "s/^START=.*/START=\"$SERVICE_START\"/g" /etc/default/sheepdog

		db_get sheepdog/daemon_args
		sed -i "s/^DAEMON_ARGS=.*/DAEMON_ARGS=\"$RET\"/g" /etc/default/sheepdog
	    fi
    fi
fi

#DEBHELPER#

exit 0
