.TH "h52gif" 1
.SH NAME
h52gif \- Converts an HDF5 file to a GIF file. 
.SH SYNOPSIS
.B h52gif 
h5_file gif_file 
.B -i 
h5_image [
.B -p 
h5_palette ] 
.SH DESCRIPTION
h52gif accepts as input the HDF5 file h5_file and the names of images and associated palettes within that file as input and produces the GIF file gif_file, containing those images, as output.
.PP
h52gif expects at least one h5_image. You may repeat
.RS
-i h5_image [-p h5_palette]
.RE
up to 50 times, for a maximum of 50 images. 
.SH OPTIONS
.TP
.B \-i h5_image
Image option, specifying the name of an HDF5 image or dataset containing an image to be converted 
.TP
.B \-p h5_palette
Palette option, specifying the name of an HDF5 dataset containing a palette to be used in an image conversion 
.SH "SEE ALSO"
\&\fIh5dump\fR\|(1), \fIh5ls\fR\|(1), \fIh5diff\fR\|(1),
\&\fIh5repart\fR\|(1), \fIh5import\fR\|(1), \fIgif2h5\fR\|(1), \fIh5perf\fR\|(1)
