.TH "h5redeploy" 1
.SH NAME
h5redeploy \- Updates HDF5 compiler tools after an HDF5 software installation in a new location. 
.SH SYNOPSIS
h5redeploy [help | -help] 
.PP
h5redeploy [-echo] [-force] [-prefix=dir] [-tool=tool] [-show] 
.SH DESCRIPTION
h5redeploy updates the HDF5 compiler tools after the HDF5 software has been installed in a new location. 
.SH OPTIONS
.TP
.B "help, -help"
Prints a help message. 
.TP
.B \-echo
Shows all the shell commands executed. 
.TP
.B \-force
Performs the requested action without offerring any prompt requesting confirmation. 
.TP
.B \-prefix=dir
Specifies a new directory in which to find the HDF5 subdirectories lib/ and include/.  (Default: current working directory) 
.TP
.B \-tool=tool
Specifies the tool to update. tool must be in the current directory and must be writable.  (Default: h5cc) 
.TP
.B \-show
Shows all of the shell commands to be executed without actually executing them.
