.TH BSH 1
.SH NAME
bsh \- BeanShell: A Java scripting environment (command-line version).
.SH SYNOPSIS
.B bsh
.RB [\| \-classpath
.IR path \|]
.RI [\| file \|]
.br

.SH "DESCRIPTION
BeanShell is a small, embeddable, Java source interpreter with object scripting
language features, written in Java. BeanShell executes standard Java statements
and expressions, in addition to obvious scripting commands and syntax. You can
also script objects as simple method closures like those in Perl and
JavaScript(tm).

.B bsh
starts the command-line version of BeanShell.
.SH OPTIONS
The program
.B bsh
optionally takes a
.B \-classpath
option which sets the value of the
.B CLASSPATH
environment variable to the specified path before starting the BeanShell.  This
option is mainly provided for compatibility with JDE (Java Development
Environment for Emacs).

In addition, a file to be executed may be given as argument to
.BR bsh .
.SH "SEE ALSO"
.B xbsh
- the windowed version of BeanShell.

More documentation on BeanShell can be found in
.I /usr/share/doc/bsh-doc/
if the bsh-doc package is installed.
.SH AUTHOR
This manual page was written by Ruud de Rooij <ruud@debian.org>
for the Debian GNU/Linux system (but may be used by others).
