Document: sick-beard
Title: Debian sick-beard Manual
Author: <insert document author here>
Abstract: This manual describes what sick-beard is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sick-beard/sick-beard.sgml.gz

Format: postscript
Files: /usr/share/doc/sick-beard/sick-beard.ps.gz

Format: text
Files: /usr/share/doc/sick-beard/sick-beard.text.gz

Format: HTML
Index: /usr/share/doc/sick-beard/html/index.html
Files: /usr/share/doc/sick-beard/html/*.html
