
.TH svm-subset 1 "DEC 2009" Linux "User Manuals"
.SH NAME 
svm-subset \- a subset selection tool for LIBSVM

.SH SYNOPSIS
.B svm-subset [ -s
.I method
.B ]
.I dataset number
.B [
.I output1
.B ] [
.I output2
.B ]

.SH DESCRIPTION
Training large data is time consuming. Sometimes one should work on a
smaller subset first. The python script subset.py randomly selects a
specified number of samples. For classification data, we provide a
stratified selection to ensure the same class distribution in the
subset.

.SH OPTIONS
.IP "-s method"
.TP
.B 0
--
stratified selection (classification only) (default)
.TP
.B 1
--
random selection
.TP
.IP "output1"
The subset. If output1 is omitted, the subset will be printed on the screen.
.IP "output2"
The rest of data.

.SH FILES
See
.BR svm-train (1) 
for the format of 
.I dataset

.SH EXAMPLES
.IP
svm-subset heart_scale 100 file1 file2
.LP
From heart_scale 100 samples are randomly selected and stored in
file1. All remaining instances are stored in file2.
.SH BUGS
Please report bugs to the Debian BTS.
.SH AUTHOR
Chih-Chung Chang, Chih-Jen Lin <cjlin@csie.ntu.edu.tw>, Chen-Tse Tsai <ctse.tsai@gmail.com> (packaging)
.SH "SEE ALSO"
.BR svm-train (1),
.BR svm-predict (1)
