#!/bin/sh
set -e

case "$1" in
    purge)
	#
	# Remove log files
	#
	rm -f /var/log/boot

	# Remove rc symlinks in the reverse dependency order they were
	# inserted
        update-rc.d stop-bootlogd        remove >/dev/null || exit $?
        update-rc.d stop-bootlogd-single remove >/dev/null || exit $?
        update-rc.d bootlogd             remove >/dev/null || exit $?
        ;;
esac

#DEBHELPER#
