debian/tmp/usr/lib/libatksharpglue-3.so 				/usr/lib/cli/atk-sharp-3.0/
debian/tmp/usr/lib/libgtksharpglue-3.so 				/usr/lib/cli/gtk-sharp-3.0/
debian/tmp/usr/lib/libpangosharpglue-3.so				/usr/lib/cli/pango-sharp-3.0/
debian/tmp/usr/lib/mono/gac/atk-sharp/*/atk-sharp.dll*		/usr/lib/cli/atk-sharp-3.0/
debian/tmp/usr/lib/mono/gac/gdk-sharp/*/gdk-sharp.dll*		/usr/lib/cli/gdk-sharp-3.0/
debian/tmp/usr/lib/mono/gac/gtk-dotnet/*/gtk-dotnet.dll*	/usr/lib/cli/gtk-dotnet-3.0/
debian/tmp/usr/lib/mono/gac/gtk-sharp/*/gtk-sharp.dll*		/usr/lib/cli/gtk-sharp-3.0/
debian/tmp/usr/lib/mono/gac/pango-sharp/*/pango-sharp.dll*	/usr/lib/cli/pango-sharp-3.0/
