#!/bin/sh -e
#
# preinst script for the Debian GNU/Linux gsl-bin package
#
# Written and GPL'ed by Dirk Eddelbuettel <edd@debian.org>   

case "$1" in

    install|upgrade)     
        # We want to remove previous versions' documentation directory
	test -d /usr/share/doc/gsl-bin && rm -rf /usr/share/doc/gsl-bin
	;;

    abort-upgrade)
        ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        ;;

esac

#DEBHELPER#

exit 0                 

