debian/tmp-deb/usr/bin/lsusb                     /usr/bin
debian/tmp-deb/usr/bin/usb-devices               /usr/bin
debian/tmp-deb/usr/bin/usbhid-dump               /usr/bin
debian/tmp-deb/usr/sbin/update-usbids            /usr/sbin
debian/tmp-deb/usr/share/man/man1/usb-devices.1  /usr/share/man/man1
debian/tmp-deb/usr/share/man/man8/lsusb.8        /usr/share/man/man8
debian/tmp-deb/usr/share/pkgconfig/usbutils.pc   /usr/share/pkgconfig
debian/tmp-deb/var/lib/usbutils/usb.ids          /var/lib/usbutils
