.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH BLAS-TEST 1 "January 29, 2002" netlib "Linux Programmer's Manual"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
x{s,d,c,z}c?blat{1,2,3} - testing programs for blas
.SH SYNOPSIS
.B x{s,d,c,z}c?blat1
.br
.B x{s,d,c,z}c?blat{2,3}
.RI < " parameter file" 
.SH DESCRIPTION
This manual page documents briefly the blas testing programs.
This manual page was written for the Debian GNU/Linux distribution
because the original programs do not have manual pages.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
.B blas
is a library of Basic Linear Algebra routines, accessed through either
a Fortran and/or a C interface.  These routines are categorized into
three levels: level1 referring to vecotr-vector operations, level2 to
matrix-vector operations, and level3 to matrix-matrix operations.   In
addition, all routines are written in four "precisions", single
precision real (s), double precision real (d), cingle precision
complex (c), and double precision complex (z).
.br
The testing binaries examine routines in the level
indicated by the last character in the program name and in the
precision indicated by the second character in the program name.  The
stem "blat" in the program name refers to a Fortran interface tester,
whereas a "cblat" stem refers to a C interface tester.
.br
The test programs for levels 2 and 3 read a set of parameters
specifying the problem ranges to examine on standard input.  Sample
input files are found in /usr/share/doc/blas-test/examples.  Files of
the form {s,d,c,z}in{2,3} are input files for the C interface testing
programs, while files or the form {s,d,c,z}blat{2,3}d are input files
to the Fortran testing programs.
.br
On Debian systems, these programs are dynamically linked against the
blas library.  This enables the user to test and compare
alternate versions of the library, such as those provided by
atlas, through the use of the LD_LIBRARY_PATH and LD_PRELOAD
environment variables.  One can confirm the versions of the libraries
being tested in a given environment with the aid of the ldd program.
.SH OPTIONS
These programs take no command line options.
.\" .SH SEE ALSO
.SH AUTHOR
This manual page was written by Camm Maguire <camm@enhanced.com>,
for the Debian GNU/Linux system (but may be used by others).
