.TH HSMARKDOWN 1 "March 23, 2010" "Pandoc User Manuals"
.SH NAME
.PP
hsmarkdown - convert markdown-formatted text to HTML
.SH SYNOPSIS
.PP
hsmarkdown [\f[I]input-file\f[]]\&...
.SH DESCRIPTION
.PP
\f[B]hsmarkdown\f[] converts markdown-formatted text to HTML.
It is designed to be usable as a drop-in replacement for John
Gruber's \f[B]Markdown.pl\f[].
.PP
If no \f[I]input-file\f[] is specified, input is read from
\f[I]stdin\f[].
Otherwise, the \f[I]input-files\f[] are concatenated (with a blank
line between each) and used as input.
Output goes to \f[I]stdout\f[] by default.
For output to a file, use shell redirection:
.PP
\f[CR]
      hsmarkdown\ input.txt\ >\ output.html
\f[]
.PP
\f[B]hsmarkdown\f[] is implemented as a symlink to the
\f[B]pandoc\f[](1) executable.
When called under the name \f[B]hsmarkdown\f[], \f[B]pandoc\f[]
behaves as if it had been called with the options
\f[B]--from\ markdown\ --to\ html\ --strict\f[] and disables all
other options.
(Command-line options will be interpreted as filenames, as they are
by \f[B]Markdown.pl\f[].)
.SH SEE ALSO
.PP
\f[B]pandoc\f[](1).
The \f[I]README\f[] file distributed with Pandoc contains full
documentation.
.PP
The Pandoc source code and all documentation may be downloaded from
<http://johnmacfarlane.net/pandoc/>.
.SH AUTHORS
John MacFarlane.

