.TH d-feet "1" "May 2008"
.SH NAME
d\-feet \- D-Bus viewer and debugger

.SH SYNOPSIS
\fBd\-feet\fR [\fIoptions\fR] [\fIproject\-file\fR]

.SH OPTIONS

.TP
\fB\-h\fR , \fB\-\-help\fR
Show help message and exit
.TP
\fB\-l\fR , \fB\-\-local\-dirs\fR
Use files from the local directory tree

.SH AUTHOR
This manual page was written by Laurent Bigonville <bigon@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
.PP
The original software was written by
John (J5) Palmieri <johnp@redhat.com>
