.TH tcltk-depends 1 "2010-01-10" "0.2" "Tcl/Tk packages for Debian GNU/Linux"
.SH "NAME"
tcltk\-depends \- calculates Tcl/Tk dependencies

.SH "SYNOPSIS"
\&\fBtcltk-depends\fR [\fIdebhelper\ options\fR]

.SH "DESCRIPTION"
tcltk-depends is a debhelper-like program which is responsible for generating
the ${tcl:Depends}, ${tk:Depends}, ${tclsh:Depends} and ${wish:Depends}
substitution variables and adding them to substvars files.
.PP
If you use this program, your package must build-depend on tcl-dev
or tk-dev.

.SH "SEE ALSO"
\&\fIdebhelper\fR\|(7)
.PP
This program is not a part of debhelper.

.SH "AUTHOR"
Sergei Golovan <sgolovan@debian.org>
