.TH MARKDOWN_PY 1

.SH NAME
markdown_py \- a Python implementation of John Gruber's Markdown.

.SH SYNOPSIS
.B markdown_py [\fIoptions\fR] [\fIINPUT_FILE\fR]
.RS 0
(STDIN is assumed if no INPUT_FILE is given)

.SH OPTIONS
.TP
\fB--version\fR
Show program's version number and exit.
.TP
\fB-h\fR, \fB--help\fR
Show the help message and exit.
.TP
\fB-f \fIOUTPUT_FILE\fR, \fB--file=\fIOUTPUT_FILE\fR
Write output to OUTPUT_FILE. Defaults to STDOUT.
.TP
\fB-e \fIENCODING\fR, \fB--encoding=\fIENCODING\fR
Encoding for input and output files.
.TP
\fB-q\fR, \fB--quiet\fR
Suppress all warnings.
.TP
\fB-v\fR, \fB--verbose\fR
Print all warnings.
.TP
\fB-s \fISAFE_MODE\fR, \fB--safe=\fISAFE_MODE\fR
\'replace\', \'remove\' or \'escape\' HTML tags in input.
.TP
\fB-o \fIOUTPUT_FORMAT\fR, \fB--output_format=\fIOUTPUT_FORMAT\fR
\'xhtml1\' (default), \'html4\' or \'html5\'.
.TP
\fB--noisy\fR
Print debug messages.
.TP
\fB-x \fIEXTENSION\fR, \fB--extension=\fIEXTENSION\fR
Load extension EXTENSION.
.TP
\fB-n\fR, \fB--no_lazy_ol\fR
Observe number of first item of ordered lists.

.SH DESCRIPTION
Command-line Markdown compiler based on python-markdown module, with extensions support.

.SH AUTHOR
This manual page was written by Dmitry Shachnev <mitya57@gmail.com>.
