.TH DRICONF 1 "August 14, 2005"
.SH NAME
driconf \- DRI configuration GUI
.SH DESCRIPTION
Driconf is a graphical configuration tool for the Direct Rendering Infrastructure
(DRI). It allows customizing performance and visual quality settings of OpenGL
drivers on a per-driver, per-screen and/or per-application level.

The settings are stored in a system wide or per-user XML configuration file which
is parsed by the OpenGL drivers on startup.
.SH SEE ALSO
Please see /usr/share/doc/driconf/ for more documentation.
.SH AUTHOR
This manual page was written by Michel Daenzer <daenzer@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
