'\" t
.\"     Title: ts.conf
.\"    Author: Russell King
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: Wed 06 Aug 2008 10:46:33 ART
.\"    Manual: tslib
.\"    Source: Debian 5
.\"  Language: English
.\"
.TH "TS\&.CONF" "5" "Wed 06 Aug 2008 10:46:33 ART" "Debian 5" "tslib"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ts.conf \- Configuration file for tslib, controlling touch screens for embedded devices\&.
.SH "DESCRIPTION"
.PP
The idea of tslib is to have a core library that provides standardised services, and a set of plugins to manage the conversion and filtering as needed\&.
.PP
The plugins for a particular touchscreen are loaded automatically by the library under the control of a static configuration file,
/etc/ts\&.conf\&.
/etc/ts\&.conf
gives the library basic configuration information\&. Each line specifies one module, and the parameters for that module\&. The modules are loaded in order, with the first one processing the touchscreen data first\&. For example:
.sp
.if n \{\
.RS 4
.\}
.nf
  module_raw input
  module variance delta=30
  module dejitter delta=100
  module linear
   
.fi
.if n \{\
.RE
.\}
.SH "MODULE PARAMETERS"
.PP
\fBvariance\fR
.RS 4
Tries to do it\*(Aqs best in order to filter out random noise coming from touchscreen ADC\*(Aqs\&. This is achieved by limiting the sample movement speed to some value (e\&.g\&. the pen is not supposed to move quicker than some threshold)\&.
.sp
This is a \*(Aqgreedy\*(Aq filter, e\&.g\&. it gives less samples on output than receives on input\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBParameters:\fR
\fBdelta\fR\&.
.sp
Set the squared distance in touchscreen units between previous and current pen position (e\&.g\&. (X2\-X1)^2 + (Y2\-Y1)^2)\&. This defines the criteria for determining whenever two samples are \*(Aqnear\*(Aq or \*(Aqfar\*(Aq to each other\&.
.sp
If the distance between previous and current sample is \*(Aqfar\*(Aq, the sample is marked as \*(Aqpotential noise\*(Aq\&. This doesn\*(Aqt mean yet that it will be discarded; if the next reading will be close to it, this will be considered just a regular \*(Aqquick motion\*(Aq event, and it will sneak to the next layer\&. Also, if the sample after the \*(Aqpotential noise\*(Aq is \*(Aqfar\*(Aq from both previously discussed samples, this is also considered a \*(Aqquick motion\*(Aq event and the sample sneaks into the output stream\&.
.RE
.RE
.PP
\fBdejitter\fR
.RS 4
Removes jitter on the X and Y co\-ordinates\&. This is achieved by applying a weighted smoothing filter\&. The latest samples have most weight; earlier samples have less weight\&. This allows to achieve 1:1 input\->output rate\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBParameters:\fR
\fBdelta\fR\&.
.sp
Squared distance between two samples ((X2\-X1)^2 + (Y2\-Y1)^2) that defines the \*(Aqquick motion\*(Aq threshold\&. If the pen moves quick, it is not feasible to smooth pen motion, besides quick motion is not precise anyway; so if quick motion is detected the module just discards the backlog and simply copies input to output\&.
.RE
.RE
.PP
\fBlinear\fR
.RS 4
Linear scaling module, primarily used for conversion of touch screen co\-ordinates to screen co\-ordinates\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBParameters:\fR
\fBxyswap\fR\&.
.sp
Interchange the X and Y co\-ordinates \-\- no longer used or needed if the new linear calibration utility ts_calibrate is used\&.
.RE
.RE
.SH "ENVIRONMENT VARIABLES"
.PP
Latest versions of the Xorg tslib input driver use
\fBhal\fR
to configure the touchscreen within Xorg\&. Environment variables are only needed for the tslib commands\&.
.PP
\fBTSLIB_TSDEVICE\fR
.RS 4
If the default touchscreen device cannot be found, set the
\fBTSLIB_TSDEVICE\fR
environment variable to the touchscreen device to use\&.
.sp
Default:
/dev/input/event0
.RE
.PP
\fBTSLIB_CONSOLEDEVICE\fR
.RS 4
Tslib default console device\&.
.sp
Default:
/dev/tty
.RE
.PP
\fBTSLIB_CALIBFILE \fR
.RS 4
Stores calibration data obtained using
ts_calibrate\&.
.sp
Default:
/etc/pointercal
.RE
.PP
\fBTSLIB_CONFFILE\fR
.RS 4
Set a different location for the
ts\&.conf
configuration file itself\&.
.sp
Default;
/etc/ts\&.conf\&.
.RE
.PP
\fBTSLIB_FBDEVICE\fR
.RS 4
Framebuffer device to use for the touchscreen support\&.
.sp
Default:
/dev/fb0\&.
.RE
.PP
\fBTSLIB_PLUGINDIR\fR
.RS 4
Plugin directory for tslib\&.
.sp
Default:
/usr/lib/$triplet/ts0/
where triplet is the MultiArch path, e\&.g\&. arm\-linux\-gnueabi\&.
.RE
.SH "AUTHOR"
.PP
This manual page was written by Neil Williams
codehelp@debian\&.org
for the
Debian(TM)
distribution because the original program does not have a manual page, but may be used by others\&. Permission is granted to copy, distribute and/or modify this document under the terms of the
GNU
General Public License, Version 2 any later version published by the Free Software Foundation\&.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common\-licenses/GPL\&.
.SH "AUTHOR"
.PP
\fBRussell King\fR
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2008 Neil Williams
.br
