'\" t
.\"     Title: TS_CALIBRATE
.\"    Author: Russell King
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: January 21, 2008
.\"    Manual: tslib
.\"    Source: Debian 1
.\"  Language: English
.\"
.TH "TS_CALIBRATE" "1" "January 21, 2008" "Debian 1" "tslib"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ts_calibrate \- A test program to calibrate a touch screen for embedded devices\&.
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBts_calibrate\fR, a basic test program for touchscreen library\&.
.PP
This manual page was written for the
Debian(TM)
distribution because the original program does not have a manual page\&.
.SH "ENVIRONMENT VARIABLES"
.PP
Latest versions of the Xorg tslib input driver use
\fBhal\fR
to configure the touchscreen within Xorg\&. Environment variables are only needed for the tslib commands\&.
.PP
TSLIB_TSDEVICE
.RS 4
TS device file name\&.
.sp
Default (non inputapi): /dev/touchscreen/ucb1x00
.sp
Default (inputapi) [Debian]: /dev/input/event0
.RE
.PP
TSLIB_CALIBFILE
.RS 4
Calibration file\&.
.sp
Default: /etc/pointercal
.RE
.PP
TSLIB_CONFFILE
.RS 4
Configuration file for tslib\&.
.sp
Default: /etc/ts\&.conf
.RE
.PP
TSLIB_PLUGINDIR
.RS 4
Plugin directory\&.
.sp
Default:
/usr/lib/$triplet/ts0/
where triplet is the MultiArch path, e\&.g\&. arm\-linux\-gnueabi\&.
.RE
.PP
TSLIB_CONSOLEDEVICE
.RS 4
Console device\&.
.sp
Default: /dev/tty
.RE
.PP
TSLIB_FBDEVICE
.RS 4
Framebuffer device\&.
.sp
Default: /dev/fb0
.RE
.PP
For more information on tslib configuration, see
ts\&.conf
(5)
.SH "AUTHOR"
.PP
This manual page was written by Neil Williams
codehelp@debian\&.org
for the
Debian(TM)
system (but may be used by others)\&. Permission is granted to copy, distribute and/or modify this document under the terms of the
GNU
General Public License, Version 2 any later version published by the Free Software Foundation\&.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common\-licenses/GPL\&.
.SH "AUTHOR"
.PP
\fBRussell King\fR
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2008 Neil Williams
.br
