'\" t
.\"     Title: TS_PRINT
.\"    Author: Russell King
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: January 21, 2008
.\"    Manual: tslib
.\"    Source: Debian 1
.\"  Language: English
.\"
.TH "TS_PRINT" "1" "January 21, 2008" "Debian 1" "tslib"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ts_print \- Just prints touchscreen events\&.
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBts_print\fR, used to print touchscreen events instead of painting them on the framebuffer\&.
.PP
This manual page was written for the
Debian(TM)
distribution because the original program does not have a manual page\&.
.SH "SEE ALSO"
.PP
For more information on general tslib configuration, see
ts\&.conf
(5) or for a quick summary of the environment variables, see
ts_calibrate
(1)\&.
.SH "AUTHOR"
.PP
This manual page was written by Neil Williams
codehelp@debian\&.org
for the
Debian(TM)
system (but may be used by others)\&. Permission is granted to copy, distribute and/or modify this document under the terms of the
GNU
General Public License, Version 2 any later version published by the Free Software Foundation\&.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common\-licenses/GPL\&.
.SH "AUTHOR"
.PP
\fBRussell King\fR
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2008 Neil Williams
.br
