.TH UPDATE-TEXMF 8
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
update-texmf \- shell script to generate /etc/texmf/texmf.cnf
.SH SYNOPSIS
.B update-texmf
.I "[options]"
.br
.SH DESCRIPTION
This manual page documents briefly the
.BR update-texmf
command.
This manual page was written for the Debian GNU/Linux distribution
because the original script was designed for Debian packaging system.
.PP
.B update-texmf
is a shell script to generate /etc/texmf/web2c/texmf.cnf from files in 
/etc/texmf/texmf.d/*.cnf
.PP
A user who wants to customize /etc/texmf/web2c/texmf.cnf should add, 
for example, 22mymacro.cnf in /etc/texmf/texmf.d/ and run 'update-texmf'.
.SH OPTIONS
.TP
.B \-v, --verbose
Show verbose messages.
.TP
.B \-d, --debug
Show debugging information, and don't delete temporary files. Implies
--verbose. 
.SH SEE ALSO
.PP
Further information can be found in
/usr/share/doc/tex-common/README.Debian.{txt,pdf.html}
.PP
.SH AUTHOR
This manual page was written by Atsuhito Kohda <kohda@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
