.TH UPDATE-TEXMF-CONFIG 8
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
update-texmf-config \- script used in maintainer scripts to trigger tex-common actions
.SH SYNOPSIS
.B update-texmf-config
.I "[options]"
.br
.SH DESCRIPTION
This manual page documents briefly the
.BR update-texmf-config
command.
This manual page was written for the Debian GNU/Linux distribution
because the original script was designed for Debian packaging system.
.PP
.B update-texmf-config
is a shell script that is called from maintainer scripts shipping new
map files, hyphenation patterns, or any other TeX input
file.
.PP
The script simply activates the respective trigger, namely texmf-map
for font map files, texmf-hyphen for hyphenation patterns, and 
texmf-lsr for updates to the lsr database. All
the necessary action will then be carried out by the tex-common package.
.SH OPTIONS
.TP
.B map
Activate the texmf-map trigger.
.TP
.B hyphen
Activate the texmf-hyphen trigger.
.TP
.B lsr
Activate the texmf-lsr trigger.

.SH SEE ALSO
.PP
Further information can be found in
/usr/share/doc/tex-common/README.Debian.{txt,pdf.html}
.PP
.SH AUTHOR
This manual page was written by Norbert Preining <preining@logic.at>,
for the Debian GNU/Linux system (but may be used by others).
