.\" gpm.conf.5
.\" Written in 2005 by Peter Samuelson for the Debian Project.
.\"
.\" No rights are reserved; anyone may copy, modify and distribute this
.\" file in any way and for any purpose, exactly as though it were in
.\" the public domain.
.\"
.Dd January 5, 2005
.Dt GPM.CONF 5
.Os Debian 3.0
.\"
.Sh NAME
.Nm gpm.conf
.Nd startup configuration file for gpm
.\"
.Sh DESCRIPTION
.Pp
.Nm
specifies options to be passed to the
.Nm gpm
daemon at start time.  It is parsed by the init script, rather than by
.Nm gpm
itself.  It comprises variable assignments in Bourne shell syntax:
\fIvariable\fR=\fIvalue\fR (with no extra spaces; to embed spaces or
other shell metacharacters in values, use quotes as in shell
scripting).  Blank lines and lines beginning with a hash ("\fB#\fR")
are ignored.
.Pp
Settings are implemented by setting flags on the
.Nm gpm
command line; these are documented in
.Xr gpm 8 .
The following variable names are specified:
.Bl -tag
.It device
Specifies the device file for your primary mouse.  This sets
.Fl m .
.It type
Specifies the protocol for your primary mouse.  This sets
.Fl t .
.It device2, type2
The same as
.Va device
and
.Va type ,
but for your secondary mouse.  These set
.Fl m
and
.Fl t
after passing
.Fl M .
If either of these are defined, both must be.
.It responsiveness
Specifies the responsiveness for your primary mouse.  This sets
.Fl r .
.It sample_rate
Specifies the sample rate for your primary mouse.  This sets
.Fl s .
.It repeat_type
Enables the
.Nm gpm
repeater and sets the repeater protocol, using the
.Fl R
flag.  Repeat type
.Va none
or an empty value will disable the repeater.
.It append
Any options specified here are appended to the
.Nm gpm
command line.  If you use multiple options, you will need to enclose
the value in quotes ("").
.El
.\"
.Sh EXAMPLES
.Pp
A simple
.Nm
file for a PS/2 mouse whose protocol should be autodetected, and which
should be repeated in
.Pa /dev/gpmdata
as a serial Microsoft Intellimouse:
.Bd -literal -offset indent
# Sample gpm.conf

device=/dev/psaux
type=autops2
repeat_type=ms3
.Ed
.Pp
This will cause the daemon to be started as
.Nm gpm Fl m Ar /dev/psaux Fl t Ar autops2 Fl Rms3 .
.\"
.Sh FILES
.Pa /etc/gpm.conf
.\"
.Sh SEE ALSO
.Xr gpm 8 ,
.Xr dpkg\-reconfigure 8 .
.Nm dpkg\-reconfigure Ar gpm
can be used to generate and update the
.Nm
file automatically.
