.TH bstyleconvert 1 "mars 17, 2005" "bstyleconvert" "X11"
.SH NAME
bstyleconvert \- a Blackbox style conversion utility
.SH SYNOPSIS
.B bstyleconvert
.IR "files" ...
.SH DESCRIPTION
.B Blackbox
0.70+ is committed to fully support the style syntax of previous versions,
thus allowing older styles to be loaded and used. 
However, if one of your favorite styles seems 'broken', you can try this utility.
.PP
.B
bstyleconvert
reads given old 
.B
Blackbox
style file(s) (<= 0.65) and produces according new style file(s), appending '\-new' to
original filename(s).
.br
.SH OPTIONS
This program does not support (nor need) any options.
.br
.SH SEE ALSO
.BR blackbox (1),
.BR bsetbg (1),
.BR bsetroot (1).
.br
.SH WEB SITES
.TP 5
.B The Blackbox Wiki site:
http://blackboxwm.sourceforge.net/
.TP 5
.B Blackbox styles documentation
http://blackboxwm.sourceforge.net/BlackboxDocumentation/BlackboxStyles
.br
.SH AUTHOR
.B
bstyleconvert
was written by Sean 'Shaleh' Perry <shaleh@debian.org> and Bradley T Hughes <bhughes at trolltech.com>.
.PP
This manual page was written by Mathieu Baeumler <mathieu.baeumler@gmail.com>,
for the Debian project (but may be used by others).
