Document: harfbuzz
Title: Debian harfbuzz Manual
Author: <insert document author here>
Abstract: This manual describes what harfbuzz is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/harfbuzz/harfbuzz.sgml.gz

Format: postscript
Files: /usr/share/doc/harfbuzz/harfbuzz.ps.gz

Format: text
Files: /usr/share/doc/harfbuzz/harfbuzz.text.gz

Format: HTML
Index: /usr/share/doc/harfbuzz/html/index.html
Files: /usr/share/doc/harfbuzz/html/*.html
