.\" $Id: kdm.options.5,v 1.2 2004/02/27 22:45:20 ccheney Exp $
.\"
.\" Copyright 1998, 2002, 2003 Branden Robinson <branden@debian.org>.
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; version 2.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License with
.\" the Debian operating system, in /usr/share/common-licenses/GPL;  if
.\" not, write to the Free Software Foundation, Inc., 59 Temple Place,
.\" Suite 330, Boston, MA 02111-1307 USA
.TH kdm.options 5 "2003\-09\-18" "Debian Project"
.SH NAME
kdm.options \- configuration options for X display manager
.SH DESCRIPTION
.I /etc/kde4/kdm/kdm.options
contains a set of flags that determine some of the behavior of the
X display manager
.BR kdm (1).
.PP
.I /etc/kde4/kdm/kdm.options
may contain comments, which begin with a hash mark and end at the next
newline, just like comments in shell scripts.  The rest of the file
consists of options which are expressed as words separated by hyphens, with
only one option per line.  If an option is present with the \(oqno\-\(cq
prefix, or absent, it is disabled, otherwise it is considered enabled.
.PP
Available options are:
.TP
.B ignore\-nologin
Normally, the contents of the /etc/nologin file will be displayed using
.BR xmessage (1x)
(if
.B xmessage
is available), and the user will be returned to the kdm login screen after
the xmessage is dismissed.  If this option is enabled, kdm starts a session
as usual (after the xmessage is dismissed, if xmessage is available).
.TP
.B restart\-on\-upgrade
Enable this option with caution on \(oqproduction\(cq machines; it causes
the kdm daemon to be stopped and restarted on upgrade, even if the process
has children (which means it is managing X sessions).  Typically when a
package that contains a daemon is being installed or upgraded, its
maintainer scripts stop a running daemon process before installing the new
binary, and restart it after the new binary is installed.  Stopping kdm
causes immediate termination of any sessions it manages; in some situations
this could be an unwelcome surprise (for instance, for remote kdm users who
had no idea the administrator was performing system maintenance).  On the
other hand, for machines that stay up for long periods of time, leaving the
old daemon running can be a bad idea if the new version has, for instance,
a fix for a security vulnerability (overwriting kdm's executable on the
file system has no effect on the copy of kdm in memory).  The kdm
pre\-removal script checks to see if the kdm process has any children; if
it does, it is possible that someone's session would be killed by stopping
kdm, so a warning is issued and an opportunity to abort the upgrade of kdm
is provided.  If this option is disabled (the Debian default), kdm will be
not be stopped or started during an install or upgrade; the administrator
will have to do so by hand (with \(oq/etc/init.d/kdm restart\(cq, or by
rebooting the system) before the newly installed kdm binary is used.
.PP
Users of older versions of the Debian system should note that the
\(oqrun\-xconsole\(cq option has been removed.  Shell scripts named
.I /etc/kde4/kdm/Xsetup
and
.I /etc/kde4/kdm/Xreset
can be edited to disable or modify the running of xconsole on the kdm
greeter screen; see the
.B kdm
manual page for more information.
.SH AUTHOR
This manpage was written by Branden Robinson for the Debian Project.
.SH SEE ALSO
.BR xmessage (1x),
.BR kdm (1x)
