bin/bib2xml    usr/bin
bin/biblatex2xml    usr/bin
bin/ebi2xml	    usr/bin
bin/copac2xml    usr/bin
bin/end2xml    usr/bin
bin/endx2xml    usr/bin
bin/isi2xml    usr/bin
bin/med2xml    usr/bin
bin/modsclean    usr/bin
bin/ris2xml    usr/bin
bin/wordbib2xml usr/bin
bin/xml2ads    usr/bin
bin/xml2bib    usr/bin
bin/xml2end    usr/bin
bin/xml2isi    usr/bin
bin/xml2ris    usr/bin
bin/xml2wordbib    usr/bin

