#! /bin/sh -e 

PROVIDED_MODELS="helmholtz navier-stokes resultoutput heatequation linearelasticity k-epsilon meshdeform advection-diffusion elasticplate electrostatics freesurface poissonboltzmann reynolds saveline savescalars statcurrent"

# Remove all possible file symlinks before removing package files
case "$1" in
    remove|purge)
	for model in $PROVIDED_MODELS; do
	    rm -f /usr/share/ElmerGUI/edf/$model.xml;
	done
	;;
    *)
    	;;
esac

#DEBHELPER#
