#! /bin/sh
set -e

if [ "$1" = "purge" ] ; then
  # remove empty/unused scorefiles
  SCORE_FILES="@SCORE_FILES@"

  for FILE in $SCORE_FILES; do
	rm -f /var/games/$FILE
  done

  if [ -d /var/games ]; then
	rmdir --ignore-fail-on-non-empty /var/games
  fi
fi

#DEBHELPER#
