#
# Digital Clock
#
etc/gconf/schemas/awn-applet-digital-clock.schemas
usr/lib/awn/applets/digital-clock/*.so
usr/share/avant-window-navigator/applets/digital-clock/
usr/share/avant-window-navigator/applets/digital-clock.desktop
usr/share/avant-window-navigator/schemas/awn-applet-digital-clock.schema-ini
usr/share/icons/hicolor/scalable/apps/awn-applet-digital-clock.svg
#
# Main menu
#
usr/lib/awn/applets/main-menu/*.so
usr/share/avant-window-navigator/applets/main-menu.desktop
#
# Places
#
usr/lib/awn/applets/places/*.so 
usr/share/avant-window-navigator/applets/places.desktop 
usr/share/avant-window-navigator/schemas/awn-applet-places.schema-ini
etc/gconf/schemas/awn-applet-places.schemas
#
# Sysmon
#
usr/share/avant-window-navigator/applets/sysmon.desktop
usr/share/avant-window-navigator/schemas/awn-applet-sysmon.schema-ini
usr/lib/awn/applets/sysmon/*.so
etc/gconf/schemas/awn-applet-sysmon.schemas
#
# Webapplet
#
usr/lib/awn/applets/webapplet/*.so
usr/share/avant-window-navigator/applets/webapplet.desktop
usr/share/avant-window-navigator/applets/webapplet/*.ini
usr/share/avant-window-navigator/applets/webapplet/icons/
usr/share/avant-window-navigator/schemas/awn-applet-webapplet.schema-ini
etc/gconf/schemas/awn-applet-webapplet.schemas
