#
# Calendar
#
etc/gconf/schemas/awn-applet-calendar.schemas
usr/share/avant-window-navigator/applets/calendar/
usr/share/avant-window-navigator/applets/calendar.desktop
usr/share/avant-window-navigator/schemas/awn-applet-calendar.schema-ini
#
# Media-icons
#
usr/share/avant-window-navigator/applets/media-icons/*.py
usr/share/avant-window-navigator/applets/media-icons/icons/*.svg
usr/share/avant-window-navigator/applets/media-icon-previous.desktop
usr/share/avant-window-navigator/applets/media-icon-next.desktop
usr/share/avant-window-navigator/applets/media-icons.desktop
#
# Pandora
#
usr/share/avant-window-navigator/applets/pandora/
usr/share/avant-window-navigator/applets/pandora.desktop
etc/gconf/schemas/awn-applet-pandora.schemas
usr/share/avant-window-navigator/schemas/awn-applet-pandora.schema-ini
#
# SlickSwitcher
#
usr/share/avant-window-navigator/applets/slickswitcher/
usr/share/avant-window-navigator/applets/slickswitcher.desktop
etc/gconf/schemas/awn-applet-slickswitcher.schemas
usr/share/avant-window-navigator/schemas/awn-applet-slickswitcher.schema-ini
#
# Tomboy
#
usr/share/avant-window-navigator/applets/tomboy-applet/
usr/share/avant-window-navigator/applets/tomboy-applet.desktop
#
# YAMA
#
usr/share/avant-window-navigator/applets/yama/
usr/share/avant-window-navigator/applets/yama.desktop

