#
# Animal farm
#
usr/share/avant-window-navigator/applets/animal-farm/*.py
usr/share/avant-window-navigator/applets/animal-farm/icons/*.svg
usr/share/avant-window-navigator/applets/animal-farm.desktop
#
# Bandwidth-monitor
#
etc/gconf/schemas/awn-applet-bandwidth-monitor.schemas
usr/share/avant-window-navigator/applets/bandwidth-monitor/*.py
usr/share/avant-window-navigator/applets/bandwidth-monitor/*.ui
usr/share/avant-window-navigator/applets/bandwidth-monitor/images/*.png
usr/share/avant-window-navigator/applets/bandwidth-monitor.desktop
usr/share/avant-window-navigator/schemas/awn-applet-bandwidth-monitor.schema-ini
#
# Battery
#
etc/gconf/schemas/awn-applet-battery.schemas
usr/share/avant-window-navigator/applets/battery/*.py
usr/share/avant-window-navigator/applets/battery/*.ui
usr/share/avant-window-navigator/applets/battery/themes/*/*.svg
usr/share/avant-window-navigator/applets/battery.desktop
usr/share/avant-window-navigator/schemas/awn-applet-battery.schema-ini
#
# Cairo-clock
#
etc/gconf/schemas/awn-applet-cairo-clock.schemas
usr/share/avant-window-navigator/applets/cairo-clock/
usr/share/avant-window-navigator/applets/cairo-clock/themes/*/*.svg
usr/share/avant-window-navigator/applets/cairo-clock.desktop
usr/share/avant-window-navigator/schemas/awn-applet-cairo-clock.schema-ini
#
# Comics
#
etc/gconf/schemas/awn-applet-comics.schemas
usr/share/avant-window-navigator/applets/comics/*.py
usr/share/avant-window-navigator/applets/comics/feeds/
usr/share/avant-window-navigator/applets/comics/feed/
usr/share/avant-window-navigator/applets/comics/ui/
usr/share/avant-window-navigator/applets/comics/icons/
usr/share/avant-window-navigator/applets/comics.desktop
usr/share/avant-window-navigator/schemas/awn-applet-comics.schema-ini
usr/share/avant-window-navigator/applets/comics/comics.sh
#
# CPU Freq
#
etc/gconf/schemas/awn-applet-cpufreq.schemas
usr/share/avant-window-navigator/applets/cpufreq/
usr/share/avant-window-navigator/applets/cpufreq.desktop
usr/share/avant-window-navigator/schemas/awn-applet-cpufreq.schema-ini
#
# Dialect
#
etc/gconf/schemas/awn-applet-dialect.schemas
usr/share/avant-window-navigator/applets/dialect/
usr/share/avant-window-navigator/applets/dialect.desktop
usr/share/avant-window-navigator/schemas/awn-applet-dialect.schema-ini
#
# Feeds
#
etc/gconf/schemas/awn-applet-feeds.schemas
usr/share/avant-window-navigator/applets/feeds/
usr/share/avant-window-navigator/applets/feeds/*.py
usr/share/avant-window-navigator/applets/feeds/icons/*.svg
usr/share/avant-window-navigator/applets/feeds.desktop
usr/share/avant-window-navigator/schemas/awn-applet-feeds.schema-ini
#
# File-browser-launcher
#
etc/gconf/schemas/awn-applet-file-browser-launcher.schemas
usr/share/avant-window-navigator/applets/file-browser-launcher/*.py
usr/share/avant-window-navigator/applets/file-browser-launcher.desktop
usr/share/avant-window-navigator/schemas/awn-applet-file-browser-launcher.schema-ini
#
# Hardware sensors
#
etc/gconf/schemas/awn-applet-hardware-sensors.schemas
usr/share/avant-window-navigator/applets/hardware-sensors/
usr/share/avant-window-navigator/applets/hardware-sensors.desktop
usr/share/avant-window-navigator/schemas/awn-applet-hardware-sensors.schema-ini
#
# Mail
#
usr/share/avant-window-navigator/applets/mail/
usr/share/avant-window-navigator/applets/mail.desktop
etc/gconf/schemas/awn-applet-mail.schemas
usr/share/avant-window-navigator/schemas/awn-applet-mail.schema-ini
#
# Media Player
#
etc/gconf/schemas/awn-applet-media-player.schemas
usr/share/avant-window-navigator/applets/media-player/*.py
usr/share/avant-window-navigator/applets/media-player/*.ui
usr/share/avant-window-navigator/applets/media-player/icons/*.png
usr/share/avant-window-navigator/applets/media-player.desktop
usr/share/avant-window-navigator/schemas/awn-applet-media-player.schema-ini
#
# Media-control
#
etc/gconf/schemas/awn-applet-media-control.schemas
usr/share/avant-window-navigator/applets/media-control/*.py
usr/share/avant-window-navigator/applets/media-control/*.ui
usr/share/avant-window-navigator/applets/media-control/icons/*.svg
usr/share/avant-window-navigator/applets/media-control.desktop
usr/share/avant-window-navigator/schemas/awn-applet-media-control.schema-ini
#
# Mount
#
etc/gconf/schemas/awn-applet-mount.schemas
usr/share/avant-window-navigator/applets/mount/*.py
usr/share/avant-window-navigator/applets/mount/*.ui
usr/share/avant-window-navigator/applets/mount/icons/*.png
usr/share/avant-window-navigator/applets/mount.desktop
usr/share/avant-window-navigator/schemas/awn-applet-mount.schema-ini
#
# Stack
#
etc/gconf/schemas/awn-applet-stacks.schemas
usr/share/avant-window-navigator/applets/stacks/
usr/share/avant-window-navigator/applets/stacks.desktop
usr/share/avant-window-navigator/schemas/awn-applet-stacks.schema-ini
#
# Quit
#
etc/gconf/schemas/awn-applet-quit.schemas
usr/share/avant-window-navigator/applets/quit/*.py
usr/share/avant-window-navigator/applets/quit*.desktop
usr/share/avant-window-navigator/schemas/awn-applet-quit.schema-ini
#
# Thinkhdaps
#
usr/share/avant-window-navigator/applets/thinkhdaps/
usr/share/avant-window-navigator/applets/thinkhdaps.desktop
#
# Todo
#
etc/gconf/schemas/awn-applet-to-do.schemas
usr/share/avant-window-navigator/applets/to-do/
usr/share/avant-window-navigator/applets/to-do.desktop
usr/share/avant-window-navigator/schemas/awn-applet-to-do.schema-ini
#
# Volume-control
#
etc/gconf/schemas/awn-applet-volume-control.schemas
usr/share/avant-window-navigator/applets/volume-control/
usr/share/avant-window-navigator/applets/volume-control.desktop
usr/share/avant-window-navigator/schemas/awn-applet-volume-control.schema-ini
#
# Weather
#
etc/gconf/schemas/awn-applet-weather.schemas
usr/share/avant-window-navigator/applets/weather/
usr/share/avant-window-navigator/applets/weather.desktop
usr/share/avant-window-navigator/schemas/awn-applet-weather.schema-ini
