#
#Awn system monitor
#
usr/share/avant-window-navigator/applets/awnsystemmonitor.desktop
usr/lib/awn/applets/awnsystemmonitor/*.so
etc/gconf/schemas/awnsystemmonitor.schemas
#
#Awn Terminal
#
usr/lib/awn/applets/awnterm/*.so
usr/share/avant-window-navigator/applets/awnterm.desktop
usr/share/avant-window-navigator/schemas/awn-applet-awnterm.schema-ini
etc/gconf/schemas/awn-applet-awnterm.schemas
#
#Cairo menu
#
usr/share/avant-window-navigator/applets/cairo-menu.desktop
usr/lib/awn/applets/cairo-menu/*.so
etc/gconf/schemas/awn-applet-cairo-menu.schemas
usr/share/avant-window-navigator/schemas/awn-applet-cairo-menu.schema-ini
#
# Notification area
#
etc/gconf/schemas/awn-applet-notification-area.schemas
usr/lib/awn/applets/notification-area/*.so
usr/share/avant-window-navigator/applets/notification-area.desktop
usr/share/avant-window-navigator/applets/notification-area/
usr/share/avant-window-navigator/schemas/awn-applet-notification-area.schema-ini
usr/share/icons/hicolor/scalable/apps/notification-area.svg
#
#Notification daemon
#
etc/gconf/schemas/awn-applet-notification-daemon.schemas
usr/share/avant-window-navigator/schemas/awn-applet-notification-daemon.schema-ini
usr/share/avant-window-navigator/applets/notification-daemon.desktop
usr/lib/awn/applets/notification-daemon/*.so
etc/gconf/schemas/awn-applet-notification-daemon.schemas
#
#Shiny Switcher
#
usr/lib/awn/applets/shinyswitcher/*.so
usr/share/avant-window-navigator/applets/shinyswitcher.desktop
usr/share/avant-window-navigator/schemas/awn-applet-shinyswitcher.schema-ini
etc/gconf/schemas/awn-applet-shinyswitcher.schemas
usr/share/avant-window-navigator/applets/shinyswitcher/shiny-prefs.py
usr/share/avant-window-navigator/applets/shinyswitcher/*.ui
#
# Show Desktop
#
usr/lib/awn/applets/showdesktop/*.so
usr/share/avant-window-navigator/applets/showdesktop.desktop
#
# Garbage
#
usr/lib/awn/applets/garbage/*.so 
usr/share/avant-window-navigator/applets/garbage.desktop 
usr/share/avant-window-navigator/schemas/awn-applet-garbage.schema-ini
etc/gconf/schemas/awn-applet-garbage.schemas
