#!/bin/sh

set -e

#  This file was shipped by eperl (<= 2.2.14-7), but since 2.2.14-8
#  users are encouraged to put a symlink to /usr/bin/eperl if they
#  need CGI scripting.  This link is removed when uninstalling eperl.
cgi_nph_eperl=/usr/lib/cgi-bin/nph-eperl

#  This file is managed by postinst, so remove it too.
cgi_suid_eperl=/usr/lib/cgi-bin/suideperl

[ "$1" = "remove" ] && [ -L $cgi_nph_eperl ] && rm -f $cgi_nph_eperl
[ "$1" = "remove" ] && [ -f $cgi_suid_eperl ] && rm -f $cgi_suid_eperl

#DEBHELPER#

exit 0
