.TH wicd-cli 8 "Dec 2009"
.SH NAME
wicd-cli \- command-line interface to wicd
.SH SYNOPSIS
.B wicd-cli
.RI [ options ]
.SH DESCRIPTION
This manual page documents briefly the \fBwicd-cli\fP command.
.PP
\fBwicd-cli\fP is a scriptable command-line only "client" for \fBwicd\fP.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show summary of options.
.TP
\fB\-n \fInetwork-id\fB, \-\-network=\fInetwork-id\fR
Specify which network \fBwicd-cli\fR should act on.
.TP
\fB\-p \fIproperty\fB, \-\-network\-property=\fIproperty\fR
Show \fIproperty\fR from network details.
.TP
\fB\-s \fIvalue\fB, \-\-set\-to=\fIvalue\fR
Set selected \fIproperty\fR to \fIvalue\fR
.TP
\fB\-m \fIname\fR, \fB\-\-name=\fIname\fR
Set the name for the profile to load/save to \fIname\fR.
.TP
.B \-S, \-\-scan
Scan available wireless networks.
.TP
.B \-w, \-\-save
Save the network connection profile.
.TP
.B \-l, \-\-list\-networks
List the networks WICD has in its cache.
.TP
.B \-d, \-\-network\-details
Show details of selected network.
.TP
.B \-x, \-\-disconnect
Disconnect from the current network.
.TP
.B \-c, \-\-connect
Connect to the selected network.
.TP
.B \-e, \-\-list\-encryption\-types
View the available encryption templates WICD can use.
.TP
.B \-y, \-\-wireless
Use the wireless interface.
.TP
.B \-z, \-\-wired
Use the wired interface.
.TP
.B \-o, \-\-load\-profile
Load a wired connection profile.
.SH SEE ALSO
.BR wicd (1),
.BR wicd-client (1),
.BR wicd-gtk (8),
.BR wicd-curses (8)
.SH AUTHOR
wicd-cli was written by Ronuk Raval.
.PP
This manual page was written by David Paleino <dapal@debian.org>,
for the Debian project (and may be used by others).
