debian/tmp/usr/bin/qemu-alpha-static
debian/tmp/usr/bin/qemu-armeb-static
debian/tmp/usr/bin/qemu-arm-static
debian/tmp/usr/bin/qemu-cris-static
debian/tmp/usr/bin/qemu-i386-static
debian/tmp/usr/bin/qemu-m68k-static
debian/tmp/usr/bin/qemu-microblaze-static
debian/tmp/usr/bin/qemu-microblazeel-static
debian/tmp/usr/bin/qemu-mipsel-static
debian/tmp/usr/bin/qemu-mips-static
debian/tmp/usr/bin/qemu-ppc64abi32-static
debian/tmp/usr/bin/qemu-ppc64-static
debian/tmp/usr/bin/qemu-ppc-static
debian/tmp/usr/bin/qemu-s390x-static
debian/tmp/usr/bin/qemu-sh4eb-static
debian/tmp/usr/bin/qemu-sh4-static
debian/tmp/usr/bin/qemu-sparc32plus-static
debian/tmp/usr/bin/qemu-sparc64-static
debian/tmp/usr/bin/qemu-sparc-static
debian/tmp/usr/bin/qemu-unicore32-static
debian/tmp/usr/bin/qemu-x86_64-static
debian/qemu-debootstrap usr/sbin
debian/overrides/qemu-user-static usr/share/lintian/overrides/
