debian/qemu-ifup etc/
debian/tmp/usr/bin/qemu-system-alpha
debian/tmp/usr/bin/qemu-system-arm
debian/tmp/usr/bin/qemu-system-cris
debian/tmp/usr/bin/qemu-system-i386
debian/tmp/usr/bin/qemu-system-lm32
debian/tmp/usr/bin/qemu-system-m68k
debian/tmp/usr/bin/qemu-system-microblaze
debian/tmp/usr/bin/qemu-system-microblazeel
debian/tmp/usr/bin/qemu-system-mips
debian/tmp/usr/bin/qemu-system-mips64
debian/tmp/usr/bin/qemu-system-mips64el
debian/tmp/usr/bin/qemu-system-mipsel
debian/tmp/usr/bin/qemu-system-ppc
debian/tmp/usr/bin/qemu-system-ppc64
debian/tmp/usr/bin/qemu-system-ppcemb
debian/tmp/usr/bin/qemu-system-s390x
debian/tmp/usr/bin/qemu-system-sh4
debian/tmp/usr/bin/qemu-system-sh4eb
debian/tmp/usr/bin/qemu-system-sparc
debian/tmp/usr/bin/qemu-system-sparc64
debian/tmp/usr/bin/qemu-system-x86_64
debian/tmp/usr/bin/qemu-system-xtensa
debian/tmp/usr/bin/qemu-system-xtensaeb
debian/tmp/usr/share/man/man1/qemu.1
debian/tmp/usr/share/qemu/*.dtb
pc-bios/qemu-icon.bmp /usr/share/qemu/
