Welcome to Debian GNU/Linux ${DEBIAN_VERSION}!

This is a Debian installation ${MEDIA_TYPE},
built on ${BUILD_DATE}.

Enter one of the following options to begin:

install     32-bit processor (G4 or earlier)
install64   64-bit processor (G5 or IBM POWER3/4/5)
expert      expert mode on 32-bit processor
expert64    expert mode on 64-bit processor

If the system fails to boot at all (the typical
symptom is a white screen which doesn't go away),
add 'video=ofonly'.

Press the Tab key for a full list of options, or enter
'help' for help.
