<?xml version="1.0"?>

<xsl:stylesheet version="1.0"
xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

<xsl:template match="/">
  <html>
	<head>
<style type="text/css" media="screen">
html { background: #000; margin: auto;}
.disclose { font-weight: bold; font-size: .75em; margin: auto; max-width: 30em; border: 1px solid #ccc;}
table { background-color: #ddd; margin: auto; border: 1px solid #000; overflow: hidden;}
caption { color: #fff; }
a:link { color: #D8D8D8; }
a:visited { color: #D8D8D8; }
th { border: 1px solid #000; }
td { overflow: hidden; }
.pn { max-width: 15em; font-weight: bold; border: 1px solid #000; background-color: lightgreen; }
.psprezz { max-width: 10em; font-weight: bold; background-color: #9999FF; }
.psprezzh { font-weight: bold; background-color: #9999FF; }
.pdebu { max-width: 10em; background-color: lightblue; }
.pdebt { max-width: 10em; background-color: #FFFFCC; }
.pur { max-width: 10em; font-weight: bold; background-color: #996600; }
.purh { font-weight: bold; background-color: #996600; }
.puq { max-width: 10em; font-weight: bold; background-color: salmon; }
.puqold { max-width: 10em; background-color: salmon; }
</style>
<script type="text/javascript">
<!--
var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-28599323-1']);
_gaq.push(['_setDomainName', 'sprezzos.com']);
_gaq.push(['_trackPageview']);
(function() {
	var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
//-->
</script>
	</head>
  <body>

	  <center><a href="https://www.sprezzatech.com/wiki/index.php/SprezzOS_1"><img src="http://sprezzos.com/sprezzos-banner.png" alt="Download SprezzOS 1 today!" /></a></center>
<br /><table>
<caption>
	<h2> APT distributions' package version matrix</h2>
	<h3>Last updated: </h3>
<br /><br /><div class="disclose">
Full disclosure: this table is generated by, and in the interests of, <a href="http://www.sprezzatech.com">Sprezzatech</a>
and <a href="http://www.sprezzos.com">The SprezzOS Project</a>, even though it
will probably be of direct use to competing efforts, argh.
Mail <a href="mailto:nick.black@sprezzatech.com">Nick Black</a> with questions or comments.<br />
</div>
<br /><br /><table>
<caption>Legend</caption>

<tr><td class="pdebu">
				Debian Unstable feeds SprezzOS and Ubuntu Raring, and spawned Debian Wheezy.
			</td></tr>
<tr><td class="psprezzh">
				SprezzOS modifies and/or updates some packages.
			</td></tr>
<tr><td class="purh">
				Ubuntu Raring modifies and/or updates some packages, and spawned Ubuntu Quantal.
			</td></tr>
<tr><td class="pdebt">
				Debian Wheezy has some old packages (relative to Unstable).
			</td></tr>
<tr><td class="puq">

				Ubuntu Quantal has some modified packages.
			</td></tr>
<tr><td class="puqold">
				Ubuntu Quantal also has some packages that are just old, their raring days long gone.
			</td></tr>
</table>
<br /><br />
</caption>
<tr bgcolor="#9acd32">
<th>Package</th>
 <th class="psprezzh">SprezzOS 1</th>
 <th class="debu">Debian Unstable</th>
 <th class="debt">Debian Wheezy</th>
 <th class="purh">Ubuntu Raring</th>
 <th class="puqold">Ubuntu Quantal</th>
</tr>
      <xsl:for-each select="//tr">
	<xsl:sort select="td[1]" />
        <tr class="pr">
		<td class="pn">
		<xsl:value-of select="./td[1]"/>
		</td>
		<xsl:if test="contains(./td[2], 'SprezzOS')">
		<td class="psprezz">
			<xsl:value-of select="./td[2]"/>
		</td>
		</xsl:if>
		<xsl:if test="not(contains(./td[2], 'SprezzOS'))">
		<td class="pdebu">
			<xsl:value-of select="./td[2]"/>
		</td>
		</xsl:if>

		<xsl:if test="./td[3] = ''">
			<td/>
		</xsl:if>
		<xsl:if test="./td[3] != ''">
		<td class="pdebu">
			<xsl:value-of select="./td[3]"/>
		</td>
		</xsl:if>

		<xsl:if test="./td[4] = ''">
			<td/>
		</xsl:if>
		<xsl:if test="./td[4] != ''">
			<xsl:if test="./td[3] = ./td[4]">
			<td class="pdebu">
				<xsl:value-of select="./td[4]"/>
			</td>
			</xsl:if>
			<xsl:if test="./td[3] != ./td[4]">
			<td class="pdebt">
				<xsl:value-of select="./td[4]"/>
			</td>
			</xsl:if>
		</xsl:if>

		<xsl:if test="./td[5] = ''">
			<td/>
		</xsl:if>
		<xsl:if test="./td[5] != ''">
			<xsl:if test="contains(./td[5], 'ubuntu')">
			<td class="pur">
				<xsl:value-of select="./td[5]"/>
			</td>
			</xsl:if>
			<xsl:if test="not(contains(./td[5], 'ubuntu'))">
			<td class="pdebu">
				<xsl:value-of select="./td[5]"/>
			</td>
			</xsl:if>
		</xsl:if>

		<xsl:if test="./td[6] = ''">
			<td/>
		</xsl:if>
		<xsl:if test="./td[6] != ''">
			<xsl:if test="contains(./td[6], 'ubuntu')">
			<td class="puq">
				<xsl:value-of select="./td[6]"/>
			</td>
			</xsl:if>
			<xsl:if test="not(contains(./td[6], 'ubuntu'))">
				<xsl:if test="./td[3] = ./td[6]">
					<td class="pdebu">
					<xsl:value-of select="./td[6]"/>
					</td>
				</xsl:if>
				<xsl:if test="./td[3] != ./td[6]">
					<td class="puqold">
					<xsl:value-of select="./td[6]"/>
					</td>
				</xsl:if>
			</xsl:if>
		</xsl:if>

        </tr>
      </xsl:for-each>
    </table>
<center>
	<br />
	<br />
	<a href="https://www.sprezzatech.com/wiki/index.php/SprezzOS_1"><img src="http://sprezzos.com/sprezzos-banner.png" alt="Download SprezzOS 1 today!"/></a>
</center>
  </body>
  </html>
</xsl:template>

</xsl:stylesheet> 
