/usr/share/apache2/icons/
/usr/share/apache2/error/
/usr/share/apache2/default-site/htdocs/index.html	/usr/share/apache2/build
debian/icons/*.png		/usr/share/apache2/icons
/usr/sbin/envvars-std           /usr/share/apache2/build
/usr/sbin/envvars		/usr/share/apache2/build
/usr/sbin/apachectl		/usr/share/apache2/build
/usr/lib/cgi-bin/printenv.*	/usr/share/apache2/build
debian/index.html		/usr/share/apache2/default-site/
