usr/lib/*/pkgconfig
usr/lib/*/libpst*.so
usr/lib/*/libpst*.a
usr/include/libpst-4
usr/share/doc/libpst-*/devel usr/share/doc/libpst-dev/
usr/share/man/man5
usr/share/doc/*/*.html usr/share/doc/libpst-dev/
usr/share/doc/*/ChangeLog usr/share/doc/libpst-dev/
usr/share/doc/*/AUTHORS usr/share/doc/libpst-dev/
usr/share/doc/*/COPYING usr/share/doc/libpst-dev/
usr/share/doc/*/README usr/share/doc/libpst-dev/
usr/share/doc/*/NEWS usr/share/doc/libpst-dev/
