.TH HWCLOCK 5 "Feb 2012" "" "Debian Administrator's Manual"
.SH NAME
hwclock \- variables that affect the behaviour of the hwclock boot script
.SH DESCRIPTION
The
.I /etc/default/rcS
file contains variable settings in POSIX format:
.IP "" .5i
VAR=VAL
.PP
Only one assignment is allowed per line.
Comments (starting with '#') are also allowed.

.SH OPTIONS
The following variables can be set.

.IP \fBBADYEAR\fP
This is used to specify that the hardware clock is incapable of storing
years outside the range of 1994-1999.  Set to \fByes\fP if the hardware is
broken or \fBno\fP if working correctly.

.IP \fBHWCLOCKACCESS\fP
If the hardware clock is not accessible, set to \fBno\fP, in which
case hwclock will not be run.  Otherwise, set to \fByes\fP.

.IP \fBHWCLOCKPARS\fP
Additional options for hwclock.  Unset by default.  For example, this
may be use to specify the machine hardware clock type for Alphas.

.IP \fBHCTOSYS_DEVICE\fP
The hardware clock device you want to use.  Defaults to \fBrtc0\fP.
It should probably match the CONFIG_RTC_HCTOSYS_DEVICE kernel config
option.

.SH AUTHOR
Roger Leigh <rleigh@debian.org>

.SH SEE ALSO
.BR hwclock (8),
.BR rcS (5).
