#!/bin/sh
set -e
test "$1" = configure || exit 0
/usr/lib/emacsen-common/emacs-package-install git

# Clean up after 1:1.7.4.1-1 through 1:1.7.4.1-3.
! test -L /usr/share/git-core/emacs/emacs ||
rm -f /usr/share/git-core/emacs/emacs
! test -L /usr/share/doc/git/contrib/emacs.old ||
rm -f /usr/share/doc/git/contrib/emacs.old

# Replace the old /usr/share/doc/git/contrib/emacs directory
# with a symlink.
test -z "$2" &&
! test -L /usr/share/doc/git/contrib/emacs &&
test -d /usr/share/doc/git/contrib/emacs || exit 0

if ! rmdir /usr/share/doc/git/contrib/emacs; then
  echo Moving /usr/share/doc/git/contrib/emacs to emacs.old >&2
  mv -f /usr/share/doc/git/contrib/emacs /usr/share/doc/git/contrib/emacs.old
fi
ln -s ../../../git-core/emacs /usr/share/doc/git/contrib/emacs
