#!/bin/sh
set -e

case "$1" in
    configure)
        if [ -x /etc/init.d/apache2 ]
        then
            if which /usr/sbin/invoke-rc.d >/dev/null 2>&1
            then
                invoke-rc.d apache2 reload || true
            else
                /etc/init.d/apache2 reload || true
            fi
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
