'\" t
.\"     Title: BLUEZ-SIMPLE=AGENT
.\"    Author: Nobuhiro Iwamatsu <iwamatsu@nigauri.org>
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 09/09/2010
.\"    Manual: bluez-simple-agent
.\"    Source: http://bluez.org
.\"  Language: English
.\"
.TH "BLUEZ\-SIMPLE=AGENT" "1" "09/09/2010" "http://bluez\&.org" "bluez-simple-agent"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
bluez-simple-agent \- A PIN management and agent program for pairing to Bluetooth device\&.
.SH "SYNOPSIS"
.HP \w'\fBbluez\-simple\-agent\ [<hciX>]\ [<bdaddr>]\ [remove]\fR\ 'u
\fBbluez\-simple\-agent [<hciX>] [<bdaddr>] [remove]\fR
.SH "DESCRIPTION"
.PP
bluez\-simple\-agent is pass agent program for bluetooth\&.
.SH "OPTIONS"
.PP
\fB<hciX>\fR
.RS 4
The command is applied to device hciX , which must be the name of an installed Blue\(hy tooth device\&. If not specified, the command will be sent to the first available Blue\(hy tooth device\&.
.RE
.PP
\fB<bdaddr>\fR
.RS 4
bdaddr of device doing pairing\&.
.RE
.PP
\fBremove\fR
.RS 4
Remove intended bdaddr from database\&.
.RE
.SH "AUTHOR"
.PP
\fBNobuhiro Iwamatsu\fR <\&iwamatsu@nigauri\&.org\&>
.RS 4
Wrote this manpage for the Debian system\&.
.RE
