.TH BLUETOOTH-AGENT "1" "March 2010"
.SH NAME
bluetooth-agent \- Bluetooth pass agent
.SH SYNOPSIS
.B bluetooth-agent
.SH DESCRIPTION
\fBBluetooth-agent\fP is pass agent program for bluetooth.

.SH USAGE
.TP
bluetooth-agent [\fB--adapter\fP adapter-path] [\fB--path\fP agent-path] <passkey> [<device>]
.SH AUTHOR
This manual page was written by Nobuhiro Iwamatsu <iwamatsu@debian.org>,
for the Debian GNU/Linux system (but may be used by others).

