.TH GMIME-UUDECODE "1" "January 2012" "gmime-uudecode - GMime 2.6.4" "User Commands"
.SH NAME
gmime-uudecode \- decode a uuencoded stream to its binary form
.SH SYNOPSIS
.B gmime-uudecode
[\fIoptions\fR] [ \fIfile \fR]...
.SH DESCRIPTION
gmime-uudecode decodes one or more \fIfile\fRs from their form as a
uuencoded text stream, and writes them to the filesystem, setting
their modes as indicated in the stream.  If no \fIfile\fR is
specified, gmime-uudecode reads from standard input.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
display help and exit
.TP
\fB\-v\fR, \fB\-\-version\fR
display version and exit
.TP
\fB\-o\fR, \fB\-\-output\-file\fR=\fIFILE\fR
output to FILE instead of the filename indicated by the stream
.SH AUTHOR
gmime-uudecode was written by Jeffrey Stedfast.  This manual page was
written by Daniel Kahn Gillmor for the Debian Project (with the
assistance of help2man), but may be used by others.
.SH LICENSE
gmime-uuencode and this manual page are both licensed under the LGPL,
version 2.1 or later.  On Debian systems, please see
/usr/share/common-licenses/LGPL-2.1
.SH "SEE ALSO"
.BR gmime\-uuencode (1)
