.TH GMIME-UUENCODE "1" "January 2012" "gmime-uuencode - GMime 2.6.4" "User Commands"
.SH NAME
gmime-uuencode \- encode a binary file to a text stream
.SH SYNOPSIS
.B gmime-uuencode
[\fIoptions\fR] [ \fIfile \fR] \fIname\fR
.SH DESCRIPTION
gmime-uuencode encodes \fIfile\fR to a text stream and emits that
stream to standard output.  If \fIfile\fR is not indicated on the
command line, gmime-uuencode reads from standard input instead.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
display help and exit
.TP
\fB\-v\fR, \fB\-\-version\fR
display version and exit
.TP
\fB\-m\fR, \fB\-\-base64\fR
use RFC1521 base64 encoding
.SH AUTHOR
gmime-uuencode was written by Jeffrey Stedfast.  This manual page was
written by Daniel Kahn Gillmor for the Debian Project (with the
assistance of help2man), but may be used by others.
.SH LICENSE
gmime-uuencode and this manual page are both licensed under the LGPL,
version 2.1 or later.  On Debian systems, please see
/usr/share/common-licenses/LGPL-2.1
.SH "SEE ALSO"
.BR gmime\-uudecode (1)
