.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH GNOME-PAINT 1 "June 15, 2010"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
gnome-paint \- simple, easy-to-use paint program for GNOME
\fB
.RE
\fB
.SH SYNOPSIS
.nf
.fam C
\fBgnome-paint\fP

.fam T
.fi
.fam T
.fi
.SH DESCRIPTION
This manual page documents briefly the
.B gnome-paint
commands.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBgnome-paint\fP is a program inspired by MS Paint and designed 
for GNOME (and maybe other) desktop environment.  It could be used to 
manipulate images in a very simple way.

.SH AUTHOR
gnome-paint was written by Rogério Ferro do Nascimento (rogerio) 
<rogerioferro@gmail.com>.
.PP
This manual page was written by Aron Xu <happyaron.xu@gmail.com>,
for the Debian project (and may be used by others).
