#!/bin/sh

CAMOMILE_VERSION=$2
ORIG=$1

set -e 

TMPFILE=`tempfile -s .tar`

bzip2 -dc $ORIG > $TMPFILE

#tar --delete -f $TMPFILE camomile-$CAMOMILE_VERSION/unidata/UnicodeData.txt

gzip -c $TMPFILE > ${ORIG%%-$CAMOMILE_VERSION.tar.bz2}_$CAMOMILE_VERSION.orig.tar.gz
