.TH "BASHBUG" "1" "11 December 2007" "GNU Bash 3\.1" "bashbug"
.nh
.ad l
.SH "NAME"
bashbug - report a bug in bash
.SH "SYNOPSIS"
.HP 8
\fBbashbug\fR [\fB\-\-help\fR] [\fB\-\-version\fR] [\fB\fIbug\-report\-email\-addresses\fR\fR]
.SH "DESCRIPTION"
.PP

\fBbashbug\fR
is a utility for reporting bugs in Bash to the maintainers\.
.PP

\fBbashbug\fR
will start up your preferred editor with a preformatted bug report template for you to fill in\. Save the file and quit the editor once you have completed the missing fields\.
\fBbashbug\fR
will notify you of any problems with the report and ask for confirmation before sending it\. By default the bug report is mailed to both the GNU developers and the Debian Bash maintainers\. The recipients can be changed by giving a comma separated list of
\fIbug\-report\-email\-addresses\fR\.
.PP
If you invoke
\fBbashbug\fR
by accident, just quit your editor\. You will always be asked for confirmation before a bug report is sent\.
.SH "OPTIONS"
.PP
.PP
\fB\-\-help\fR
.RS
Show a brief usage message and exit\.
.RE
.PP
\fB\-\-version\fR
.RS
Show the version of
\fBbashbug\fR
and exit\.
.RE
.PP
\fBbug\-report\-email\-addresses\fR
.RS
Comma separated list of recipients\' email addresses\. By default the report is mailed to both the GNU developers and the Debian Bash maintainers\.
.RE
.SH "ENVIRONMENT"
.PP
.PP
\fBDEFEDITOR\fR
.RS
Editor to use for editing the bug report\.
.RE
.PP
\fBEDITOR\fR
.RS
Editor to use for editing the bug report (overridden by
\fBDEFEDITOR\fR)\.
.RE
.SH "SEE ALSO"
.PP

\fBbash\fR(1),
\fBreportbug\fR(1),
\fBupdate-alternatives\fR(8)
for preferred editor\.
.SH "AUTHOR"
.PP
This manual page was written by Christer Andersson
<klamm@comhem\.se>
for the Debian project (but may be used by others)\.
