#!/bin/sh

#DEBHELPER#

if [ "$1" = "purge" ]; then
	rm -f /etc/bind/rndc.key /etc/default/bind9
	rmdir /etc/bind >/dev/null 2>&1 || true
	rm -f /etc/apparmor.d/force-complain/usr.sbin.named >/dev/null 2>&1 || true
	rmdir /var/lib/bind
	# delete bind daemon user, if it exists
	if getent passwd bind > /dev/null ; then
	    echo "Deleting bind user"
	    deluser  --quiet bind > /dev/null || true
	fi
fi
