.\"
.\" Created by Torsten Marek <shlomme@debian.org>

.TH PYLUPDATE4 1 "2007/07/31" "pylupdate 4.3"
.SH NAME
pylupdate4 \- create or update Qt Linguist translation files for PyQt4 applications
.SH SYNOPSIS
.B pylupdate4
[\fIOPTION\fR]... \fIPROJECT-FILE\fR
.br
.B pylupdate4
[\fIOPTION\fR]... \fISOURCE\fR... \fB\-ts\fR \fITRANSLATION-FILE\fR...
.SH DESCRIPTION
.B pylupdate4
reads a qmake project file (.pro), finds the translatable strings in the specified sources and updates the  translation files (.ts  files) specified in it. The translation files are given to the translator who can use Qt Linguist to read the files and insert the translations.
.br
The .ts file format is a simple human-readable XML format that can be used with version control systems if required.

.SH OPTIONS
.TP
\fB\-help\fR
Show a summary of the options.
.TP
.B \-version
Display the version number of pylupdate4 of the version of Qt which PyQt4 was generated for.
.TP
.B \-noobsolete
Drop all obsolete strings.
.TP 
.B \-verbose
Increase verbosity.

.SH AUTHOR
This manual page was written for Debian GNU/Linux by and Torsten Marek <shlomme@debian.org>, but may freely be used by others.
