'\" t
.\" ** The above line should force tbl to be a preprocessor **
.\" Man page for man
.\"
.\" Copyright (C), 2002 Free Software Foundation, Inc.
.\"
.\" You may distribute under the terms of the GNU General Public
.\" License as specified in the file COPYING that comes with the
.\" glibc distribution.
.\"
.\"
.TH glibcbug 1 "10 January 2002" "" "Debian GNU/Linux"
.SH "NAME"
glibcbug \- Report a bug to the Glibc developers
.SH "SYNOPSIS"
.B glibcbug
.SH "DESCRIPTION"
.B glibcbug
is a tool for reporting bugs to the glibc maintainers.
It automatically starts an editor where the user can enter details
of the bug. On completion, the bug is sent to the appropriate
address.
The User should replace the comments (text surrounded by
<angle quotes>, and fill in the Subject: and From: lines with
a summary and e-mail address.

If the user believes the bug is related to Debian rather than to the
glibc (libc6) package, then the
.B reportbug
command should be used instead.
.SH "ENVIRONMENT"
.B glibcbug
will utilize the following enviromntal variables if they exist:
.TP
.B EDITOR
and
.B VISUAL 
Specifies the preferred editor. If
neither are set, 
.B glibcbug
will default to 
.B /usr/bin/sensible-editor
to determine a working editor.
.TP
.B HOME
Directory in which the failed bug report is saved if the mail fails.
.SH "SEE ALSO"
reportbug(1)
.SH "AUTHOR"
Alastair McKinstry <mckinstry@computer.org>.
