.\" Do not restrict distribution.
.\" May be distributed under the GNU General Public License
.TH PLDD 1 "11 January 2012"
.SH NAME
pldd \- list dynamic shared objects loaded into process
.SH SYNOPSIS
.B pldd
.RB [OPTION]...
PID
.SH DESCRIPTION
.B pldd
lists the dynamic shared objects loaded into a process.
.SH OPTIONS
.TP
.B \-\-usage
Give a short usage message.
.TP
.B \-V\ \-\-version
Print the version number of
.BR pldd .
.TP
.B \-?\ \-\-help
Usage information.
.SH AUTHOR
Ulrich Drepper.
.SH SEE ALSO
.BR ldd (8).
