=head1 NAME

index_create - create a JPIP (JPEG 2000 Part 9) indexed JP2 file from a J2K file


=head1 SYNOPSIS

B<index_create> I<source> I<destination> I<indexversion>


=head1 DESCRIPTION

B<index_create> creates a JPIP-indexed JP2 file from a J2K file


=head1 OPTIONS

=over

=item I<source>

J2K file to index

=item I<destination>

J2P file to write the indexed file to

=item I<indexversion>

Index version to use:

=over

=item 0. [faix] 4-byte and no AUX fields

=item 1. [faix] 8-byte and no AUX fields

=item 2. [faix] 4-byte and AUX fields

=item 3. [faix] 8-byte and AUX fields

=back

=back


=head1 AUTHOR

Written by Paul Hampson <Paul.Hampson@Pobox.com> based on the output of index_create -h as part of the Debian packaging of OpenJPEG


=head1 COPYRIGHT

Copyright 2007 Paul Hampson


=head1 SEE ALSO

Annex I from JPIP-FCD-version 2 (SC 29 N5727), L<http://www.2kan.org/public/2KAN_JPIP_overview.doc>
