.TH BINWALK "1" "April 2012" "binwalk" "User Commands"
.SH NAME
binwalk \- binary image search tool
.SH SYNOPSIS
.B binwalk
[\fIOPTIONS\fR] [\fIFILE1\fR] [\fIFILE2\fR] [\fIFILE3\fR] ...
.SH DESCRIPTION

Binwalk is a tool for searching a given binary image for embedded files and executable code. Specifically, it is designed for identifying files and code embedded inside of firmware images. Binwalk uses the libmagic library, so it is compatible with magic signatures created for the Unix file utility. 

.SH OPTIONS
.TP
\fB\-o\fR, \fB\-\-offset=\fR<int>
File offset to start searching at
.TP
\fB\-l\fR, \fB\-\-length=\fR<int>
Number of bytes to search
.TP
\fB\-b\fR, \fB\-\-align=\fR<int>
Set byte alignment
.TP
\fB\-f\fR, \fB\-\-file=\fR<file>
Log results to file
.TP
\fB\-m\fR, \fB\-\-magic=\fR<file>
Magic file to use [/etc/binwalk/magic.binwalk]
.TP
\fB\-g\fR, \fB\-\-grep=\fR<string>
Only display results that contain the text <string>
.TP
\fB\-r\fR, \fB\-\-raw\-bytes=\fR<string>
Search for a sequence of raw bytes inside the target file (implies \fB\-a\fR, \fB\-d\fR, \fB\-I\fR)
.TP
\fB\-y\fR, \fB\-\-search=\fR<filter>
Only search for matches that have <filter> in their description (implies \fB\-t\fR, \fB\-d\fR, \fB\-k\fR)
.TP
\fB\-x\fR, \fB\-\-exclude=\fR<filter>
Exclude matches that have <filter> in their description
.TP
\fB\-i\fR, \fB\-\-include=\fR<filter>
Include matches that are normally excluded and that have <filter> in their description *
.TP
\fB\-a\fR, \fB\-\-all\fR
Search for all matches, including those that are normally excluded *
.TP
\fB\-d\fR, \fB\-\-defaults\fR
Speed up scan by disabling default filters **
.TP
\fB\-I\fR, \fB\-\-show\-invalid\fR
Show results marked as invalid ***
.TP
\fB\-t\fR, \fB\-\-fast\fR
Speed up scan by only loading signatures specified by \fB\-i\fR or \fB\-y\fR
.TP
\fB\-u\fR, \fB\-\-update\fR
Update magic signature files
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Enable verbose mode
.TP
\fB\-s\fR, \fB\-\-smart\fR
Disable smart matching (implies \fB\-a\fR)
.TP
\fB\-k\fR, \fB\-\-keep\-going\fR
Don't stop at the first match (implies \fB\-I\fR)
.TP
\fB\-c\fR, \fB\-\-validate\fR
Validate magic file
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Supress output to stdout
.TP
\fB\-A\fR, \fB\-\-opcodes\fR
Scan for executable code (implies \fB\-a\fR)
.TP
\fB\-C\fR, \fB\-\-cast\fR
Cast file contents as various data types (implies \fB\-k\fR)
.PP
*   Signatures of two bytes or less are excluded by default. Use \fB\-i\fR or \fB\-a\fR to include them in the search.
.PP
**  Default filters include 'gzip', 'lzma' and 'jffs2' results.
.IP
Disabling the default filters (\fB\-d\fR) will speed up scan time, but may miss these file types.
.PP
*** By default, all results that contain the text 'invalid' will not be shown. Use \fB\-I\fR to display them.

