.TH "catfish" "1"
.SH "NAME"
catfish \- A gtk2 file search front-end with support for several engines
.SH "SYNOPSIS"
\fB
.SH "DESCRIPTION"
.B catfish
is gtk2 python application that provides a graphical front-end to the many
different search back-ends such as locate, slocate, tracker, beagle, strigi,
pinoti, and find.
.SH "AUTHOR"
.PP
This manual page was written by Cody A.W. Somerville <cody-somerville@ubuntu.com> 
for the \fBUbuntu GNU/Linux\fP system.


