usr/bin/tracker-needle
usr/bin/tracker-preferences

usr/share/applications/tracker-*.desktop
usr/share/icons/

usr/share/tracker/tracker-preferences.ui
usr/share/tracker/tracker-search-bar.ui
usr/share/tracker/tracker-needle.ui

usr/share/man/man1/tracker-needle.1
usr/share/man/man1/tracker-preferences.1
usr/share/man/man1/tracker-search-bar.1

# GNOME 3 panel applet
usr/share/tracker/tracker-search-bar-menu.xml
usr/share/gnome-panel/4.0/applets/org.gnome.panel.SearchBar.panel-applet
usr/share/dbus-1/services/org.gnome.panel.applet.SearchBarFactory.service
usr/lib/tracker/tracker-search-bar

# Nautilus tagging extension
usr/lib/nautilus/extensions-3.0/libnautilus-tracker-tags.so
