usr/bin/tracker-control

usr/share/dbus-1/services/org.freedesktop.Tracker1.service
usr/share/dbus-1/services/org.freedesktop.Tracker1.Writeback.service

usr/share/tracker/tracker-miner.xml
usr/share/tracker/tracker-miner-web.xml
usr/share/tracker/tracker-statistics.xml
usr/share/tracker/tracker-backup.xml
usr/share/tracker/tracker-resources.xml
usr/share/tracker/tracker-status.xml
usr/share/tracker/tracker-writeback.xml

usr/lib/tracker/tracker-store
usr/lib/tracker/tracker-writeback

usr/lib/tracker-0.16/writeback-modules/*.so

usr/share/man/man1/tracker-store.1
usr/share/man/man1/tracker-writeback.1
usr/share/man/man1/tracker-control.1

usr/share/glib-2.0/schemas/
usr/share/locale/
usr/share/tracker/ontologies/
usr/share/tracker/languages/

etc/xdg/autostart/tracker-store.desktop
