usr/lib/tracker/tracker-miner-fs
etc/xdg/autostart/tracker-miner-fs.desktop
usr/share/dbus-1/services/org.freedesktop.Tracker1.Miner.Applications.service
usr/share/dbus-1/services/org.freedesktop.Tracker1.Miner.Files.service
usr/share/man/man1/tracker-miner-fs.1
usr/share/tracker/miners/tracker-miner-applications.desktop
usr/share/tracker/miners/tracker-miner-files.desktop
debian/30-tracker.conf etc/sysctl.d/
