#! /bin/sh
set -e

if [ "$1" = "configure" ] || [ "$1" = "triggered" ]; then
    if [ -d /usr/share/applications ]; then
        # rebuild index
        I=/usr/share/applications/bamf.index
	echo "Rebuilding $I..."
        rm -f $I
        perl -ne 'if (/^Exec=(.+)$/) { $f = (split "/", $ARGV)[-1]; print "$f\t$1\n"; }' /usr/share/applications/*.desktop > $I.new || rm -f $I.new
        [ -e $I.new ] && mv $I.new $I || true
    fi
fi

#DEBHELPER#
