#!/bin/sh

set -e

# Old versions added a gnokii user too, not needed anymore so it can 
# be removed on upgrade too.
if getent passwd gnokii; then
    if [ $1 = "purge" ]; then
        userdel --remove gnokii
    else
        userdel gnokii
    fi
fi

case "$1" in
  remove|purge)
    if getent group gnokii; then
      dpkg-statoverride --quiet --remove /usr/sbin/mgnokiidev || true
      groupdel gnokii
    fi
esac

#DEBHELPER#
