#!/bin/bash

set -e

# Move a conffile without triggering a dpkg question
mv_conffile() {
    local OLDCONFFILE="$1"
    local NEWCONFFILE="$2"

    [ -e "$OLDCONFFILE" ] || return 0

    echo "Preserving user changes to $NEWCONFFILE ..."
    mv -f "$NEWCONFFILE" "$NEWCONFFILE".dpkg-new
    mv -f "$OLDCONFFILE" "$NEWCONFFILE"
}

case "$1" in
configure)
    if dpkg --compare-versions "$2" le "0.6.28.dfsg-2"; then
        mv_conffile /etc/gnokiirc /etc/xdg/gnokii/config
    fi
esac

#DEBHELPER#
