.TH update-command-not-found 8 "2008-10-24" "0.2.26-1" "Command not found helper"

.SH NAME
update-command-not-found \- update the command-not-found cache

.SH SYNOPSIS
.B update-command-not-found [-h|--help|-n|--no\-apt\-file]

.SH DESCRIPTION
.B update-command-not-found
updates the cache (databases) for command-not-found using the files in
/var/cache/apt/apt-file, which are fetched by apt-file.

.SH OPTIONS
.TP
.B \-h or \-\-help
Print the help message
.TP
.B \-n or \-\-no\-apt\-file
Do not run apt-file update before updating the cache.

.SH AUTHOR
command-not-found was written by Zygmunt Krynicki, update-command-not-found 
was written by Julian Andres Klode <jak@debian.org>

.PP
This manual page was written by Julian Andres Klode <jak@debian.org> for the
Debian project, but may be used by others.
