usr/lib/*/libqpidcommon.so
usr/include/qpid/Address.h
usr/include/qpid/amqp_0_10
usr/include/qpid/CommonImportExport.h
usr/include/qpid/Exception.h
usr/include/qpid/ImportExport.h
usr/include/qpid/InlineAllocator.h
usr/include/qpid/InlineVector.h
usr/include/qpid/framing
usr/include/qpid/log
usr/include/qpid/management
usr/include/qpid/Msg.h
usr/include/qpid/Options.h
usr/include/qpid/RangeSet.h
usr/include/qpid/SessionId.h
usr/include/qpid/sys
usr/include/qpid/Url.h
../../src/qpid/*.h usr/include/qpid
../../src/qpid/sys/*.h usr/include/qpid/sys
../../src/qpid/management/*.h usr/include/qpid/management
../../src/qpid/framing/*.h usr/include/qpid/framing
