#!/bin/sh

set -e

case "$1" in
    install|upgrade)
	# Do away with update-alternative for /usr/bin/gs, we have one
	# grand unified Ghostscript now!
	if dpkg --compare-versions "$2" lt-nl "8.63.dfsg.1-1"; then
		update-alternatives --remove-all gs || true
		update-alternatives --remove-all gs.1 || true
	fi
	;;
    abort-upgrade)
	;;
    *)
	echo "preinst called with unknown argument \`$1'" >&2
	exit 1
	;;
esac

#DEBHELPER#

exit 0
