.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH MAKEHUMAN 1 "November 2, 2009"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
makehuman \-  application for the modelling of 3-Dimensional characters
.SH SYNOPSIS
.B makehuman
.SH DESCRIPTION
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBMakeHuman\fP is an open source (so it's completely free), innovative
and professional software for the modelling of 3-Dimensional humanoid
characters.
MakeHuman 
.PP
Features that make this software unique include a new,
highly intuitive GUI and a high quality mesh, optimized to work in
subdivision surface mode (for example, Zbrush). Using MakeHuman, a
photorealistic character can be modeled in less than 2 minutes.
.PP
After installing the application, you can run run it from the
.B Applications
menu.
.SH AUTHOR
makehuman has been written and is maintained by The MakeHuman Team. For
further details, visit http://www.makehuman.org/.
.PP
This manual page was written by Alessio Treglia <quadrispro@ubuntu.com>,
for the Debian project (and may be used by others).
