.TH smpeg-config 1
.SH NAME
smpeg-config \- script to get information about the installed version of SMPEG
.SH SYNOPSIS
\fBsmpeg-config\fR [\-\-prefix\fI[=DIR]\fP] [\-\-exec\-prefix\fI[=DIR]\fP] [\-\-version] [\-\-libs] [\-\-cflags]
.SH DESCRIPTION
.PP
\fIsmpeg-config\fP is a tool that is used to determine the compiler and linker
flags that should be used to compile and link programs that use \fISMPEG\fP
library.
.
.SH OPTIONS
.TP 8
.B  \-\-version
Print the currently installed version of \fISMPEG\fP on the standard output.
.TP 8
.B  \-\-libs
Print the linker flags that are necessary to link a \fISMPEG\fP-using program.
.TP 8
.B  \-\-library-libs
Print the linker flags that are necessary to link a library that uses 
\fISMPEG\fP. (This excludes any static objects required for linking, since 
these must be linked only by executable programs.)
.TP 8
.B  \-\-plugin-libs
Print the linker flags that are necessary to link an \fISMPEG\fP-using object 
that is to be accessed via
.IR dlopen (3).
This may include static objects with PIC symbol information.  This option
should
.B not
be used for ordinary shared libraries or standalone applications.
.TP 8
.B  \-\-cflags
Print the compiler flags that are necessary to compile a \fISMPEG\fP-using
library or program.
.TP 8
.B  \-\-prefix=PREFIX
If specified, use PREFIX instead of the installation prefix that \fISMPEG\fP
was built with when computing the output for the \-\-cflags and
\-\-libs options. This option is also used for the exec prefix
if \-\-exec\-prefix was not specified. This option must be specified
before any \-\-libs, \-\-library-libs, \-\-plugin-libs or \-\-cflags options.
.TP 8
.B  \-\-exec\-prefix=PREFIX
If specified, use PREFIX instead of the installation exec prefix that
\fISMPEG\fP was built with when computing the output for the \-\-cflags,
\-\-libs, \-\-library-libs and \-\-plugin-libs options.  This option must 
be specified before any \-\-libs, \-\-library-libs, \-\-plugin-libs or 
\-\-cflags options.
.SH AUTHOR
The SDL MPEG Player Library was written by Karl Robillard and Sam Lantinga
of Loki Entertainment Software. Please report any bugs and/or fixes to
smpeg@lokigames.com. Streaming MPEG support was contributed by Vivien
Chappelier.
.P
This manual page was written by Stefan Gybas <sgybas@debian.org> and
modified by Joe Drew <drew@debian.org> and Branden Robinson
<branden@debian.org> for the Debian GNU/Linux operating system, but may be
used by others.
