.TH EXTLINUX\-INSTALL 8 2012\-12\-05 4.06 "EXTLINUX installation tool"

.SH NAME
extlinux\-install \- install EXTLINUX on your drive

.SH SYNOPSIS
\fBextlinux\-install\fR \fIDEVICE\fR [\fIEXTLINUX_OPTIONS\fR]

.SH DESCRIPTION
Install EXTLINUX on your drive.

.SH OPTIONS
extlinux\-install has no options.

.SH HOMEPAGE
More information about EXTLINUX and the syslinux project can be found at <\fIhttp://www.syslinux.org/\fR>.

.SH AUTHOR
EXTLINUX was written by  H. Peter Anvin <\fIhpa@zytor.com\fR>.
.PP
extlinux\-install and this manual page was written by Daniel Baumann <\fIdaniel.baumann@progress-technologies.net\fR>.
