.TH DEFMT\-C 1 "March 19th, 2011" "ispell 3.3.02"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
defmt\-c, defmt\-sh - a sample ispell deformatter for C, C++, and shell sources
.SH SYNOPSIS
.B ispell \-F defmt\-c
.RI [ ispell_options ]
.br
.B ispell \-F defmt\-sh
.RI [ ispell_options ]
.SH DESCRIPTION
The
.B defmt\-c
and
.B defmt\-sh
programs are sample deformatter provided primarily to show how to write
filters for use with
.BR ispell (1)'s
.I \-F
switch.  They allow
.BR ispell (1)
to be used to check C and C++ programs as well as shell scripts
(and any other languages that use # for comments and both quote styles
for strings).
.SH SEE ALSO
.BR ispell (1)
.SH AUTHOR
Geoff Kuennin <geoff@cs.hmc.edu>
.PP
This manual page was written by Robert Luberda <robert@debian.org>
(based on deformatters/README file from the ispell source package)
for the Debian project (and may be used by others).
