#!/bin/sh
set -e

#DEBHELPER#

PACKAGE="libgphoto2"

case "$1" in
    configure)
	# remove old fdi files
	rm -f /usr/share/hal/fdi/information/10freedesktop/10-camera-$PACKAGE.fdi
	rm -f /usr/share/hal/fdi/information/20thirdparty/$PACKAGE.fdi
	rm -f /usr/share/hal/fdi/information/10freedesktop/10-camera-$PACKAGE-device.fdi
	;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac


exit 0

