#! /bin/sh

PACKAGE="libgphoto2"

set -e

case "$1" in
    remove)
	rm -f /usr/share/hal/fdi/information/20thirdparty/$PACKAGE.fdi || true
	rm -f /usr/share/hal/fdi/information/10freedesktop/10-camera-$PACKAGE.fdi || true
	rm -f /usr/share/hal/fdi/information/10freedesktop/10-camera-$PACKAGE-device.fdi || true
	;;

    purge|disappear|upgrade|failed-upgrade|abort-install|abort-upgrade)
	;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
esac

#DEBHELPER#

exit 0
