.TH YDUMP 1 "December 5, 2010" "ydump User Manual"
.SH NAME
.PP
ydump - JSON pretty printer.
.SH SYNOPSIS
.PP
ydump [options] file
.SH DESCRIPTION
.PP
JSON pretty printer using yojson and easy-format.
.SH OPTIONS
.TP
.B -o 
Output file
.RS
.RE
.TP
.B -std
Convert tuples and variants into standard JSON, refuse to print NaN
and infinities, require the root node to be either an object or an
array.
.RS
.RE
.TP
.B -c
Compact output (default: pretty-printed)
.RS
.RE
.TP
.B -s
Streaming mode: read and write a sequence of JSON values instead of
just one.
.RS
.RE
.TP
.B -ob
Experimental
.RS
.RE
.TP
.B -help|--help
Display list of options
.RS
.RE
.SH AUTHORS
Sylvain Le Gall.

