.\"  -*- nroff -*-
.\"
.\" This manual page xqilla.1 is based on xqilla help output.
.\"
.\" Author: Tommi Vainikainen <thv@iki.fi>
.\"
.\" Copyright (c) 2001-2008
.\"     DecisionSoft Limited. All rights reserved.
.\" Copyright (c) 2004-2008
.\"     Oracle. All rights reserved.
.\" Copyright (C) 2010
.\"     Tommi Vainikainen. No rights reserved.
.\"
.\" Licensed under the Apache License, Version 2.0 (the "License");
.\" you may not use this file except in compliance with the License.
.\" You may obtain a copy of the License at
.\"
.\"     http://www.apache.org/licenses/LICENSE-2.0
.\"
.\" Unless required by applicable law or agreed to in writing, software
.\" distributed under the License is distributed on an "AS IS" BASIS,
.\" WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
.\" See the License for the specific language governing permissions and
.\" limitations under the License.
.\"
.\" Created: 2010-01-21
.\"
.TH XQILLA "1" "January 2010" "xqilla" "User Commands"
.SH NAME
xqilla \- run XQuery and XPath 2 expressions
.SH SYNOPSIS
.B xqilla
[\fIOPTION\fR]... \fXQUERY-FILE\fR...
.SH DESCRIPTION
Run XQuery and XPath 2 expressions from QUERY-FILE.
.TP
\fB\-h\fR
Show help and exit
.TP
\fB\-p\fR
Parse in XPath 2 mode (default is XQuery mode)
.TP
\fB\-P\fR
Parse in XPath 1.0 compatibility mode (default is XQuery mode)
.TP
\fB\-s\fR
Parse XSLT 2.0
.TP
\fB\-f\fR
Parse using W3C Full-Text extensions
.TP
\fB\-u\fR
Parse using W3C Update extensions
.TP
\fB\-e\fR
Parse using XQilla specific extensions
.TP
\fB\-d\fR
Run the query in interactive debugging mode
.TP
\fB\-x\fR
Use the Xerces-C data model (default is the FastXDM)
.TP
\fB\-i\fR \fIfile\fR
Load XML document and bind it as the context item
.TP
\fB\-b\fR \fIbaseURI\fR
Set the base URI for the context
.TP
\fB\-v\fR \fIname\fR \fIvalue\fR
Bind the name value pair as an external variable
.TP
\fB\-o\fR \fIfile\fR
Write the result to the specified file
.TP
\fB\-n\fR \fInumber\fR
Run the queries a number of times
.TP
\fB\-q\fR
Quiet mode - no output
.TP
\fB\-t\fR
Output an XML representation of the AST
.PP
The
.B xqilla
command line tool can be used to run XQuery and XPath 2
expressions. It is also a good example of how to use the
.B Simple API
of the
.B XQilla
library.
.SH "REPORTING BUGS"
Report bugs to <https://sourceforge.net/projects/xqilla/support>.
.SH COPYRIGHT
Copyright \(co 2001-2008 DecisionSoft Limited.
.br
Copyright \(co 2004-2008 Oracle.
.PP
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
<http://www.apache.org/licenses/LICENSE-2.0>
.PP
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
.SH "SEE ALSO"
The full documentation for the
.B XQilla library
is available at <http://xqilla.sourceforge.net/Documentation>.
